### ISSUE TITLE
Signing Epinio images

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1011]
**Is your feature request related to a problem? Please describe.**

Operators of Cloud Native platforms are becoming increasingly aware of their upstream software supply chain. To give greater security, we should provide all of the images that we require from a registry that we control as well as sign those images to show that there hasn't been any tampering in transit or caching. 

**Describe the solution you'd like**

When we cut a release, we should copy the images that we tested with into our own registry along with signatures from cosign.

**Comment by olblak** [comment]
We improve the release process by using [GoReleaser](https://goreleaser.com/) which allow to easily sign generated artifacts with cosign

**Comment by agracey** [comment]
@olblak Since we are using goreleaser, can we also build images for aarch64 and s390x (IIRC, that tool can cross-compile easily)? They won't be usable at the moment due to the lack of buildpack support but means that someone looking to work on buildpack support could more easily experiment!

**Comment by olblak** [comment]
@agracey yes it's something we could easily do using QEMU from GitHub action

**Comment by olblak** [comment]
It would be great to combine this work with https://github.com/epinio/epinio/issues/1284

**Comment by andreas-kupries** [comment]
https://goreleaser.com/customization/docker_sign/#signing-docker-images-and-manifests

**Comment by andreas-kupries** [comment]
On `cosign`: https://docs.sigstore.dev/cosign/installation/
