### ISSUE TITLE
Get familiar with Cypress framework to test Epinio UI

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1020]
First part of the epic #1000 about UI testing.

UI team will provide us some basics tests  we will be able to leverage for testing Epinio's UI.
Waiting that, we can start getting familiar with Cypress.
- Read [documentation](https://docs.cypress.io/guides/overview/why-cypress)
- [Install Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress)
- Run sample tests integrated in Cypress
- Try to run the existing [Rancher's UI tests](https://github.com/rancher/dashboard/tree/master/cypress) 

Full stack example application that demonstrates testing with Cypress in practical and realistic scenarios with github actions etc..
https://github.com/cypress-io/cypress-realworld-app

**Comment by juadk** [comment]
I was able to run the existing Rancher dashboard tests (Cypress) on my laptop ,tried to add a test to check if the Epinio icon exists and if we can click on it and go the Epinio page.
![image](https://user-images.githubusercontent.com/6025636/143473652-9f89ef62-464c-46e0-80d2-45cb8cee8163.png)

**Comment by ldevulder** [comment]
I'm playing with Cypress, first test to check that there is no Epinio instances on a fresh installation is working.

**Comment by ldevulder** [comment]
Done with the Cypress basics. I've added support for CA certificates and began to work on added a test.
