### ISSUE TITLE
Don't display API credentials in the console

### ISSUE THREAD

**Issue by olblak** [epinio/epinio#1022]
**Describe the bug**

At the end of the Epinio installation, API credentials are displayed directly in the console output. 
Considering that It's pretty common nowadays to use tooling to collect logs and then send them to a third service, depending on how we install epinio like using the helm chart, there is a risk to leak those credentials.

Instead of showing 

```
System domain: epinio.local
API User: xxx
API Password: yyy
```

Wouldn't it be better to show something like 

```
System domain: epinio.local
To retrieve the generated API user, please execute `kubectl get secret --namespace epinio default-epinio-user -o go-template='{{.data.username|base64decode}}{{ "\n" }}'`
To retrieve the generated API password, please execute  `kubectl get secret --namespace epinio default-epinio-user -o go-template='{{.data.password|base64decode}}{{ "\n" }}'`

```  

Hint: Make sure to search through the existing issues, as they often contain important information on recent changes.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio with `epinio install --system-domain local`

**Expected behavior**
I would expected that credentials remains secret

**Comment by ldevulder** [comment]
I think that this is obsolete since the helm charts, no?

**Comment by jimmykarily** [comment]
This was the old binary installer. This shouldn't be an issue anymore (with the single chart).
