### ISSUE TITLE
Extract the declarative installer to a new repository

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1028]
https://github.com/epinio/installer

The installer should have its own lifecycle. It shouldn't depend on Epinio code and we should be able to release independently. If an Epinio release needs a minimum version of the installer to work, that will be part of the release notes of Epinio.

Original Spike: https://github.com/epinio/epinio/issues/1006
Working branch: https://github.com/epinio/epinio/tree/mm/manifest-installer

NOTE: Let's wait until we find a fix for the mountCA issue (see the issue linked above) and until we have successfully pushed an application on Epinio installed with the installer from the spike.

## Acceptance Criteria

- The installer repository has it's own Makefile to build it for various architectures (like the Epinio repository does)
- The installer should have its own pipeline for releases that works like the one on Epinio.
- The installer should have its own test suite. Some basic test to bootstrap the suite, is ok for this story.

**Comment by olblak** [comment]
> The installer repository has it's own Makefile to build it for various architectures (like the Epinio repository does)
> The installer should have its own pipeline for releases that works like the one on Epinio.

May I suggest [GoReleaser](https://github.com/goreleaser/goreleaser). 
It's a great tool that handles the release process, we could easily sign artifacts and build for other architecture like arm64

Here two examples:
* [Configuration](https://github.com/updatecli/updatecli/blob/main/.goreleaser.yml)
* [Workflow](https://github.com/updatecli/updatecli/blob/main/.github/workflows/release.yaml)

To automate release changelogs, I prefer to use [ReleaseDrafter](https://github.com/release-drafter/release-drafter)

Feel free to ping me if you want a demo

**Comment by jimmykarily** [comment]
TODO list for the epinio repository cleanup (happening [here](https://github.com/epinio/epinio/tree/1028-move-to-new-installer)):

[] Remove old installer
[] Switch CI to use the new installer (it needs a first release)
[] Create CI to release the new helm chart + manifest + assets along with each epinio release

**Comment by jimmykarily** [comment]
This is the development process we came up with in order to keep development and releasing as easy as possible:

- We add the helm chart repository as a git module inside `epinio/epinio`. This will be used to deploy the CI epinio cluster to run tests on. This will also be used during development to test our changes. We need to do this because sometimes, the changes on the epinio API server, require changes on the epinio chart itself. When that's the case, we will make those changes in the git module itself and we will commit them along with the changes on the main repo. The epinio Deployment in the helm chart will point to an older version of Epinio binary but we will solve it like we did up to now: we will patch the binary.
- When a PR on `epinio/epinio` is tested green and it merged the `epinio/epinio` CI will:
  - build an image for the epinio api server pod. It will be tagged with the commit that was merged.
  - automatically create a PR against the helm chart repo which will add the changes made inside the git module and will change the epinio Deployment in the helm chart to use the latest epinio image build (see previous bullet).
- The CI of the helm chart repository will test this automated PR, running all the public cloud provider scenarios + the installer tests that have been removed form the epinio/epinio repository.
- If the above PR turns up green, we merge it, if not we fix what's broken

When the time comes to release:
- On the epinio/epinio side, we just tag `main`. This should build an image that has the version tag this time (not the commit hash). A release is created with all the binaries built like it happened so far. An automated PR will again be opened on the helm chart side, to bump the epinio Deployment to use this new image. (should we also sync with the git module? Is it possible that they diverged?)
- On the helm chart side, after we have merged the above PR and CI is green, we tag `main` and CI creates a new release. It will build and publish the 2 helm charts. They should also be available under Github assets.

Comments welcome. Again, the goal is to keep development and release easy after we do all the wiring.

**Comment by juadk** [comment]
> * When a PR on `epinio/epinio` is tested green and it merged the `epinio/epinio` CI will:
>   
>   * build an image for the epinio api server pod. It will be tagged with the commit that was merged.
>   * automatically create a PR against the helm chart repo which will add the changes made inside the git module and will change the epinio Deployment in the helm chart to use the latest epinio image build (see previous bullet).
> * The CI of the helm chart repository will test this automated PR, running all the public cloud provider scenarios + the installer tests that have been removed form the epinio/epinio repository.

Does it mean we will do public cloud testing for every PR? I'm thinking about costs and letsencrypt rate limit.

**Comment by jimmykarily** [comment]
Only docs were left. Now moved to : https://github.com/epinio/epinio/issues/1062 . Closing this.
