### ISSUE TITLE
Epinio UI test- add a test to add and delete a Namespace

### ISSUE THREAD

**Issue by prabalsharma** [epinio/epinio#1035]

**Comment by juadk** [comment]
- [ ] Create namespace
- [ ] Delete namespace
- [ ] Deploy app in your fresh namespace
The code works but it's not production level at all, for instance, create an app should be a function.

**Comment by juadk** [comment]
Last thing for this card is to add a regression test about creating an app without any namespace. At the moment, it gives a type error.
