### ISSUE TITLE
Application `origin` behaves unexpectedly 

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1058]
**Describe the bug**
There's a few blockers which is stopping the UI from using the new Application `origin`.

- It's not populated when 'pushing' an app via the UI (which calls the create, store, stage, etc endpoints directly), though works from the CLI
- It's only populated when the app reaches the 'running' status. If the app never reaches this state it's harder for a user to independently debug the issue.

**Expected behavior**
- No additional endpoints need to be called or information supplied to set the `origin` of an application
- Once the `origin` is determined/set for an application it's made available via the API

**Comment by andreas-kupries** [comment]
Currently origin information is saved by the `deploy` endpoint of an application.
This is where the information is transfered from client server. See models.

This was done to ensure that origin information always reflects the currently running app.
Well, with a small window when the running version terminates while the new version is brought up.

As @jimmykarily pointed out during the review of the PR implementing it, when the orig information is saved earlier, like at staging, or even earlier, then it will not match the running application anymore, but the intended to run. Which may fail to stage. At which point we have bad data in the system, i.e. origin information for the failed stage and not what is running.

I currently suspect that you are not populating the origin information in the request model for `deploy`.

**Comment by richard-cox** [comment]
Ah, I'd assumed it was persisted in some way by the calls leading up to `deploy`. I've now updated `deploy` to use the new property
