### ISSUE TITLE
Stage endpoint without a blobuid

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1073]
This is a follow up of this story: https://github.com/epinio/ui/issues/10

Currently the stage endpoint expect a [blobuid](https://github.com/epinio/epinio/blob/5988d5ce30bcfaefc71c67aa6479f8c5f2392098/pkg/api/core/v1/models/models.go#L153). That blod uid is the id of the blob that was previously uploaded. In order to allow restaging an application with the latest version of the code (e.g. from the web ui), we must make that parameter optional. If it's not there, the latest blob should be used, if one exists. Otherwise handle errors properly.

**Comment by jimmykarily** [comment]
Added BuilderImage field on the Application CRD here: https://github.com/epinio/application/pull/3
As the field description says, Epinio will try to use this builder image if one is not provided.

The "stage" endpoint requires 3 pieces of information on the request:

1. The app name and namespace to identify which app is going to be staged
2. The blob uid
3. The builder image

We can make the blob uid optional which is what this issue is all about. If it's not set, Epinio will try to use the last one.
In order to keep the restage request as simple as possible, we will make the builder image optional too. If one is not set, the previous one will be used.

This means, we don't need a new endpoint for re-staging. It also means, the web UI doesn't need to store the builder image anywhere in order to resend is when trying to restage. Epinio server will take care of it. @richard-cox is this good?

**Comment by richard-cox** [comment]
@jimmykarily looks good!

**Comment by jimmykarily** [comment]
Sibling PR: https://github.com/epinio/helm-charts/pull/50
