### ISSUE TITLE
Do not retry in Cli if the namespace already exists

### ISSUE THREAD

**Issue by thardeck** [epinio/epinio#1081]
Do not retry to create the namespace in Cli if it already exists. Follow up for the mentioned TODO:

https://github.com/epinio/epinio/blob/1cc932fb809132ad00212715aa98f882e3f1ac0d/internal/api/v1/namespace/create.go#L40-L43

**Comment by jimmykarily** [comment]
Steps to reproduce:
- Deploy epinio
- Create a namespace: `epinio namespace create mynamespace`
- Try to create the namespace again: `epinio namespace create mynamespace`

What happens:
The cli keeps retrying as if this error could go away

What should happen:
Print the error once and exit

**Comment by jimmykarily** [comment]
Another solution is to not re-try at all, ever. We added the retry because we run that command at the end of `epinio install` automatically and Epinio API server wasn't ready. We no longer have the `epinio install` command so we can remove the retry.
