### ISSUE TITLE
CI: re-add a weekly test with letsencrypt-production

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1088]
The nighly tests will be executed with letsencrypt-staging, to avoid quota issues. But as this test needs a 2-stages installation (cert-manager first then epinio) it could be a good idea to keep this test on a weekly basis. It's also useful to test the production one, as this one could be used by customers.

**Comment by jimmykarily** [comment]
If letsencrypt-staging works and letsencrypt-production doesn't then it's a problem of letsencrypt. We test the staging one daily so no need of an additional test.
