### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1099]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to attach a debugger to a running workload to set breakpoints and better understand what's happening in my service.

**Describe the solution you'd like**
I think there are two parts needed to get this done. The first is documenting how to preserve debug symbols for each supported language in the paketo buildpacks. The second is to be able to forward ports directly from a pod so it looks like localhost.

**Comment by jimmykarily** [comment]
@agracey can you describe the debugging process for local development? (including a sample app if needed). This should be used as a test to validate that the feature works after we implement it.

**Comment by agracey** [comment]
I can adopt the examples in this org to have the right launch.json (both debug and basic push)

FWIW, here's the docs that I wrote for CF:

https://github.com/SUSE-Developer-Community/sandbox-welcome-content/blob/master/content/cli.md#debugging 

This shows the VS Code config that I use for node.js apps. (I don't recall if the port number change is actually needed or if I used it to highlight directionality). The main difference is that we shouldn't have to use SSH to do this with Epinio because we have better primitives to work with.


The basic flow is:

- Run app with debug symbols and correct environment variables to tell debugger to accept connections (I described how to do this for a node.js and Java but might need to research more for others)
- Once running, start port forward to pod 
- Tell VS Code to attach debugger to local port
- Trigger app with http
- Step through code and see stack
- Push new code and reattach

(I can record a brief demo of what this looks like to the user without any new features)

Longer term, this can probably be simplified for the user by the VSCode plug-in to allow for the experience to just be `shift-F5`

**Comment by agracey** [comment]
At some point, paketo buildpacks will make this easier for us with: https://github.com/paketo-buildpacks/rfcs/blob/main/text/0037-remote-debug.md

**Comment by agracey** [comment]
For Java, this is documented here https://paketo.io/docs/howto/java/#enable-remote-debugging

**Comment by enrichman** [comment]
I did a simple test with a Java application, using `kubectl port-forward` and it works.

Am I missing something? Maybe we should just describe the process on how to do it.

**Comment by jimmykarily** [comment]
@agracey there are 2 different concepts in this story:

- port forwarding
- debugging symbols/flags passed to the buildpack

Can we split them in 2 separate stories? Looking at how `kubectl` implements port-forward, it will look similar to the work done for #1098.  Something like:

- `epinio` listens on a port (like kubectl does here: https://github.com/kubernetes/client-go/blob/7f0455096073f978a0f4b832c7ab10a0ed5a66b9/tools/portforward/portforward.go#L211)
- epinio server authenticates and proxies this URL: https://github.com/kubernetes/kubectl/blob/a4aec62157e9fd73a038c9aab36822707277f00c/pkg/cmd/portforward/portforward.go#L409 like we do here: https://github.com/epinio/epinio/blob/d41d04e60a2e216ab240c274c6a50b6d2f1568c1/internal/api/v1/application/exec.go#L69

**Comment by agracey** [comment]
I think that makes sense.

**Comment by agracey** [comment]
The port-forwarding is the important part. Once we have that, we can work out of band to write up the docs for each language.

**Comment by jimmykarily** [comment]
Port forwarding is done. Created an issue for the documentation: https://github.com/epinio/docs/issues/56
I will close this for now, documentation is too open ended to keep the milestone open for it.
