### ISSUE TITLE
Response from GET services is different than GET service

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1104]
**Describe the bug**
- `/services` responds with a `ServiceResponse` model
  ```
	Meta          ServiceRef          `json:"meta"`
	Configuration ServiceShowResponse `json:"configuration"`
  ```
-  `/namespaces/<namespace>/services/<name>` responds with a `ServiceShowResponse`
   ```
 	Username  string            `json:"user"`
	Details   map[string]string `json:"details,omitempty"`
	BoundApps []string          `json:"boundapps"`
   ```

**Expected behavior**
- The API should return a consistent response when listing all services and fetching a specific service. This should include identification properties i.e. meta with name & namespace.
- This affects how the UI processes the response from services/service, how the unique id is calculated and how we handle edit

**Comment by richard-cox** [comment]
There were some recent changes to the service/s models
- https://github.com/epinio/epinio/issues/981
- https://github.com/epinio/epinio/pull/1014

I totally missed this issue when reviewing the PR

**Comment by andreas-kupries** [comment]
I confirm the differences in the code. The list endpoints return a slice of ServiceResponses, and each such structure is a combination of Meta and ShowReponse. The show endpoint returns only a single ShowResponse.

The fix should be to upgrade the show endpoint to return a single full ServiceResponse.
