### ISSUE TITLE
Build last helm chart locally for public cloud CI tests

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1105]
When we install Epinio in public clouds (and RKE in our self host runners), we use the last release of the [Epinio Helm chart](https://github.com/epinio/epinio/blob/main/acceptance/helpers/epinio/epinio.go#L27).

But sometimes, a change is introduced in the epinio server and we also need a change in the helm chart, that's why we need to build the last helm chart locally (with chartmuseum) before triggering the installation. Like we do in the main CI with [chartmuseum](https://github.com/epinio/epinio/blob/main/scripts/setup-chart-museum.sh)

Issue : https://github.com/epinio/epinio/runs/4771873657?check_suite_focus=true

**Comment by andreas-kupries** [comment]
Research
  - https://github.com/epinio/epinio/blob/main/.github/workflows/main.yml#L106 (and 2 other) seems to be the referenced places in the main CI ... The `prepare_environment_k3d` target calls on the `setup_chart_museum` target.

If I understand the request correctly the fix would to add `make setup_chart_museum` before the `make test-acceptance-install` commands of `rke.yaml` and siblings.
