### ISSUE TITLE
UI CORS pre-flight requests getting stuck

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1114]
The UI makes a CORS pre-flight request to epinio and sometimes this puts the httprouter in an infinite loop also maximizing CPU usage.

This seems to be a bug in copy of httprouter code in gin. The problem occurs somewhere here: https://github.com/gin-gonic/gin/blob/master/tree.go#L518-L523 (`continue` is called but next loop brings us to the same point).

The order in which our routes are registered ([here](https://github.com/epinio/epinio/blob/main/internal/api/v1/router.go#L127)) is random, because of the ways maps work in Golang (no guaranteed order when calling `range`). This seems to sometimes affect whether the problem occurs or not.

I had good luck reproducing the problem with a request like this:

```
curl -k "https://epinio.10.86.4.38.omg.howdoi.website/api/v1/namespaces/workspace/applications/test/deployasdf"
```
(`deployasdf` is important, other strings may not reproduce the problem)
The app doesn't need to exist, just fire the request and see what happens. If it's stuck then it's reproduced.

In some other cases I got a 50X error and golang paniced, but this happened less ofter (though it happened many times and had something to do with index out of range). This could be yet another issue.

If the problem doesn't occur, just kill the epinio server pod and try again after the new pod comes up.

**Comment by jimmykarily** [comment]
After trying various things and adding debug output everywhere, there 2 routes seemed relevant to me so I commented them out: https://github.com/epinio/epinio/blob/main/internal/api/v1/router.go#L93-L94

I couldn't reproduce the error after that. This is just one more data point but given how random everything is, commenting out those 2 lines may have just hid the problem (which may occur with some other url for example).

Tip: checkout git-gonic and add a `replace` statement in `go.mod` to be able to debug using the local checkout:

```
replace github.com/gin-gonic/gin => ../../gin
```
(make sure you checkout `v1.7.4` tag on the gin repo)

**Comment by richard-cox** [comment]
For tracking purposes, this looks like it's the cause of the forever `Deploy`ing step when creating an app in the UI. For that use case the `/deploy` pre-flight hangs indefinitely. Interestingly calls before and after this are fine. I don't think anyone has hit the hang for other endpoints, and for this specific endpoint the failure is sporadic. QA have picked this up via https://github.com/epinio/epinio/issues/988#issuecomment-971610198
