### ISSUE TITLE
epinio binary in epinio-server pod reports version v0.0.0-dev

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1121]
## Acceptance Criteria

- `epinio version` returns the right version (when run inside the epinio server pod)
- `/api/v1/info` endpoint returns the same (right) version
- when the epinio server starts, it should print the version
- [optional] create and install test that checks that the version on the image of the server pod matches the one from the binary. If the image doesn't have version information, it should (e.g. a label). This could be extracted to another issue.

**Comment by thardeck** [comment]
Looks like it was broken by changing LDFLAGS in the Dockerfile: https://github.com/epinio/epinio/commit/d4633517daf56e2cd685f7e384732841208a7fac
