### ISSUE TITLE
Error while installing epinio on k3d

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1122]
**Describe the bug**

Installing Epinio with helm on k3d wil return an error

```
-> % helm install --set systemDomain=$EPINIO_SYSTEM_DOMAIN epinio-installer epinio/epinio-installer 
Error: failed post-install: job failed: BackoffLimitExceeded
```

Looking at the logs it seems that the installer is not able to check that Traefik is installed in the `kube-system` namespace

**Expected behavior**
The installer should check the Traefik is already available and skip.

**Logs**

```
error for 'traefik': failed installing traefik, output:
Release "traefik" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "traefik" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "traefik": current value is "kube-system"
: exit status 1
failed to install all components
failed installing traefik, output:
Release "traefik" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "traefik" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "traefik": current value is "kube-system"
: exit status 1
```

**Cluster (please complete the following information):**
 - Provider: K3D (and maybe other)

**Comment by rne1223** [comment]
Hit the same bug using k3s. I got around it by installing k3s without traefik. 
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -`.

**Comment by gitricko** [comment]
tryingto follow the doc directly for k3d.. couldnt install it. I think the installer helm chart is no longer available. Looks good on the videos but could not install it

**Comment by juadk** [comment]
> tryingto follow the doc directly for k3d.. couldnt install it. I think the installer helm chart is no longer available. Looks good on the videos but could not install it

That's true, `epinio-installer` is not available anymore, we removed it from the helm repo as well as from documentation. 
The way to install Epinio is to use the epinio helm chart (https://artifacthub.io/packages/helm/epinio/epinio).
We are updating the documentation and it should be merged today. In the meantime, you can install Epinio on k3d following this page: https://docs.epinio.io/installation/installation.html

**Comment by gitricko** [comment]
Thanks for the response. I tried to follow religious on that link and could get it to work (+ this as well https://docs.epinio.io/howtos/install_epinio_on_k3d.html)

I am not claim to be K8S expert but i think the install instruction should be clear and concise so that newbie can get it to work by just literally follow the instructions. Especially, now we have things like K3d and Kind. It should be simple. I must say, i was alittle disappointed cos i manage to get KubeCF to work on Kind but not for Epinio 

Please ping here to let me know when the new doc has drop. I can help with docu if you let me. 


> > tryingto follow the doc directly for k3d.. couldnt install it. I think the installer helm chart is no longer available. Looks good on the videos but could not install it
> 
> That's true, `epinio-installer` is not available anymore, we removed it from the helm repo as well as from documentation. The way to install Epinio is to use the epinio helm chart (https://artifacthub.io/packages/helm/epinio/epinio). We are updating the documentation and it should be merged today. In the meantime, you can install Epinio on k3d following this page: https://docs.epinio.io/installation/installation.html

**Comment by gitricko** [comment]
Already hit the first issue
```
$ k3d cluster create epinio -p '80:80@server[0]' -p '443:443@server[0]'
FATA[0000] failed to transform ports: Failed to parse node filters (with suffix): invalid format or empty subset in 'server[0]' 
```

I think the above is new command

**Comment by gitricko** [comment]
Here is my shameless plug for a "installer" for epinio for users of Linux/Mac. Windows need WSL though i did not test

https://gist.github.com/gitricko/b5125a3649e5d52faec4e4f9a496e166

Just a makefile... and run command
```
make install-epinio
```
