### ISSUE TITLE
Switch to smaller docker image

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1145]
The Epinio server uses the [epinio-base image](https://github.com/epinio/epinio/blob/main/images/baseimage-Dockerfile), however we don't need any of the installed tools.

We could switch to distroless or "from scratch" and reduce the image size by about 200mb (260mb vs 60mb). 

This is a good cleanup, because we don't need to build and maintain the base image anymore.

* epinio-server listens on port 80, image needs root
* patch script for CI needs to be adapted
* talks to k8s, does SSL work?
* same image in CI as in [release](https://github.com/epinio/epinio/blob/main/.goreleaser.yml#L71-L108)

**Comment by agracey** [comment]
There is a SLE BCI minimal image that might work as well. 

Does epinio-server need to listen on port 80 or could that change to 8080? It would be nice if we could run without root.

**Comment by thardeck** [comment]
Some statistics regarding size:
```
docker image inspect registry.suse.com/bci/bci-minimal --format='{{.Size}}'  |  numfmt --to=iec
43M
docker image inspect alpine --format='{{.Size}}'  |  numfmt --to=iec
5.4M
docker image inspect busybox --format='{{.Size}}'  |  numfmt --to=iec
1.2M
```
