### ISSUE TITLE
domain / systemDomain mismatch in epinio-installer chart

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1146]
**Describe the bug**

From @agracey, in slack:

> I'm running into an issue trying to upgrade my cluster  (I blew it all away to make sure it wasn't anything weird that I did...) It looks like the latest epinio-installer chart still tries to install from epinioChart: "https://github.com/epinio/helm-charts/releases/download/epinio-0.2.3/epinio-0.2.3.tgz" Which doesn't know that systemDomain got renamed to domain . Also, why is the epinio chart itself not the same version?

**To Reproduce**

Try to install via the epinio-installer helmchart.
No further detail provided, like a command sequence :(

**Expected behavior**

Proper installation

**Logs**

Not provided :(

**Cluster (please complete the following information):**

Unknown. Should not be relevant.

**Desktop/CLI (please complete the following information):**

Unknown. Should not be relevant.

**Additional context**

n/a

**Comment by andreas-kupries** [comment]
@agracey Could this have been a mismatch of using an older installer chart with a newer epinio chart ?

Huh. Actually inverted, based on my research:

  - New installer chart (near 0.3.6 with rename) was used with old epinio (0.2.3 without rename).

---

My initial assumption on reading the issue was that I had forgotten to update the installer chart.
Then I looked at https://github.com/epinio/helm-charts/pull/64 and found that assumption to be incorrect.
See https://github.com/epinio/helm-charts/pull/64/files#diff-d027f6fca610418a1131c3f0740243ad91eab5702bbaccde70dc1b999eee3a5b in the PR commits.
I did all the renames in synch.

As you mentioned `epinio-0.2.3` I looked into the HC repo history. (`gitk` to the resuce :heart:).
The [PR 64](https://github.com/epinio/helm-charts/pull/64) doing the rename was done and merged just after `epinio-0.2.3` was released (and the associated `epinio-installer` chart is `0.3.5`).

Yesterday we got releases of `epinio-0.2.4` and `epinio-installer-0.3.6` which both have the `system(Domain)` rename.

Based on this research my conclusion is that you used a near-0.3.6 installer with the old epinio chart and thus got the mismatch as the installer had the rename and epinio did not.

Please check if the newly released 0.2.4/0.3.6 combo works for you.

**Comment by andreas-kupries** [comment]
From slack:

> @manno  We currently think there is a bug in the 0.3.6 chart, where it refers to the old epinio version
> https://github.com/epinio/helm-charts/pull/72

I see that PR just merged. Expect a new installer release soon.

**Comment by ldevulder** [comment]
> I see that PR just merged. Expect a new installer release soon.

New installer helm chart released, the issue should be gone!

**Comment by juadk** [comment]
Tested yesterday with our Cypress tests. I can not reproduce the issue anymore with the latest version (epinio-installer-0.3.7).

**Comment by andreas-kupries** [comment]
Thank you. Closing.
