### ISSUE TITLE
Extend upload API to support both `tar` and `zip`, and update client, backend, etc.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1149]
With the old implementation only tar.gz seems to work when doing the 'push' form the ui. When supply a zip file the `/store` and `/stage` calls both succeed however the call to `/complete` fails with a 500 error
```
Server Backtrace: Tasks Completed: 4 (Failed: 1, Cancelled 0), Skipped: 0\ngithub.com/epinio/epinio/internal/api/v1/application.Controller.Staged.func1\n\t/go/src/github.com/epinio/internal/api/v1/application/stage.go:285
```
It would help the usability of the UI if both tar.gz and zip file types were supported.

Supporting zip would also make it easier to support the 'folder' source as well (it's much easier client side to create a zip file from a local folder).

**Comment by richard-cox** [comment]
The request is to support both `tar.gz` and `zip`. That would remove the need for converting from or to zip in the frontend.

**Comment by andreas-kupries** [comment]
Updated the title

**Comment by andreas-kupries** [comment]
The endpoints involved in running an application are

  1. create app resource
  2. upload sources (store to s3)
  3. stage sources (read from s3, save image to registry)
  4. deploy (read image from registry)

Of these only step 3 has to know the format the sources are in, and there only the `unpack` step. The `download` sub-step does not care about the format, like step 2. While both nominally handle the uploaded sources the only thing they do is passing it into and out of the configured S3 for storage. Neither does care about the format the sources are in. The `buildpack` step expects the unpacked sources, i.e. a directory hierarchy.

Step 1 obviously has nothing to do with sources at all, and step 4 knows to expect an OCI image.

So, primary focus has to be on https://github.com/epinio/epinio/blob/bbb0412d2761c612d25562249b167c554c78f8d2/internal/api/v1/application/stage.go#L367

Regarding the cli client I see no need for updating it. It currently supports specification of sources as directory, or git repository. That it uses tar internally to package these up is immaterial and does not have to change. It would be different if it would already support specification as tarball instead of as directory. In that case adding support for zip would make sense.

Thus, no secondary focus is required.

Note, I expect the unpack script to become complicated enough that #1175 will gain priority.

**Comment by andreas-kupries** [comment]
The part

> unpack-blob Tar?
unpack-blob Tar: tar: invalid tar magic
unpack-blob OK

of the log seems to indicate that the unpack script did not test the other formats after it failed for tar ...
I will look into this again.

**Comment by andreas-kupries** [comment]
Note that the scripts for staging are in the epinio helm chart, see `epinio/templates/stage-scripts.yaml`.
They are saved in the cluster as config map. That means you can edit them on the fly in the cluster.

**Comment by richard-cox** [comment]
> Note that the scripts for staging are in the epinio helm chart, see `epinio/templates/stage-scripts.yaml`. They are saved in the cluster as config map. That means you can edit them on the fly in the cluster.

@andreas-kupries I'm flip-flopping between projects again but if there's anything you'd like me to try or validate just let me know

**Comment by andreas-kupries** [comment]
Not yet. Had a quick look at the relevant code, i.e.

```
   mkdir /workspace/source/app
    (  cd /workspace/source/app
       ( echo Tar? ; tar -xvf  "../${BLOBID}" 2>&1 | sed -e 's/^/Tar: /' ) || \
       ( echo Zip? ; unzip     "../${BLOBID}" 2>&1 | sed -e 's/^/Zip: /' ) || \
       ( echo Tgz? ; tar -xvzf "../${BLOBID}" 2>&1 | sed -e 's/^/Tgz: /' ) || \
       ( echo Tbz? ; tar -xvjf "../${BLOBID}" 2>&1 | sed -e 's/^/Tbz: /' ) || \
       ( echo Txz? ; tar -xvJf "../${BLOBID}" 2>&1 | sed -e 's/^/Txz: /' ) || \
       ( echo "Unable to unpack. No supported archive file format found" ; exit 1 )
       echo OK
    )
```

and it still looks ok to me with `||` to chain attempts at unpacking.
I will have to trial this locally.
From the log it jumped from Tar directly to ok, ignoring all the remaining clauses.

**Comment by andreas-kupries** [comment]
:disappointed: I confirm local failure of this code. Now why/how was this working when I wrote it ?
Regardless, now working on a fix.

```
work@tagetarl:~/SUSE/dev/epinio> ./z.sh x/docs.tar
Tar?
Tar: ./
Tar: ./epinio.png
Tar: ./howtos/
Tar: ./howtos/acceptance_tests.md
Tar: ./howtos/custom-python-builder.md
Tar: ./howtos/development.md
Tar: ./howtos/README.md
Tar: ./howtos/new-api-user.md
Tar: ./references/
Tar: ./references/api/
Tar: ./references/api/swagger.json
Tar: ./explanations/
Tar: ./explanations/configuration-management-internals.md
Tar: ./explanations/futureplans.md
Tar: ./README.md
OK

work@tagetarl:~/SUSE/dev/epinio> ./z.sh x/docs.zip 
Tar?
Tar: tar: This does not look like a tar archive
Tar: tar: Skipping to next header
Tar: tar: Exiting with failure status due to previous errors
OK
```

**Comment by andreas-kupries** [comment]
It seems that it is the `... | sed ...` parts which break it.
That would also explain why it worked first. 
Because the `sed` part was added later.
And not fully re-tested (my bad).

I believe I now understand. While the `tar` command fails, the `sed` does not, and that is the state of the clause, so it stops.
And only ever executes the first clause.

I will now remove the `sed` parts and make a chart PR for that.

For immediate testing in your env edit the config map and the replace the code mentioned in https://github.com/epinio/epinio/issues/1149#issuecomment-1070615355 with

```
mkdir /workspace/source/app
    (  cd /workspace/source/app
       ( echo Tar? ; tar -xvf  "../${BLOBID}" ) || \
       ( echo Zip? ; unzip     "../${BLOBID}" ) || \
       ( echo Tgz? ; tar -xvzf "../${BLOBID}" ) || \
       ( echo Tbz? ; tar -xvjf "../${BLOBID}" ) || \
       ( echo Txz? ; tar -xvJf "../${BLOBID}" ) || \
       ( echo "Unable to unpack. No supported archive file format found" ; exit 1 )
       echo OK
    )
```

Beware indentation (yaml!)

**Comment by andreas-kupries** [comment]
Chart PR https://github.com/epinio/helm-charts/pull/141
Epinio PR https://github.com/epinio/epinio/pull/1303
