### ISSUE TITLE
Shell to specific app instance

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1151]
A follow up of : https://github.com/epinio/epinio/issues/1098 (Depends on it)

## Acceptance Criteria

- The user should be able to list instances of an app (as pod names? TBD)
- The user should be able to pass the desired instance to `epinio app exec` and get a shell to that one. This parameter can be optional. If not set, we give a shell to a random instance.
- [Optional] Tab completion for the above parameter. This way the user doesn't have to run one command to discover instances and one to get a shell.

We probably have to implement a new endpoint to list application instances or make it part of `AppShow`. The UI will need some information about instances too so let's make sure we are in sync. cc @richard-cox

**Comment by jimmykarily** [comment]
Here is what the AppShow endpoint returns currently:

```
{
  "meta": {
    "name": "sample",
    "namespace": "workspace"
  },
  "configuration": {
    "instances": 2,
    "services": [],
    "environment": {},
    "routes": [
      "sample.172.18.0.3.omg.howdoi.website"
    ]
  },
  "origin": {
    "Kind": 1,
    "git": {
      "repository": ""
    },
    "path": "/home/dimitris/workspace/epinio/epinio/assets/sample-app"
  },
  "deployment": {
    "active": true,
    "createdAt": "2022-01-31T12:26:50Z",
    "restarts": 0,
    "memoryBytes": 89010176,
    "millicpus": 1,
    "desiredreplicas": 2,
    "readyreplicas": 2,
    "username": "admin",
    "stage_id": "0d9f5e397dfb2283",
    "status": "2/2",
    "routes": [
      "sample.172.18.0.3.omg.howdoi.website"
    ]
  },
  "status": "running",
  "statusmessage": ""
}
```

the 3 fields: `restarts`,  `memoryBytes` and `millicpus` are aggregates of all pods.

I'm planning to add a field `Replicas` which will be an array of objects. We will be able to show the value for each Pod separately. Do we still need the aggregate fields? The clients can sum up the values if they want to show one value. @richard-cox ?

**Comment by richard-cox** [comment]
Per pod will be fine. Just to clarify though on user facing interfaces `Replica` / `Pod` will translate to an "Instance"? Will the resources consumed cover the pod in it's entirety (container that hosts the app itself + epinio required sidecars like linerd-proxy)?

**Comment by jimmykarily** [comment]
right now, we sum the metrics from all containers, app and sidecars. The suggestion is to show the same information but per Pod.

**Comment by jimmykarily** [comment]
This is the new response:

```
{
  "meta": {
    "name": "sample",
    "namespace": "workspace"
  },
  "configuration": {
    "instances": 2,
    "services": [],
    "environment": {},
    "routes": [
      "sample.172.18.0.4.omg.howdoi.website"
    ]
  },
  "origin": {
    "Kind": 3,
    "container": "splatform/sample-app",
    "git": {
      "repository": ""
    }
  },
  "deployment": {
    "active": true,
    "createdAt": "2022-02-01T08:09:01Z",
    "desiredreplicas": 2,
    "readyreplicas": 2,
    "replicas": {
      "sample-77f8c45c77-d662v": {
        "name": "sample-77f8c45c77-d662v",
        "memoryBytes": 3182592,
        "millicpus": 0,
        "restarts": 0,
        "ready": true
      },
      "sample-77f8c45c77-s4rnh": {
        "name": "sample-77f8c45c77-s4rnh",
        "memoryBytes": 48648192,
        "millicpus": 0,
        "restarts": 0,
        "ready": true
      }
    },
    "username": "admin",
    "status": "2/2",
    "routes": [
      "sample.172.18.0.4.omg.howdoi.website"
    ]
  },
  "status": "running",
  "statusmessage": ""
}

```

**Comment by jimmykarily** [comment]
And this is what it looks like from the cli:

```
~/workspace/epinio/epinio (1151-shell-to-specific-instance)*$ epinio app show sample

🚢 Show application details
Namespace: workspace
Application: sample

✔️  Details:
|        KEY        |                VALUE                 |
|-------------------|--------------------------------------|
| Origin            | splatform/sample-app                 |
| Status            | 2/2                                  |
| Username          | admin                                |
| StageId           |                                      |
| Age               | 2h32m23s                             |
| Active Routes     |                                      |
|                   | sample.172.18.0.4.omg.howdoi.website |
| Desired Instances |                                    2 |
| Bound Services    |                                      |
| Environment       |                                      |

✔️  Instances: 
|          NAME           | READY |  MEMORY  | MILLICPUS | RESTARTS |  AGE  |
|-------------------------|-------|----------|-----------|----------|-------|
| sample-77f8c45c77-dhrqh | true  | 43.0 MiB |       544 |        1 | 3m17s |
| sample-77f8c45c77-6z6zt | true  | 0 B      |         0 |        0 | 15s   |
```

**Comment by jimmykarily** [comment]
This is part 2: https://github.com/epinio/epinio/tree/1151-shell-to-specific-instance-2
 which allows the user to specify the instance to shell to. Its working but I want to add a couple of tests for it:

- check that it errors when the specified instance doesn't exist
- check that it works when the specified instance exists
- keep checking that it works with no instance defined
