### ISSUE TITLE
Golang training

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1186]
Training to improve Golang knowledge.

**Comment by andreas-kupries** [comment]
Maybe add links to the training resources here ?

**Comment by enrichman** [comment]
Or we can move this to a discussion, not sure if it's an issue. :)

**Comment by ldevulder** [comment]
> Maybe add links to the training resources here ?

Sure! It's this one: https://www.udemy.com/course/go-the-complete-developers-guide

**Comment by ldevulder** [comment]
> Or we can move this to a discussion, not sure if it's an issue. :)

Not it's not an issue, but as only issue can be added in the Planning we were asked at some point to create this kind of "issue" to track what we are doing.

So I can close it now yes, but in that case I will not have any card/issue associated to me to see what I'm doing.

**Comment by ldevulder** [comment]
Done!
