### ISSUE TITLE
Epinio tries to deploy an app but build stage failed

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1209]
**Describe the bug**
Build of the application is failing, but epinio tries to deploy it anyway.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio
2. Push an app
3. See error

**Expected behavior**
Epinio should fail at the end of the build process with a "clear" error message.

**Logs**
```
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack Paketo PHP Distribution Buildpack 0.5.0 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack   Resolving PHP version 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack     Candidate version sources (in priority order): 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack       buildpack.yml    -> "7.3.x" 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack       default-versions -> "7.4.*" 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack  
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack failed to satisfy "php" dependency version constraint "7.3.x": no compatible versions on "io.buildpacks.stacks.bionic" stack. Supported versions are: [7.4.26, 7.4.27, 8.0.14, 8.0.15] 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack ERROR: failed to build: exit status 1 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack _ _ __ ___ _____ Done 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack                                  Dload  Upload   Total   Spent    Left  Speed 
100     9    0     9    0     0   1800      0 --:--:-- --:--:-- --:--:--  1800 
🕞  [stage.workspace.wordpress.b4497587b83108fa-79p5v] buildpack shutdown 

Deploying application ...

🕞  Creating application resources
```

You can increase Epinio's logging by exporting these variables:
```
export TRACE_LEVEL=255
export DEBUG=true
```

**Cluster (please complete the following information):**
 - Provider: K3s (but it happens on any k8s distro)
 - Options: default installation
 - Kubernetes Version: 1.21

**Desktop/CLI (please complete the following information):**
 - OS: Linux, but should be the same on other OSes
 - Epinio Version: `main` (exactly: ` v0.3.6-28-gcd6e72be`)
 - Epinio Install Options: `--set skipTraefik=true --set domain=192.168.4.63.omg.howdoi.website`

**Additional context**
N/A

**Comment by andreas-kupries** [comment]
While I do not have the wordpress/php used to induce the failure, I can edit the scripts to force such.

I.e. insert a `false`, or an `exit 1` into one of the script and see how the process behaves.

**Comment by andreas-kupries** [comment]
It seems that we need `set -e` to force exit on error, and `trap .. ERR` for the init containers to kill linkerd (which may or may not be up at the time).
