### ISSUE TITLE
List installed/supported buildpacks

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#121]
The user needs to be able to tell which buildpacks are installed/supported in a specific installation of Carrier.

A command like `carrier buildpacks` would be useful.

**Comment by agracey** [comment]
Since buildpacks are just fancy containers, what does installing a new buildpack look like?

**Comment by jimmykarily** [comment]
@agracey buildpacks are included in the builder image (see here: https://buildpacks.io/docs/operator-guide/create-a-builder/), they are not standalone containers that run in the cluster somewhere. That's the reason why we have different builders like `paketobuildpacks/builder:full` and `paketobuildpacks/builder:tiny`. Adding a buildpack means one would need a new different builder. How that happens is up to Carrier to decide. Either we support multiple builders but the user will have to choose one when pushing the app (no automated detection happens between builders afaik, but I could be wrong), or the user will have to change the builder image globally to use one that has the needed buildpack.

**Comment by agracey** [comment]
Thank you for the explanation! 

It would definitely be useful to have a flag specifying your own builder image but that's likely a fairly low priority? This would make building your own buildpacks much less painful

On my own, I might tear apart what gets loaded into the builder to see if it's possible to adjust at run time.

**Comment by andreas-kupries** [comment]
```
d run -it --rm quay.io/asgardtech/paketobuildpacks-builder:full-cf /bin/bash -c 'cat /cnb/buildpacks/*/*/buildpack.toml'
```

So, the core of the idea here is

  - Modify the warm up job for the builder image to run the `/bin/bash -c 'cat /cnb/buildpacks/*/*/buildpack.toml'` command.
  - Capture the output from that, somehow.
  - Parse the TOML ... Need something capable of parsing a TOML aggregated from many files
    If not possible the command above has to be modified to insert some kind of separator between the files.
    We can then look for that in a pre-parsing step.
  - Stash the extracted set of buildpacks (names, versions, descriptions, ...) into a config map.
  - The `carrier buildpacks` command simply reads that config map.

**Comment by andreas-kupries** [comment]
Tested, and `/bin/bash -c 'for info in /cnb/buildpacks/*/*/buildpack.toml ; do echo MARKER ; cat $info ; done'` does work.
Needs a nicer marker, however that is trivial. ... Something like `___carrier_inspection___` maybe.

**Comment by andreas-kupries** [comment]
TOML parsing for Go -- `https://www.google.com/search?q=golang+toml+parsing`
First two results:

  - https://github.com/pelletier/go-toml
  - https://github.com/BurntSushi/toml

BurntSushi uses reflection, and apparently works similar to the standard `json` and `xml` packages, with `struct` annotations to perform mapping. It is also behind the TOML spec, and abandoned. ... Up to date to TOML 0.4.

The Pelletier one requires explicit navigation of a tree object structure it generates.

**Comment by andreas-kupries** [comment]
Example for using BurntSushi - https://stackoverflow.com/questions/34307488/go-how-to-use-toml-files

ConfigMaps ... Are just single-level key/value structures. You store fully nested yaml structures.
While various examples look at first glance as if they do exactly that, a second look shows that it is faked with a text block which is formatted like yaml, and can be decoded as such in a second steps. The more explicit examples fake it using a text block in json, where this is obvious.

So, I can either 

  1. Use a single config map for all the build packs, whose single key is a text block containing the actual structure, i.e. array of objects, one object per build pack.

  2. Or map each build pack to a single config map, for a collection of config maps to retrieve.

No 1. allows for trivial access via `Get` on the chosen name, and requires a secondary parsing stage.
No 2. requires retrieval via `List` (with a label-selector to get just the maps for build packs) and then direct access to the structures.

Overall I seem to prefer no 2, as it requires less hoops to jump through on retrieval.
And the number of buildpacks is not so large that speed of `List` should be an issue.

Both possibilities should have roughly the same amount of complexity for the conversion from TOML also.

**Comment by andreas-kupries** [comment]
Go forward with no 2.

**Comment by andreas-kupries** [comment]
For getting the output from the pod/container ... A variant of our tailer should suffice. The tailer cannot be used as-is because it has forwarding the received log data to carrier's stdout baked in.

**Comment by andreas-kupries** [comment]
From :rocket: ...., all @jimmykarily 

```
I  had a quick look at the issue you are working on. In case this is useful to you, if you do
`docker inspect paketobuildpacks/builder:full | less` and look for `io.buildpacks.buildpack.order`
there is a list of buildpacks. Maybe this is an alternative to what you are trying
```

```
 the builder image only lives in 2 places currently, the warm up job (which is "optional") and
the kubernetes Pipeline object. It would be easy and useful if the user could use different
builder image if they wanted to (through some carrier command). To make sure buildpack
 listing always works we should better:
- Lookup the used image in the Pipeline definition
- Inspect it and get the buildpack list
I'm not sure how to inspect the image
```

```
I think the information in docker inspect
can also be fetched with curl from the registry
it's the image metadata
the buildpack list may be in more than one places in the metadata, I just found one
maybe you can find it in shallower places
https://stackoverflow.com/questions/31025139/curl-command-for-docker-inspect
```

```
something like this should work but needs authentication:
`curl https://registry.hub.docker.com/v2/paketobuildpacks/builder/manifests/full`
```

```
 another way to do it would be:
- whenever the builder image is changed, we warm up the cluster by pulling it (this ensures
  any time we try to use the image will be instant)
- when user tries to list the buildpacks we spin up a pod/job with the builder image and run
  a command that returns the list we care about. That must be closer to what you are already
  trying to do, not sure. btw this fellow has a script that may be helpful is we want to go the
  image inspection way:  `https://ops.tips/blog/inspecting-docker-image-without-pull/`

    ops.tips
    Inspecting Docker images without pulling them
    How to inspect a docker image from dockerhub without pulling it

so in case it changes, we don't use cached information
maybe the only different is that we always lookup the used image on the Pipeline object and
collect the information from that image itself
I don't know exactly what you were doing so I'll stop brainstorming here since you probably
tried some of these already. I just wanted to give my 2 cents.
```

**Comment by andreas-kupries** [comment]
Pipeline inspection: `k get pipelines.tekton.dev -n carrier-workloads staging-pipeline -o yaml | m`
Deeper:
`k get pipelines.tekton.dev -n carrier-workloads staging-pipeline -o json | jq '.spec.tasks[1].params[0].value'`

    1 -> name = "stage"
    0 -> name = "BUILDER_IMAGE"

**Comment by jimmykarily** [comment]
For now, we documented where buildpacks come from with links to upstream docs: https://github.com/epinio/epinio/blob/main/docs/supported-apps.md

That should be enough for people to know what applications are supported. Closing until we need a better solution.
