### ISSUE TITLE
Epinio uses helm to create the workload's deployment

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1224]
This is a follow up. Ref #361 

As a first, we want to replace the deployment manifests with a generic helm chart.
See #851 the previous attempt for a generic helm chart that can be used.
We don't embed secrets and services. It is fine for the chart to work only on the Epinio cluster.

Later stories will deal with customization of the chart and being able to take (generated) charts to another cluster.

Work is done in
  * #1225
  * https://github.com/epinio/helm-charts/pull/105
  * https://github.com/epinio/application/pull/5

**Comment by andreas-kupries** [comment]
Hypper note: https://github.com/rancher-sandbox/hypper/blob/main/cmd/hypper/install.go
Specifics: https://github.com/rancher-sandbox/hypper/blob/1ac0a7588bf2bd5122218befba13d01e664b7de9/cmd/hypper/install.go#L25-L31(helm go packages)
References https://pkg.go.dev/helm.sh/helm/v3 == https://github.com/helm/helm

However see also https://github.com/mittwald/go-helm-client -- Simplified API on top of the previous?!

**Comment by andreas-kupries** [comment]
Generic chart from older work: https://github.com/manno/epinio-helm-app

**Comment by andreas-kupries** [comment]
Example resources of current direct construction...
  - [INGRESS.txt](https://github.com/epinio/epinio/files/8109020/0.INGRESS.txt)
  - [SERVICE.txt](https://github.com/epinio/epinio/files/8109022/0.SERVICE.txt)
  - [DEPLOYMENT.txt](https://github.com/epinio/epinio/files/8109023/0.DEPLOYMENT.txt)
Check against draft chart resources to note and fix differences in the setup since the draft work

**Comment by andreas-kupries** [comment]
Note: Quite a bit of the servers' operation, namely around workloads, assumes the presence of a deployment resource, and/or, and/or ingress. To keep things simple enough now it is assumed that even a custom chart will provide these three resources.

**Comment by olblak** [comment]
Did we consider saving the helm template directly in the git repository containing the application code? 
Like in the "chart" directory

I can imagine that it would have many consequences and side effects that we would have to cover such as 

- Should Epinio detect that the helm chart deployed on the Kubernetes cluster is different than the one in the git repository

But at the same time, it would allow the developer to customize the chart based on its need.

**Comment by andreas-kupries** [comment]
> Did we consider saving the helm template directly in the git repository containing the application code?

I do not believe so. You are talking about the user placing their custom app chart with the application sources, and epinio detecting such and using it for deployment, right ?

I could see this as useful for one-off apps with custom setup. However AFAIU this feature is targeted at operators deploying lots of apps all with the same custom chart. I do not see them copying their custom chart into the sources of each app.

**Comment by olblak** [comment]
> I do not believe so. You are talking about the user placing their custom app 
I more see it as a way for the developer to extend what Epinio is initially providing

1. Epinio create a helm chart with ingress+service+deployment
2. Developer add a PV&PVC
3. Epinio detect the change and apply it

I agree that it diverges from the "developer knows nothing about Kubernetes"

**Comment by olblak** [comment]
> I do not see them copying their custom chart into the sources of each app.

I would see it as Epinio deploying the code directly in the git repository

**Comment by andreas-kupries** [comment]
> 1. Epinio create a helm chart with ingress+service+deployment
> 2. Developer add a PV&PVC

How does the developer get the helm chart out of epinio ?

> 3. Epinio detect the change and apply it

How does epinio detect a change made outside of it ?

Note, when I say git repository I am thinking about a repository like on github, holding some app sources.

You seem to be talking about something else ?
Note that epinio does not have an internal git repository holding app sources or such.
(We had such at the beginning, using gitea. This is gone. Epinio stores app sources internally in a PVC. This data is not accessible to a user).
