### ISSUE TITLE
`push` has to validate the appname for characters not allowed by kubernetes.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#123]
Just tried to `cd sample-app ; carrier push "x$(date +%Y%m%d_%H%M%S)"` as a means of generating a dynamic app name so that I do not have to count myself when repeatedly `push`ing while working on the user feedback stuff.

Did not start ... Found the following error in the el-listener log:
```
PipelineRun.tekton.dev \"staging-pipeline-run-x20210208_144322-t8g67\" is invalid: metadata.name:
Invalid value: \"staging-pipeline-run-x20210208_144322-t8g67\": a DNS-1123 subdomain must consist
of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
(e.g. 'example.com', regex used for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

The issue is the name, i.e. `x20210208_144322`. The `_` is not allowed. Kubernetes rules about naming are leaking through, and we are not checking about any of these.

Found that `.` is not allowed either, in some different place:
```
admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed:
Invalid resource name: special character . must not be present: metadata.name"
```

**Comment by jimmykarily** [comment]
I would say, we should start with:

- uniqueness (in the org scope)
- allowed characters
- name size ( < 63 ? check k8s docs)
