### ISSUE TITLE
Implement origin checker for websocket upgrades

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1234]
- The application log [websocket.Upgrader](https://github.com/epinio/epinio/blob/1b4f8da2aefcb5c22e74d4e6e7b38cdc6728dbc2/internal/api/v1/application/logs.go#L80) will error out when it does not have a `CheckOrigin` function and the request contains an `origin` header
  -  See https://pkg.go.dev/github.com/gorilla/websocket#hdr-Origin_Considerations
- Request here is to add an `CheckOrigin` function to the upgrader. I think the following should work.
  - Succeeds if
    - `access_control_allow_origin` env var has not been configured 
    - `origin` header is missing
    - `origin` header matches one in the `access_control_allow_origin` list (note - might need to check the spec on how these should be compared, i think it may be everything up to the path)
- This should only be applicable to the UI when hosted in rancher, not when standalone

> Note - I only found `websocket.Upgrader` in the app log context, but this solution would need to be applied wherever sockets are used

**Comment by jimmykarily** [comment]
I'm trying to understand what kind of matching I should do between the origin header and the access-control-allow-origin setting. Reading here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin it seems that only absolute matches, `*` or `null` are valid with usage of `null` being discouraged. So checking for absolute match or `*` is enough?

**Comment by richard-cox** [comment]
I was worried we had to support multiple values for `access-control-allow-origin`, going on the docs a single one is fine. At the moment we send an `origin` which includes the `scheme`. So as long as our epinio docs specify the same when setting the helm value `accessControlAllowOrigin` then an absolute match should work (or any for `*`)
