### ISSUE TITLE
Publish Epinio on Rancher Marketplace

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1248]
### Discussed in https://github.com/epinio/epinio/discussions/1183

<div type='discussions-op-text'>

<sup>Originally posted by **agracey** January 20, 2022</sup>
We should add Epinio to the Rancher Marketplace sooner rather than later.

I'll be setting up a call shortly with the team that maintains the catalog to see if anything additional needs to be done.

In the meantime, here are a few resources on process and requirements:

- https://github.com/rancher/charts/blob/release-v2.6/docs/developing.md#introducing-a-new-package
- https://github.com/rancher/charts/blob/release-v2.6/docs/developing.md#making-changes-to-packages
- https://confluence.suse.com/display/EN/Feature+Charts+Helm+Requirements

</div>

**Comment by jimmykarily** [comment]
We got questions.yaml now: https://github.com/epinio/helm-charts/releases/tag/epinio-0.6.0

**Comment by andreas-kupries** [comment]
We do not seem to have fulfilled all the requirements yet
(My take based on reading https://confluence.suse.com/display/EN/Feature+Charts+Helm+Requirements)

  - Missing an `app-readme.md`
  - We have a CRD in the epinio chart
      - Ok, that looks to be something we can handle in the submission, via a patch to the epinio chart.
  - Our image references are not in rancher format.
  - We do not use the rancher helpers for a custom registry
    - :warning: this is not about the registry used by epinio for the app images.
    - This is about the registry where the epinio image itself is pulled from.

Something to look into in the near? future:

> UI: Charts will require creating a custom UI page for deploying as we are moving away from questions.yml.

And later on that page

> Questions.yml Deprecation

@agracey ^ What do you know about this ?

**Comment by andreas-kupries** [comment]
This issue depends on #1305

**Comment by andreas-kupries** [comment]
Work is done in PR https://github.com/rancher/charts/pull/1814

**Comment by andreas-kupries** [comment]
Created EIO request - https://github.com/rancherlabs/eio/issues/997

**Comment by jimmykarily** [comment]
Blocked by: https://github.com/epinio/epinio/issues/1680

**Comment by jimmykarily** [comment]
`rancher/helm-controller:v0.12.1` needs to be mirrored too

**Comment by jimmykarily** [comment]
> 

@andreas-kupries explained that this is included as a helm asset so this is not a blocker.

**Comment by jimmykarily** [comment]
> `rancher/helm-controller:v0.12.1` needs to be mirrored too

@andreas-kupries reminder ;)

**Comment by andreas-kupries** [comment]
> > `rancher/helm-controller:v0.12.1` needs to be mirrored too
> 
> @andreas-kupries reminder ;)

@jimmykarily Can you tell me where it was needed ? Would like to make note of that in the image-mirror PR to-be

**Comment by andreas-kupries** [comment]
And based on the results of https://hub.docker.com/search?q=mirrored-helm-controller, i.e. __nothing was found__ I will have to make an EIO request also. (In contrast to https://hub.docker.com/search?q=mirrored-coreos-flannel)

**Comment by jimmykarily** [comment]
> > > `rancher/helm-controller:v0.12.1` needs to be mirrored too
> > 
> > 
> > @andreas-kupries reminder ;)
> 
> @jimmykarily Can you tell me where it was needed ? Would like to make note of that in the image-mirror PR to-be

https://github.com/epinio/helm-charts/blob/3ece8553d285058bd2cfa7feb62b9e57a51f3b86/chart/epinio/templates/helm-controller.yaml#L49

**Comment by jimmykarily** [comment]
It makes me wonder if the condition here works as expected: https://github.com/epinio/helm-charts/blob/3ece8553d285058bd2cfa7feb62b9e57a51f3b86/chart/epinio/templates/helm-controller.yaml#L1

I mean, I was testing on a "rancher cluster", the whole file should have been skipped (?)

**Comment by andreas-kupries** [comment]
Latest PRs, i.e.
- https://github.com/rancher/charts/pull/2135
- https://github.com/rancher/charts/pull/2126

are merged. With this Epinio is released in to the Rancher v2.6 Marketplace.
