### ISSUE TITLE
Allow for developer to set custom values for apps (based on what is provided by the chosen custom appchart)

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1252]
**Is your feature request related to a problem? Please describe.**

Now that we are allowing Ops to customize the application helm chart, it would be useful to allow developers to set new values for the app deployment. This will enable more flexibility in how ops and devs work together and really allow ops to give the best DX possible.

**Describe the solution you'd like**

Allow setting of values via the CLI, the UI, and the manifest file. I'd also suggest that we don't allow overriding of values that we generate by putting all of the values in their own "tree".

**Describe alternatives you've considered**

You could likely make this work by abusing environment variables but that's really not a good way to go.

**Comment by jimmykarily** [comment]
@richard-cox suggested that we use a custom key for user provided values (e.g. `userValues`). This will allow us to show only those values in the UI so that we don't confuse the user with values they can't and are not supposed to change.

**Comment by jimmykarily** [comment]
In any case, the operator should decide which values should the user be allowed to change and Epinio should ensure the user can't change anything other than those values.

Maybe in the future the operator could provide allowed range of "values" for the various keys to limit what the user can set the keys to.

**Comment by jimmykarily** [comment]
The solution implemented here may also work for this: https://github.com/epinio/epinio/issues/1633#issuecomment-1195054999

**Comment by andreas-kupries** [comment]
> Epinio should ensure the user can't change anything other than those values.

This implies that the CLI and UI have a means of getting the information about the allowed keys from the appchart ... Either because the are listed in the appchart CR, or by going deeper into the chart and looking at the default `values.yaml` directly.

**Comment by andreas-kupries** [comment]
# Specification __Draft__ :construction: 

  - Additional option `--foo` (short `-f`), syntax `-f key=value`, help: `chart customixations variables to be used`.
    (:construction: figure out a good name of the option)
  - The option applies to `push`, `app create`, `app update`. Semantics like `--env`
  - Store the information server side: Extend `app CRD`, or YAARS (yet another app-related secret - See `env` storage).
    (:construction: Choose.)
  - Extend app manifest structure to hold this information.
  - Validation of the key/value data:
      - Doing it as part of deployment, i.e. when the appchart is pulled in to determine the referenced helm chart might be easiest. Would however also mean that app staging is done, and wasted effort.
      - Better to do before staging ... Actually even better before upload. No wasted effort at all.
          - Price is requirement for a new API endpoint to implement the validation (`app validate customizations`)
      - Basic validation is just `Does the key exist ?`.
      - Additional validation would be `Is the value ok according to declared type ?`.
      - Have to extend `appchart CRD` to contain the list of fields, types ...
          - Extending with chart level customization of the underlying chart (fixed set) enables multiple app charts to use the same helm chart in different configurations (Example: regular/stateful)
          - Or, app level customization, core of this ticket. For the example above: key `stateful`, type `bool`. Then it would be a single appchart instead of two, and the selection of the behaviour is through customization (`--foo`) instead of appchart selection (`--app-chart`). IOW `--foo stateful=true` vs `--app-chart standard-stateful`.
          - Note: With the correct implementation both possibilities would be doable.

**Comment by andreas-kupries** [comment]
- CRD PR: https://github.com/epinio/application/pull/11
  - chart PR: :construction: 
  - epinio PR: :construction:
