### ISSUE TITLE
If build fails before logging can start, no logs are shown

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1263]
**Describe the bug**

When a build fails faster than the logging can connect, the logs never show and you are left with no clue why your code didn't build.

**To Reproduce**

This is a race condition, so it doesn't always fail.

1. push app that will fail to build (12factor with buildpack.yml specifying a too old version of ruby)

"Broken" buildpack.yml in 12factor: 
```
mri:
  version: 2.6.7
```

**Expected behavior**

**Logs**

```
agracey@agracey-desktop ~/P/e/12factor> epinio push -n twelve

🚢 About to push an application with the given setup
Manifest: <<Defaults>>
Name: twelve
Source Origin: /home/agracey/Projects/examples/12factor
Target Namespace: workspace
Builder: paketobuildpacks/builder:full

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)

Create the application resource ...
2022/03/02 09:33:22 EpinioApiClient: "msg"="response is not StatusOK" "error"="Conflict: Application 'twelve' already exists" "status"=409

Application exists, updating ...

Collecting the application sources ...

Uploading application code ...

Staging application with code...

🕞  Running staging
🚢 Streaming application logs
Namespace: workspace
Application: twelve
2022/03/02 09:33:30 EpinioApiClient: "msg"="response is not StatusOK" "error"="Internal Server Error: Failed to stage" "status"=500
error pushing app to server: waiting for staging failed: All attempts fail:
#1: Internal Server Error: Failed to stage
```

**Cluster (please complete the following information):**
 - Provider: Rancher Desktop on Windows
 - Options: none
 - Kubernetes Version: 1.21.7-k3s

**Desktop/CLI (please complete the following information):**
 - OS: WSL
 - Epinio Version: 0.5.0
 - Epinio Install Options: --set domain=blah

**Comment by andreas-kupries** [comment]
The command to get the staging the logs after the fact is `epinio app logs --staging APPNAME`.

I do not see a way of getting rid of the race condition in the staging itself.
The server setting up watches and kube core processing them is inherently concurrent with the staging pod itself.

Client side the staging logs shown during push are also handled by a goroutine.
This allows the client to concurrently check and wait for staging to complete.
The log goroutine may end by itself, or be killed through a stop channel (bool).
Currently there is no report back from it to the main at all.

Possible solutions:

  1. Generally print a message referencing `epinio app logs --staging APPNAME` as a means of seeing the logs after the fact.
  2. Complexify the interaction with the log goroutine to report back how many log lines were received and printed. Print the message from (1) if that is under a threshold (less than X, ... X = 5 ?)

**Comment by agracey** [comment]
I think option #1 is likely a good thing anyways and #2 makes sense. I'd imagine you can do it all client side, right?

**Comment by richard-cox** [comment]
Note that these logs would also be shown in the UI. Could we we keep the message for no.1 general? "<something something>. Application staging logs can be viewed in the UI or CLI (`epinio app logs --staging APPNAME`)"

**Comment by jimmykarily** [comment]
There are [some recent changes](https://github.com/epinio/epinio/pull/1489/files) that probably made this even harder to reproduce. Before those changes, the time window to show the logs was until the container was stopped. Now we still return logs from stopped staging containers but only until [staging is complete](https://github.com/epinio/epinio/blob/151121bfb2aed5fb89a8a851d1c38f187a10e7ee/internal/cli/usercmd/app.go#L618). While there is still a chance that the staging is complete before we get a chance to show any logs, the fact that we will show the logs of the failed container if we have enough time to fetch it, makes the window of failure even smaller.

I will give it a try but I think, if it's too hard to reproduce maybe it's not important enough to handle.

**Comment by andreas-kupries** [comment]
And we can put a note in the docs, and/or the main output of `push` that `epinio app logs --staging ...` is available to look later.

**Comment by jimmykarily** [comment]
I can't reproduce it. I will try to show the proposed text when staging fails, just in case.

**Comment by jimmykarily** [comment]
I'll do this:

```
🕞  [stage-workspace-12fact-4148be0421665ac2f71629c70b76fdf9433zh2tc] buildpack failed to satisfy "ruby" dependency version constraint "=2.6.7": no compatible versions on "io.buildpacks.stacks.bionic" stack. Supported versions are: [2.7.5, 2.7.6, 3.0.3, 3.0.4, 3.1.1, 3.1.2] 
🕞  [stage-workspace-12fact-4148be0421665ac2f71629c70b76fdf9433zh2tc] buildpack ERROR: failed to build: exit status 1 

🚢  You can access the staging logs at any time, using this command:

epinio app logs --staging 12factor2

❌  error pushing app to server: waiting for staging failed: All attempts fail:
#1: Internal Server Error: Failed to stage
```

**Comment by jimmykarily** [comment]
I just read Richard's comment about keeping it generic. Will use this text instead:

```
```
