### ISSUE TITLE
Document Editing of Helm chart(s)

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1271]
**Is your feature request related to a problem? Please describe.**
For the new application helm charts, we should provide some mechanism to push updates or edit in place

**Describe the solution you'd like**
I'd ideally like to see a way to edit charts similar to `kubectl edit` or an editor in the UI

**Describe alternatives you've considered**
We could give access to the s3 bucket and let operators edit there but it seems dangerous

**Additional context**
This doesn't necessarily need to be done in the epinio cli but that's likely the easiest place to do this.

**Comment by jimmykarily** [comment]
Given an application helm chart will be referenced using some url pointing to a tarball, operators can alter the helm chart outside epinio and simply update the tarball Epinio consumes. If editing happens only while developing the helm chart, then we shouldn't care much about versioning and upgrading existing apps to the updated helm chart. But we need a flow on how to update a helm chart for existing applications.

E.g.
- The operator releases a helm chart
- The developer deploys an application with that helm chart
- The operator changes the helm chart

What happens next? Should Epinio automatically redeploy the application using `helm upgrade`?

I think, how the editing happens is the least important part of this process.

**Comment by agracey** [comment]
I think upgrading the workload on helm chart changes should be out of scope. That should be left to the user or some other component. 

Good practice for the ops team would be to incrementally version the chart, so maybe we keep the chart version stored in the app metadata and provide it back to the client? This way it would be trivial to script the upgrade of workload and would also keep us out of trouble if someone didn't want to upgrade their workload yet.

**Comment by jimmykarily** [comment]
We agreed to just document how to [add additional helm charts](https://github.com/epinio/epinio/issues/1270), how to replace an existing helm chart with a newer version, how to version helm charts etc. So we should do this after we have implemented #1270 and the rest of the relevant stories. This may just be docs.

**Comment by agracey** [comment]
Renamed title so I wouldn't keep thinking it was new functionality...

**Comment by jimmykarily** [comment]
WIP branch: https://github.com/epinio/docs/tree/1271-additional-appcharts
