### ISSUE TITLE
When I change the Epinio domain, apps keep the old domain

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1272]
The app ingresses (routes) are not updated to the new domain. Is there a way to change the ingress, without pushing the app?

Maybe we should implement `epinio app edit` for the app manifest or make ingresses/routes a first class data structure, by adding endpoints?

**Comment by jimmykarily** [comment]
> Is there a way to change the ingress, without pushing the app?

https://docs.epinio.io/howtos/custom_routes.html#custom-routes

We have:

```
epinio app update sample --route i-own-this-awesome-domain.org
```

**Comment by manno** [comment]
The app routes can be chosen independently from the system domain. We consider the system domain to be controlled by the clusters operator, the app routes by the developer users.  

The referenced issue on Windows can be solved by using localhost as a system domain.
