### ISSUE TITLE
`epinio app restage` command

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1275]
[We added the ability to stage an app without specifying a blob id (aka restage)](https://github.com/epinio/epinio/issues/1073) for the web UI, but we didn't implement an `epinio app restage` command.

## Acceptance Criteria

- `epinio app restage` command exists and calls the `stage` endpoint without a blobuid like the web UI does.

**Comment by enrichman** [comment]
While trying to add some tests I've encountered some difficulties, so I'm going to open smaller PRs.

Adding ApiClient interface to add some tests
* https://github.com/epinio/epinio/pull/1289  

Moving AppLogs from EpinioClient to the APIClient (to make the APIClient easy to mock)
* https://github.com/epinio/epinio/pull/1291  

Adding the `restage` command
* https://github.com/epinio/epinio/pull/1290
