### ISSUE TITLE
[Spike] Service Marketplace (powered by Helm)

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1281]
The devops team needs to be able to create Service Custom resources on the epinio cluster which will describe how a helm chart should be installed. The information needed is:

- The url for the helm chart (with a version)
- The default values
- A whitelist of values (or a range?) the user is allowed to override
- A description of the service (free text for the listing)
- A way to define what the output of the provisioning process is. It should probably be a secret but some charts create a secret using the name of the release. This is not always a static string, maybe we want a "variable" (e.g. "release_name"). TBD.

More info here: https://github.com/epinio/epinio/issues/1012

**Comment by jimmykarily** [comment]
With @enrichman we gave flux crds a try:

- https://fluxcd.io/docs/components/source/helmrepositories/
- https://fluxcd.io/docs/components/source/helmcharts/
- https://fluxcd.io/docs/components/helm/helmreleases/

with a couple of controllers installed:
- https://github.com/fluxcd/helm-controller
- https://github.com/fluxcd/source-controller

which we installed with `flux install` because the flat yamls (see the github release of each controller) were missing rbac resources so needed more work.

It turns out we could use list `helmcharts` as the available things that can be provisioned and create `helmreleases` in order to provision the services.

We also gave the [rancher/helm-controller](https://github.com/k3s-io/helm-controller) a try. It comes installed by default on k3d. Although it's very simple and does the job of provisioning a helm chart, there is no resource that can be listed that acts as the "available helm charts". In other words, before you create a helmchart (rancher one, no flux), that helm chart is nowhere on the cluster. The moment you create that resource, the helm chart is installed.

I think the flux resources make a better candidate. We now want to see if they have some field there is way to implement:

- service description
- whitelist of values the user is allowed to change
- standard secret output

Regarding the whitelist of values, flux supports [values overrides](https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides) with `spec.values` always winning. Any values defined by the operator in `spec.values` will not be available to the user to override, but this makes it a blacklist instead of a whitelist.

**Comment by jimmykarily** [comment]
If we don't find a way to implement the above features using flux crds, we can create our own Service CRD that has a these attributes and when the user requests a service to be provisioned, we can use the rancher helm-controller to install the helm chart. No flux resources in this solution.

**Comment by jimmykarily** [comment]
The following image describes the solution using a Service CRD and rancher helm-controller:

![Epinio services](https://user-images.githubusercontent.com/2794419/157880067-1a5dbcee-5515-4540-bd68-301205715559.png)

One problem is that the relation between the helmchart and the Service is lost because the rancher helmcharts don't support any labels or annotations to keep the information of what service was used to create the helmchart. In other words, Epinio will see helmcharts deployed but will not be able to tell which "service class" they implement.

**Comment by jimmykarily** [comment]
Flux helm-release [supports post rendering](https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers) which may allow us to put annotations on some resources, but possible not the helm-release itself.

**Comment by jimmykarily** [comment]
Useful information, helm doesn't support adding custom labels to releases: https://github.com/helm/helm/issues/7007

If Epinio provisions a service by calling helm directly (with not CRD involved), there is not easy way to "tag" that helm release as an Epinio service instance. Filtering which helm releases are epinio service instance among all helm releases on the cluster becomes a bit more complicated.

**Comment by jimmykarily** [comment]
Here is an idea on how to standardize the output of service provisioning.

Service CR can give the name of a secret that should become a "Configuration" and we can simply label that secret after installation is done. I tried that locally and if you put the Epinio labels on a secret, it appears in the `epinio configuration list`. When you try to `show` it it fails if the name of the secret is not following Epinio's conventions. This can easily be solved if we do the secret lookup not based on the name but on an annotation or label. In other words, any secret could become a "Configuration" if we just label it properly. This allows us to standardize the output of service provisioning like this:

- Operator defines the secret to be annotated (probably using some "template", can't be hardcoded)
- Epinio installs the helm chart and after it's done it adds the appropriate labels to the secret to make it a "Configuration".
- The name of the configuration should not be the name of the secret. Epinio should control what the configuration is called.
- `epinio service bind` is an alias of `epinio configuration bind`. This will allow the user to bind the resulting secret using the "configuration name". 

So, if user may provision a MySQL database with the name "mydb" which may result in a secret called "mydb-secret". Epinio will put an annotation/label for the Configuration name on the resulting secret with the value "mydb". `epinio configuration list" will show the new configuration with the name "mydb".  

![Epinio services - take #2](https://user-images.githubusercontent.com/2794419/159015208-49f0d97c-8470-4c48-9bdb-11dd528ae70c.png)

**Comment by gitricko** [comment]
I am really looking forward to this! Once this is working, I will move our dev environment from KubeCF to Epinio and migrate our app + CI/CD to it!

**Comment by jimmykarily** [comment]
We discussed how a service instance should be represented in Epinio. Here are the 2 options we came up with:

## Rancher helm-controller

Pros:

- `helm install` is handled by a third party controller, we don’t need to write any code for that
- Easy to label the helmchart custom resource and add meta information. This makes the helmchart a good resource to represent the “service instance”. We can put labels to tag it as a service instance and point to the catalog service this instance belongs too.

Cons:
- k3d/k3s already runs this but outside the cluster (no visible Pod). Figuring out whether to install the controller or not should be based on “capabilities”, looking up the helmchart CRD.
- The controller has to run on the kube-system namespace (https://github.com/k3s-io/helm-controller#cluster-scoped-deploys) or some other namespace but the helmcharts CRs have to be created in that namespace too. The actual helm releases can be deployed in the application namespace, next to the apps themselves but we need to manually delete the CRs before deleting the application namespace in order to have the helm charts properly uninstalled by the controller (the controller acts on CR deletion). Creating the CRs in the application namespace, seems to also work, but the namespace cannot be deleted because of failing finalizers (maybe a bug?)
- Any implementation and workaround that may work today, may break in the future because the rancher helm controller doesn’t seem to be a generic component developed to be used in non k3s cases.
- If we deploy helm-controller as part of Epinio, removing it, removes all `helmcharts`. Even traefik in a k3d cluster. Assuming we detect existing helm-controller correctly, this may not be an issue. If not, we may destroy someones cluster by uninstalling Epinio.


## Just helm releases

Pros:
- No additional components need to be installed (e.g. a controller)
- The helm releases already have the status field (e.g. `helm status epinio-postgresql -o json | jq .info.status)

Cons:
- There is no way to label a helm release. There are labels on the helm secret (when secrets are used as a storage) (https://github.com/helm/helm/blob/ee3f270e1eff0d462312635ad91cecd6f1fce620/pkg/storage/driver/secrets.go#L144) but there is no way to add custom labels to that. This means, in order to tell if a helm release is actually an Epinio service instance (and not just some release that was deployed in the application namespace by someone), we can only rely on the release name with some convention. E.g. `epinio-123-mydb` could mean, it’s an epinio service instance for a catalog service `123` (we need to implement some ID mechanism) and the name of the service instance is mydb. If we need more metadata in the future, we may not be able to fit it in the name, so this solution is very limited. Also, we are going to make every `Opaque` secret appear as a Configuration. Some helm charts name their secrets after the release, which means the Configuration would also get our suffix. We either keep it as is (giving the Configuration a suffix that makes no sense to the user) or we have to manually remove suffixes when we present Configurations (complicated).

- When we remove an application namespace, we still have to call `helm uninstall` to properly uninstall the charts. This means, we didn’t gain much compared to the helm-controller solution in that regard.

**Comment by jimmykarily** [comment]
Catalog is there. The rest of the story will continue here: https://github.com/epinio/epinio/issues/1332

**Comment by gitricko** [comment]
@jimmykarily is this in the release for 0.6.2 ? How can i test the default service catalog and create a backing service through CLI ?

**Comment by jimmykarily** [comment]
@gitricko this commit is in `0.6.2` : https://github.com/epinio/epinio/commit/222b21cd which enables the `epinio service catalog` and `epinio service catalog myservice` endpoints. These commands are "hidden" in the sense that they don't appear when you run `epinio help`. We are trying to keep the PRs small and reviewable while we ship this feature but also be able to try out what we have ready. 

Running the 2 new commands will not return any services because there are no services shipped out of the box with Epinio yet. We added MySQL, PostgreSQL and Redis here: https://github.com/epinio/helm-charts/pull/159 so the next release of the helm chart will create 3 "dev" services.

You can create a service that Epinio will list with a yaml like this one: https://github.com/epinio/application/blob/main/config/samples/application_v1_service.yaml (there is a mistake in that yaml, `chart: bitnami/postgresql`  should be `chart: postgresql`). You just `kubectl apply -n epinio -f service.yaml` that.

Still you won't be able to provision any services until the work here is done: https://github.com/epinio/epinio/issues/1332
We are actively working on this story and hoping to have something ready by the end of this or the next week. Stay tuned!

**Comment by gitricko** [comment]
Thanks for the update @jimmykarily ...

Can you include rabbitmq too in the first release, pretty please... ? Then you complete my `nameko-devex` git-repository

> Still you won't be able to provision any services until the work here is done: #1332 We are actively working on this story and hoping to have something ready by the end of this or the next week. Stay tuned!

**Comment by jimmykarily** [comment]
The reason we implement services as helm charts is to allow operators to add any service they want in an easy way. We want to avoid maintaining many services in the default Epinio installation. It may be a good idea to create a repository for additional services where people can contribute any service they want. Those services would be added to an Epinio cluster by simply `kubectl apply`ing the relevant yamls from that repo.

Would that work for you @gitricko ?

**Comment by gitricko** [comment]
Hi @jimmykarily,

Sorry for the late reply. I finally got time to play around with epinio again and realize it is now 0.7.1. I have tested the `epinio service create` for postgresql and rabbitmq and bind it... saw the configuration folder being created with credential file

However, I was stump for an hour where to get the userid and it turns out i need to look at the defaults from bitami. 

- Q1: Is there a way to configure the service with `epinio service create`

> You can create a service that Epinio will list with a yaml like this one: https://github.com/epinio/application/blob/main/config/samples/application_v1_service.yaml (there is a mistake in that yaml, chart: bitnami/postgresql should be chart: postgresql). You just kubectl apply -n epinio -f service.yaml that.

- Q2: I tried to create my own helm service above... and it worked. However, i wonder to encode `values` is it like this ?
```yaml
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: service-sample
spec:
  name: service-sample
  shortDescription: |
    A simple description of this service.
  description: |
    A longer description of the same service. This will be used when describing
    this service.
  chart: postgresql
  helmRepo:
    name: bitnami
    url: "https://charts.bitnami.com/bitnami"
  values: "{'auth.database': 'mydb-name'}"
```
- Q3: Wonder if there is a better step by step instructions to how to get real Let'sEncrypt certificates via cert-manager. My app has a webhook and plaid cant call it since it is a self sign cert.

Otherwise, this is looking really really good for dev/test environment.

Thanks!

**Comment by jimmykarily** [comment]
Hi @gitricko , thanks for trying this out. 

Q1: we agreed to keep it simple for now. No values can be passed by the user. Only the operator can define values when creating the service

Q2: Your values should work. That's how [we do it in tests too](https://github.com/epinio/epinio/blob/main/acceptance/api/v1/service_create_test.go#L102). A multi-line yaml should also work but needs testing. We just set the field of the helmchart crd which is consumed by [the rancher helm-controller](https://github.com/k3s-io/helm-controller)

Q3: We don't have instructions yet. I assume it's possible, since we have cert-manager around, and we also have our issuers. But needs some experimentation to get it right. 

I hope this helps

**Comment by enrichman** [comment]
Thanks @gitricko, I've just fixed the sample and tried the yaml version of the values. :slightly_smiling_face:
