### ISSUE TITLE
MacOS: CLI executable is blocked by GateKeeper

### ISSUE THREAD

**Issue by moio** [epinio/epinio#1284]
**Describe the bug**
Running `epinio` on the command line results in the following [GateKeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) error:

![Screen Shot 2022-03-08 at 13 39 04](https://user-images.githubusercontent.com/250541/157240718-02aad9cf-a0e8-487c-a206-f0b4136f00cb.png)

**To Reproduce**
1. download executable
2. `chmod +x ./epnio-darwin-x86_64`
3. `./epnio-darwin-x86_64`

**Expected behavior**
GateKeeper should still show a dialog, but identifying the developer and allowing to whitelist the command. Example (from Rancher Desktop):

![Screen Shot 2022-03-08 at 13 50 27](https://user-images.githubusercontent.com/250541/157241716-938a9f72-c6dd-402f-9e3c-fde1e2a3947e.png)

**Logs**
None relevant

**Cluster (please complete the following information):**
Irrelevant

**Desktop/CLI (please complete the following information):**
 - OS: MacOS Monterey 12.2.1, Intel
 - Epinio Version: v0.5.2

**Additional context**

Recent MacOS versions require notarization of executables - without notarization GateKeeper will prevent execution as per the screenshot above.

Some possible alternatives to address the issue are:
 - to just notarize executables
 - as a workaround, at least document users are expected to create a GateKeeper exception to run the non-notarized executable. This can be done by:
   - attempting and failing to run the executable once
   - going to System Preferences -> Security immediately afterwards and clicking on "Allow Anyway" from the screen below:

![Screen Shot 2022-03-08 at 13 38 51](https://user-images.githubusercontent.com/250541/157242337-dd8a06ce-40fc-4d33-973a-ea3dd2bb254b.png)

 - release the binary via a package manager such as [brew](https://brew.sh/) or [macports](https://www.macports.org/)

**Comment by pgonin** [comment]
Rancher Desktop gets official SUSE signature
Would that be required for unblocking in that case ?

**Comment by olblak** [comment]
Epinio swiched to Goreleaser to manage the release process.
So we could easily configured it as describe [here](https://goreleaser.com/customization/sign/)

The most difficult part is to identify which method to use between certificate,gpg, or cosign.
I guess we need a signing certificate.

**Comment by enrichman** [comment]
HI @moio, we have recently added the latest `epinio` version to `brew` (https://github.com/Homebrew/homebrew-core/pull/97204) .
I've tried on my Macbook and I wasn't able to reproduce the problem. Could you give a try and see if that fixes the problem?

```
brew update
brew install epinio
```

We are also working on [automating the releases](https://github.com/epinio/epinio/pull/1308). :slightly_smiling_face:
