### ISSUE TITLE
epinio chart and cli ignore the `image.{bash,awscli}.*` settings.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1305]
**Describe the bug**

This is a sub issue for #1248.

Rancher requires chart support to support airgapped installation and the like. A chart has to specify images in a specific format rancher will then use to redirect all image requests from the chart to its own registry.

While the epinio chart contains most basic support for the `awscli` and `bash` images the server uses during staging this support is incmplete. The `values.yaml` only contains the necessary repository and tag settings. Missing:

  1. The chart does not use these settings, i.e. they are not stored in cluster resources, and
  2. The epinio binary actually has the images baked into it, i.e. is not reading the information from cluster resources.

**Expected behavior**

The epinio server has to read the image information from cluster resources, and the chart has to pass the settings into whatever cluster resources the reads from.

**Proposed change**

  1. Pass the image references into the same config map the server reads the staging scripts from.
  2. Extend the epinio server to read the image references at the same time it reads the scripts.

**Comment by jimmykarily** [comment]
There is also this one:

```
internal/manifest/manifest.go:  DefaultBuilder = "paketobuildpacks/builder:full"
```

**Comment by andreas-kupries** [comment]
Yep.

Chart PR = https://github.com/epinio/helm-charts/pull/148
Epinio PR = https://github.com/epinio/epinio/pull/1311
