### ISSUE TITLE
Test Epinio installation on top of nginx ingress controller

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1323]
Now it's possible to install epinio with nginx ingress controller, we should add a test for this scenario. 
acceptance install test? and/or e2e test?

- [x] Manual test
- [x] Automated test

**Comment by juadk** [comment]
Manual test:

1. Deploy k3s without traefik 
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy traefik" sh -`
2. Install cert-manager
```
kubectl create namespace cert-manager
helm repo add jetstack https://charts.jetstack.io
kubectl create namespace cert-manager
helm install cert-manager --namespace cert-manager jetstack/cert-manager  --set installCRDs=true  --set extraArgs[0]=--enable-certificate-owner-ref=true
```

3. Install the nginx controller
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml`

Two choices here:

- Patch ingressclass resource to add the annotation `is-default-class": "true"`
`kubectl patch ingressclass nginx --type=merge -p '{"metadata": { "annotations": {"ingressclass.kubernetes.io/is-default-class": "true"}}}'`

or
- Install Epinio with this option `--set ingress.ingressClassName=nginx`

4. Install Epinio
```
helm repo add epinio https://epinio.github.io/helm-charts
helm repo update
helm install epinio -n epinio --create-namespace epinio/epinio --set global.domain=<MY_IP>.omg.howdoi.website
```

5. Epinio embedded UI should be reachable at `https://epinio.<MY_IP>.omg.howdoi.website`

I deployed an app and it worked well.

**Comment by gitricko** [comment]
@juadk I verified that this work using my Makefile test as well: https://gist.github.com/gitricko/b5125a3649e5d52faec4e4f9a496e166

``` DOMAIN=<MY_IP>.omg.howdoi.website make install-epinio-nginx ```
This will test the console app + simple conda-app.

However, it failed on my own app (works via traefik)
```
🚢 About to push an application with the given setup
Manifest: <<Defaults>>
Name: expense-mgt
Source Origin: /home/ubuntu/environment/expense-mgt
Target Namespace: workspace

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)

Create the application resource ...

Collecting the application sources ...

Uploading application code ...
error pushing app to server: can't upload archive: server status code: Request Entity Too Large
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Looks like i need to configure the nginx

**Comment by juadk** [comment]
@gitricko Thanks for the feedback, I will try to reproduce with your env.

**Comment by juadk** [comment]
My first automated test on EKS is green https://github.com/epinio/epinio/actions/runs/2101908969
I'm trying to enable more logs in the test.

**Comment by gitricko** [comment]
> @gitricko Thanks for the feedback, I will try to reproduce with your env. For now, I only tested on k3s, I will test more infra for sure.

In order for you to reproduce it... you need to push a large project with lots of files... then it will break nginx. But i believe that can be resolve if you can configure nginx.conf with these directive

```
...
 # src: https://github.com/cloudfoundry/capi-k8s-release/issues/6
 client_max_body_size 9999M;
...
```

where you need to se the client_max_body_size to a large value than the default when it was undeclared

**Comment by juadk** [comment]
> In order for you to reproduce it... you need to push a large project with lots of files... then it will break nginx. But i believe that can be resolve if you can configure nginx.conf with these directive

I think I don't have such a project... but if I understand correctly, it's more a configuration tuning of nginx, so not directly related to Epinio.

**Comment by gitricko** [comment]
the question is how do we install nginx in such a way that we can configure above attribute (client_max_body_size)

**Comment by juadk** [comment]
> the question is how do we install nginx in such a way that we can configure above attribute (client_max_body_size)

I've found this https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size
But I'm not sure we want to deal with nginx specificities in the Epinio's documentation. Maybe just giving the link with a short explanation will be enough?
