### ISSUE TITLE
As support staff, it would be nice to have a "Debug Mode"

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#133]
It might be worth having a "debug mode" that sets up kubeapi watch commands before any resources get created (other than the CRDs themselves)

This could help with diagnosing any race conditions or unmet dependencies.

**Comment by andreas-kupries** [comment]
This sounds to be something for users who have great knowledge of internals. ... I.e. us developers of the system.
I am not as convinced that regular users will have use for it.
Except when something breaks, to activate it on request from a developer, to get a deeper view into the operation and derailing.

**Comment by agracey** [comment]
Right, I guess the title is wrong. Should be "As a support engineer".

**Comment by andreas-kupries** [comment]
Now that makes sense

**Comment by jimmykarily** [comment]
Debugging Epinio installation (or Epinio in general) is something for the ops team not the developer. As such, it can be done with the regular tools (e.g. kubectl). Nothing we add to Epinio will make it easier than simply using kubectl but it will be a nightmare to maintain and keep it useful. I will close this until there is a user demand.
