### ISSUE TITLE
Look at removing quarks from installation procedure

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#134]
I understand that quarks is used only for secret generation at the moment. To my outsider perspective, this seems like a lot of maintenance overhead for minimal benefit. 

I'm not familiar with the specific, but would it be possible to do this generation in helm, or kustomize, or maybe the carrier cli itself? I've also seen other projects just pre-compute a sane default then document how to change it.

For cert generation, there is cert manager which can totally do self signed certs https://cert-manager.io/docs/configuration/selfsigned/

**Comment by jimmykarily** [comment]
Worth investigating @agracey thanks. I'm linking to this issue here: https://github.com/SUSE/carrier/issues/129

because at least the image could be a lot smaller (which reduces the overhead but not the maintenance one).

**Comment by agracey** [comment]
@andreas-kupries @jimmykarily This is done, right?

**Comment by jimmykarily** [comment]
No we still installs quarks secret and use it to generate at least one resource here: https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L497
That is a CA so we should be able to use cert-manager for that too. Let's keep this open to investigate.

**Comment by jimmykarily** [comment]
Quarks is gone. Closing.
