### ISSUE TITLE
`epinio app export` extract image too

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1352]
The `epinio export` could be used to migrate the app deployment to a different cluster.
The command is missing the export of the image.

Follow up of: https://github.com/epinio/epinio/issues/1253

# Acceptance Criteria

- `epinio app export` also extract the application image in some format which allows it to be imported to some registry
- [Optional] make it optional with some flag

**Comment by enrichman** [comment]
After the epinio export, the import can be done with helm.
