### ISSUE TITLE
build-in services should have a stubbed version

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1363]
Currently we just install the latest version of the helm charts but the user has no idea what version they get.

## Acceptance Criteria

- It is clear to the Epinio user, which version of the service they get
- The user always gets the same version when they provision the same catalog service

**Comment by thardeck** [comment]
The four supported services are provided here from bitnami: https://github.com/epinio/helm-charts/blob/main/chart/epinio/templates/service-catalog.yaml

The current Chart `version` and `appVersion` for these services can be looked up here:

- https://github.com/bitnami/charts/tree/master/bitnami/mysql
- https://github.com/bitnami/charts/tree/master/bitnami/postgresql
- https://github.com/bitnami/charts/tree/master/bitnami/redis
- https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq


For showing the version we probably need to adapt the Service cli `catalog`, `list`, `create` and `show`. The same goes for the api models to provide feature parity.

Regarding #1356 we might need to show two versions, the currently installed/used version of a service and the version referenced by the installed Epinio release. But this could be done as part of the upgrade implementation I suppose.

**Comment by andreas-kupries** [comment]
Question. The internal `helm` package used by app deployment allows the helm chart to be specified by name and version.
These two pieces of information are pulled out of the appchart `Name` field, splitting it on `:`. IOW it is possible to specify a
chart `foo:v2` and the deployment system will look for and use chart `foo`, with version/tag `v2`. 

Without a version/tag in the name, i.e. just `foo` the implied version is `latest`.

Does the service code support the same (kind of) thing ?

The ticket description seems to mix two things:

  - Showing a concrete chart version for a service instance which was deployed with the implied `latest`.
    That is something which should be retrievable from the deployed release.
    - Or is it desired to show a concrete version for the service class, when nothing is specified ?
      That would require helm repo access for each class when the catalog is listed, i.e. get all the available versions for a named chart, then select down to the latest, or directly get the latest version (not sure if that is possible for a helm repo).
      Caching ... Not good, as the latest version can change any time.
  - Setting a concrete version on the builtin service classes to ensure getting a specific version.
    This points back to my question at the beginning, if the code actually support specifying a version for a chart.

**Comment by andreas-kupries** [comment]
Well ...

  - service catalog X
    - Does not show all details. I.e. all the helm information is missing.
  - service create
     - Does not show the configuration / details of the new service.
     - Does not wait for the service creation to be complete.

Service version not supported in the code yet. Looks to be easy to add however.
