### ISSUE TITLE
Bump goreleaser to 1.8.x

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1365]
Up to know we used the latest goreleaser version in our release pipeline but after 1.18.0 our releases broke: https://github.com/epinio/epinio/runs/6078945820?check_suite_focus=true

[We reverted to `1.7.0`](https://github.com/epinio/epinio/pull/1366#pullrequestreview-945786739) to make it work but we need to find what the issue is.  This looks relevant: https://github.com/goreleaser/goreleaser/pull/3016

**Comment by manno** [comment]
Opened issue upstream: https://github.com/goreleaser/goreleaser/issues/3057
