### ISSUE TITLE
Services shell completion (and "match" endpoints)

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1367]
`epinio service show` (and `delete` ?) doesn't have tab completion like other commands do. To make this work, we are missing a "match" endpoint to find matching service instances, plus some cobra configuration.

**Comment by jimmykarily** [comment]
Done here? https://github.com/epinio/epinio/commit/b3070bf2445a2150039e0536d5628842c45f75d3

**Comment by andreas-kupries** [comment]
The b3070bf is for #1486, fixing issue #1476, which looks to be a duplicate of this here.
I would go with "this here is done".
