### ISSUE TITLE
User should be able to log in 

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1374]
**Is your feature request related to a problem? Please describe.**
In the current configuration, we have a bit of a bootstrap problem where you either need to build the `~/.config/epinio/settings.yaml` file or have access to the cluster to run `epinio settings update`.

**Describe the solution you'd like**
A user should be able to run `epinio login` that would ask the user for the api url, username, and password.

**Comment by jimmykarily** [comment]
The settings file also needs the CA for the epinio server which can't be fetched through the epinio API unless we expose that API through plain http too. The idea was that the operator give the user the full `settings.yaml` file not just the credentials. Pretty much like it happens with kubeconfig files.

**Comment by agracey** [comment]
The more important part of this is what is stored in kubernetes. 

The password field there should be stored salted and hashed in a non-reversable way. Then when an auth request comes, you compare using the verify function instead of equality. 

For the human side of this, the admin would hash a password, store the output while giving the input to the developer. Or the developer would give the hashed password to the admin to store. 

This weirdness is why we need to eventually work with an upstream auth provider (such as Dex) and not handle passwords ourselves. That and people are going to ask how to hook into their existing LDAP server.

**Comment by enrichman** [comment]
@agracey thanks, I think that the comment was related to the https://github.com/epinio/epinio/issues/1361 issue though.
This login part is going to affect only the developers settings.

I will address the hashed password issue in a separate PR.

**Comment by agracey** [comment]
You are right... I had both open next to each other

**Comment by agracey** [comment]
Since the change to hashed passwords will break `epinio settings update` and likely force this log in flow, the two likely need to release at the same time.

We will need to document this change as soon as both are released:

- https://epinio.io: https://github.com/epinio/epinio.io/blob/main/content/_index.html
- https://github.com/epinio/helm-charts/blob/main/chart/epinio/templates/NOTES.txt
- https://github.com/epinio/homebrew-tap/blob/main/Formula/epinio.rb
- https://github.com/epinio/extension-docker-desktop/blob/main/ui/src/epinio/Pusher.js
- Digital Ocean scripts, not sure where they are?
- https://github.com/epinio/docs/blob/main/docs/tutorials/quickstart.md (should add a note about logging in)
- https://github.com/epinio/docs/blob/main/docs/howtos/install_epinio_on_rancher_desktop.md
- https://github.com/epinio/docs/blob/main/docs/references/authorization.md
- https://github.com/epinio/docs/blob/main/docs/references/cli/epinio_settings_update.md

Any other place referencing `epinio settings update`

This workflow change should also be noted in the release notes as it's a breaking change for anyone already using the platform.
