### ISSUE TITLE
Chore: code clean up

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1378]
Clear out any dead code paths and refactor for maintenance quality of life

**Comment by jimmykarily** [comment]
Refactoring and removing dead code can be done at any point, it's not even a major version bump (doesn't change any functionality). I don't think we need this to be in `v1` milestone.

**Comment by agracey** [comment]
This came up in the v1 planning but I forgot who asked for me to add it. IIRC, the thought was it would make maintenance easier longer term so pushing it into 1.0 made sense. 

I'm ok to drop it from the milestone
