### ISSUE TITLE
Document what customizations are supportable

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1379]
**Is your feature request related to a problem? Please describe.**
We have several places where admins can change the behavior of the system. We should document which ones are safe and to what extent they can be changed.

**Comment by jimmykarily** [comment]
Are we talking about these?

- load balancers (traefik, nginx etc)
- S3 backends (minio, aws, etc)
- registries (built-it, dockerhub etc)
- builder images during staging
- app charts
- catalog services
- other?

**Comment by agracey** [comment]
Yes. I think what likely needs to be written is what features of each boundry that we need (that might not be generic).

For example, could likely say that "We use the networking v1 Ingress and work with any ingress that consumes it" and be done with ingress but might need a little more language around app charts and catalog services. For those, I'd imagine it doesn't need to be longwinded, just enough to give an impression of what can be changed without breaking (e.g. "needs to have an ingress and deployment for the api to pull the right data back.").
