### ISSUE TITLE
Document developer onboarding

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1382]
Since we already have support for multiple users, we should document the workflow for onboarding a developer into an Epinio cluster.

**Comment by jimmykarily** [comment]
We already have this page: https://docs.epinio.io/references/authorization#add-a-new-user

I guess the request is for a dedicated "onboarding users" page (?). cc @agracey

**Comment by andreas-kupries** [comment]
Define "onboarding". What are the things and actions you (@agracey) consider to be "onboarding" ?

**Comment by agracey** [comment]
What I was thinking was that adding a new developer to a project is a relatively common task. We need to document the flow of getting that dev set up. That would be 

- What the admin (or automation) needs to set up
- What the admin needs to communicate to the developer
- How the developer logs in to get going (without access to kubectl)

This should likely be done after [any new login flow is done](https://github.com/epinio/epinio/issues/1374) and [we are more secure](https://github.com/epinio/epinio/issues/1361)

**Comment by andreas-kupries** [comment]
The first of the tutorials covering this issue is https://github.com/epinio/docs/pull/145
As there are more tutorials coming this ticket will stay open and in progress.

**Comment by jimmykarily** [comment]
The PR it merged. We are planning to do some additional work on this but no need to keep this issue open.
