### ISSUE TITLE
How-To: Orchestrate Services that actually creates native cloud services

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1384]
**Is your feature request related to a problem? Please describe.**
Love version 0.7.1 where I could create backing service via `epinio service create`. Even love how easy to add new services as helmcharts into the [service catalog](https://github.com/epinio/epinio/issues/1281#issuecomment-1089850024) All these are useful for local dev-test environment but I wonder if we can use the same consistent way to create services from the native Cloud infrastructure. eg: AWS RDS postgres 

**Describe the solution you'd like**
eg: `epinio service create aws-rds-postgres mypostgres`

**Describe alternatives you've considered**
I understand you can create these AWS service separately and then use epinio configuration to store the secrets.. but it does not seems quite right

**Additional context**
eg: Similar to CF create service where if you have install service broker app and registers them as service broker

**Comment by enrichman** [comment]
Closing this, since we have found a way on how to leverage the AWS cli during the creation of a service.
