### ISSUE TITLE
Bump DO Epinio version

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1388]
[We now have Epinio listed](https://github.com/epinio/helm-charts/issues/63) but the version is still 0.5.0. We need to bump it to the latest version.

We also need to try out the instructions and scripts to make sure they are working (https://github.com/epinio/epinio/issues/1391)

**Comment by juadk** [comment]
I opened a separate issue to track the installation test https://github.com/epinio/epinio/issues/1391

**Comment by jimmykarily** [comment]
Currently installing on DO doesn't work. We've sent an email to their support and we opened a thread here: https://forum.digitalocean.com/t/how-can-i-debug-the-deploy-sh-script/695

**Comment by jimmykarily** [comment]
PR: https://github.com/digitalocean/marketplace-kubernetes/pull/381/files

**Comment by jimmykarily** [comment]
This PR is not moving. Let's replace it with one that removes Epinio from the markeplace.

**Comment by jimmykarily** [comment]
Our PR has been merged. I tried the 1-click installation and it worked file. I also updated the instructions (through vendor's portal) to match v1.0.0 and the fact that we no longer have `epinio settings update`. The instructions haven't been updated yet, I think there is some manual review process involved.

**Comment by jimmykarily** [comment]
I sent an email to one-clicks-team@digitalocean.com and CCed team@epinio.io

**Comment by jimmykarily** [comment]
And it's now updated.
