### ISSUE TITLE
`epinio service unbind` command

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1390]
Users can unbind the secrets with `epinio configuration unbind` but it's confusing if they bound the service with `epinio service bind` and especially if that bound more than one secrets. An `epinio service unbind` command that unbinds all the secrets belonging to the service would be useful.

Relevant story: https://github.com/epinio/epinio/issues/1359 (same backend code?)

**Comment by gitricko** [comment]
Yes, i was confuse... thanks for clarification. I think having a service unbind will make it consistent

**Comment by jimmykarily** [comment]
WIP branch: https://github.com/epinio/epinio/tree/1390-service-unbind
