### ISSUE TITLE
Try installing Epinio in Digital Ocean

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1391]
I tried to install Epinio 0.5.0 in Digital Ocean but I got an error without any clue about what failed there.

### Select Epinio in the marketplace
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/6025636/165295202-779ba618-4cd0-4502-a885-e095b6ae881f.png">

### Install it in a fresh cluster
![image](https://user-images.githubusercontent.com/6025636/165294365-1259ed8e-f18b-4ae9-a4ef-2cd86e13d69c.png)

![image](https://user-images.githubusercontent.com/6025636/165294219-cfae7811-af90-4922-83b5-ffd7afd431e0.png)

### Installation error
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/6025636/165295047-0fc76892-7b0d-4b4c-ba56-b4db7368de7a.png">

Unfortunately, no log or event in the k8s cluster, I don't even see a pod created by epinio installation.

**Comment by juadk** [comment]
@jimmykarily just requested help [on the Digital Ocean forum](https://forum.digitalocean.com/t/how-can-i-debug-the-deploy-sh-script/695)

**Comment by jimmykarily** [comment]
Opened a PR here: https://github.com/digitalocean/marketplace-kubernetes/pull/381/files

**Comment by jimmykarily** [comment]
Bumped Epinio chart version to v1.0.0 in the PR

**Comment by jimmykarily** [comment]
Made a comment here: https://github.com/epinio/epinio/issues/1388#issuecomment-1115867209

Closing this.
