### ISSUE TITLE
Can't restage a failed app

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1393]
I tried to stage [an app](https://github.com/gofiber/recipes/tree/master/heroku). I created this Procfile:

```
web: heroku
```

and the app fails to start with this error:

```
bash: heroku: command not found
```

I tried to fix the application by changing the Procfile but when I push again I get:

```
❌  error pushing app to server: can't deploy app: Internal Server Error: another operation (install/upgrade/rollback) is in progress
```

This is Epinio failing to call `helm install` . The only way to fix the problem is delete the app and push again. It should be possible to re-stage a failed app without deleting it.

**Comment by jimmykarily** [comment]
There is a [`Recreate`](https://github.com/mittwald/go-helm-client/blob/ff8c3f746ba437180065a19ce9dbe4e67abc3531/types.go#L141) flag that, when set to true, makes the next `epinio push` to succeed. There is still the problem that `epinio push` doesn't return although the Pod errors out. There must be a way to tell helm to return when some Deployment/Pod returns errors. Otherwise the helm deployment is stuck in `pending-install` state. It can only be listed with:

```
helm list -A --pending
```

**Comment by andreas-kupries** [comment]
@jimmykarily Note https://pkg.go.dev/github.com/mittwald/go-helm-client#ChartSpec.Timeout

This timeout should stop the push after a while ...

Checking ... We are using it: https://github.com/epinio/epinio/blob/a6689cf879b38181ae010e091b999f114489a0a8/internal/helm/helm.go#L185
And the value is: 10 minutes https://github.com/epinio/epinio/blob/a6689cf879b38181ae010e091b999f114489a0a8/internal/duration/duration.go#L13

**Comment by andreas-kupries** [comment]
Running until timeout (for this test reduced to 5 min) you get:

> 🕞  [stage-workspace-fox-12-9f9a7e6963dc51d0a7d496b530df345e738k78cj] buildpack Adding cache layer 'paketo-buildpacks/go-build:gocache' 
🕞  [stage-workspace-fox-12-9f9a7e6963dc51d0a7d496b530df345e738k78cj] buildpack _ _ __ ___ _____ Done 

> Deploying application ...

> ❌  error pushing app to server: can't deploy app: Internal Server Error: release fox-ff0f0a8b656f0b44c26933acd2e367b6c1211290 failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
work@tagetarl:~/SUSE/dev/epinio> 

I wonder, should maybe run a progress indicator while `Deploying application ...`.

... Done ... And reduced timeout to 2 minutes, from the original 10.

**Comment by jimmykarily** [comment]
I'm not sure if every application can be deployed in 2 minutes. Given this timer starts after staging, the only thing that can be slow is the downloading of the produced image from the registry. Depending on the size of the image, where the registry and epinio live, this could be slow.

 Since helm doesn't tell us what is going on with the deployment, another approach would be to monitor the application pods ourselves. This creates even more requirements and limitations on what the application chart needs to implement (e.g. we wanted to allow some flexibility so that the operators could use Statefulsets instead of Deployments), but I think we could always expect the application to run inside properly labeled Pods. While deployment is happenening, we could show the status of those Pods. E.g. `not-created-yet`, `running`, `failing with error: ...` . 


Also, I'm wondering if we do anything after `helm install` which will be skipped in the case of a timeout. iirc, it should work fine eventually, if it just needed more time.

**Comment by andreas-kupries** [comment]
> Since helm doesn't tell us what is going on with the deployment

We do have a log callback. You see the output from that in the server log. However even that only provides a basic not ready report.

```
2022/06/21 11:58:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="creating 4 resource(s)"
2022/06/21 11:58:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="beginning wait for 4 resources with timeout of 5m0s"
2022/06/21 11:58:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Deployment is not ready: workspace/rboring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f. 0 out of 1 expected pods are ready"
[...]
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Install failed and atomic is set, uninstalling release"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="uninstall: Deleting boring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Starting delete for \"rboring-boring1721904o-b2ec8ed3c4ca870f587712abff5a9a091778d042\" Ingress"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Starting delete for \"rboring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f\" Service"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Starting delete for \"rboring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f\" Deployment"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="Starting delete for \"rboring-boring1721904o-b2ec8ed3c4ca870f587712abff5a9a091778d042\" Certificate"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="helm" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "report"="purge requested for boring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f"
2022/06/21 12:03:28 EpinioServer: "level"=1 "msg"="responding with json error response" "requestId"="c3b43a32-8e8e-4f0e-8b4e-416989bc7e2a" "action"="github.com/epinio/epinio/internal/api/v1/application.Controller.Deploy-fm" "errors"="release boring-2c7fba49380be2a63d1f9f8c9fcad20bb1d23d0f failed, and has been uninstalled due to atomic being set: timed out waiting for the condition"
```

**Comment by andreas-kupries** [comment]
> While deployment is happenening, we could show the status of those Pods. E.g. not-created-yet, running, failing with error: ... .

Remember that this would require either cli polling, or a websocket to transfer the stream information from server to cli/ui.

That feels to me to be something out of scope for v1. Big change, high risk.

**Comment by andreas-kupries** [comment]
> I'm not sure if every application can be deployed in 2 minutes. Given this timer starts after staging, the only thing that can be slow is the downloading of the produced image from the registry. Depending on the size of the image, where the registry and epinio live, this could be slow.

3 minutes feels ok to me ... 4 minutes and higher I see the user getting strongly impatient ...

**Comment by jimmykarily** [comment]
ok how about we:

- allow the user to restage (by updating the release)
- Decrease the timeout to something sane
- Create an issue to handle this better post-v1

**Comment by andreas-kupries** [comment]
We have done the first two things here. I will make the issue for post-v1.
