### ISSUE TITLE
Remove the create/delete operator actions from the `epinio app chart` ensemble.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1400]
We currently expose the `epinio app chart create` and `... delete` commands.
These commands signify operator actions which should not be available to developers.
Hide the commands at least.
Better remove them entirely.

@agracey Comments ?

**Comment by agracey** [comment]
I'd remove them for now. We can add back in after we have "RBAC"

**Comment by andreas-kupries** [comment]
Ok. See #1401 for the work ... :construction: updating the tests.
Removal was minimal, to allow for trivial restoration.

**Comment by agracey** [comment]
git cherry-pick reverts FTW!
