### ISSUE TITLE
Application pod does not restart after Git commit and subsequent staging

### ISSUE THREAD

**Issue by troytop** [epinio/epinio#141]
I edited the source of my application in Gitea and committed the change. I wasn't sure this would trigger staging, but it did. 

The staging completed successfully, but the application pod did not restart.

Manually restarting the application pod showed the changes to the app.

**Comment by agracey** [comment]
Now when I push again, I get ```🚢 Application already exists. Updating.

Webhook already exists.```

**Comment by thardeck** [comment]
Confirmed duplicate of  #262, will be fixed soon as part of that issue.
