### ISSUE TITLE
Add API endpoint to download app manifest

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1427]
**Is your feature request related to a problem? Please describe.**
- CLI offers an `epinio app manifest` command to create a manifest
- The UI is unable to use this

**Describe the solution you'd like**
- Provide the same functionality as the cli but over API
- Suggest something like GET `/namespaces/{Namespace}/applications/{App}/manifest`

**Describe alternatives you've considered**
- It doesn't look like the command does much but convert the app resource into a different format. This could be replicated in the UI but could be brittle on manifest changes

This blocks https://github.com/epinio/ui/issues/30

**Comment by andreas-kupries** [comment]
The endpoint underlying `e app show` provides all the information needed to create the manifest from it.
See the code at https://github.com/epinio/epinio/blob/main/internal/cli/usercmd/app.go#L269-L284
The manifest structure is just a bit of a wrapper around name, configuration, and origin structures we find in the result of show.
In a sense `e app manifest` is just a different transform of the data displayed by `e app show`.

A new endpoint is not required.

**Comment by andreas-kupries** [comment]
Relevant structures:

  - Show response: https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/models/app.go#L30-L33
  - Manifest: https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/models/models.go#L79-L87

The saved manifest is simply the yaml marshaling of that structure, with some parts hidden.

**Comment by richard-cox** [comment]
I would still vote that business logic like creating a manifest should be done in a central, common point rather than duplicated in clients. Lets discuss this in the next planning call

**Comment by richard-cox** [comment]
After thinking about this, the UI is now closely coupled with the manifest anyway (in the create app process the user can upload a manifest and the UI then assigns those values to internal structures). So if the manifest changes it will break the UI anyway. Given that, the UI might as well create manifest
