### ISSUE TITLE
Chore -- Add samples that are more complex OSS projects

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1428]
Our current samples are pretty simple and don't give a good example of the power and flexibility of our solution. It would be nice to smoke test, document, and demo how to use Epinio for larger OSS projects. 

Some potential projects to look at:
- https://github.com/openEHR
- https://github.com/rancher
- https://github.com/salesagility/SuiteCRM
- https://github.com/magento
- ???

**Comment by gitricko** [comment]
I personally think it is a great idea. I am going to my own at some point using https://github.com/gitricko/nameko-devex (it has smoke-test, stress test and it is compatible with CF) Having a PaaS that it can deploy to from 1 [make](https://gist.github.com/gitricko/b5125a3649e5d52faec4e4f9a496e166) command is very attractive.

Another real work example that i can think of is Plaid's Pattern.
https://github.com/plaid/pattern

**Comment by andreas-kupries** [comment]
Look into more concrete tickets coming out of https://github.com/epinio/epinio/wiki/Deployment-Sharing-Session
