### ISSUE TITLE
[CI] - GKE tests fails since 4 days

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1434]
We have to investigate why our GKE tests are failing since 3 days.
To understand the failure, I think we will need to reproduce it ouside of the CI.
First broken test: https://github.com/epinio/epinio/actions/runs/2279391144
Log:
```
<Scenario1> GKE, epinio-ca
  Installs with loadbalancer IP, custom domain and pushes an app
  /home/runner/work/epinio/epinio/acceptance/install/scenario1_test.go:48
STEP: Checking LoadBalancer IP 05/06/22 02:47:13.87
------------------------------
• [FAILED] [49.647 seconds]
<Scenario1> GKE, epinio-ca
/home/runner/work/epinio/epinio/acceptance/install/scenario1_test.go:19
  [It] Installs with loadbalancer IP, custom domain and pushes an app
  /home/runner/work/epinio/epinio/acceptance/install/scenario1_test.go:48

  Begin Captured GinkgoWriter Output >>
    STEP: Checking LoadBalancer IP 05/06/22 02:47:13.87
  << End Captured GinkgoWriter Output

  Unexpected error:
      <*json.SyntaxError | 0xc0004228b8>: ***
          msg: "invalid character 'W' looking for beginning of value",
          Offset: 1,
      ***
      invalid character 'W' looking for beginning of value
  occurred
  In [It] at: /home/runner/work/epinio/epinio/acceptance/install/scenario1_test.go:63
```

**Comment by andreas-kupries** [comment]
This sort of looks like an endpoint returning non-json data where the test expected to always get json.
Might be useful to insert strategic `By()` commands in the text to show values before `Expect`ing on them.

**Comment by jimmykarily** [comment]
Maybe we should handle this in the code itself. We can try to parse json and when that fails we can throw an error that includes the raw text.

**Comment by jimmykarily** [comment]
Sorry, my mistake, the parsing happens in the test itself. Lets fix it on the test then.

**Comment by jimmykarily** [comment]
PR: https://github.com/epinio/epinio/pull/1438

**Comment by jimmykarily** [comment]
There is a warning line printed before the actual json:

```
  W0511 10:04:00.206992   11715 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
  To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
  ***
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": ***
          "annotations": ***
              "cloud.google.com/neg": "***\"ingress\":true***",
              "meta.helm.sh/release-name": "traefik",
              "meta.helm.sh/release-namespace": "traefik"
          ***,
```

I'm not sure if that line is printed to the error stream but even if it did, [the method we use](https://github.com/epinio/epinio/blob/cc1b6e7a36046367f81ff20c3159e9a122424e1d/acceptance/helpers/proc/proc.go#L35-L42) writes both streams to the same buffer so we can't skip the error one. Maybe it's simpler to just fix the warning.

**Comment by juadk** [comment]
yes I agree, I will fix the warning.
