### ISSUE TITLE
Auth unit test non-deterministic failure

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1455]
**Describe the bug**

Intermittent failure of auth unit test for auth package. See with commit 27a98279141f48dfcd2f5f12c7107b2845bde2ba

> Auth users RemoveNamespaceFromUsers when users have the namespace [It] will be removed
> /home/work/SUSE/dev/epinio/internal/auth/auth_test.go:168  Expected
>       <string>: user3
>   to equal
>       <string>: user2
>   In [It] at: /home/work/SUSE/dev/epinio/internal/auth/auth_test.go:191

Rerun the tests and it likely passes. 

It looks as if the expected call order of `user2 user3` does not always happen.
It looks as if `user3 user2` is also possible.

I suspect that a go map is involved. Their iteration order is not deterministic.

**To Reproduce**

Go to the referenced commit. Compile epinio. Run the unit tests until the error is seen. multiple times might be required given the non-determinism.

**Expected behavior**

Always pass, do not fail.

**Comment by andreas-kupries** [comment]
A first attempt at fixing this revealed that the bad case comes with a call count of 3, instead of 2. There is something deeper going on than just the unexpected order.

**Comment by enrichman** [comment]
This should be fixed now that #1460 is merged.
