### ISSUE TITLE
Add additional information to service instance resource type

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1466]
Let's record the **version** of the catalog service that was used at the time of provisioning, on the instance itself (label on the helmchart resource?)

We want the "app version", not the helm chart version (which is already recorder on the `helmchart` resource).

**Comment by jimmykarily** [comment]
- [ ] Create/update tests
- [ ] Add the label
- [ ] Serve the information through the API
- [ ] Show the information on the cli
- [ ] Server the information on the web UI
