### ISSUE TITLE
Track buildpack data in the Application resource

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1468]
**Is your feature request related to a problem? Please describe.**
In order to add more value to the UI we would like additional information extracted from the staging process to be supplied to the UI via the `application`'s `deployment` property

**Describe the solution you'd like**
Looking at the build logs the default builder image `paketobuildpacks/builder:full` outputs the type of buildpack it uses. 

![image](https://user-images.githubusercontent.com/18697775/169046405-10045173-4ba7-4538-8647-24c83d9431f2.png)

We would like the following info added to the `deployment` property 
- Friendly build pack name (`Paketo Procfile Buildpack`)
- Build pack version (`5.1.1`)
- Build pack link (`https://github.com/paketo-buildpacks/procfile`)

**Comment by jimmykarily** [comment]
There is the BOM (bill of materials) label on the generated image. We can probably find the used buildpacks in that.

**Comment by agracey** [comment]
I don't think we should track this on the Application resource but instead look it up from annotations on the OCI artifact (And if those don't exist, we should write an rfc to add them)
