### ISSUE TITLE
Add additional information to configuration resource type

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1471]
**Is your feature request related to a problem? Please describe.**
We should be able to determine where a configuration came from, in particular if the configuration was associated with a service instance. This will help the user differentiate between their own configurations and those created by epinio. Other functionality can be gated on this as needed (prevent deletion of configurations created by epinio)

**Describe the solution you'd like**
The configuration resource looks roughly like 
```
   {
      "meta":{
         "name":"from-ui-my-redis",
         "namespace":"from-ui"
      },
      "configuration":{
         "user":"",
         "details":{
            "redis-password":"uasfRHYhqL"
         },
         "boundapps":[
            "chatty-app"
         ]
      }
   }
```
The `configuration` section should contain information on
- if applicable, the name of the service instance that caused the configuration to be created
- any other interesting things epinio has available 
  - epinio.suse.org/configuration-type: custom 

**Additional context**
- See discussion in slack, started 18th May

**Comment by jimmykarily** [comment]
Let's consider blocking the deletion of Configurations that belong to services on the API level. This will apply both to the Web UI and the cli then. Currently, if the user deletes (or edits) a Configuration belonging to a Service instance, there is not way to reset it to the original secret.
