### ISSUE TITLE
The application templates should be able to use OCI artifacts for helm

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1485]
If I specify my helm chart in an AppChart using an `oci://` link, it fails with this error:

```
Deploying application ...

❌  error pushing app to server: can't deploy app: Internal Server Error: unable to lookup chart "oci://registry.digitalocean.com/helmtesting/epinio-stateful/epinio-stateful-application:0.1.15", missing registry client
```

**Comment by agracey** [comment]
Here's the line generating the error https://github.com/helm/helm/blob/fa6ba5bb29bd7f8bde3a264ea63ff97a4ff0fe5a/pkg/action/install.go#L679

**Comment by andreas-kupries** [comment]
That is in the `helm/helm` package, i.e. the helm reference implementation. I do not see us fixing that.

Also, you specification is incomplete IMHO. You have two ways of specifying a chart in the AppChart resource.

For one, as a `curl`-able link. Example:

```
spec:
  helmChart: https://github.com/epinio/helm-charts/releases/download/epinio-application-0.1.17/epinio-application-0.1.17.tgz
```

For two, as a combination of repository and chart name (plus version). Example:

```
spec:
  helmRepo: https://epinio.github.io/helm-charts
  helmChart: epinio-application:0.1.17
```

Which of these forms did you use, exactly ?

My speculation is:

```
spec:
  helmRepo: oci://registry.digitalocean.com/helmtesting/epinio-stateful
  helmChart: epinio-stateful-application:0.1.15
```

or similar. How badly off am I ?

**Comment by kkaempf** [comment]
no further replies, closing
