### ISSUE TITLE
Record design choices

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#149]
It might be worth using a tool like https://github.com/thomvaill/log4brains to keep track of different choices and their rationale.

**Comment by kkaempf** [comment]
Maybe we can do without a tool and just adhere to a process of documenting ideas, research outcomes, and agreements in an RFC-style document.

**Comment by andreas-kupries** [comment]
Kubecf uses ADR's (Architecture Decision Records). See ... Nevermind ... The log4brains is ADR tooling ...
The kubecf tooling is https://github.com/npryce/adr-tools
The article behind things is http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions .

@kkaempf Note that ADR are RFC-like documents.
