### ISSUE TITLE
Write process to deploy latest repo and latest UI

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1540]
# Process to deploy latest standalone UI  synced with latest ui-backend and epinio
## To get the very latest version of Epinio 

Alias epinio commnand in you `.bashrc` or `.zshrc`:
```
alias git_magic_command='git submodule sync --recursive && git submodule update --init --recursive && git submodule foreach --recursive "git checkout . && git reset --hard && git clean -dffx"'
```
<br>
### To be done in [epinio/epinio](https://github.com/epinio/epinio) repo: 

Open a terminal and execute:

```
export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig
git_magic_command
```
Ensure you have nodes running:

```
epinio git:(main) kubectl get nodes
NAME                             STATUS   ROLES                  AGE    VERSION 
k3d-epinio-acceptance-server-0   Ready    control-plane,master   109s   v1.20.11+k3s2 
```
Execute:
```
make install-cert-manager
make prepare_environment_k3d  
```
Check epinio version with `epinio info`:
It should output the current version, plus and aditional number

```✔️  Epinio Environment 
Platform: k3s 
Kubernetes Version: v1.20.11+k3s2 
Epinio Server Version: v0.8.0-124-g57f85060 
Epinio Client Version: v0.8.0-124-g57f85060 
```
######Optional: create a symlink for the latest versions

`ln -s ~/epinio/dist/epinio-linux-amd64 /usr/local/bin/epinio`

---

#### To be done in [epinio/ui-backend](https://github.com/epinio/ui-backend) repo: 

Execute: 
`epinio settings show` -> Copy the id

On another terminal execute the following with the copied ID:

```
cd ui-backend/src/jetstream
go build && EPINIO_API_URL=https:${COPIED_ID}.omg.howdoi.website EPINIO_WSS_URL=https://epinio.${COPIED_ID}.omg.howdoi.website EPINIO_API_SKIP_SSL=true EPINIO_VERSION=dev ./jetstream  
```

If this error appears...
```
FATA[Wed Jun  8 12:22:40 CEST 2022] You must configure either an Encryption key or the Encryption key filename  
```
...do this:  
```
cp src/jetstream/config.example src/jetstream/config.properties 
```
...and retry previous command (go build...)

Now the backend should be ok and we can start the rancher dashboard deployment:
<br />

#### To be done in [rancher/dashboard](https://github.com/rancher/dashboard/tree/epinio-dev) repo: 

Open new terminal poiting to `dev` branch on [rancher/dashboard](https://github.com/rancher/dashboard/tree/epinio-dev) repo

Ensure you have `node version 16.15.0` (others may work as well)

On dashboard repo, open file `nuxt.config.js` and  ensure you have this configuration:

```
import config from './shell/nuxt.config';

export default config(__dirname, {
  excludes: ['rancher-components'],
  // excludes: ['fleet', 'example']
  // autoLoad: ['fleet', 'example']
});
```

Execute:
```
Yarn install global 
yarn install 
API=https://localhost:5443 RANCHER_ENV=epinio yarn mem-dev 
``` 

Rancher Standalone UI should now be opened on `https://localhost:8005`

Note: if UI does not open and you see this error in `ui-backend` terminal...
`ERRO[Wed Jun  8 12:25:53 CEST 2022] failed to find an epinio endpoint   `

…make sure you add this on: `ui-backend/src/jetstream/config.properties`
`AUTH_ENDPOINT_TYPE=epinio `

**Comment by mmartin24** [comment]
@jimmykarily , mind pls reviewing this doc to see if it is in sync with the deployment we did yesterday and if I missed any point?
@juadk and @richard-cox, feel free to take a look and see if it accurate / works for you. Thanks
We can later agree in which part of the repo to place it if we think is ok.

**Comment by jimmykarily** [comment]
As notes I think it's complete (matching what we did yesterday). As docs it needs a bit different phrasing and some cleanup.

E.g.

- The "git_magic_command" is just a local alias I like to use, it's not needed though. One just has to sync the submodule.
- The copying of `config.example` to `config.properties` is always needed. I'm not sure if `config.dev` was the one that worked in the end. Also the addition of `AUTH_ENDPOINT_TYPE` is also always needed.
- Exclusion of `nuxt.config.js` has been removed by Richart here: https://github.com/rancher/dashboard/commit/76cf91ca300fbfe40543bb004d492c4ca456f5aa
- regarding node version, we should document the maximum node version that works.

and generally, some rephrasing to improve the flow as a step-by-step guide.

**Comment by richard-cox** [comment]
There's some existing docs spread across both https://github.com/epinio/ui/tree/dev/docs/developer and https://github.com/epinio/ui-backend#development, both are out of date and disjointed.  

I need to update the `config.x` files to make it clear what's needed or should be populated. For instance only the version and theme env vars are required now when running `./jetstream`.

In terms of location it would be consolidate everything in `epinio/ui`

Side note - the docs for releasing the ui, both embedded and standalone, are pretty solid at https://github.com/epinio/ui/tree/dev/docs/developer#build--release

**Comment by juadk** [comment]
In my dev/testing process, I simply use `git pull --recurse-submodules` to sync the submodule.
