### ISSUE TITLE
Login command in cli lacking username

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1545]
**Describe the bug**
Currently, after deploying epinio, the suggested command to log in from cli lacks the username:

`epinio login -u  https://epinio.172.21.0.3.sslip.io`

![image](https://user-images.githubusercontent.com/37271841/173107508-7968bde3-79b6-4015-906f-9de1ce1c6b14.png)
Hint: Make sure to search through the existing issues, as they often contain important information on recent changes.

**To Reproduce**
1. Install Epinio
2. Observe how the command is 
`epinio login -u  https://epinio.172.21.0.3.sslip.io`

**Expected behavior**
The commnad should include the username in order not to throw an error

**Cluster (please complete the following information):**
 - Provider: [K3D]

**Desktop/CLI (please complete the following information):**
 - OS: [Linux]
 - Epinio Version: v0.9.0-0.0.3
 - Epinio Install Options: [e.g. loadbalancer, type of system domain]

**Comment by andreas-kupries** [comment]
This looks to be an issue with the `NOTES.txt` from the epinio chart.

> work@tagetarl:~/SUSE/dev/epinio/helm-charts> cat chart/epinio/templates/NOTES.txt
> To interract with your Epinio installation download the latest epinio binary from https://github.com/epinio/epinio/releases/latest.
>
> Login to the cluster with:
>
>    `epinio login -u {{.Values.api.username}} https://epinio.{{ .Values.global.domain }}`
>
> or go to the dashboard at: https://epinio.{{ .Values.global.domain }}
>
> If you didn't specify a password the default one is `password`.
>
> For more information about Epinio, feel free to checkout https://epinio.io/ and https://docs.epinio.io/.

Note that there is a user name referenced. This variable is likely empty, or does not exist.

**Comment by andreas-kupries** [comment]
Right. The issue is that `.Values.api.username` got removed recently. It was replaced with the `.Values.api.users` list which contains two standard users, `admin` and `epinio`, in this order.

**Comment by andreas-kupries** [comment]
- Chart PR https://github.com/epinio/helm-charts/pull/222
  - Main PR  https://github.com/epinio/epinio/pull/1549

**Comment by juadk** [comment]
Validated in the latest release: :heavy_check_mark: 
```
NOTES:
To interact with your Epinio installation download the latest epinio binary from https://github.com/epinio/epinio/releases/latest.

Login to the cluster with any of

    `epinio login -u 'admin' 'https://epinio.<my-domain>'`
    `epinio login -u 'epinio' 'https://epinio.<my-domain>''`
```
