### ISSUE TITLE
Bad return value when we are rate limited by the kube api

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1560]
Follow up of https://github.com/epinio/ui/issues/115#issuecomment-1148425343

**Comment by andreas-kupries** [comment]
Apparently we are being rate limited by the kube api and we don't handle that gracefully on the epinio server side, returning a 500. There are various ways this can be solved:

    Make the /complete endpoint return immediately with a response indicating whether the app is ready or not and let the clients poll
    Make the /complete endpoint retry to talk to kubernetes when it's rate limited (maybe this should happen anyway, even when the above solution is selected).
    Detect this type of error in the UI and retry, with or with no fix on the epinio server side (just a workaround).

In any case, a 500 is not a proper return value when we are rate limited.

**Comment by enrichman** [comment]
We are not getting many of this error. Let's close this for now.
