### ISSUE TITLE
[ui-backend] Session handling

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1576]
The `epinio-ui` is not be able to handle sessions with multiple instances.

**Describe the bug**
I was trying to see if we were able to handle sessions with multiple backends, and while with Epinio seems possible we have some issues scaling the `ui-backend`.

**To Reproduce**

Scale the `ui-backend` replicas to something like 5.
Try to login with the dashboard.

Logs from the `epinio-ui`

```
│ epinio-ui-7dcd7bfd7d-4zltv ERRO[Mon Jun 20 14:59:29 UTC 2022] User session could not be found: Session value not found user_id                                                                                                            │
│ epinio-ui-7dcd7bfd7d-4zltv {"time":"2022-06-20T14:59:29.441679705Z","level":"ERROR","prefix":"echo","file":"main.go","line":"1255","message":"code=401, message={\"status\":\"error\",\"error\":\"User session could not be found\"}"}    │
│ epinio-ui-7dcd7bfd7d-4zltv Request: [2022-06-20T14:59:29Z] Remote-IP:"10.42.0.1" Method:"GET" Path:"/pp/v1/epinio/rancher/v3/users" Status:401 Latency:167.538µs Bytes-In:0 Bytes-Out:60                                                  │
│ epinio-ui-7dcd7bfd7d-6rm7x ERRO[Mon Jun 20 14:59:29 UTC 2022] User session could not be found: Session value not found user_id                                                                                                            │
│ epinio-ui-7dcd7bfd7d-6rm7x {"time":"2022-06-20T14:59:29.445252566Z","level":"ERROR","prefix":"echo","file":"main.go","line":"1255","message":"code=401, message={\"status\":\"error\",\"error\":\"User session could not be found\"}"}    │
│ epinio-ui-7dcd7bfd7d-6rm7x Request: [2022-06-20T14:59:29Z] Remote-IP:"10.42.0.1" Method:"POST" Path:"/pp/v1/epinio/rancher/v3/tokens" Status:401 Latency:123.786µs Bytes-In:2 Bytes-Out:60       
```

![image](https://user-images.githubusercontent.com/1763949/174630207-78323419-4e99-4c1d-a809-8f6a22209724.png)

**Comment by jimmykarily** [comment]
ui-backend seems to support other databases: https://github.com/epinio/ui-backend/blob/57c64c5566e874648466845abb39142e9bdd4435/src/jetstream/datastore/datastore.go#L40

if the session is stored in the database (probably true), then using the same database for all ui-backend instances would solve this problem. Let's consider this when we work on running ui-backend in HA mode.
