### ISSUE TITLE
Settings file on Windows should not be created at the drive root

### ISSUE THREAD

**Issue by jandubois** [epinio/epinio#1579]
The settings are stored at `/.config/epinio/settings.yaml`, which is not an absolute path (it is missing the drive letter), and is outside the users profile directory.

It should be stored under `%APPDATA%` (the location of the roaming profile, that travels with the user to different machines in the same domain), or under `%LOCALAPPDATA%` if the settings are only valid on the local machine (or contain large files).

**Comment by jandubois** [comment]
You may also want to create a symlink inside the WSL distros to point to the config file on the Windows side. So when you login from a Windows shell, you are also logged in in your WSL2 shells.

Rancher Desktop does this for your `~/.kube/config`:

```console
jan@DESKTOP-4992680:~$ ls -l ~/.kube
total 0
lrwxrwxrwx 1 jan jan 29 Jun 20 23:01 config -> /mnt/c/Users/Jan/.kube/config
```

**Comment by jimmykarily** [comment]
We are using the `HOME` env variable: https://github.com/epinio/epinio/blob/cf3d73ae60ad4ed9bd1283d9969ed06d15176731/internal/cli/settings/settings.go#L23

I think we should be using `os.UserHomeDir()` instead.

**Comment by jandubois** [comment]
Yes, `HOME` is not a thing on Windows; it is called `USERPROFILE`, which is what `os.UserHomeDir()` will return.

Creating a `%USERPROFILE%\.config` directory is still not a Windows thing, but I think should be acceptable. Normally you would create `%APPDATA%\epinio` and/or `%LOCALAPPDATA%\epinio` for settings and local data files respectively.

The advantage of using the `%APPDATA%` folder is that in an enterprise environment the content is mirrored to the domain controller, so when you log into a new machine (or just switch between laptop and desktop), the setup files are already there. This is also the reason that only small files should go into `APPDATA`; otherwise login/logout get slow because of all the data copying.

Example values from my machine:

```
USERPROFILE=C:\Users\Jan
APPDATA=C:\Users\Jan\AppData\Roaming
LOCALAPPDATA=C:\Users\Jan\AppData\Local
```

**Comment by jimmykarily** [comment]
We could use a library like this one: https://github.com/shibukawa/configdir

**Comment by jimmykarily** [comment]
That library was created before this issue: https://github.com/golang/go/issues/29960
Also I don't see how that could work without "+build" tags, it's probably based on some very old version of go, not sure how that worked.

This looks more promising: https://github.com/adrg/xdg
