### ISSUE TITLE
--trace-level option doesn't seem to work

### ISSUE THREAD

**Issue by jandubois** [epinio/epinio#1592]
Specifying `--trace-level 255` has no effect, neither before or after the subcommand (`login`). Only the `TRACE_LEVEL` environment variable seems make a difference:

```console
$ epinio --trace-level 255 login -u admin -p password --trust-ca https://epinio.127.0.0.1.sslip.io

🚢  Login to your Epinio cluster [https://epinio.127.0.0.1.sslip.io]

✔️  Trusting certificate...

✔️  Login successful

$ epinio login -u admin -p password --trust-ca --trace-level 255 https://epinio.127.0.0.1.sslip.io

🚢  Login to your Epinio cluster [https://epinio.127.0.0.1.sslip.io]
[...]

$ TRACE_LEVEL=255 epinio login -u admin -p password --trust-ca https://epinio.127.0.0.1.sslip.io
2022/06/22 09:16:11 Settings-0xc000185130: "level"=4 "msg"="Loading" "from"="/Users/jan/.config/epinio/settings.yaml"
2022/06/22 09:16:11 Settings-0xc000185130: "level"=4 "msg"="Loaded" "value"="namespace=(workspace), user=(admin), pass=(password), api=(https://epinio.127.0.0.1.sslip.io), wss=(wss://epinio.127.0.0.1.sslip.io), color=(true), appchart=(), @(/Users/jan/.config/epinio/settings.yaml)"
[...]
```

That's why I filed #1580 because I thought `--trace-level` did not produce additional output, so setting `DEBUG=true` must have made the difference. But I guess I must have set both variables mentioned in the issue template, and it was `TRACE_LEVEL` that did it.

**Comment by enrichman** [comment]
Thanks @jandubois , I will try it tomorrow. in my personal backlog I would like to refactor how we read and bind flags.
Maybe this could be an opportunity to do that. 😄

**Comment by andreas-kupries** [comment]
I confirm the behaviour.

Places using `TRACE_LEVEL` and `trace-level` are:

```
./.github/ISSUE_TEMPLATE/bug_report.md:44:export TRACE_LEVEL=255

./helm-charts/chart/epinio/templates/server.yaml:279:            - name: TRACE_LEVEL

./internal/cli/usercmd/push.go:53:	details := log.V(1) // NOTE: Increment of level, not absolute. Visible via TRACE_LEVEL=2

./helpers/tracelog/logger.go:2:// This logger will not print anything, unless TRACE_LEVEL is at least 1
./helpers/tracelog/logger.go:18:// TraceLevel returns the trace-level argument
./helpers/tracelog/logger.go:20:	return viper.GetInt("trace-level")
./helpers/tracelog/logger.go:30:	// trace-level 0 prints nothing, well technically it would print NewLogger().V(-1)
./helpers/tracelog/logger.go:31:	pf.IntP("trace-level", "", 0, "Only print trace messages at or above this level (0 to 255, default 0, print nothing)")
./helpers/tracelog/logger.go:32:	viper.BindPFlag("trace-level", pf.Lookup("trace-level"))
./helpers/tracelog/logger.go:33:	argToEnv["trace-level"] = "TRACE_LEVEL"
```

The logger.go is the most central here I believe.

**Comment by andreas-kupries** [comment]
In contrast, `--timeout=multiplier` and `EPINIO_TIMEOUT_MULTIPLIER` work as expected. I.e. both forms of setting the value do work. The code looks identical to trace setup, except for the names, of course.

**Comment by andreas-kupries** [comment]
Ditto `verbosity` ...

An ordering issue maybe ?
Could the code query for the trace level before the command line is parsed ?
And for the other options it is queried after ?

**Comment by andreas-kupries** [comment]
Yes, very much looks like that.

https://github.com/epinio/epinio/blob/ba5c7457505c0a46e9b11c0a6f786a5603e3ff3f/internal/cli/root.go#L41-L42

**Comment by andreas-kupries** [comment]
Lets see if cobra has a hook to run code after the command line is parsed, and before the `Run` function of the found command is invoked.

**Comment by andreas-kupries** [comment]
That works.

**Comment by enrichman** [comment]
Yes, that is the func that we need to use. The refactor that I wanted to do was about having a Config struct that will be binded to the variables. I read this blog post few weeks ago https://carolynvanslyck.com/blog/2020/08/sting-of-the-viper/ and she was showing a way to bind everything correctly: https://carolynvanslyck.com/blog/2020/08/sting-of-the-viper/

I was trying to play a bit with it to try a clean implementation (https://github.com/enrichman/epinio-client-go/tree/main/internal/cli/cmd), but since we are handling lot of things in the `init()` funcs then it's a "big" refactor.
