### ISSUE TITLE
Test user interaction with epinio login command

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1601]
Until now, we do not test user interaction with the epinio login command, we use all the requested flag to avoid interaction (https://github.com/epinio/epinio/blob/main/acceptance/install/scenario5_test.go#L129).

That's why the CI did not spot this issue https://github.com/epinio/epinio/issues/1577
All the public cloud tests use it without interaction, so It could be relevant to also test user interaction in some, at least on windows (AKS tests) and macos (EKS), full matrix [here](https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)).

Example: https://pkg.go.dev/os/exec@go1.18.3#example-Cmd.StdinPipe

**Comment by andreas-kupries** [comment]
We look to have this in https://github.com/epinio/epinio/blob/main/acceptance/login_test.go
