### ISSUE TITLE
Document locking down Epinio with NeuVector 

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1604]
We should generate a ruleset to allow NeuVector to secure the Epinio components. This should be relatively straightforward since we can let it [train the ruleset](https://open-docs.neuvector.com/policy/modes#discover) based on test runs then [store in a CRD](https://open-docs.neuvector.com/policy/usingcrd) for distribution.

**Comment by jimmykarily** [comment]
First things first, I installed neuvector alongside Epinio following [their documentation](https://github.com/neuvector/neuvector-helm).

I had to enable ingress and set `k3s.enabled` to true to make it work with k3d:

```
helm upgrade --install neuvector --namespace neuvector neuvector/core  --set imagePullSecrets=regsecret --set manager.ingress.enabled=true --set manager.ingress.host=neuvector.172.18.0.2.omg.howdoi.website --set k3s.enabled=true
```
