### ISSUE TITLE
New TLS cert on every new app pushed

### ISSUE THREAD

**Issue by pedroh4659** [epinio/epinio#1605]
**Describe the bug**
In every push of a different app, a new certificate request is sent to Let'sEncrypt and a new challenge is created. There are two problems with this:
1. It is slow. Each certificate request takes about 1-2 minutes to fully complete, and until then the application is insecure
2. It is not scalable. Let'sEncrypt limits the amount of requests to the same DNS, so in high load situations, this limit can be surpassed and all future requests for that DNS will be blocked. The exact limits are documented here: https://letsencrypt.org/docs/rate-limits/

**To Reproduce**
1. Push any application to Epinio
2. Watch as a new challenge is issued (kubectl get challenge -n epinio) or
3. See that a new certificate was created (kubectl get certificates -n epinio)

**Expected behavior**
Maybe there should be a way of deploying Epinio using wildcard DNS, so all new applications use the same certificate from the top domain.

**Logs**
This is a log from when the LetsEncrypt limit was surpassed

```The certificate request has failed to complete and will be retried: Failed to wait for order resource "epinio-n72n45-2651626544" to become ready: order is in "errored" state: Failed to create Order: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: epinio.example.com: see https://letsencrypt.org/docs/duplicate-certificate-limit/```

It can be acquired describing the challenge

**Cluster:**
 - Provider: K3D
 - Kubernetes Version: v1.23.6

**Desktop/CLI (please complete the following information):**
 - OS: Ubuntu 18.04
 - Epinio Version: 1.0.0
 - LoadBalancer: Happens when using both Nginx and Traefik

**Comment by pedroh4659** [comment]
Ok, so I managed to get it working by doing the following:

1. I manually set up a default certificate on Traefik, which is a wildcard as I wanted. In this way, Epinio still keeps generating the certificates for each app, but Traefik just ignores it and uses the default
2. I gave Epinio a dummy cluster issuer, so it does not uses the production ACME of LetsEncrypt

Still, I consider this a 'hack', so maybe there is another way of doing it instead of 'tricking' Epinio?

**Comment by juadk** [comment]
Thanks for the report! Do not expect a feedback this week, it's a special week at SUSE (Hackweek). Talk to you next week.

**Comment by jimmykarily** [comment]
If we implement a way to use a wildcard certificate (matching the "system domain") then we need to make sure, [custom routes](https://docs.epinio.io/howtos/custom_routes) still work. Custom routes will still need a certificate per route.

**Comment by jimmykarily** [comment]
Fixing this should take these other issues into account: https://github.com/epinio/epinio/issues/1585
User may or may not want wildcard certificates. If we support more than one domain (as we do with the "system domain" now), the wildcard/no-wildcard setting seems to belong to the "domain object" (which we don't currently have).

I wonder if the problem in this issue can be solved by creating a custom issuer that always returns the same wildcard certificate for every Certificate resource created. Almost like [what @pedroh4659 describes](https://github.com/epinio/epinio/issues/1605#issuecomment-1170391320) but letting Epinio create certificates as usual.

**Comment by jimmykarily** [comment]
> I wonder if the problem in this issue can be solved by creating a custom issuer that always returns the same wildcard certificate for every Certificate resource created. Almost like https://github.com/epinio/epinio/issues/1605#issuecomment-1170391320 but letting Epinio create certificates as usual.

Correcting myself, the issuer doesn't decide what the host is for certificates neither creates them, only signing them. It's the application chart that creates them: https://github.com/epinio/helm-charts/blob/3954c214de3d7b957cfc2054ba4fa4bfa140f5a3/chart/application/templates/ingress.yaml#L1-L15

By changing the application chart's logic, we can control whether to create a new certificate or use an existing one [for the application's Ingress](https://github.com/epinio/helm-charts/blob/3954c214de3d7b957cfc2054ba4fa4bfa140f5a3/chart/application/templates/ingress.yaml#L45). We should pass the name of the existing secret to the chart of course. It' possible but needs some wiring up.

What may complicate things is that wildcard certificates with let's encrypt [need the DNS challenge](https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates) but we setup [the http solver](https://github.com/epinio/helm-charts/blob/3954c214de3d7b957cfc2054ba4fa4bfa140f5a3/chart/epinio/templates/cluster-issuers.yaml#L24).

**Comment by pedroh4659** [comment]
@jimmykarily thank you for your response. I believe the first solution works better because it's better for automation purposes, also it simplifies the developer job, seems like a good feature.

**Comment by jimmykarily** [comment]
Yes, now that I think again, both solutions offer the same options but the second one is more explicit and requires more collaboration between devs and operators. I think I prefer the first one too. It would be nice if operators could add certificates to Epinio without having to restart the epinio server (which is what would happen if it was an environment variable or a flag of the epinio server command). We can rely on labeled secrets to detect available certificates at runtime. The feature is taking shape now...

**Comment by jimmykarily** [comment]
@andreas-kupries thanks for writing this down. It looks good to me. I'm just concerned by the fact that labels/annotations may not match the domain the certificate is valid for. This is manual and can break even for a simple typo. The information on what domains the certificate is valid for is already inside the secret:

```
kubectl get secret -n workspace rsample-sample2example-c28512e2f6d3a2c68d97c6aa727b90f317ce50c9 -o json | jq -r '.data["tls.crt"]' | base64 -d | openssl x509 -text -noout | grep DNS
                DNS:sample2.example.com
```

but it feels too heavy of an operation to do on every push. Maybe it's ok to do it once when the server loads? It may delay the startup of the server though, and adding more certificates will require a restart of the server. Maybe we can give it a try and see how fast it is (e.g. load all secrets in one request using a label selector and extract the valid domains in Go-space).

**Comment by andreas-kupries** [comment]
Yes, mismatches are a concern also. Missed that. I had not realized (or forgotten) that the domain is stored inside of the cert also.
Ok, lets change the spec to

  - label secrets as before (`epinio.io/routing: <arbitrary text>`) for selection, and then
  - spike on extracting the domains in go ...

There is a `crypto/x509` package in the go standard lib. We may be using it already ...
Grep ...
And look at https://github.com/epinio/epinio/blob/b96fd2ed8cd9f36b16e65a2057e7f0b83ebe9c34/internal/api/v1/application/stage.go#L628-L649 and https://github.com/epinio/epinio/blob/b96fd2ed8cd9f36b16e65a2057e7f0b83ebe9c34/helpers/cahash/cahash.go
That should be good starting points.
