### ISSUE TITLE
Creating new users does not work

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1606]
**Describe the bug**
Following the instructions here:
https://github.com/epinio/epinio/blob/main/docs/howtos/new-api-user.md

**To Reproduce**
1. Install Epinio 1.0.0
2. Follow above instruction to create user/password
3. Try to login via admin UI. It will give invalid password

Note:
The only way i could install new user is via helmchart install of epinio now
```
	helm install epinio -n epinio --create-namespace epinio/epinio \
		--set global.domain=${DOMAIN} \
		--set global.tlsIssuer=letsencrypt-epinio \
		--set api.users[0].username=admin \
		--set api.users[0].passwordBcrypt='$$2a$$12$$ZZVP/sisDGMEZHea8yqbr.1Us/HXVv0B9jlPcD1tBBPqrY1Z7cZFG' \
		--set api.users[0].role=admin \

```
which is not ideal.

**Expected behavior**
I should be able to login

**Logs**
If applicable, add logs to help explain your problem.

You can use attachments to add a screenshot of your clusters state, e.g. from k9s.

If you paste long logs, you could also add them into a collapsed block:

&lt;details&gt;
  &lt;summary&gt;Click to expand&lt;summary&gt;

  \```
2022/06/29 04:33:54 EpinioServer: "msg"="ERROR" "error"="wrong password" "requestId"="3f041182-f665-4d6b-8bcb-172db27867cd" "origin"="/api/v1/info" "error"="wrong password"
2022/06/29 04:33:54 EpinioServer: "msg"="Error" "error"="wrong password"
  \```
&lt;details&gt;

You can increase Epinio's logging by exporting this variable:

```
export TRACE_LEVEL=255
```

To follow the server logs you can use:

`kubectl logs -n epinio -l app.kubernetes.io/name=epinio-server -c epinio-server -f`

**Cluster (please complete the following information):**
 - Provider: K3D, 
 - Kubernetes Version: 1.22

**Desktop/CLI (please complete the following information):**
 - OS: Linux, 
 - Epinio Version: 1.0.0
 - Epinio Install Options: loadbalancer

**Additional context**
Anything special about your setup, like using a proxy or special DNS setup?

**Comment by juadk** [comment]
Thanks for the report! Do not expect a feedback this week, it's a special week at SUSE (Hackweek). Talk to you next week.

**Comment by jimmykarily** [comment]
The linked docs are out of date. These are the valid ones: https://docs.epinio.io/references/authorization#add-a-new-user
Since this PR: https://github.com/epinio/helm-charts/pull/208 the password is not plain text but a hash.

**Comment by gitricko** [comment]
> The linked docs are out of date. These are the valid ones: https://docs.epinio.io/references/authorization#add-a-new-user Since this PR: [epinio/helm-charts#208](https://github.com/epinio/helm-charts/pull/208) the password is not plain text but a hash.

Thanks. I just verified... creating via kubectl with the yaml indeed works well!

Created some help cli to help me maintain some users.
eg: create user : `make ep-create-user USERID=myuser2 USERPW=password`
eg: delete user:  `make ep-delete-user USERID=myuser2` 

```
#Makefile

check_defined = \
    $(strip $(foreach 1,$1, \
        $(call __check_defined,$1,$(strip $(value 2)))))
__check_defined = \
    $(if $(value $1),, \
      $(error Undefined $1$(if $2, ($2))))

ep-list-users:
	kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials'

ep-list-admins:
	kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials,epinio.io/role=admin'

ep-create-user:
	$(call check_defined, USERID, USERID need to be set)
	$(call check_defined, USERPW, USERPW need to be set)
	USERID=$(USERID) \
	USERPW=$(USERPW) \
	./makefile.sh ep-create-user
	
ep-delete-user:
	$(call check_defined, USERID, USERID need to be set)
	USERID=$(USERID) \
	kubectl delete secrets -n epinio ouser-$(USERID)

```

```
#makefile.sh

#src: https://docs.epinio.io/references/authorization#add-a-new-user
function ep-create-user {
	USERPW_HASH=$(htpasswd -bnBC 10 "" ${USERPW} | tr -d :)
	
	cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "user"
  name: ouser-${USERID}
  namespace: epinio
stringData:
  username: ${USERID}
  password: "${USERPW_HASH}"
  namespaces: |
    workspace
    workspac3
EOF
}

$*
```

Closing this issue. Thanks @jimmykarily

**Comment by jimmykarily** [comment]
Created a PR to remove the outdated docs: https://github.com/epinio/epinio/pull/1623
