### ISSUE TITLE
Fix artifacthub security report

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1619]
Bumps things until it looks fine: https://artifacthub.io/packages/helm/epinio/epinio?modal=security-report

**Comment by jimmykarily** [comment]
Latest commit of kubed (config-syncer) seems to fix the warning:

https://github.com/kubeops/config-syncer/commit/119c1f52fbeb6d83951141c6e4acd9fb0279b997#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L99

![image](https://user-images.githubusercontent.com/2794419/177935677-2bfcefaa-022c-442f-8d41-240dc2902e55.png)

but there isn't a release yet that includes that fix. Their CI is also broken: https://github.com/kubeops/config-syncer/runs/6736653101?check_suite_focus=true which may explain why there is no release.

I think we should merge [the PR](https://github.com/epinio/epinio/pull/1628) as it is an find a solution for kubed in another PR.

**Comment by jimmykarily** [comment]
Also opened an issue for kubed: https://github.com/kubeops/config-syncer/issues/523

**Comment by jimmykarily** [comment]
Let's fix things that don't need an upstream change and release and we fix the rest in another PR. e.g. nginx gives us an `F` which we can easily fix.

**Comment by jimmykarily** [comment]
config-syncer (aka kubed) issues don't get a lot of attention. We could remove kubed from Epinio completely if we documented how the operator should update the registry secret in all namespaces if they want to change it. E.g.

- Epinio automaticlaly creates a copy of the registry secret when a new namespace is created.
- When the secret needs to be rotated, we document an one liner that uses some labels to select and patch the copies of that secret in all Epinio namespaces (a manual step taken by the operator).

It's not as good as kubed but it removes one dependency.

**Comment by jimmykarily** [comment]
[We bumped nginx to 1.23](https://github.com/epinio/helm-charts/commit/cd20e6912863927d48e86715ef44ec01a33751db) but it still gets an "F":

![image](https://user-images.githubusercontent.com/2794419/180771896-d1addac8-116b-45f0-a8b7-9dbd755a010c.png)

**Comment by enrichman** [comment]
Outdated
