### ISSUE TITLE
SLC / MVP requirements

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#162]
Ability to deploy an app (like Wordpress) and its dependencies (resp. dependent services, like MySQL) honoring [Dev/Prod parity](https://12factor.net/dev-prod-parity)

- can deploy an app like wordpress (see #144)
- can deploy and bind to service in public cloud (see #157, #160; using [crossplane](https://crossplane.io))
- can deploy and bind to service in local cluster (tba; using [minibroker](https://github.com/kubernetes-sigs/minibroker))
- TLS enabled (#62, #63, #130)
- most bugs fixed

**Comment by jimmykarily** [comment]
done
