### ISSUE TITLE
[UX] - Check if more logs can be added when an app fails to deploy

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1627]
When an app like this one (https://github.com/paketo-buildpacks/samples/tree/main/java/akka) fails to load logs stop in the point it could not continue but does not give more information:

![Image](https://user-images.githubusercontent.com/37271841/177702239-a063c5e5-77db-4cab-92b7-43e29664ad78.png)

If there is more hints of what could have caused the problem and it is possible, we may want to add it here

**Comment by andreas-kupries** [comment]
The logs seen are the logs provided by the paketo builder and buildpacks as they process the app sources.
Epinio itself has not other information.

The best possibility would be if paketo and buildpacks react to some kind of environment variable to enhance their logging.
It will have to be checked in the paketo and buildpack documentation if such a variable exists, and what it would have to be set to.

**Comment by mmartin24** [comment]
thanks @andreas-kupries .
Is there any way to "add" some other logging not necessarily from Buildpack only like network disconnections that could somehow help a bit to find a possible issue?

**Comment by andreas-kupries** [comment]
The staging runs in its own pod and container, and the only code in that container is the builder, and the buildpacks. Only they can report any issues they see, network and others.

The epinio server, running in its own separate pod/container has no reach to monitor whatever networking is required by staging.

I do not know if there are tools and such which could be used to inspect the kubernetes networking layer for any issues. Especially issues not in the pod running such introspection (I could see them as security issues to happen, i.e. eaves dropping at least).
