### ISSUE TITLE
[spike/research] civo marketplace

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1632]
Civo has a markeplace:

https://www.civo.com/marketplace

Let's have a look on how we could list Epinio here: https://github.com/civo/kubernetes-marketplace

**Comment by enrichman** [comment]
I was trying to launch a cluster but the app is not yet visible. I pinged Civo about this, let's wait for a response, and maybe a quick test. :+1:

**Comment by enrichman** [comment]
Epinio is available on the CIVO marketplace and it works. Closing. 👍 

Thanks @saiyam1814 !
