### ISSUE TITLE
Allow pass a namespace value with CLI

### ISSUE THREAD

**Issue by hadirga** [epinio/epinio#1635]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select the namespace where an app is pushed using the CLI. This would allow to change the `epinio/settings.yaml` file every time I want to push an app for a specific namespace.

**Describe the solution you'd like**
Expansion to the `epinio app push` to allow passing a flag like `--namespace namespace-value` when multiple namespaces where defined.

**Describe alternatives you've considered**
I considered the alternatives where the file `settings.yaml` remains open or it was opened every time I need push an app to a specific namespace.  

**Additional context**
The CLI command can looks like this one:
`epinio app push my-app --namespace namespace-value`

**Comment by andreas-kupries** [comment]
You are welcome - I created a documentation issue for this now - https://github.com/epinio/docs/issues/148
