### ISSUE TITLE
cert-manager version 1.7.x reaching EOL

### ISSUE THREAD

**Issue by claudioser** [epinio/epinio#1639]
**Describe the bug**
Using cert-manager in order to be able to have certs available for every app deployed.
when trying to deploy app, epinio push-n 12factor, still received non secure connectivity on url. 

Looking at pods in the relevant 'workspace' namespace, there was a pod called "acme-xxx " ( or something like that ), that had an error "exec /app/cmd/acmesolver/acmesolver: exec format error" - this was due to cert-manager version being 1.7.2 

Updated cert-manager to 1.7.3 and subsequently to 1.8 and the app url resolved correctly with cert. . furthemore cert-manager 1.7 is eol -  https://cert-manager.io/docs/installation/supported-releases/

The above is for info, and perhaps doc should also reflect requirement when using letsencrypt-production ClusterIssuer

**Cluster (please complete the following information):**
 - Provider:  RKE2 
 - Options: [e.g. number of nodes, storageclasses, loadbalancer if customised]
 - Kubernetes Version: v1.23.7

**Desktop/CLI (please complete the following information):**
 - OS: Linux, 
 - Epinio Version: 1.0.0 
 - Epinio Install Options:  Loadbalancer provided by haproxy(outside cluster ) to serve worker nodes 
 -

**Comment by jimmykarily** [comment]
We are still using 1.7.1 in our development scripts: https://github.com/epinio/epinio/blob/4d05cce028b5899e720502a74268bf1814447fcb/Makefile#L184 and it's working but should definitely document a working, supported, cert-manager version.

**Comment by andreas-kupries** [comment]
Versions since 1.7.1 (we are using in dev)

```
cert-manager/cert-manager                  	v1.9.0       	v1.9.0     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.8.2       	v1.8.2     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.8.1       	v1.8.1     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.8.0       	v1.8.0     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.7.3       	v1.7.3     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.7.2       	v1.7.2     	A Helm chart for cert-manager                     
cert-manager/cert-manager                  	v1.7.1       	v1.7.1     	A Helm chart for cert-manager    
```

https://cert-manager.io/docs/installation/supported-releases/

Version|Released|EOL|Kubernetes|
-- | -- | -- | --
1.7 | Jan 26, 2021 | Jul 22, 2022 | 1.18 → 1.23
1.8 | Apr 05, 2022 | Release of 1.10 | 1.19 → 1.24
1.9 | Jul 22, 2022 | Release of 1.11 | 1.20 → 1.24

1.7 is now EOL for 3 days. 1.9 was released just 3 days ago.
1.8 looks to be a good middle.

All of them look to be the kube versions we are working with.

**Comment by andreas-kupries** [comment]
Update to 1.8.2 looks good for CI and public cloud CI. PR to review. Documentation to do.
