### ISSUE TITLE
unable to scale up sample app - 12factor

### ISSUE THREAD

**Issue by claudioser** [epinio/epinio#1641]
**Describe the bug**
1 instance of 12factor sample app, deploys fine.
Then try to scale up, and get strange behaviour of pods not starting/ crash loopbackoff and then even original instance of app, also gets redeployed. Please see screen shots below

Hint: Make sure to search through the existing issues, as they often contain important information on recent changes.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio on cluster with ClusterIssuers - letsencrypt-production enabled
2. Push 12factor sample app
3. Go inti GUI and scale up instance
4. See errors in screenshot below

havent tested on other sample apps
**Expected behavior**
would expect instances to be scaled up/down, with no interruption ( as seen per pod) to original instance

**Logs**
If applicable, add logs to help explain your problem.

You can use attachments to add a screenshot of your clusters state, e.g. from k9s.

If you paste long logs, you could also add them into a collapsed block:

&lt;details&gt;
  &lt;summary&gt;Click to expand&lt;summary&gt;

  \```
  pasted log
  \```
&lt;details&gt;

You can increase Epinio's logging by exporting this variable:

```
export TRACE_LEVEL=255
```

To follow the server logs you can use:

`kubectl logs -n epinio -l app.kubernetes.io/name=epinio-server -c epinio-server -f`

**Cluster (please complete the following information):**
 - Provider: RKE2 
 - Options: [e.g. number of nodes, storageclasses, loadbalancer if customised]
 - Kubernetes Version: 1.23.7
 - Cluster provided by Harvester - StorageClass - Harvester

**Desktop/CLI (please complete the following information):**
 - OS: Linux,
 - Epinio Version: 1.0.0
 - Epinio Install Options:  LB provided by haproxy 
 - 
**Additional context**
Anything special about your setup, like using a proxy or special DNS setup?
[epinio-scaleup-screenshot and podLog.docx](https://github.com/epinio/epinio/files/9094968/epinio-scaleup-screenshot.and.podLog.docx)

**Comment by jimmykarily** [comment]
Looking at the attached docx file, the error is "input/output error". This feels like an issue with the storage on the cluster or something. Have you tried to reproduce this on any other cluster? We do test the scaling feature: https://github.com/epinio/epinio/blob/4d05cce028b5899e720502a74268bf1814447fcb/acceptance/apps_test.go#L232-L256  (and CI is currently green).

**Comment by andreas-kupries** [comment]
@claudioser Is there anything new on this, i.e. have you checked @jimmykarily suggestion of using a different cluster ?

**Comment by andreas-kupries** [comment]
Attempted to reproduce on my local k3s. Scaling up to 96 instances with no problems. Scaling to 100 has 4 pods kept in pending, i.e. k3s not scheduling them, out of capacity. Even so, no crashes.
