### ISSUE TITLE
Failure to push an application from git repository where revision is a commit id

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1642]
**Describe the bug**

Of the two command

1. `epinio push --name fox --git=https://github.com/richard-cox/epinio-sample-app,a9665a17e4d863cc7b6d6a40ea4d4d51d0bcd12c`
2. `epinio push --name fox --git=https://github.com/richard-cox/epinio-sample-app,master`

the first fails with an internal server error. The commit id/hash is treated as a branch name, and such does exist.

**To Reproduce**

See above.

**Expected behavior**

No error, working push

**Comment by richard-cox** [comment]
Linking dependent issue https://github.com/epinio/ui/issues/63
