### ISSUE TITLE
Add error check inside func in tests

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1644]
The `proc.Kubectl` and the `machine.Epinio` commands are returning the out and the err.
Since in tests we are always err checking the returned error maybe we can just do this check inside the func and keep the tests shorter and cleaner.

From:
```
out, err := proc.Kubectl("apply", "-f", tempFile)
Expect(err).ToNot(HaveOccurred(), out)

out, err := env.Epinio("", "apps", "env", "show", appName, "MYVAR")
Expect(err).ToNot(HaveOccurred(), out)
```
to:
```
out := proc.Kubectl("apply", "-f", tempFile)

out := env.Epinio("", "apps", "env", "show", appName, "MYVAR")
```

and if we still need to check for a specific error we can add a `proc.KubectlWithErr` and `machine.EpinioWithErr` func.

**Comment by agracey** [comment]
Mis-clicked :(
