### ISSUE TITLE
Allow ignore files to be pushed

### ISSUE THREAD

**Issue by hadirga** [epinio/epinio#1646]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select some files to be ignored of the upload process when my app is pushed.

**Describe the solution you'd like**
I believe that we could use a `.gitignore` like file, maybe named `.epinioignore` or even a flag like `--exclude` to be able to ignore a list of files. 

**Describe alternatives you've considered**
I considered creating a folder named `push_to_epinio` to copy all the files I wanted to push to epinio.

**Additional context**
https://github.com/buildpacks/pack/issues/210

**Comment by jimmykarily** [comment]
This is a nice feature indeed. It makes sense to skip the files, not only during staging but also when uploading the code. This needs to be implemented in every client (both the cli and the UI). I see @richard-cox created an issue for the UI side but I wonder what is possible when you "upload  a folder" using the browser. Is it possible to skip files using globs/patterns ? In the cli, we already ignore some files: https://github.com/epinio/epinio/blob/4d05cce028b5899e720502a74268bf1814447fcb/helpers/tar.go#L25 so it shouldn't be too hard to implement this.

**Comment by jimmykarily** [comment]
We should look for some "standard" way to define files/directories. I wonder if all the tools use some standard (e.g. gitignore, cfignore etc). Using a standard would make it easier to implement it both on the cli and the frontend.

**Comment by richard-cox** [comment]
We did something similar in Stratos world to only upload a filtered list, so should be possible here. We'd be able to find something to use standard globs

**Comment by agracey** [comment]
We could use the moby pattern matcher library like docker does: https://github.com/moby/patternmatcher/blob/main/patternmatcher.go

**Comment by gitricko** [comment]
it will be nice to have this.. currently, we are doing some files moving magic in order for us to push app
