### ISSUE TITLE
Explore debugging vs security tradeoffs and enhancements

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#165]
It improves security to build minimal footprint containers for the applications being built. The problem is that these minimal builds don't tend to have even the basic tools needed for debugging (such as a shell). 

One potential solution could be to build a standard debug container that gets added to the pod spec while in carrier but doesn't get published into production environments. 

I'm sure there are other ways to approach this and it might be worth exploring those

**Comment by mook-as** [comment]
Depending on what you want, [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) might be useful here; however, it's in alpha, needs a feature gate, and might not be widely available.

**Comment by agracey** [comment]
I would love ephemeral containers once they are ready!

**Comment by jandubois** [comment]
@agracey Just came across https://github.com/aylei/kubectl-debug Haven't tried it yet (or even read the README carefully), but it looks like something relevant to this issue 😄

**Comment by agracey** [comment]
If there's no hidden gotcha in there. That is pretty close to the experience that I would want! Thank you for finding that, I might write a blog about it as well

**Comment by agracey** [comment]
I'm going to close this in favor of a new ticket about hiding potential tradeoffs behind feature flags.
