### ISSUE TITLE
Other auth methods

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1651]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use other authentication methods for Epinio users. For instance we use Rancher for our cluster and have LDAP auth for users. In order for us to be able to use epinio, we would need something like LDAP or OIDC authentication. (or auth based on the Kubernetes user)

**Describe the solution you'd like**
Authentication methods like LDAP, OIDC, or the Kubernetes authenticaiton

**Describe alternatives you've considered**
The only alternative is creating users with the bae64 password which is not secure enough for us to use.

**Comment by braunsonm** [comment]
It seems this is a duplicate of others:
https://github.com/epinio/epinio/issues/425
https://github.com/epinio/epinio/issues/1571

This issue can be closed, just very excited about this feature in order for Epinio adoption.

**Comment by enrichman** [comment]
Yes, we are working on this!
