### ISSUE TITLE
Code Structure around App, AppRef, Workload, AppDeployment

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1657]
# Background

The comment https://github.com/epinio/epinio/pull/1652#discussion_r929736755 spawned a larger discussion about code structure around the named structures and functionality when it became clear that `Workload` cannot be simply eliminated as we wished.

The reason for that the fact that `App` is defined in `models` and therefore cannot be extended with methods in `application`. The discussion of the three possible solutions which I came up with showed stark differences in our definitions of "Model" as concept, with consequent differences in how to handle the issue.

# The various ideas.

  1. Put the methods on the `App` structure, i.e. move them into the `models` package. I am arguing against this from the POV that a Model is data without logic, or minimal logic, and logic is in the Controller [1]. @jimmykarily argues for it from a POV where a model can have logic, i.e. is, in MVC terms , a fusion of model and controller, an active model.

  1. Keep the `Workload` helper structure, and have it reference a full `App` structure instead of just the `AppRef`. Now all the desired information is available. Further, `Get` can be changed to return only an `error` value. The `AppDeployment` would be directly added to the referenced `App`.

  1. In the previous the `Workload` is effectively the Controller, and instead of creating it only temporarily we could rename it to `AppCtrl` (or similar) and make it the main data structure passed around internally, instead of `App`. The `App`, as model, would be restricted to be send over the API, and to be received. For the latter it would then be immediately wrapped into a Controller.

Note that our intermediate solution (see https://github.com/epinio/epinio/commit/6b070caadb31c350cc874eb9fb7cb307562b0bbd) of adding the `desiredInstances` information through the constructor can been as a small step towards idea (2) above, just limited to adding the minimally needed `App` field, instead of the whole.

---
[1] https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

**Comment by jimmykarily** [comment]
Regarding (1), my POV for the model is the same as the link you posted:

> It directly manages the data, logic and rules of the application.

the controller is only meant to be a thin layer between the view and the model, validation user input and passing it to model methods. I'm not saying we should go for a "fat model" that does everything in one struct/class/object. Up to know I thought we were only splitting the "model layer" in various well defined entities (or structs/classes/etc) (As [described here](https://stackoverflow.com/a/14045514)) but I feel the packages we implemented are so tightly coupled that should have been one package.

Also, regarding this:

> The App, as model, would be restricted to be send over the API, and to be received. 

I think the mere description above, shows that we are calling `App` a model although it's only used for presentation.

My concerns are not that much about being pedantic with MVC definitions though. I mostly care about code being understandable with classes/structs having a well defined role, whatever that role may be. Sometimes it's hard to know whether you need an `App` or an `AppRef` in code, or whether you need a `Workload` or an `AppDeployment`. In many cases we just go back and forth between them until we get the information we need.

**Comment by andreas-kupries** [comment]
True. ... Actually, all the endpoint working with an app receive an AppRef, which is then turned into an App (if needed), by means of the temp. `Workload` structure. (Deep in the `application` package, as part of the Lookup). Should possibly review all the endpoints.

**Comment by andreas-kupries** [comment]
More discussion ... https://github.com/epinio/epinio/pull/1652#discussion_r929916233 ... Basically if the `AppDeployment.CreatedAt` field is sensible at all. 

In the old code is was the Deployment's CreatedAt, and could thus diverge strongly from the Pod timestamps, i.e. scale app to zero instances, and days later up again. The deployment age is then that many days higher than the pod ages.

In the current new code it is synthesized from the Pod ages, taking the oldest.

Full removal was proposed. I argued against, as it being an API change, incurring incompatibility. @jimmykarily remembered discussion with @manno from weeks back that the API /swagger spec is not necessarily part of what we declare stable. Which would allow us to make such changes to the API still, without running into compatibility issues.

**Comment by agracey** [comment]
@andreas-kupries Is this still an open issue?

**Comment by andreas-kupries** [comment]
Technically yes. Practically I do not see us working on it until it becomes absolutely necessary by something else.
Closing.
