### ISSUE TITLE
Epinio architectural diagram

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1664]
We need an detailed architectural diagram for Epinio to be used as documentation. 

I started looking at [c4model](https://c4model.com/) through [c4builder](https://adrianvlupu.github.io/C4-Builder/) as an option. In theory it's nice but I can't create a sensible diagram for Epinio. There are some entities that are not represented in a visually sensible way (e.g. Kubernetes itself). Will keep looking.

**Comment by jimmykarily** [comment]
C4-PlantUML allows us to draw Boundaries : https://github.com/plantuml-stdlib/C4-PlantUML#getting-started
These could be used to show which components are running inside Kubernetes.

**Comment by jimmykarily** [comment]
Actually c4builder and C4-plantUML have the same features. Making Kubernetes be the main system seems to be the right thing to do. I'll try something now.

**Comment by jimmykarily** [comment]
Started working branch: https://github.com/epinio/epinio/tree/1664-architectural-diagram

**Comment by jimmykarily** [comment]
Draft PR: https://github.com/epinio/epinio/pull/1677

**Comment by lpaulxvi** [comment]
Few suggestions/request to support the use cases where the target user for the Architecture diagram may be interested in all the components interactions for the purpose of understanding the access/network requirements or provenance of the artifacts being deployed.
(1) Can we relect in the diagram that we provide an instance of Docker registry and S3 storage within Epinio deployment since  these services and also Dev grade instances of Helm based data services can also (or by default) run within the same K8s cluster?
(2) Add the Authentication mechanism from the different actors (Dev/Ops) which is currently using basic auth and then Dex(future or experimental) 
(3)   indicate the options for Application sources used from the UI/CLI from external git/local fs etc...
If the above makes the fisrt level Architecture diagram too complex, then perhaps refer to them in additional drill-down diagrams.

**Comment by jimmykarily** [comment]
I updated the branch to show the various push options (local dir, git, pre-cooked container image). I also added information how components authenticate with each other. See here: https://github.com/epinio/epinio/blob/7a626a3aeefd538bf89014c5da0eeb01eb44bf6c/docs/explanations/architecture/containers.png

If and when we merge the dex work, and after we release it, we can update the diagram to include dex, for now things are simple.

I think my changes address points 2 and 3. Maybe adding some text to the markdown page will add more clarity.

I'm still thinking what's the best way to address point#1.

**Comment by jimmykarily** [comment]
This is what the alternative diagram would look like: https://github.com/epinio/epinio/blob/f805583a5c28351b5bf8cbc991eb9977caf5f512/docs/explanations/architecture.md

I'm not sure I like the result but if this is helpful for now, we can agree to improve it as we go. @lpaulxvi any thoughts?

**Comment by lpaulxvi** [comment]
Sorry for the delay... what tool did you use to render the diagram? Perhaps I can re order some things a bit and see if it looks easier on some of the interactions.
Comments: 
- Are Application Users meant to be those accessing the deployed apps or being able ot view the Epinio catalog (for available Helm charts?)
- I know it can be and probably will be in Prod) external to the K8S cluster hosting Epinio but it is still a bit fuzzy for the reader on where the Registry and S3 can reside (e.g for deployment of Epinio using Rancher Desktop or other local Dev environments).
- When you have done your eval with Dex, it would be useful to show this in the picture. Not having his the AuthN/AuthZ integrates with either an external provider will beg the question from the target reader(if they have Security concerns)
- Perhaps a lifecycle list of CRUD actions for the deployed App could be useful. THe reader may not be familiar with what push can accomplish after the initial deployment.

**Comment by jimmykarily** [comment]
@lpaulxvi I used the Visual Studio code plugin while working on the diagram to have a live preview (See other options here: https://plantuml.com/running). I used the `jar` file from here to produce the final png in the PR (the visual studio plugin exports but in low resolution, wasn't sure how to change that):

https://github.com/plantuml/plantuml/releases/tag/v1.2022.6

You can see the command here: https://github.com/epinio/epinio/pull/1677/files#diff-046550912fd553d4caaa88ff9a00b016e67d7ebc20c344de30d57e5e24ba01bbR12

Generally, you can place some boxes next to each other (e.g. [Using `Lay_R` et al](https://github.com/plantuml-stdlib/C4-PlantUML#layout-arrange-elements-without-relationships)) but you don't have full control on how the diagram is rendered. 

On your questions now:

- Yes, Application users are the consumers of the deployed applications. Developers are the ones that access the service catalog. It's difficult to show the latter in the diagram.
- I think when someone sees `S3` the first thing that comes in mind is AWS S3 but in any case, this type of information belongs to documentation in my opinion. There are too many options to put in a diagram.
- I don't want to document dex before we merge and release it because until that's done, there is always the possibility that we drop it for something else.
- I agree, but does that list belong to this diagram? Isn't this something for documentation?
