### ISSUE TITLE
All CI tests fail due to timeout when installing Epinio

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1675]
Since 08/05/22 EKS-CI, EKS-LETSENCRYPT-CI, AKS-CI, AKS-LETSENCYPT-CI and also RKE-CI since 08/06/22 fail when installing Epinio.
We need to investigate why and fix it 

Example with [EKS-CI](https://github.com/epinio/epinio/runs/7718893975?check_suite_focus=true#step:9:309): 

```
    STEP: Installing Epinio 08/08/22 05:01:53.275
  << End Captured GinkgoWriter Output

  Release "epinio" does not exist. Installing it now.
  Error: timed out waiting for the condition

  Unexpected error:
      <*exec.ExitError | 0xc00064a040>: {
          ProcessState: {
              pid: 57736,
              status: 256,
              rusage: {
                  Utime: {
                      Sec: 4,
                      Usec: 875937,
                      Pad_cgo_0: [0, 0, 0, 0],
                  },
                  Stime: {
                      Sec: 1,
                      Usec: 301678,
                      Pad_cgo_0: [0, 0, 0, 0],
                  },
                  Maxrss: 73805824,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 34620,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 4520,
                  Msgrcv: 6224,
                  Nsignals: 775,
                  Nvcsw: 523,
                  Nivcsw: 59030,
              },
          },
          Stderr: nil,
      }
      exit status 1
  occurred
  In [It] at: /Users/runner/work/epinio/epinio/acceptance/install/scenario4_test.go:117
```

Pasting also other cases:

- [AKS-CI](https://github.com/epinio/epinio/runs/7717561544?check_suite_focus=true#step:8:298)
- [AKS-LETSENCRYPT-CI](https://github.com/epinio/epinio/runs/7718542485?check_suite_focus=true#step:8:300)
- [GKE-CI](https://github.com/epinio/epinio/runs/7718138502?check_suite_focus=true#step:11:312)
- [GKE-LETSENCRYPT-CI](https://github.com/epinio/epinio/runs/7719325176?check_suite_focus=true#step:11:312)
- [RKE-CI](https://github.com/epinio/epinio/runs/7718313063?check_suite_focus=true#step:12:127)

**Comment by mmartin24** [comment]
Note, while RKE-CI failed on 08/05/22 during the Metallb installation process ([link](https://github.com/epinio/epinio/runs/7667889141?check_suite_focus=true#step:12:142)), from next day onwards failed during Epinio installation as the rest; so it seemed a one-time issue


```
STEP: Installing MetalLB 08/04/22 08:14:15.234
  << End Captured GinkgoWriter Output

  Error from server (InternalError): error when creating "../../assets/tests/resources.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "[https://metallb-webhook-service.metallb.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s](https://metallb-webhook-service.metallb.svc/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s)": dial tcp 10.42.0.11:9443: connect: connection refused
  Error from server (InternalError): error when creating "../../assets/tests/resources.yaml": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post "[https://metallb-webhook-service.metallb.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s](https://metallb-webhook-service.metallb.svc/validate-metallb-io-v1beta1-l2advertisement?timeout=10s)": dial tcp 10.42.0.11:9443: connect: connection refused
```

**Comment by thehejik** [comment]
I was able reproduce the original issue with RKE workflow (the second issue seems to be unrelated):
```
  Release "epinio" does not exist. Installing it now.
  Error: timed out waiting for the condition
```

It came from `helm upgrade --install epinio ... --wait` - the problem is, that for some reason epinio-server pod doesn't start and ends up in `CrashLoopBackOff` state with following error in logs:

```bash
kubectl logs epinio-server-6b4dc6f84c-vc7pr -n epinio 

❌  error creating handler: SESSION_KEY environment variable not defined
```

Still needs to be investigated.

**Comment by thehejik** [comment]
The issue is that latest epinio helm chart doesn't set `SESSION_KEY` variable anymore (shouldn't be needed for recent epinio binary). Due to that helm installation fails on timeout when using `--wait` even before building, patching and injecting the epinio binary into epinio-server pod.
