### ISSUE TITLE
Confirm Epinio works with k3s

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1690]
This ticket started with this observation from Andrew: https://suse.slack.com/archives/C03BFFJ0R8Q/p1660755703007099

> What version of k8s have we tested against? I'm running into an issue with k3s 1.24.3 on an opensuse leap 15.4 box I think it was an issue with k3s and firewalld that presented very strangely (edited)

To verify the issue I tried to deploy Epinio on k3s versions `1.23.6`, `1.23.9 `and latest` 1.24.3` on `openSUSE Tumbleweed` and `openSUSE Leap 15.4` and I always unable to visualize in the UI the deployed Epinio getting a `Bad Gateway` error screen even when Epinio seemed installed
![Image](https://user-images.githubusercontent.com/37271841/185437257-1ab1e7c4-1ad0-4b5f-94c4-0c9887068893.png)

Doing several tests I observed the `kube-system/metrics-server` pod is always unhealthy:

![Image](https://user-images.githubusercontent.com/37271841/185437732-44b6a28f-1aa3-4a7c-b606-6aa7be70321c.png)
![Image](https://user-images.githubusercontent.com/37271841/185437765-f74cffb0-3a64-4531-b72c-cc422964ad8b.png)

This pod is healthy for instance when we deploy k3d:

![Image](https://user-images.githubusercontent.com/37271841/185439025-c4dbdd1a-2843-44b7-ad9c-b3bc9d9fe554.png)

I am not sure at this point if I am missing anything or we are having an issue with k3s installing Epinio, and if so, if it is because that `kube-system/metrics-server` pod
I raised this ticket to see if anyone else is facing the same problem.

Note: we do use k3s 1.23.6 with Vagrant to deploy Rancher Dashboard and still today it is working fine for this purpose.

**Comment by agracey** [comment]
Once I turned off firewalld, everything started working as expected. My bet is that k3s expects iptables instead?

**Comment by mmartin24** [comment]
Actually worked once the firewalld was disabled:

```
mmartin@localhost:~> firewall-cmd --state
not running
```

![image](https://user-images.githubusercontent.com/37271841/185505615-92b9178a-1794-4b41-ab06-47c46a404414.png)

**Comment by mmartin24** [comment]
The above screenshot is using v1.23.9+k3s1 (so it seems it happens in previous versions to 1.24 as well) and can be seen how after firewalld is off the `kube-system/metrics-server` pod goes back to normal:

![image](https://user-images.githubusercontent.com/37271841/185507207-c80565ce-e9e3-4a74-9d41-75507257d563.png)

**Comment by andreas-kupries** [comment]
I agree that this is not something fixable in epinio, or even in the scope of epinio. I see in the slack that @agracey mentioned it ` might be something to report to the k3s team`, and I agree with that.

**Comment by mmartin24** [comment]
Thanks @andreas-kupries
@agracey I just created this ticket for the k3s team: https://github.com/k3s-io/k3s/issues/6024

Closing this ticket since does not seem Epinio related
