### ISSUE TITLE
Creating application with the name as numbers only will fail

### ISSUE THREAD

**Issue by scures** [epinio/epinio#1696]
**Describe the bug**
While creating an application if the name it's numbers only, it will be created but the deployment will be interrupted.
Trying to delete the application after creation also won't work, see the error:
![image](https://user-images.githubusercontent.com/88777903/186633505-00b7e16d-e533-4287-8a41-9b45022f55ae.png)

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Create a new app `epinio app create 1337`
2. Try to delete the app`epinio app delete 1337`

**Expected behavior**
The app should be deleted. Instead, an error is thrown;
```
🚢  Deleting application...
Name: 1337
Namespace: workspace
..
❌  error deleting app: Internal Server Error: uninstall: Release name is invalid: -77ba9cd915c8e359d9733edcfe9c61e5aca92afb
```

**Desktop/CLI (please complete the following information):**
 - OS: MacOS
- Epinio Version: 1.1.0
- Go Version: go1.18.4

**Comment by Ghgore** [comment]
Are numerical names intended behavior, or would the fix to this be to simply disallow these types of names?

**Comment by mmartin24** [comment]
@jimmykarily I just checked this issue again with latest version of epinio today and I am still seeing the issue

![image](https://user-images.githubusercontent.com/37271841/186858977-d2facb47-1cd5-4952-b422-673e272edcb5.png)

**Comment by jimmykarily** [comment]
> Are numerical names intended behavior, or would the fix to this be to simply disallow these types of names?

I would say, if there is reason to disallow them, well then we should allow them. In other words, let's see why it breaks and decide. Looking at @mmartin24 's output, it seems that we strip the numbers and there is nothing left, probably here: https://github.com/epinio/epinio/blob/bfff304e42d46cf1fb1fb576c7288f88d65e194a/internal/names/names.go#L75
