### ISSUE TITLE
Make CI green again

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1714]
- [ ] https://github.com/epinio/epinio/runs/8156409897?check_suite_focus=true
- [x] https://github.com/epinio/epinio/actions/runs/2990617447
- [x] https://github.com/epinio/epinio-end-to-end-tests/issues/223

**Comment by andreas-kupries** [comment]
WRT second: 

```
Run google-github-actions/setup-gcloud@v0
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/aeb623e1-204c-461e-a0f4-bd00527006d2 -f /home/runner/work/_temp/6c8660dc-c70f-4643-b5df-b12a32e460a5
Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud --quiet auth activate-service-account epci-gke-sa@***.iam.gserviceaccount.com --key-file -`: ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid grant: account not found', ***'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'***)
Please run:
```

The authentication data comes from

```
     - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.EPCI_GCP_CREDENTIALS }}'
```

The referenced secret was updated last on Oct 15, 2021, as per https://github.com/epinio/epinio/settings/secrets/actions
Not quite a year ago.

@juadk @ldevulder IIRC either of you did the original setup of this, right ?

Do you still have notes, etc. which can help us to update everything to new accounts ?
Related to that, do you know who manages the GKE projects and accounts used by SUSE in general, if any ?

According to @pgonin (at https://suse.slack.com/archives/C02DBSHPC2V/p1661932247235099?thread_ts=1661930338.866529&cid=C02DBSHPC2V) the existing accounts were terminated.

**Comment by ldevulder** [comment]
> The referenced secret was updated last on Oct 15, 2021, as per https://github.com/epinio/epinio/settings/secrets/actions
> @juadk @ldevulder IIRC either of you did the original setup of this, right ?
It was just after our arrival on the project, not sure if the secret was updated/created by Julien or not, but for sure not me. I remember that I began to work on RKE2, not GCP.

I just remember that later I had to fix the AKS account to match the new policy. But procedure is different on AKS and GCP.

> Do you still have notes, etc. which can help us to update everything to new accounts ?
Not on my side, but usually can be found with google (at least that what I did when I updated AKS account).

> Related to that, do you know who manages the GKE projects and accounts used by SUSE in general, if any ?
No, @pgonin do you know this?

**Comment by thehejik** [comment]
related PR https://github.com/epinio/epinio-end-to-end-tests/pull/222
