### ISSUE TITLE
Fix GC credentials issue for GKE tests

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1715]
[GKE](https://github.com/epinio/epinio/runs/8181651205?check_suite_focus=true#step:7:27) and [GKE-LETSENCRYPT-CI](https://github.com/epinio/epinio/runs/8182741170?check_suite_focus=true) test are failing with this credential error:

```
ERROR: (gcloud.container.clusters.delete) There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid grant: account not found', ***'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'***)
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Error: Process completed with exit code 1.
```

We need to fix it to allow test run normally.

**Comment by olblak** [comment]
I recently had to create a service principal account for another project and I used the this Github Action https://github.com/rancher/fleet/blob/master/.github/workflows/gke.yml#L45L48

**Comment by andreas-kupries** [comment]
See also #1714

**Comment by olblak** [comment]
Normally @mmartin24 fixed this earlier today

**Comment by mmartin24** [comment]
The issue was fixed creating a new Service Account and VPC and later updating credentials on Epinio repo. This will prevent that credentials are associated to people and instead accessible to SUSE users with access to Google Cloud within `ei-container-eco`

Credits to @olblak   for showing this process summarized here:

### Create Service account on GC: 
- Enter GC here: https://console.cloud.google.com/welcome?project=ei-container-eco&authuser=1. Ensure you are in `ei-container-eco`
- Go to `IAM Admin > Service Accounts` and created new service acount `epinio-ci` and create a new `Key` as well
- With that key update `EPCI_GCP_CREDENTIALS` in Actions secrets/Update secret in epinio repo 
- Back in GC change tabs to `IAM` and give the following roles to `epinio-ci`: `Kubernetes Engine Admin`, `Kubernetes Engine Cluster Admin`, `Service Account User`

### Create a new VPC:
- In GC go to `VPC` and create a new vpc `epinio-ci` with the following config:

```
epinio-ci
Description: Network used by Epinio to run some tests
Subnet creation mode: Auto subnets
Dynamic routing mode: Regional
VPC network ULA internal IPv6 range: Disabled
DNS server policy: None
Maximum transmission unit: 1460
```

### Updating GKE and GKE-letsencrypt scripts on Epinio

Once the above was done added new network variables  to `gke.yaml` and `gke-letsencrypt.yaml` done here:
https://github.com/epinio/epinio/pull/1718/files

### Results:
GKE passing: https://github.com/epinio/epinio/actions/runs/2993305935
GKE-LETSENCRYPT passing: https://github.com/epinio/epinio/actions/runs/2993461641
![image](https://user-images.githubusercontent.com/37271841/188469251-262b1afa-dfeb-4cb4-a2a7-77c26fa08ef6.png)


@olblak, please feel free to add anything if I missed any point and thanks again for your help here.

**Comment by mmartin24** [comment]
> See also #1714

Thanks @andreas-kupries . I already commented there and checked the corresponding one of the 2 task there as completed.
Closing now this issue.
