### ISSUE TITLE
Allow bulk deletion in Epinio from CLI

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1739]
**Issue**:
Currently, if we have several applications running on Epinio and want to delete them all, we have to do it one by one through the CLI. This does not happen in the UI where bulk deletion is allowed. 

**Request**:

- Allow an user to perform bulk deletion for `Applications`, `Services` and `Configurations` and any other type of actions that may contain a number of items subject to be deleted if no collisions exist.

**Other possible considerations:**
- If a collision or any other issue prevented the deletion of a particular app, service or config, this one could be skipped and continue deleting instead of stopping the process
- It would be nice if a description of what has been deleted and unbinded in the process could be displayed; like currently happens when an user deletes an app binded to a service:

```
➜  epinio git:(main) ✗ epinio app delete testapp1     

🚢  Deleting application...
Name: testapp1
Namespace: workspace
..........................................🚢  
|       UNBOUND CONFIGURATIONS        |
|-------------------------------------|
| x57adfcee73692eb703d7cbd17e99-mysql |

✔️  Application deleted.

```

Edit:
Converted this ticker into an epic and divided it into these tasks:

- Configuration batch deletion: https://github.com/epinio/epinio/issues/1740
- Applications batch deletion: https://github.com/epinio/epinio/issues/1742
- Service batch deletion: https://github.com/epinio/epinio/issues/1743

**Comment by mmartin24** [comment]
Converted this issue into epic as commented offline and split into 3 tasks:

- Configuration batch deletion: https://github.com/epinio/epinio/issues/1740
- Applications batch deletion: https://github.com/epinio/epinio/issues/1742
- Service batch deletion: https://github.com/epinio/epinio/issues/1743

Feel free to split further if needed

**Comment by enrichman** [comment]
When we have the batch deletion endpoints we can implement the "delete all" command, using the batch deletion.
