### ISSUE TITLE
[spike/research] AWS IAM SAML integration

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1758]
We need to try out the SAML integration with Dex (AWS IAM)

**Comment by gitricko** [comment]
There is a way to do this with AWS if SAML is not possible. Here is the architecture diagram
![Pomerium Architecture](https://user-images.githubusercontent.com/18060558/194122036-ddbd4d96-97c1-40e9-b497-ac94f26d9f45.png)

All we need to do is to get use AWS cognito and use it as a bridge to AWS IAM Identity Center.

We tested against NeuVector and it works and we are hoping to try it with dex as well... but did not have time to complete the build locally... if you can help, we can verify for you

@enrichman

**Comment by enrichman** [comment]
Thanks @gitricko . Good to know that we could use Cognito as a bridge if somewhere in the future the SAML connector will be deprecated. Since it's still widely used I don't see it coming soon. We should be fine with the SAML integration.

**Comment by enrichman** [comment]
Ok, it works! I'm leaving here a few lines on how to setup AWS and Dex to integrate Epinio.

## AWS

First of all we need to create a custom SAML application on AWS.  

Go to _**AWS IAM Identity Center**_ > **_Applications_** > **_Add Application_**

![Screenshot from 2022-10-10 16-56-43](https://user-images.githubusercontent.com/1763949/194903252-aa0f48c6-a49f-4887-ba48-22dd3ae194bf.png)

Click on the **Add custom SAML 2.0 application** checkbox and click **Next**.

Give it a name and a description, take note of the **IAM Identity Center sign-in URL** (it should be something like https://portal.sso.eu-west-1.amazonaws.com/saml/assertion/XXXYYYZZZ) and **download the certificate**.

Leave the optional **Application properties** empty.

Add the Dex URL in the **Application metadata** section:

|                                              |                                                             |
|--------------------------------------|---------------------------------------------------|
| Application ACS URL           |  https://auth.mydomain.com/callback  |
| Application SAML audience |  https://auth.mydomain.com                |

**Submit** your application.

Now we have to **Edit the Attribute Mappings**

![Screenshot from 2022-10-10 17-01-57](https://user-images.githubusercontent.com/1763949/194905545-06881106-8200-447a-b79e-35df7787113a.png)

Use this values

| Application attribute | AWS attribute | format          |
| ---------------------------|--------------------|------------------|
| Subject                    | ${user:email}  | persistent     |
| name                       | ${user:name}  | unspecified  |
| email                        | ${user:email}  | unspecified  |

**Note:** if you have some 403 error it could be easily due to an attribute misconfiguration!  
Be careful to specifiy the _persistent_ format in the _Subject_ attribute.  

![Screenshot from 2022-10-10 17-02-11](https://user-images.githubusercontent.com/1763949/194906538-76687277-370d-46a8-a25a-bab8a67e71a9.png)

Remember to **assign your application** to your users.

## Dex

Now you have to edit your Dex configuration, adding the [SAML connector](https://dexidp.io/docs/connectors/saml/).  

To do this you will need the AWS SSO URL, and the base64 encoded AWS certificate.

To encode the certificate:
```
cat /path/to/my/AWS_SSO.pem | base64 -w0
```

and then your connectors configuration should be something like this

```yaml
connectors:
- type: saml
  id: saml
  name: AWS
  config:
    entityIssuer: "https://auth.mydomain.com"
    ssoURL: "https://portal.sso.eu-west-1.amazonaws.com/saml/assertion/XXXYYYZZZ"
    caData: XXXYYYZZZ== # the base64 encoded AWS certificate 
    redirectURI: "https://auth.mydomain.com/callback"
    usernameAttr: name
    emailAttr: email
```

Now you can restart Dex and you should be able to login with the `epinio` CLI with the `--oidc` flag:

```
epinio login --oidc https://epinio.mydomain.com
```

![image](https://user-images.githubusercontent.com/1763949/194907565-a32dce06-17c9-45ff-9ae1-cff9d3137955.png)

**Comment by riqueps** [comment]
Hello @enrichman 

Thanks for your documentation, it worked like a charm.

Just one correction: `Application SAML audience` must have `/` at the end of url ( https://auth.mydomain.com/ )

**Comment by enrichman** [comment]
Great! Good to hear that. And if without the trailing `/` it wasn't working I'm happy to see that you figured out the problem (it worked for me).

**Comment by riqueps** [comment]
Trying to get this Architecture working:

![image](https://user-images.githubusercontent.com/47371890/195105196-c45ee2b8-884d-47f9-85e2-e0e431fd7bc8.png)

Epinio web UI, worked fine, when accessing I got redirected to Pomerium to be authenticated and after authenticated I was redirected back to epinio ui url.

But when trying to login via epinio cli (`epinio login --oidc https://epinio.domain.com`), it returns the error bellow and did not open the web page to be authenticated:
`❌  constructing dexProviderConfig: creating the provider: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got "text/html": invalid character '<' looking for beginning of value`

**Comment by riqueps** [comment]
I put Pomerium in front of epinio and dex, so when I run `epinio login --oidc ...`, before I can access dex or epinio services first I need to be authenticated against [pomerium](https://www.pomerium.com/docs/overview/architecture) (vpn-less solution, so either epinio or dex are not directly faced to internet anymore).

Accessing Epinio flow:
https://epinio.domain  -->  redirect to pomerium to be authenticated against my IdP  -->  after authenticated redirects me back to epinio https://epinio.domain.

So if I not get authenticated by pomerium, I'm not allowed to access the services behind it, in this case dex or epinio.

This error from epinio cli is because the cli is trying to talk with Dex but Pomerium is getting this request.

![image](https://user-images.githubusercontent.com/47371890/195594049-f0b96051-29a2-4bc9-844a-953a52ed9545.png)

**Comment by enrichman** [comment]
I see. I'm wondering if the last fix that I merged yesterday (https://github.com/epinio/epinio/pull/1787) would solve this issue.

It adds the possibility to set a different endpoint to fetch the dex configuration, and by default it will have the `http://dex.epinio.svc.cluster.local` url, instead of using the issuer url.

So if the problem was related to this external roundtrip (blocked by Pomerium) it would be already solved with the next release.

**Comment by riqueps** [comment]
Humm.  I'm thinking if this will resolve the issue.
Because pomerium is a proxy-aware identity solution, so it'll get the epinio cli request and then follow pomerium authentication flow before redirects to epinio api.
Take a look at the demo bellow that I did for epinio web ui.

https://drive.google.com/file/d/11hkC2JCjBk1zyp3smYLFLqYJ49skX8NX/view?usp=sharing

**Comment by enrichman** [comment]
Ok, maybe I understood the flow. In this way you are skipping the Dex integration.

Should you try to go through Dex after Pomerium? I'm not sure if it's possible but Dex should act as an IdP and ask the authentication to AWS: Pomerium -> Dex -> AWS.

I don't know how to handle this setup though. Probably I should try to setup a Pomerium instance.

**Comment by enrichman** [comment]
No, I don't think it will. Probably the flow should be a little different, and going through Dex after Pomerium.

A test would be setting up Pomerium as a static client in the Dex configuration as a static client, maybe acting as a trusted peer for the epinio-api, as the epinio-cli does. And then going from Dex to the Cognito or AWS authentication.
Then in the Pomerium config you should setup Dex as the IdP, adding also the epinio-api scope (`audience:server:client_id:epinio-api`) probably, like the CLI does.

https://github.com/epinio/epinio/blob/eca9b94cf58f0120643cc9d1356ad7b3b2c932f4/pkg/api/core/v1/client/client.go#L53

I've found this as a reference: https://www.pomerium.com/docs/identity-providers/dex-freeipa

It needs some tests, I'm off today but if you could try something like this it would be nice.

**Comment by riqueps** [comment]
Hum, got it!

Is there a way to do this automatically?

**Comment by enrichman** [comment]
You mean the role assignment? It's something that we don't support yet, but if you feel that would be an interesting feature I would open an issue/enhancement about it.

I don't know the details but maybe we can leverage the claimMappings, or groups. And also having a map into Epinio to understand to which group assign which role.

**Comment by riqueps** [comment]
Yes, this would be a very nice feature, which improve the experience by bringing and "zero-touch" for user creation process.

**Comment by riqueps** [comment]
Hi @enrichman

I created a local dev env with Epinio + Pomerium + OIDC provider ([you can find here](https://github.com/riqueps/epinio-pomerium)) to let us run some tests and try to figure it out how we can protect epinio cli with pomerium. Please have a look and play around.

Also I took a look how pomerium works with k8s api, it uses [impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) permissions. Do you think this is feasible with epinio cli?

**Comment by riqueps** [comment]
Hi @enrichman

I created a local dev env with Epinio + Pomerium + OIDC provider ([you can find here](https://github.com/riqueps/epinio-pomerium)), it still need some improvements, but it would let us run some tests and try to figure it out how we can protect epinio cli with pomerium. Please have a look and play around.

Also I took a look how pomerium works with k8s api, it uses [impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) permissions. Do you think this is feasible with epinio cli?

**Comment by enrichman** [comment]
Hi @riqueps, I tried your env and I managed to make it work. I had a couple of issues, one was probably related to [this](https://github.com/pomerium/pomerium/issues/3602), so I pinned the qlik image to the 0.2.2.

I don't think it would be feasible for the Epinio cli to use those, because they would need to have access to the Kubernetes APIs, while we are acting as a proxy to the k8s layer.

Do you still have any problem regarding this issue, or do you think we can close it?

**Comment by riqueps** [comment]
Hi @enrichman .
Thanks for your feedback.
About the local stack, I released a new version which deploy everything inside the k3d cluster.

Got it.
Maybe I can create a feature request for this, because is very useful get epinio cli fully working behind a VPN-less security solution (this case Pomerium).
This would enhance the dev experience, without the necessity of jump hosts, vpn clients, etc... and at the same time keep the epinio api protect.
Make sense for you?   What do you think?


**Yes, you can close this issue**, once I got Dex SSO working through SAML and OpenID .
Here is the Dex setting for OpenID
```
connectors:
- type: oidc
  id: dex_id
  name: Dex
  config:
    issuer: https://IDP_PROVIDER_URL
    clientID: dex_id
    clientSecret: dex_secret
    redirectURI: https://DEX_URL/callback
    scopes:
     - profile
     - email
     - openid
```
