### ISSUE TITLE
Move EKS tests to AWS LZ

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1760]
We have been requested to move EKS tests to AWS LZ

Links to tests:

https://github.com/epinio/epinio/actions/workflows/aks.yml?query=branch%3Amain
https://github.com/epinio/epinio/actions/workflows/aks-letsencrypt.yml?query=branch%3Amain

**Comment by mmartin24** [comment]
Initial work done:

I do not have access to repo secrets nor admin access to AWS Landing Zone.
@olblak creates IAM account, modifies secrets and attempts binding with EKS test.

**Comment by mmartin24** [comment]
New update: 

- EKS cluster `epinio-ci24149` created
- Credentials changed
- Moved region to `eu-central-1` ( https://github.com/epinio/epinio/pull/1763)
- Tests [here](https://github.com/epinio/epinio/actions/runs/3151697958/jobs/5126039138)
  - EKS cluster creation seems to be ok
  ```
  2022-09-29 13:54:36 [✔]  EKS cluster "epinio-ci24149" in "eu-central-1" region is ready
  ```
  - Fails later when updating DNS entries:
   ```
      [It] Installs with loadbalancer IP, custom domain and pushes an app with env vars
      /Users/runner/work/epinio/epinio/acceptance/install/scenario4_test.go:75
    make: *** [test-acceptance-install] Error 1
    
      Begin Captured GinkgoWriter Output >>
        STEP: Checking LoadBalancer IP 09/29/22 14:02:44.973
        STEP: Updating DNS Entries 09/29/22 14:02:50.94
      << End Captured GinkgoWriter Output
      
      An error occurred (AccessDenied) when calling the ChangeResourceRecordSets operation: User: arn:aws:iam::***:user/epinio-ci is not authorized to access this resource
   ```

**Comment by mmartin24** [comment]
Most of CI tests except RKE-CI ones failed on the updating DNS entries step mentioned above, since . Will address this today.

**Comment by mmartin24** [comment]
GKE test fixed but AKS and EKS ones still failing.
Errors:

EKS:

```
STEP: Pushing an app with Env vars 1
❌  error pushing app to server: can't upload archive: server status code: Internal Server Error
  {"errors":[{"status":500,"title":"ensuring bucket: checking bucket epinio-ci exists: 301 Moved Permanently","details":"uploading the application sources blob\nServer Backtrace: 301 Moved Permanently\nchecking bucket epinio-ci exists\ngithub.com/epinio/epinio/internal/s3manager.
``` 

AKS:

```
   STEP: Updating DNS Entries 10/03/22 02:10:59.603
  << End Captured GinkgoWriter Output

  
  An error occurred (SignatureDoesNotMatch) when calling the ChangeResourceRecordSets operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

**Comment by svollath** [comment]
Done for EKS. AWS secrets moved to ORG level, epinio-ci bucket moved to AWS LZ => EKS-CI is green again.
