### ISSUE TITLE
[UI] Remove button for custom routes not working

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1775]
### Steps to reproduce:

- In the UI, create an app with custom route
- Once created go to `Edit Config` for that app
- Click `Remove` and save

![Image](https://user-images.githubusercontent.com/37271841/190586655-d4c0ed8c-253f-4db2-86dc-f42fbe1e902b.png)

### Observed behavior:
- The app route is still displayed in the UI
![Image](https://user-images.githubusercontent.com/37271841/190586874-17286d29-7af9-4902-b981-1a40b9e715cf.png)
- If you go again to `Edit Config`, the Routes is still there:
![Image](https://user-images.githubusercontent.com/37271841/190586963-416807d7-41eb-4a5f-8c5b-75fe7d3131cf.png)

### Expected Behavior
~~The route should effectively be removed and be displayed again either in main App screen or in Details screen for that app~~
To be clarified

### Tested on:
Epinio v1.2.0-18-g3782bdf4

**Comment by enrichman** [comment]
Closing in favor of #1799
