### ISSUE TITLE
Missing docs for Dex/OIDC integration

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1779]
**Describe the bug**
The most recent release added Dex integration however it seems there are docs missing and out of date comments in the helm chart stating that it is disabled by default yet the enable flag is true. 

**Additional context**
It would be great to see docs on how CLI/UI login works with an OIDC provider and how to configure Dex from the Epinio chart.

**Comment by mmartin24** [comment]
Thanks @braunsonm. Just to confirm. Did you see this? https://docs.epinio.io/references/authentication_oidc

**Comment by thehejik** [comment]
Currently only epinio CLI supports OIDC/DEX, support for Epino UI is planned.

**Comment by braunsonm** [comment]
I did not see that! My mistake thank you!
