### ISSUE TITLE
Icon for Epinio chart is missing in the Rancher Manager UI

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1780]
**Describe the bug**

The epinio chart within the `Rancher` helm repo provides an image that does not exist.

![image](https://user-images.githubusercontent.com/18697775/194356455-25c0c91a-bc09-4d75-88b9-db679871133b.png)

The image comes from the `icon` property of epinio's `catalog.cattle.io.clusterrepos` resources

`<rancher url>/k8s/clusters/<cluster id>/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=epinio&link=icon&version=100.0.0%2Bup1.2.1`

**To Reproduce**
1) Bring up Rancher Manager (i think any production version, but seen with `2.7-head`)
2) Nav to any cluster --> Apps --> Charts and search for epinio

**Expected behavior**
Icon should be displayed

**Comment by andreas-kupries** [comment]
> The image comes from the icon property of epinio's catalog.cattle.io.clusterrepos resources

I do not know anything about these `catalog.cattle.io.clusterrepos` resources.

The possibly relevant change in the chart integration is below, which changes the chart icon from an external PNG to an integrated SVG, i.e. distributed with the `rancher/chart` repository ... I have confirmed now that the image is in that repository. I.e. I did not forget to commit it.

@PennyScissors Do you have any explanations why the image could be missing ? Some other place where it should be set ?

```
> cat packages/epinio/epinio/generated-changes/patch/Chart.yaml.patch
--- charts-original/Chart.yaml
+++ charts/Chart.yaml
[...]
+  catalog.cattle.io/type: cluster-tool
[...]
@@ -20,7 +31,7 @@
[...]
-icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
+icon: https://charts.rancher.io/assets/logos/epinio.svg
 keywords:
```

**Comment by richard-cox** [comment]
Completely missed this yesterday as well, the description also needs updating. At the moment it states `The official way to install Epinio` rather than an enticing description of what epinio is. Let me know if this should be in a separate issue

![image](https://user-images.githubusercontent.com/18697775/194518481-6b4229bb-84d1-40ea-9fe4-4ab80d703172.png)

**Comment by andreas-kupries** [comment]
Lets keep it here for now.

**Comment by andreas-kupries** [comment]
The rancher dev-2.7 branch is missing the logo, and the crd chart, and assets ... Working PR for that.

**Comment by andreas-kupries** [comment]
Ref https://github.com/rancher/charts/pull/2156

**Comment by nunix** [comment]
I would suggest the text to be based on the following (can be adjusted if needed):

> Epinio deploys Kubernetes applications directly from source code in one step.

Based on the description being short, I bypass the mention of ingress URL on purpose.

**Comment by andreas-kupries** [comment]
Should be done with https://github.com/rancher/charts/pull/2191, when it appears in the next Rancher 2.7 release

**Comment by thehejik** [comment]
Actually this will be fixed by merging this PR https://github.com/rancher/charts/pull/2606
