### ISSUE TITLE
Find a nicer logo for carrier

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#181]
I am not enamored to have a warship as our logo.

Some google searches for nicer ideas

  - https://www.google.com/search?q=container+carrier+icon
  - https://www.google.com/search?q=straddle+container+carrier+icon
  - https://www.google.com/search?q=pet+carrier+icon
  - https://www.google.com/search?q=cattle+carrier+icon

**Comment by jimmykarily** [comment]
One more type of carrier: https://cdn3.iconfinder.com/data/icons/finances-trade-flat-colorful/614/4705_-_Box_Carrier-512.png

**Comment by andreas-kupries** [comment]
- https://www.pngitem.com/middle/ixwxixT_cargo-boat-rubber-stamp-cargo-ship-logo-png/
- https://www.istockphoto.com/de/vektor/schiff-und-boot-icon-set-gm498254970-79550275
- https://www.canstockphoto.com/cargo-ship-60666738.html
- https://icon-library.com/images/cargo-ship-icon/cargo-ship-icon-21.jpg (https://icon-library.com/icon/cargo-ship-icon-21.html)
- https://www.wdi-python.de/fileadmin/user_upload/symbole/Maritime/STRADDLE-CARRIER.jpg
- https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdkrWsDQjZUgUpEAyTesUxzJ8Ao-_C4MtcVQ&usqp=CAU

- https://hhla.de/unternehmen/news/detailansicht/weltweit-modernster-hybrid-van-carrier

**Comment by agracey** [comment]
Maybe something like: http://www.abbeydaledirect.co.uk/images/srv/product-enlargement/Restraining/Liftease%20Cattle%20Lifter.jpg

**Comment by andreas-kupries** [comment]
Mooted by project rename and chosen logo.
