### ISSUE TITLE
Ensure Epinio does not appear in Rancher UI's Cluster Tools section

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1815]
- The Rancher UI has a page titled Cluster Tools that lists helm charts that offer secondary functionality for a cluster (monitoring, logging, alerting, networking, backups, etc)
- The Epinio chart mistakenly briefly appeared here (at the moment it's hidden as the chart is experimental)
- As Epinio is more of a core reason for the cluster, rather than a tool for managing it, it shouldn't be categorised as a cluster tool

This is an easy fix, just requires the removal of a chart annotation 
```
catalog.cattle.io/type: "cluster-tool"
```

> It might be worth checking if the type should be something else, rather than removing the annotation or leaving it empty

**Comment by andreas-kupries** [comment]
Refound documentation for the annotation at https://confluence.suse.com/display/EN/Feature+Charts+Helm+Requirements

> Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
> See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
>  catalog.cattle.io/type: cluster-tool

and

> Cluster Tools
>
> Starting in Rancher 2.6, a new Cluster Tools section was added to the UI to make it easier to see and deploy a specific subset of charts from the rancher/charts repo. In order to determine which charts from the rancher/charts repo should be displayed in Cluster Tools, the `[catalog.cattle.io/type](http://catalog.cattle.io/type): cluster-tool` annotation needs to be added to the helm chart. Legacy charts will also be displayed in Cluster Tools, but they do not require this annotation. 
>
> Use the following checklist to help determine if your chart is considered a cluster tool: 
>
>   - You have worked with the UI Team to add chart specific logic to the UI, and a navlink associated to the chart will appear on the sidebar after the chart is installed. 
>   - Your chart has the  `[catalog.cattle.io/namespace](http://catalog.cattle.io/namespace): cattle-<RESOURCES>-system` and `[catalog.cattle.io/release-name](http://catalog.cattle.io/release-name): <APP_NAME>` annotations (see required annotations above for more details) 
>
> Feature charts that are displayed in the Cluster Tools section will still be available in the Apps & Market place in the ui.

Of the check list we pass the second point, but not the first.

As we are certainly not a cluster-template we can only be `app`.

@enrichman @richard-cox Objections ?

**Comment by andreas-kupries** [comment]
See also https://github.com/rancher/charts/pull/2191

**Comment by andreas-kupries** [comment]
Should be done with https://github.com/rancher/charts/pull/2191 merged.
