### ISSUE TITLE
Helm chart values for Dex ingress.ClassName

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1821]
Dex ingress.ClassName and Annotations is not getting the value set through `ingress.ingressClassName=....` and `'ingress.annotations.ingress\....' ` flags.

Force to get the same ClassName and Annotations of Epinio or create a new value mapping, eg:`dex.ingress.ingressClassName=....`  ,  `'dex.ingress.annotations.ingress\....`

Tested on epinio 1.3.0

**Comment by andreas-kupries** [comment]
Investigation ...

The `dex` chart looks for `.Values.ingress.className` to set its ingress' `spec.ingressClassName` field.
In the main chart values this should translate into `dex.ingress.className`.
Like the minio's `.Values.drivesPerNode` looks to be pulled from the main charts `minio.drivesPerNode`.

Was that tried ?

**Comment by andreas-kupries** [comment]
@enrichman :warning: Looking over the helm chart I note that the `values.schema.json` does not contain specs for the new `dex` section of the `values.yaml`. Placing writing this spec under this same issue instead of making a separate ticket.

**Comment by riqueps** [comment]
Hello @andreas-kupries .
I'm testing `dex.ingress.className` and its not working.

Helm chart installation:

`helm install epinio -n epinio --create-namespace epinio/epinio --set global.domain=domain.com --set ingress.ingressClassName=nginx --set dex.ingress.className=nginx `

![image](https://user-images.githubusercontent.com/47371890/204559326-5efb2340-96b5-4d6d-9d53-c35024626b83.png)

![image](https://user-images.githubusercontent.com/47371890/204559350-619170ca-31f7-4c9d-b0ce-a240a32ed94e.png)
