### ISSUE TITLE
Enable brew to install different version of epinio cli

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1837]
**Is your feature request related to a problem? Please describe.**
As different epinio version comes fast and furious in terms of bug fixes and features improvement, it will be nice to have a way to switch between cli version easily. Currently, we use brew and I know brew has a way to switch version if the source supports it. 

**Describe the solution you'd like**
eg: `brew install epinio` will install latest version (what ever latest it maybe... say 1.4.0)
`brew install cf-cli@1.3.0`

**Describe alternatives you've considered**
downloading and moving different version to `/usr/local/bin`

**Comment by enrichman** [comment]
Yes, this could be a nice improvement, I thought that it would be somehow automatically handled by homebrew but that's not the case.

By the way did you know about the `epinio client-sync` command that we introduced recently (v1.3.0)?
It's going to sync the epinio binary to match the epinio server version that you are currently targeting.

**Comment by gitricko** [comment]
> 

Agree that might help... but some of our instances are still in 1.1 and 1.2 :-( Waiting for upgrade

**Comment by enrichman** [comment]
I think it works only on authenticated requests for security reasons:

**Comment by enrichman** [comment]
I think it works only on authenticated requests for security reasons, to avoid exposing to everyone the actual running Epinio version: https://github.com/epinio/epinio/issues/1153#issuecomment-1256161623

**Comment by andreas-kupries** [comment]
@gitricko Regarding

> I know brew has a way to switch version if the source supports it.

do you have references to brew's documentation or other places describing this ?

**Comment by andreas-kupries** [comment]
goreleaser and homebrew ... See https://goreleaser.com/customization/homebrew/

**Comment by andreas-kupries** [comment]
@gitricko Did you see my question above, about doc references ?

At the moment I have not determined how to support your request in brew.
More importantly I have not seen anything indicating that goreleaser would be able to generate such support.
IOW currently pessimistic in ability to implement your request at all.

Talked with @enrichman a bit this morning ... A possible workaround might be to fork the aforementioned `client-sync` to a `client-fetch` command able to fetch a binary directly from the github releases of epinio ... Architecture matching the client binary doing the fetch or user-specified, either latest version or user-specified, and either overwrite or save to other file. For some platforms also doing the zip extraction. ...

@enrichman Thinking about it this would be useful in our upgrade tests too. Replace our `scripts/get-latest-epinio*.sh` scripts with a single `epinio client fetch ...` to perform the local upgrade.

**Comment by andreas-kupries** [comment]
ping @gitricko

**Comment by gitricko** [comment]
sorry for the late reply... I think we can close this. We added this to our makefile
```
install-epinio-cli-linux:
	-rm -f /usr/local/bin/epinio
	curl -s -o epinio -L https://github.com/epinio/epinio/releases/download/v$(EPINIO_SERVER_VERSION)/epinio-linux-x86_64
	chmod +x ./epinio && mv epinio /usr/local/bin

install-epinio-cli-osx:
	-rm -f /usr/local/bin/epinio
	curl -s -o epinio -L https://github.com/epinio/epinio/releases/download/v$(EPINIO_SERVER_VERSION)/epinio-darwin-x86_64
	chmod +x ./epinio && mv epinio /usr/local/bin
```

To give us a way to change the epinio list instead of using brew

eg: EPINIO_SERVER_VERSION=1.6.1 make install-epinio-cli-osx
