### ISSUE TITLE
internal routes for epinio apps (internal domain) work ?

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1838]
**Is your feature request related to a problem? Please describe.**
Cloud Foundry apps can communicate with each other securely and directly over internal routes that never leave the platform. I wonder if epinio supports this

**Describe the solution you'd like**
microservice A has a public route (system domain) and will call an internal microservice B with an internal domain (similar to binding uri of service catalog) Is there such a feature and is it configured ?

**Describe alternatives you've considered**
This link https://docs.epinio.io/howtos/custom_routes seems to suggest it but the example is ANOTHER public route. We have use cases that the route is internal

**Additional context**
https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

**Comment by enrichman** [comment]
Hi @gitricko, yes, this is possible using the internal dns. Basically every deployed application has its own (kubernetes) service, which can be used to reach the application without leaving the cluster.

This is the output of `epinio app show sample` of a sample application:

```bash
-> % epinio app show sample                                                

🚢  Show application details
Namespace: workspace
Application: sample

✔️  Details:
|         KEY          |                                VALUE                                 |
|----------------------|----------------------------------------------------------------------|
| Origin               | /home/enrico/Development/SUSE/epinio/epinio/assets/golang-sample-app |
| Created              | 2022-11-04 09:34:30 +0100 CET                                        |
| Status               | 1/1                                                                  |
| Username             | admin                                                                |
| Running StageId      | 31b23c14c7db0546                                                     |
| Last StageId         | 31b23c14c7db0546                                                     |
| Age                  | 16m29s                                                               |
| Active Routes        |                                                                      |
| App Chart            | standard                                                             |
| Desired Instances    |                                                                    1 |
| Bound Configurations |                                                                      |
| Environment          |                                                                      |
| Chart Values         |                                                                      |

✔️  Instances: 
|                              NAME                               | READY | MEMORY  | MILLICPUS | RESTARTS |  AGE   |
|-----------------------------------------------------------------|-------|---------|-----------|----------|--------|
| rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209-75f58cfdbfjbvp | true  | 5.4 MiB |         0 |        0 | 16m29s |
```

The instance name `rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209-75f58cfdbfjbvp` is `<pod/service>-<instance-id>`, and so you can derive the service name leaving out the instanceID.

In this case the endpoint is just `http://rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209.workspace.svc.cluster.local`. Since the pod that I've used to curl is within the same namespace you can drop also all the rest, and just use the service name (`http://rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209`)

![image](https://user-images.githubusercontent.com/1763949/199931624-ba9c5bb3-5b04-4c9c-88d6-20796ab087cb.png)

I was thinking that we could show this endpoint in the `epinio app show` command, something like:

```
-> % epinio app show sample                                                

🚢  Show application details
Namespace: workspace
Application: sample

✔️  Details:
|         KEY          |                                VALUE                                          |
|----------------------|-------------------------------------------------------------------------------|
| Internal Routes      | rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209.workspace.svc.cluster.local  |                                                                    
```

What do you think?

**Comment by enrichman** [comment]
As a bonus point I wanted to tell you that since `v1.4.0` you can actually clear out all the external routes of an application. In this case the app is not reachable from the outside, and you can deploy it without any routes.

```bash
-> % epinio app update --help                    
Update the running application's attributes (e.g. instances)

Usage:
  epinio app update NAME [flags]

Flags:
  -z, --clear-routes          clear routes / no routes
```

```bash
-> % epinio app update -z sample                                           

🚢  Update application
Namespace: workspace
Application: sample
Routes: <clearing all>

✔️  Successfully updated application
```

**Comment by gitricko** [comment]
> 

That is an GREAT idea. In the beginning, it was how i tot it would work... looking at the backing service URI, but i could not figure out the naming convention for the app. Having stated explicitly would be helpful to automation and having a way to deploy WITHOUT public route is also needed! 

Is it possible to clear the route during the push ? Something like `epinio push --no-route`

**Comment by andreas-kupries** [comment]
The same option, i.e. `-z`/`--clear-routes` works for `push` as well. Which is why the description of the option contains the text `no routes` too.

**Comment by andreas-kupries** [comment]
To complete the trifecta, `app create` takes the option as well.

**Comment by gitricko** [comment]
> To complete the trifecta, `app create` takes the option as well.

Thanks @andreas-kupries, able to show internal routes will be a great help in terms of helping automation
