### ISSUE TITLE
As a developer, it would be nice for Epinio to repush on file change

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#184]
Similar to [`skaffold dev`](https://skaffold.dev/docs/workflows/dev/), I think it could be very useful to have a `epinio watch` or similar that triggers a push when a file changes on disk.

**Comment by enrichman** [comment]
This is possible to achieve with external tools (Fleet?) or [inotifywait](https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes).

Since this isssue has been open for more than 1y I'm going to close it.

**Comment by agracey** [comment]
It could be in the vscode plugin when we get that built.
