### ISSUE TITLE
Move self-hosted runners to GCP

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#1840]
We should move our self-hosted github action runners to GCP. That's bee done by other projects already, and basic docs are within Confluence (CECO/Self-hosted+runner+in+GCP).
So we will need to check if that fits our needs as well, and come up with a plan for moving Epinio self-hosted runners to GCP.

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.
