### ISSUE TITLE
As a developer, it would be nice to be able to snapshot the current workspace and rollback to it later

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#185]
Something like `epinio snapshot [tag-name]` and `epinio rollback [tag_name]`. 

Sure, you can do this in the actual git repo. But a quick snapshot and rollback is nice! Especially if it can allow you to do quick a/b toggles with the images already built.

**Comment by jimmykarily** [comment]
This adds very little compared to the flow with git (or other version control system) and it means we introduce a new concept to Epinio which needs a full set of controlling commands/endpoints:

- List snapshots
- Delete snapshot
- Show snapshot
- Create snapshot (by uploading the code)

not to mention UI changes for this if we want it in UI too. Given there are plans to support git better in the UI, I think this has little value. To save some time from back and forth between timezones, I'll assume we agree and close this. @agracey please re-open if I missed something.
