### ISSUE TITLE
Default paketo image for amd64 only

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1850]
**Describe the bug**
Default epinio `packeto` image `paketobuildpacks/builder:full` is available for `amd64` only, so this image won't be usable for `arm64` nor `s390x`.

I haven't found any replacement on dockerhub.

**Comment by agracey** [comment]
We should document this limitation somewhere

**Comment by enrichman** [comment]
At the moment we are not going to provide the builders for other architectures, but someone can still do this.

Let's close it and keep an eye about the future on the other issue.
