### ISSUE TITLE
Able to access minio

### ISSUE THREAD

**Issue by Lodimup** [epinio/epinio#1856]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Able to access minio using port forward

**Describe alternatives you've considered**
-
**Additional context**
I would like to access minio service that comes with epinio. Currently with port-forward minio will not let you login due to invalid ssl

**Comment by agracey** [comment]
What are you hoping to do with the data in minio? These buckets aren't supposed to be used for other workloads

**Comment by Lodimup** [comment]
> What are you hoping to do with the data in minio? These buckets aren't supposed to be used for other workloads

The disk usage keeps growing until K8s couldn't garbage collect. After uninstalling Epinio everything is back to normal. 

So, we suspect it's Minio.

**Comment by agracey** [comment]
Ok, then I think we should address that issue directly and improve our garbage collection. Would you mind if I edited the name of this ticket to reflect that? 

@gitricko We are looking at s3gw in #1876

**Comment by agracey** [comment]
@Lodimup Would you mind deleting a bunch of apps the next time you run into this to see if it resolves the issue naturally? If so, it could be that #1646 is the culprit and too much is being uploaded on each push.

**Comment by Lodimup** [comment]
Restarting the cluster make the total usage go down a bit. Not sure if related. Uninstalling/Reinstalling epinio resolved the issue.

thanks for good work!

**Comment by agracey** [comment]
I want to know why though so we can actually fix the issue 😆 

How many apps do you have running when you see the behavior? How much RAM and disk space do you have in cluster?

**Comment by Lodimup** [comment]
We really love Epinio. The spec was T2.Large, 2vcpu 8gb ram. about 4 apps.

**Comment by gitricko** [comment]
> We really love Epinio. The spec was T2.Large, 2vcpu 8gb ram. about 4 apps.

For us, we use the stock epinio with minio and registry as part of the install. Instability start to grows (timeout from registry) when we have lots of deployments. For minio, it is fairly stable. We are able to run 11 apps with 7 backing services on a C5.large 32g ram 16cpu in dockerize k3s
