### ISSUE TITLE
Show the internal routes of services

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1867]
**Is your feature request related to a problem? Please describe.**
When a user deploy a service it's difficult to understand which is the endpoint of the service.

**Describe the solution you'd like**
It will be nice to see the internal routes of the service with the `epinio service show` command, so that it could be possible to use them with the application.

**Describe alternatives you've considered**
It's possible to check the deployed kubernetes services with `kubectl` but a user with no access to the cluster could not do this.

Also sometimes it's "difficult" to know in advance the name of the service, because for example a Redis will deploy a master with some replicas:

```
-> % k get svc -n workspace                                                         
NAME                                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
x62215c67064c3cac3413ad9c6536-mongodb                ClusterIP   10.43.173.152   <none>        27017/TCP   31m
xbe737f7c936b454da33f586d0166-redis-headless         ClusterIP   None            <none>        6379/TCP    23m
xbe737f7c936b454da33f586d0166-redis-master           ClusterIP   10.43.155.49    <none>        6379/TCP    23m
xbe737f7c936b454da33f586d0166-redis-replicas         ClusterIP   10.43.106.20    <none>        6379/TCP    23m
```

**Comment by agracey** [comment]
IMO, this could be solved by cleaning up the helm charts from bitnami to be more intentional for development usage.

**Comment by enrichman** [comment]
I'm not sure what you mean. The problem is that is hard for a dev to know where it's application should point to reach its service.

With the proposal the dev can see the internal endpoints with just a `epinio service show` (as we did for the apps)



![Image](https://user-images.githubusercontent.com/1763949/203303134-8dd3599a-d2c7-4fab-9d46-5d94cc21450e.png)

**Comment by agracey** [comment]
Ok, I think I read the issue wrong. Yes, this change makes sense to me as a discovery/debug mechanism

**Comment by gitricko** [comment]
yes, this will be very useful
