### ISSUE TITLE
Secret init container

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1868]
**Is your feature request related to a problem? Please describe.**
The configuration secrets are mount to the pod under the `/configurations` path.

**Describe the solution you'd like**
A more common approach is to read configuration variables as environment variables, and it would be nice to have an init container that is capable to read the configurations and set it as env vars:

i.e.: the secret in the `/configurations/myredis/redis-password` will be avaiable also as `CONFIGURATIONS_MYREDIS_REDIS_PASSWORD` (maybe prefixed with an `EPINIO_`?).

**Comment by enrichman** [comment]
Related: https://github.com/epinio/epinio/issues/1647

**Comment by agracey** [comment]
Is this so that we can pull the values from vault?

**Comment by enrichman** [comment]
Hm, no. Probably this is a duplicate of #1647. I will close this in favor of the other one, but if we need to pull secrets from other sources we can reopen it, or open a new one.
