### ISSUE TITLE
Authentication for `--builder-image` flag

### ISSUE THREAD

**Issue by hadirga** [epinio/epinio#1872]
**Is your feature request related to a problem? Please describe.**
I'm trying to push an app using a custom builder, this builder is located in a private registry that doesn't allow access without authentication.

**Describe the solution you'd like**
We can use something like a flag to pass the registry credentials, example: the flag used by `skopeo` to authenticate destination registry  ` --dest-creds <username>:<password>`. 

**Additional context**
https://docs.epinio.io/howtos/custom_builder

**Comment by enrichman** [comment]
Hi @hadirga, if the image is located in a private registry you just probably need to provide the registry credentials to the cluster: https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

**Comment by gitricko** [comment]
@hadirga if this is not needed, please close. Thanks
