### ISSUE TITLE
[Epic] Epinio with s3gw 

### ISSUE THREAD

**Issue by giubacc** [epinio/epinio#1876]
[s3gw](https://github.com/aquarist-labs/s3gw) is the opensource S3 gateway developed by SUSE derived from [Ceph](https://github.com/ceph/ceph)'s radosgw.
s3gw is focused on light resource consumption and it is natively thought for the usage on Kubernetes.
Even if it is currently on an early stage of its development, s3gw represents the privileged choice for Epinio. 
Currently, Epinio integrates with Minio; there are some choices we must define if we want s3gw to become the Epinio's default storage gateway.

1. Do we want to keep both Minio and s3gw as choices for the Epinio user?
   - yes we do
3. If we are going to keep Minio as a possible choice, should it be the default (no I guess) ? 
   - yes at the beginning
5. Should we have a grace period where Minio remains the default choice?
   - yes at the beginning
7. How do we want to treat existing users?
   - we don't need to tread them in any way; Epinio uses S3 as an ephemeral storage
9. Should they be forced to migrate one day?
   - only if s3gw will become the only choice (not likely to)
11. Should we provide a tool to migrate user's data? who? s3gw project or Epinio?
    - not needed, see 4
13. Should Epinio import s3gw as subchart (as it is doing now for Minio) ?
    - yes because we want give the option to install s3gw as optional bundle for Epinio 
15. Should s3gw installed as bundle with Epinio use Longhorn?
    - no
17. If the 8 evaluates as NO because eg: we want to keep the dependency chain at the minimum, what are the choices here?
    - s3gw as bundle uses the default storage class or the one provided by yhe user
19. The PVC used by s3gw can be a simple hostpath? would this cause problems if the s3gw pod is rescheduled on a different host?
    - in principle use a hostpath pvc is not recommended; we are relying on the storageclass provided by the user 
21. Should s3gw-ui be installed by default with Epinio?
    - no,  as it has been done for Minio, the user can eventually enable it

**Comment by agracey** [comment]
I think this would be very useful and could be done over time to make it easier.

IMO, the path would be:
- Add as secondary option via subchart**
- Write tests using this option
- Once comfortable, switch default
- No need for migration path as all data is ephemeral and will be reconstructed on next push
  - Will need release notes saying that pushes will fail during upgrade -- but that's likely assumed to be true anyways

** Is there a better way to include as dependency without having to "vender in" with a subchart?

**Comment by giubacc** [comment]
Currently, s3gw from inside the Kubernetes cluster does not provide a TLS termination.
That is (currently) available only through the ingress on the public configured domain for s3gw.
I think this is a strict requirement s3gw must meet before starting integration.

**Comment by l-mb** [comment]
If I understand correctly, epinio uses the s3gw storage as a backup; does it even make sense to host that in the same cluster as epinio itself?

That aside, could epinio not connect to the external endpoint even though it's technically on the same cluster? That'd avoid the need for handling the internal/external cases differently.

**Comment by giubacc** [comment]
> If I understand correctly, epinio uses the s3gw storage as a backup; does it even make sense to host that in the same cluster as epinio itself?
> 
> That aside, could epinio not connect to the external endpoint even though it's technically on the same cluster? That'd avoid the need for handling the internal/external cases differently.

Even if this could be technically possible, personally I don't like this approach.
An ingress is logically made for external clients and (IMO) should not be used for communications within the cluster.
Let's keep in mind that we are offering the user the choice whether to use an ingress.
An user could legitimately want not to install an ingress but he could require an encrypted connection between epinio and s3gw.

**Comment by agracey** [comment]
> If I understand correctly, epinio uses the s3gw storage as a backup; does it even make sense to host that in the same cluster as epinio itself?

The reason we need this is for developer clusters where HA is not needed and the simplicity of an all-in-one install is important. In production environments, I would expect that we always run storage in separate clusters.

**Comment by giubacc** [comment]
@agracey @l-mb I have added 3 questions: 8 to 10

**Comment by agracey** [comment]
> * Should s3gw installed as bundle with Epinio use Longhorn?

No, the deployment target is commonly clusters where you wouldn't want to use the underlying node's storage (AWS, GCP, Azure, etc...)

> * If the 8 evaluates as NO because eg: we want to keep the dependency chain at the minimum, what are the choices here?

I think we should use the default storage class with the option of overriding it manually. If there is no default, I think helm would fail the install naturally, right?

> * The PVC used by s3gw can be a simple hostpath? would this cause problems if the s3gw pod is rescheduled on a different host?

Yes, because it wouldn't be able to reschedule. In most instances where hostpath is being used, this is a known trade-off (really only for developer environments...). It might be worth adding a line to the helm notes when hostpath is used about it being unstable in case it gets picked by accident?

**Comment by giubacc** [comment]
> No, the deployment target is commonly clusters where you wouldn't want to use the underlying node's storage (AWS, GCP, Azure, etc...)

Are we saying that in such platforms (AWS, GCP, Azure, etc...) there must be a `storageclass` that will provision storage outside of nodes? (Nearly zero expert here)

> I think we should use the default storage class with the option of overriding it manually. If there is no default, I think helm would fail the install naturally, right?

I hope so (we will test this obviously).

> Yes, because it wouldn't be able to reschedule. In most instances where hostpath is being used, this is a known trade-off (really only for developer environments...). It might be worth adding a line to the helm notes when hostpath is used about it being unstable in case it gets picked by accident?

This leads possibly to another question: would be possible to define a `storageclass` that is provisioning simple `hostpath` volumes?
Supposing this is possible and the user is choosing this; this would be acceptable? 
Suppose you are using that scenario and this happens:
1)  `epinio push -n myapp`
2)  `s3gw` pod is rescheduled on another node

The Epinio system is still into a consistent state?

**Comment by l-mb** [comment]
s3gw only relies on a persistent storage class (like LH) for redundancy, and using Longhorn for this is the preferred and tested way. In theory, any other storage class that provides the persistent volume claim also would work. The Helm chart already allows this.

In a production setup, s3gw would be deployed independently from epinio (since it's going to be a different cluster for availability reasons), at which point this is transparent to epinio anyway. And handled either via the builtin s3gw LH deployment, or by deploying LH and s3gw in conjunction.

If a localpath provisioner is used, the s3gw pod needs to assigned to that node only and not to any other.

**Comment by agracey** [comment]
> Are we saying that in such platforms (AWS, GCP, Azure, etc...) there must be a `storageclass` that will provision storage outside of nodes? (Nearly zero expert here)

Yes, for instance in AWS you can set up either EFS or EBS depending on your needs (and budget) but we can assume one exists.


> This leads possibly to another question: would be possible to define a `storageclass` that is provisioning simple `hostpath` volumes? Supposing this is possible and the user is choosing this; this would be acceptable? Suppose you are using that scenario and this happens:
> 
> 1. `epinio push -n myapp`
> 2. `s3gw` pod is rescheduled on another node
> 
> The Epinio system is still into a consistent state?

Likely no... If there are multiple nodes and one fails I don't think s3gw would get rescheduled on another node. This would cause pushes to stop working. IMO, this is not a case to be concerned about as any admin using hostpath should know that. 

If I'm wrong about the rescheduling and it does come back up but the storage is empty, Epinio should just refill the cache and continue on. The only "downtime" would be that any pushes in progress could fail if they were in the middle of a transfer.

**Comment by agracey** [comment]
> In a production setup, s3gw would be deployed independently from epinio (since it's going to be a different cluster for availability reasons), at which point this is transparent to epinio anyway. And handled either via the builtin s3gw LH deployment, or by deploying LH and s3gw in conjunction.

Agreed! I expect that very few of Epinio's default config would be used in production.

**Comment by kkaempf** [comment]
- [ ] #2109
