### ISSUE TITLE
Create Epinio Dashboard Metric

### ISSUE THREAD

**Issue by olblak** [epinio/epinio#1884]
**Is your feature request related to a problem? Please describe.**

Some metrics are useful in the lifecycle of a project to better understand how the project is evolving.
I would love to better understand how long current and old Epinio version are being used

**Describe the solution you'd like**
While doing some research on this topic I got suggested to look at https://github.com/longhorn/upgrade-responder which sounds super interesting

This would imply:
- [ ] Identifying where to host the upgrade responder service
- [ ] Add the Go snippet to the Epinio server. 

**Describe alternatives you've considered**
I had a look to 
* [GitHub Release Download Assets](https://somsubhra.github.io/github-release-stats/?username=epinio&repository=epinio&page=1&per_page=5), this information only tells me that Epinio has been downloaded, not how long it's being used.
* [ArtifactHUB](https://artifacthub.io/packages/helm/epinio/epinio)

**Additional context**

**Comment by enrichman** [comment]
The PRs for Epinio are merged. We need to finalize the Grafana dashboard, and run a couple of Influx queries for the ExtraInfo that we have.

We should also probably automate the ConfigMap update step.
