### ISSUE TITLE
Ruby version `2.7.5` of example-rails app is not supported

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1919]
**Describe the bug**

The [Rails app test](https://github.com/epinio/epinio/blob/main/acceptance/apps/rails_test.go) started failing because of the unsupported Ruby version.

https://github.com/epinio/epinio/actions/runs/3591825801/jobs/6051174104

```
buildpack failed to satisfy "ruby" dependency version constraint "2.7.5": no compatible versions on "io.buildpacks.stacks.bionic" stack. Supported versions are: [2.7.6, 2.7.7, 3.0.4, 3.0.5, 3.1.2, 3.1.3] 
```

We need to update the https://github.com/epinio/example-rails Ruby version.

**Comment by andreas-kupries** [comment]
The `2.7.5` is mentioned in `.ruby-version`, `Gemfile`, and `Gemfile.lock`. The latter looks to be generated from the second.

**Comment by andreas-kupries** [comment]
Update via `bundle install` ?!

**Comment by andreas-kupries** [comment]
Fixed with https://github.com/epinio/example-rails/pull/6
