### ISSUE TITLE
Enable access to AWS resources through Instance Profile

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1925]
Ref: #1895 

As an operator I would like Epinio to be able to access AWS resources without specifying access keys and secrets but through instance profile. This could be already possible but we need to test it.

**Comment by enrichman** [comment]
Doing some investigations it seems to work, with some changes.

I've created a policy to access the S3 with the following permissions:

```bash
aws iam create-policy \
    --policy-name EpinioECEKSClusterPolicy \
    --policy-document \
'{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:PutObject",
                "s3:GetObject",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "s3:CreateBucket",
                "s3:DeleteObject",
                "sts:AssumeRole"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}'
```

and then I've attached this policy to the instance Role:

```bash
aws iam attach-role-policy \
    --role-name 'eksctl-epinio-nodegroup-ng-x123-NodeInstanceRole-ABC123CDE456' \
    --policy-arn 'arn:aws:iam::0123456789:policy/EpinioECEKSClusterPolicy'
```

To get the instance role you can use this command:

```
kubectl -n kube-system describe configmap aws-auth | grep rolearn | cut -d':' -f7 | cut -d'/' -f2
```

To make it work we need to change the Minio client connection to use a different set of credentials. At the moment we are using the `credentials.NewStaticV4` while to get the correct profile we need to use the `credentials.NewIAM("")` (with an empty string).

https://github.com/epinio/epinio/blob/794fcb049c41687ff3834c6e80409f070adb9654/internal/s3manager/s3manager.go#L73

We also need to skip the mounting of the secrets credentials, because they will take precedence over the IAM role:

https://github.com/epinio/epinio/blob/794fcb049c41687ff3834c6e80409f070adb9654/internal/api/v1/application/stage.go#L399-L403

This was enough to use the instance role to access the S3. I'm still investigating how and if it's possible to use the same approach to get through the AWS registry (ECR). It seems that the buildpack lifecycle has some issues with that.

**Comment by enrichman** [comment]
I was having hard times to try to use the ECR registry in the same way, and it seems that is not possible:

> The Docker CLI does not support native IAM authentication methods. Additional steps must be taken so that Amazon ECR can authenticate and authorize Docker push and pull requests.
>
> https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

**Comment by thehejik** [comment]
I did post merge testing with AWS S3 resource and it works as expected.

This is simplified guide how to validate:
* deploy EKS, EBS (look into EKS-CI wf for reference)  and setup IAM according to comment above from Enrico
* export KUBECONFIG=<PATH>
* install traefik
```
helm install traefik --namespace traefik traefik/traefik --set ports.web.redirectTo=websecure --set ingressClass.enabled=true --set ingressClass.isDefaultClass=true --create-namespace
```
* install cert-manager
 ```
helm upgrade --install cert-manager --namespace cert-manager cert-manager/cert-manager --set installCRDs=true --set "extraArgs[0]=--enable-certificate-owner-ref=true" --create-namespace
```
* epinio (upstream one 1.5.2) with AWS S3 but without providing SECRETS
```
helm upgrade --install epinio --namespace epinio epinio/epinio  --set skipTraefik=true --set global.domain=REDACTED --create-namespace --set minio.enabled=false --set s3.useSSL=true --set s3.region=eu-central-1 --set s3.bucket=epinio-ci --set s3.endpoint=s3.eu-central-1.amazonaws.com
```
* patch epinio: checkout epinio/epinio, `cd epinio; make build; make patch-epinio-deployment`
* deploy simple app and look for errors in Staging phase
* verify also the bucket has a new entry

**Comment by thehejik** [comment]
Successfully verified in epinio v1.6.0
