### ISSUE TITLE
Enable access to AWS resources through IRSA (IAM Roles for Service Accounts)

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1926]
Ref: https://github.com/epinio/epinio/issues/1895

As an operator I would like Epinio to be able to access AWS resources without specifying access keys and secrets but through IRSA (IAM Roles for Service Accounts).

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by enrichman** [comment]
After some tests it seems that we only need to add the `serviceAccount` to the staging jobs.

The Epinio server has already a `epinio-server` service account that can be linked to a IAM Role. I tried with the `eksctl` cli and it was working fine. I need to try again with the AWS cli, because otherwise the eksctl will take the ownership over Helm.

**Comment by enrichman** [comment]
When the PRs are merged it will be possible to associate a serviceaccount to the staging job.

i.e.:
```
helm upgrade --install epinio epinio/epinio \
    --namespace epinio --create-namespace \
    --set global.domain=mydomain.com \
    --set server.stagingServiceAccountName=epinio-staging-service-account
```

Then we just need to create the corresponding Role and ServiceAccount. This can be done with the AWS cli but it will be easier with `eksctl` (we are not managing this with Helm, so no worries with this):

```
eksctl create iamserviceaccount \
    --name epinio-staging-service-account \
    --namespace epinio \
    --cluster ${CLUSTER_NAME} \
    --role-name "epinio-staging-role" \
    --attach-policy-arn "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/EpinioECEKSClusterPolicy" \
    --approve
```

**Comment by andreas-kupries** [comment]
This looks to become a document issue and PR, right ?

**Comment by thehejik** [comment]
Successfully validated on epinio v1.7.0 with EKS v1.23 with EBS addon. Tried only accessing AWS S3. 

Documentation https://docs.epinio.io/howtos/aws_iam_integration#authentication-with-aws-eks-service-account

* deloy EKS v1.23 inc. EBS addon - if on EKS 1.22 run `eksctl utils associate-iam-oidc-provider --cluster=$CLUSTER_NAME --approve`
* deploy epinio - use AWS S3 but do not provide AWS keys:
```
helm upgrade --install epinio --namespace epinio epinio/epinio  --set skipTraefik=true --create-namespace --set minio.enabled=false --set s3.useSSL=true --set s3.region=eu-central-1 --set s3.bucket=epinio-ci --set s3.endpoint=s3.eu-central-1.amazonaws.com  --set global.domain=<MY-DOMAIN> --set server.disableTracking=true
```
* epinio app push fails now  `❌  error pushing app to server: can't upload archive: server status code: Internal Server Error`
* create policy - `aws iam create-policy EpinioEKSClusterPolicy ...`
* create epinio-server role and hook it with OIDC_PROVIDER - `aws iam create-role ...`
* attach the role to the policy - `aws iam attach-role-policy ...`
* annotate epinio-server serviceaccount - `kubectl annotate serviceaccount epinio-server ...`
* create iamserviceaccount for epinio namespace - `eksctl create iamserviceaccount ...`
* upgrade epinio helm deployment by repeating the same command as for initial deployment but append  `--set server.stagingServiceAccountName=epinio-staging-service-account`
* pushed an APP again - now it succeeded.

When testing I was hit by a rate limiter on AWS OIDC provider (I guess - according to epinio-server logs) but it got resolved when I deleted the iamserviceaccount and recreated again. (deleted by `eksctl delete iamserviceaccount --cluster $CLUSTER_NAME --name epinio-staging-service-account --namespace epinio`)
