### ISSUE TITLE
Enable multiarch for epinio-unpacker image from goreleaser and use it in helm chart

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1935]
We have two pipelines building epinio-unpacker image.

The first one is kind of static and has multiarch support enabled already, it's currently used in helm-charts. We are building it manually by using this [workflow](https://github.com/epinio/epinio/blob/main/.github/workflows/unpacker-image.yml).

The other one which should be resolved by this issue is getting build during a release but for `amd64` only so doesn't have multiarch (arm64 and s390x) support enabled yet. This image is building during a release by using [release.yml](https://github.com/epinio/epinio/blob/main/.github/workflows/release.yml) and [goreleaser](https://github.com/epinio/epinio/blob/main/.goreleaser.yml).

To address this issue we'd need:
- [x] enable multiarch support for `epinio-unpacker:<release-tag>` image via goreleaser.
- [x] use the image in our helm charts

Ref. PR https://github.com/epinio/epinio/pull/1933
Ref. https://github.com/epinio/epinio/issues/1928

**Comment by andreas-kupries** [comment]
Oh ... Somehow skipped over the multi-arch part of the manual flow ... In that case adding multi-arch to #1933 might be easy ... (I had somehow thought that we might now have the BCI base for the other platforms).

**Comment by andreas-kupries** [comment]
Multi-Arch commit 868dd97df676023b38d505a7171c16ebd4570bcc

**Comment by andreas-kupries** [comment]
Unpacker multi arch looks ok at first glance - https://github.com/epinio/epinio/actions/runs/3638085699/jobs/6139862722 - Had to drop armv7 tough, no support in the BCI image.
