### ISSUE TITLE
[1.5.1] Helm value for `dex.ingress.className` can be set but it's ignored

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1937]
The key was introduced by https://github.com/epinio/helm-charts/pull/297 but the value is just ignored and not incorporated into dex.yaml template.

Reproducer:
In k3s traefik ingress controller is deployed by default (no ingressClassName set)  so I deployed nginx-ingress in addition from helm which uses `ingressClassName=nginx`.  (Well, it was bad idea because it cannot listen on the same address and ports as traefik but anyway this is not a problem here.)

```bash
$ helm upgrade --install epinio --namespace epinio epinio/epinio  --set skipTraefik=true --set global.domain=10.10.10.16.nip.io --set dex.ingress.className=nginx --create-namespace

# Verify if the class was set
$ kubectl get ingress -n epinio
NAMESPACE   NAME     CLASS    HOSTS                         ADDRESS         PORTS     AGE
epinio      epinio   <none>   epinio.10.10.10.16.nip.io   10.10.10.16   80, 443   20m
epinio      dex      <none>   auth.10.10.10.16.nip.io     10.10.10.16   80, 443   20m
```

**Comment by andreas-kupries** [comment]
IMHO we should report this upstream, to the DEX dev team

**Comment by andreas-kupries** [comment]
Looking at the 0.12.1 dex chart we are currently using the chart's `.Values.ingress.className` should be set as either `spec.ingressClassName` of the ingress (kube > 1.18) or as the "kubernetes.io/ingress.class" annotation of the ingress (kube <= 1.18).

More debugging of an install using `--set 'dex.ingress.className=nginx'` I find
  - The setting shows up in the `values.yaml` helm uses to template the chart and sub chart
  - It also shows up in the computed values.
  - As reported the dex ingress does not have the desired class
  - A grep through the fetched data (`helm get all`) shows that the sub chart template file `epinio/charts/dex/templates/ingress.yaml` is __not__ in the list of templated files. Only rbac, service, and deployment.
  - Which means that the templating I mentioned at the very beginning of this comment is apparently not done at all.
  - Reading the file again I see that it is guard by `if .Values.ingress.enabled`
  - Which, by default, is __off__, and the main chart does not override that.
