### ISSUE TITLE
`carrier install` fails on minikube with podman

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#194]
Installing Carrier on minikube with podman. 

`carrier install` finishes with gitea network error:

> &gt; carrier install
> 
> 🚢 Carrier installing...
> 
> Configuration...
>   🧭  system_domain: 
> 
> 🚢 Deploying Traefik Ingress.......................
> ✔️  Traefik Ingress deployed
> .
> ✔️  Created system_domain: 192.168.49.0.omg.howdoi.website
> 
> 🚢 Deploying Quarks......................
> ✔️  Quarks deployed
> 
> 🚢 Deploying Workloads....
> ✔️  Workloads deployed
> 
> 🚢 Deploying Gitea........................................................................
> ✔️  Gitea deployed
> 
> 🚢 Deploying Registry..................................
> ✔️  Registry deployed
> 
> 🚢 Deploying Tekton..............................................................W0305 17:59:21.599096   27966 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
> .......................
> ✔️  Tekton deployed
> 
> 🚢 Deploying ServiceCatalog..................................................W0305 18:00:24.075369   27966 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> 
> ✔️  ServiceCatalog deployed
> 
> ✔️  Carrier installed.
> System domain: 192.168.49.0.omg.howdoi.website
> W0305 18:00:24.129974   27966 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
> error initializing cli: gitea client failed: Get "http://gitea.192.168.49.0.omg.howdoi.website/api/v1/version": dial tcp 192.168.49.0:80: connect: network is unreachable
>

**Comment by kkaempf** [comment]
`192.168.49.0` is `cni-podman0`:

> &gt; ip a
> ...
> 8: cni-podman0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 0e:cb:00:23:02:c4 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.49.1/24 brd 192.168.49.255 scope global cni-podman0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::ccb:ff:fe23:2c4/64 scope link 
>        valid_lft forever preferred_lft forever
> ...

**Comment by kkaempf** [comment]
All subsequent `carrier` commands fail with the same network error.

**Comment by agracey** [comment]
If you browse to 192.168.49.0.omg.howdoi.website or 192.168.49.1.omg.howdoi.website, do you time out or get a 404?

I had a similar issue with k3d pulling the wrong address as docker does some remapping. The fix was to set the domain manually and I thought there was already an open issue but I'm not seeing one so I guess I dreamed it...

**Comment by AP-Hunt** [comment]
I had this issue today too, using Minikube. I got the IP to be correct by
setting MetalLBs address pool to be `${MINIKUBE_IP}/32`, but afterwards I
got timeouts to the gitea endpoint.BAll using the `omg.howdoi.website`
domain.

Similar results when using fake domain configured in `/etc/hosts` I believe
(but take that bit with a grain of salt, I don't remember the exact
configuration at the time)

**Comment by agracey** [comment]
Same question, do you get a 404 when curling `<ip>.omg.howdoi.website`? If not, try `kubectl get svc -A` -- which port is traefik running on?

Also, just so we can keep a checklist of platform specific setups for documentation, what OS are you running?

**Comment by kkaempf** [comment]
> If you browse to 192.168.49.0.omg.howdoi.website or 192.168.49.1.omg.howdoi.website, do you time out or get a 404?

Timeout for both.

**Comment by kkaempf** [comment]
Switching minikube driver from `podman` to `KVM` resolves this issue for me.

**Comment by jimmykarily** [comment]
@AP-Hunt looking at this: ```error initializing cli: gitea client failed: Get "http://gitea.192.168.49.2.omg.howdoi.website/api/v1/version": dial tcp 192.168.49.2:80: i/o timeout```

it seems `gitea.192.168.49.2.omg.howdoi.website` somehow resolves to `192.168.49.2`. Do you maybe still have the fake domain in  `/etc/hosts` ?

I had a similar issue with kind and our documented metallb setup. I'm using a remote VM on Openstack accessed using a public IP assigned by a LoadBalancer. I set my system domain to:  `vm_loadbalancer_ip_address.omg.howdoi.website`

to be able to access it from my local workstation. Then I map the kind node's ports `80` and `443` to the same ports on the VM. For some reason I can access the gitea service using the ingress url. The IP metallb assigns to the traefik service is not the one of the kind node and when I edit the traefik service and add the node's IP as `externalIPs` then all ingress works as expected.

Not sure how metallb sets up the IP it assigns to the traefik service and how routing happens but something is missing here.
@rohitsakala any idea?

**Comment by AP-Hunt** [comment]
Nope, nothing pointing at `192.168.49.2` in my `/etc/hosts` file. In case it helps, I recall running Minikube with the `docker` driver, and that's being provided by Docker Desktop For Mac.

Just to set expectations, I won't get time to test any resolutions to this until my next L&D day at work on 22nd March.

**Comment by kkaempf** [comment]
I get the initial error (carrier picking the network address ending in `.0`) also for k8s 1.19.9 (`minikube start --kubernetes-version=v1.19.9`)

**Comment by kkaempf** [comment]
With v1.19.9:

> &gt; minikube kubectl -- get services -n traefik
> NAME      TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
> traefik   LoadBalancer   10.108.76.199   192.168.39.0   80:31198/TCP,443:32745/TCP   28m

(note the `.0` in EXTERNAL-IP)

With v1.20.2

> &gt; minikube kubectl -- get services -n traefik
> NAME      TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
> traefik   LoadBalancer   10.106.200.17   192.168.39.80   80:31615/TCP,443:31939/TCP   12m

**Comment by kkaempf** [comment]
I'm closing this issue since Epinio with minikube on podman is [documented as unsupported](https://github.com/epinio/epinio/blob/main/docs/user/howtos/provision_external_ip_for_local_kubernetes.md#minikube)

The IP address issue is continued at #635
