### ISSUE TITLE
Evaluate a release cut branch before release

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1947]
Since we are evaluating a new release process for Epinio, perhaps we could debate about creating a release cut branch prior the actual release.

The basic idea is to "freeze" that branch with the changes we want to pass a few days before the actual release while regular development can continue on other branches. This would also give time to perform QA before the release.

We can discuss along on some of these items:
- Agree in advance what UI is deployed.
- List all the features that will be in.
- Review what is expected / not .

**Comment by enrichman** [comment]
We can now test the new helm-chart before the public release. We could evaluate development helm-chart but I think that we can close this for now.
