### ISSUE TITLE
Groups and Roles mapping - Not Working

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1949]
I'm trying to setup Auto Groups and Roles mapping, but it's not working.
About the env:
- Identity provider: AWS Cognito
- Auth Protocol: OIDC
- Epinio v1.5.1

Obs: I'm not using [dex SAML connector](https://dexidp.io/docs/connectors/saml/#warning) because is not being maintained 

Here is my settings:
- dex-config secret:
  I added an extra section `roleMapping` base64 encoded
![image](https://user-images.githubusercontent.com/47371890/206791473-8c2ead21-89c6-4818-b522-5e86b47112b2.png)
- dex config.yaml section:
  At the config.yaml file I added the loadAllGroups and orgs section
![image](https://user-images.githubusercontent.com/47371890/206791639-1144cbfc-428f-45a7-92db-4ef9c85f3f7f.png)
- dex roleMapping section
  - This is the roleMapping section content (which is base64 encoded at dex-config secret)
  - AWSOrg is the id whichi set at the connector settings
  - us-east-1-uQz.... is the cognito group name
![image](https://user-images.githubusercontent.com/47371890/206791698-a5d17c40-8ed0-4196-a88a-6a0a05360b63.png)

**Comment by enrichman** [comment]
Just to confirm the roleMapping section should be a separate key in the dex-config secret, at the same level of the dex configuration.

**Comment by enrichman** [comment]
I'm not sure about the `oidc` connector, but maybe you need to add the `groups` scope. Could you give a try?

**Comment by riqueps** [comment]
Just got it working through OIDC.

Dex logs:
![image](https://user-images.githubusercontent.com/47371890/207150505-e2e2317f-6f0c-4f11-8eee-d333b5782543.png)


Check the required configuration bellow:

**config.yaml:**
```
config:
 ....
    insecureEnableGroups: true
    claimMapping:
      groups: "cognito:groups"
```
![image](https://user-images.githubusercontent.com/47371890/207150076-1b9daf87-6c79-4bb5-b68d-50a70dc0d0aa.png)

**rolesMapping:**
```
- connectorId: aws_cognito
  groups:
  - id: cognito_group_name
    role: admin
```
![image](https://user-images.githubusercontent.com/47371890/207150259-ce8fd1b6-c3cc-4ccc-b508-fd9615925e16.png)
