### ISSUE TITLE
Certificate signed by unknown authority - epinio cli login

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1950]
When I log into epinio via cli, it returns a warning message: `Certificate signed by unknown authority`

- I'm using cert-manager with lets-encrypt to issue AWS certificates.
- I see the same behavior with or without --oidc flag.
- On web-ui everything looks fine.

![image](https://user-images.githubusercontent.com/47371890/206794742-fc1f3c92-5f1c-42eb-a340-ce92e3ce26ff.png)

**Comment by andreas-kupries** [comment]
Wondering if running the `epinio settings update-ca` command would help.

**Comment by olblak** [comment]
Hey thanks for reporting this issue.
Is your AWS root ca be part of https://wiki.mozilla.org/CA ?
 
If you are on a Linux machine do you have the package "ca-certificates" installed?
For example https://software.opensuse.org/package/ca-certificates on opensuse
But I am pretty sure it's the same name on other distribution as well

**Comment by riqueps** [comment]
> epinio settings update-ca

I received this message when I run `epinio settings update-ca`:
`  couldn't check kubeconfig; ensure kubeconfig is correct to continue: invalid kube config: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`

I'm running K8S version 1.22.

**Comment by enrichman** [comment]
I think that the error about the kubeconfig should not be there. A user should be able to add/update the trusted certificates also without having access to the cluster (like we do during the login). But this is a different issue, since the Amazon certificate should be trusted anyway.

**Comment by riqueps** [comment]
Hi @andreas-kupries and @enrichman:

Env details:
- EKS cluster v1.22
- Epinio v1.5.1
- Epinio cli v1.5.0
- Kubectl 1.22.16

I was researching about this and I saw that this API `client.authentication.k8s.io/v1alpha1` was deprecated and removed from K8S 1.24 ([here](https://github.com/fluxcd/flux2/issues/2817#issuecomment-1149581573)).

Does epinio use this api for something?

Because once I'm using k8s 1.22 I'm still using this api version.
kubeconfig file:
![image](https://user-images.githubusercontent.com/47371890/207596900-2ce6794f-e1d0-4ebd-9468-ec0bcbda638b.png)

**Comment by enrichman** [comment]
Thanks @riqueps, it was actually a simpler issue, and I should have already a fix for this. :+1:

**Comment by riqueps** [comment]
Tks @enrichman.

Is it possible to release as a hot fix version?
Because this issue will directly impact our CI/CD pipelines.

**Comment by enrichman** [comment]
Sure, we will try to release the `1.5.2` next week.
