### ISSUE TITLE
Extra IngressClass for epinio workload only

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1954]
Ref. https://github.com/epinio/epinio/issues/1863

Since we can now define one generic ingressClass for ep+dex and workload it would be nice to allow an extra ingress for workload only if defined.

Current state is visible in this [comment](https://github.com/epinio/helm-charts/pull/316#pullrequestreview-1213810077)

**Comment by andreas-kupries** [comment]
Notes:
1. The epinio API server recognizes the option `--ingress-class-name` and associated environment variable `INGRESS_CLASS_NAME`
1. When specified this value is passed to applications on deployment, through the `epinio.ingress` setting of the standard application chart (See `helm-charts/chart/application/values.yaml`).
1. The templating of the standard application chart copies this to the `spec.ingressClassName` of the application's ingress(es) created for the application's routes.
1. That said, the Epinio helm chart currently sets the EV (see (1)) to the value of `ingress.ingressClassName`, i.e. the same ingress class used by epinio API server and dex ingresses

It seems to me that it should be possible to do what is asked for by adding a new field to `values.yaml` where an application ingress class can be specified by the operator installing Epinio. The using location would use this when specifiedm and fall back to the current behaviour of using the same class as server+dex, if not.

@enrichman @agracey @thehejik Comments ?

**Comment by andreas-kupries** [comment]
The change has passed CI. It still requires some kind of testing that it actually works.
Some limited local testing showed it working as expected

### defaults

```
kubectl get ingress -A
NAMESPACE   NAME                                                              CLASS    HOSTS                                  ADDRESS      PORTS     AGE
epinio      dex                                                               <none>   auth.172.19.0.4.omg.howdoi.website     172.19.0.4   80, 443   31m
epinio      epinio                                                            <none>   epinio.172.19.0.4.omg.howdoi.website   172.19.0.4   80, 443   31m
workspace   rfox-fox1721904omghowd-e1b000783e607b8332f6accbe990696dc34286d9   <none>   fox.172.19.0.4.omg.howdoi.website      172.19.0.4   80, 443   8m41s
```

### --set 'ingress.ingressClassName=traefik' -- All the same

```
kubectl get ingress -A
NAMESPACE   NAME                                                              CLASS     HOSTS                                  ADDRESS      PORTS     AGE
epinio      epinio                                                            traefik   epinio.172.19.0.4.omg.howdoi.website   172.19.0.4   80, 443   16m
epinio      dex                                                               traefik   auth.172.19.0.4.omg.howdoi.website     172.19.0.4   80, 443   16m
workspace   rfox-fox1721904omghowd-e1b000783e607b8332f6accbe990696dc34286d9   traefik   fox.172.19.0.4.omg.howdoi.website      172.19.0.4   80, 443   7m29s
```

### NEW --set 'server.ingressClassName=traefik' -- Just for apps

```
kubectl get ingress -A
NAMESPACE   NAME                                                              CLASS     HOSTS                                  ADDRESS      PORTS     AGE
epinio      epinio                                                            <none>    epinio.172.19.0.4.omg.howdoi.website   172.19.0.4   80, 443   14m
epinio      dex                                                               <none>    auth.172.19.0.4.omg.howdoi.website     172.19.0.4   80, 443   14m
workspace   rfox-fox1721904omghowd-e1b000783e607b8332f6accbe990696dc34286d9   traefik   fox.172.19.0.4.omg.howdoi.website      172.19.0.4   80, 443   6m31s
```
