### ISSUE TITLE
Cleanup untagged/commits `epinio` images

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1955]
It seems that we have untagged images hanging around, and committish tags (`v1.5.1-42-g2cde6742`).

https://github.com/epinio/epinio/pkgs/container/epinio-server/versions?filters%5Bversion_type%5D=untagged

We should delete the untagged and add some automatic cleanup.

**Comment by andreas-kupries** [comment]
- https://github.com/marketplace/actions/ghcr-delete-image#usage
- https://github.com/snok/container-retention-policy

**Comment by andreas-kupries** [comment]
Retention action allows filtering/excluding through tags:
- https://github.com/snok/container-retention-policy#untagged-only
- https://github.com/snok/container-retention-policy#filter-tags
- https://github.com/snok/container-retention-policy#filter-include-untagged
-

**Comment by andreas-kupries** [comment]
Permissions needed:
- `read:packages`, and
- `delete:packages`
