### ISSUE TITLE
Unable to export app when 1.5.1 is installed as Rancher App from dev-v2.x

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1965]
**Describe the bug**
Rancher:v2.6.9 on k3s v1.24.6+k3s1
Epinio  (100.0.3+up1.5.1) Rancher App installed from `dev-v2.6` rancher repository

and
Rancher:v2.7.0 on k3s v1.24.6+k3s1
Epinio  (101.0.2+up1.5.1) Rancher App installed from `dev-v2.7` rancher repository

After deploying a sample app over webUI and calling `epinio app export sample ./` user is getting only `values.yaml` file. Chart and Image are not exported.

Missing Image was expected as we don't have `skopeo` image mirrored due to a image format incompatability but we should get `chart` in addition which is missing.

```
epinio app export sample ./

🚢  Export application
Namespace: workspace
Application: sample
Target Directory: ./

Downloading app values to 'values.yaml' 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (357/357 B, 871 kB/s)        

❌  error exporting app: server status code: Service Unavailable
```

In epinio-server logs (ENV `TRACE_LEVEL=20` in its deployment)  we see that chart endpoints returns status 503 for some reason.

```
2022/12/15 11:08:41 EpinioServer: "level"=1 "msg"="/api/v1/namespaces/workspace/applications/sample/part/chart" "status"=503 "method"="GET" "path"="/api/v1/namespaces/workspace/applications/sample/part/chart" "query"="" "ip"="10.42.0.1" "user-agent"="Go-http-client/1.1" "time"="2022-12-15T11:08:41Z" "latency"="1.33619546s"
```

**Comment by andreas-kupries** [comment]
The endpoint is called three times from the client, for the three pieces (manifest, chart tarball, and image).
The `/api/v1/namespaces/workspace/applications/sample/part/chart` is the call asking for the chart tarball. I.e. the application template.
This is also the second call of the `.../part` endpoint. The first, for the`.../part/values` has to have succeeded.
The `skopeo` becomes important in the third call for `.../part/image`. Which we do not reach here.
Which means that this issue is separate from skopeo.

**Comment by andreas-kupries** [comment]
Relevant code looks to be https://github.com/epinio/epinio/blob/df785232277e302b7e86f52bdc8bb9f2da4de8aa/internal/api/v1/application/part.go#L116-L125

And noticing function `chartArchiveURL` I am reminded that for Rancher integration the app chart tarball is placed into the server's filesystem, through a helm chart asset. I cannot seeing this playing well with a http.Get().

**Comment by thehejik** [comment]
I've successfully validated the `app export` command when epinio-1.6.1 is deployed as a Rancher App with the new epinio (server+cli) binary built after merging #2050.

This is how I was testing it:
* built latest epinio binary by `make` command
* deployed rancher 2.7.1 (on single node k3s `v1.24.6+k3s1`) by calling `make install-k3s install-helm install-cert-manager install-rancher`  in checkouted e2e repo
* added epinio app repository into rancher: https://github.com/epinio/charts.git branch: `epinio-1.6.1`
* installed the epino app from that app repository over rancher UI
* patched the epinio server binary in my cluster by calling `scripts/patch-epinio-deployment.sh` (with modified namespace `cattle-epinio-system`) from epinio repo
* deployed sample-php app by `epinio push --name sample --path .`
* exported the app by `epinio app export sample ~/export-app/`:
```
🚢  Export application
Namespace: workspace
Application: sample
Target Directory: /home/sles/git/export-app/

Downloading app values to '/home/sles/git/export-app/values.yaml' 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (357/357 B, 681 kB/s)        
Downloading app chart to '/home/sles/git/export-app/app-chart.tar.gz' 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (3.4/3.4 kB, 8.6 MB/s)        
Downloading app image to '/home/sles/git/export-app/app-image.tar' 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (929/929 MB, 120 MB/s)        
```
