### ISSUE TITLE
Bitnami helm chart versions - deprecated

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1969]
**Describe the bug**
Unable to deploy backing services from epinio service catalog,
Impacted services:
- mysql-dev
- rabbitmq-dev
- postgresql-dev
- redis-dev

**To Reproduce**
`epinio service create postgresql-dev postgres`

**Logs**
`❌  error creating service: service create failed: Internal Server Error: error deploying service helm chart: chart "postgresql" matching 11.1.28 not found in hr-ahr0chm6ly9jagfydhm-2f5fa62501c1d0b14a80f52a4e7da5b85c7a01b3 index. (try 'helm repo update'): no chart version found for postgresql-11.1.28`

**Env details**
- K8S: Aws Eks 1.22
- Epinio server: 1.5.1 and 1.5.2
- Epinio cli: 1.5.2

**Workaround**
I have updated mysql-dev application chart version to 9.4.5

**Comment by thehejik** [comment]
Just for the record the available cattalog-service app and chart versions can be obtained by:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm repo up bitnami
$ helm search repo bitnami -l
```
The versions can be updated in deployed epinio manually by:
```
$ kubectl get service.application.epinio.io -n epinio
NAME             AGE
mongodb-dev      39m
mysql-dev        39m
postgresql-dev   39m
rabbitmq-dev     39m
redis-dev        39m
$ kubectl edit service.application.epinio.io -n epinio mysql-dev
```

**Comment by riqueps** [comment]
> Just for the record the available catalog-service app and chart versions can be obtained by:
> 
> ```
> $ helm repo add bitnami https://charts.bitnami.com/bitnami
> $ helm repo up bitnami
> $ helm search repo bitnami -l
> ```
> 
> The versions can be updated in deployed epinio manually by:
> 
> ```
> $ kubectl get service.application.epinio.io -n epinio
> NAME             AGE
> mongodb-dev      39m
> mysql-dev        39m
> postgresql-dev   39m
> rabbitmq-dev     39m
> redis-dev        39m
> $ kubectl edit service.application.epinio.io -n epinio mysql-dev
> ```

In addition, here are some command lines to update the catalog:

**RabbitMQ**

`kubectl get service.application.epinio -n epinio rabbitmq-dev -o json | jq '.spec.chartVersion="11.2.2"' | kubectl apply -f -`

**Redis**

`kubectl get service.application.epinio -n epinio redis-dev -o json | jq '.spec.chartVersion="17.3.17"' | kubectl apply -f -`

**MySQL**

`kubectl get service.application.epinio -n epinio mysql-dev -o json | jq '.spec.chartVersion="9.4.5"' | kubectl apply -f -`

**Postgresql**

`kubectl get service.application.epinio -n epinio postgresql-dev -o json | jq '.spec.chartVersion="12.1.5"' | kubectl apply -f -`

**Comment by gitricko** [comment]
@riqueps @thehejik 

Making a PR so that next release, this problem will be fix once and for all
https://github.com/epinio/helm-charts/pull/322

**Comment by enrichman** [comment]
Thank you @gitricko, it seems that the Bitnami charts have a [retention policy](https://github.com/bitnami/charts/issues/10539) on their index, so this will fix the issue just for a bit.

To fix it once and for all we are having a look at the full index https://github.com/epinio/helm-charts/pull/321 (not sure if that will work).

We are going to test your PR, thanks for the contribution. /cc @mmartin24

**Comment by mmartin24** [comment]
> Thank you @gitricko, it seems that the Bitnami charts have a [retention policy](https://github.com/bitnami/charts/issues/10539) on their index, so this will fix the issue just for a bit.
> 
> To fix it once and for all we are having a look at the full index [epinio/helm-charts#321](https://github.com/epinio/helm-charts/pull/321) (not sure if that will work).
> 
> We are going to test your PR, thanks for the contribution. /cc @mmartin24

Thanks @gitricko again for the contribution. Your pr was checked and approved.
