### ISSUE TITLE
Dex Ingress Annotation

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1970]
**Feature request**
Add support to setup dex ingress Annotations through values during helm chart installation.

**Describe the solution you'd like**
This will be useful to add custom ingress annotations

**eg:** force nginx ssl redirect 
`'dex.ingress.annotations.nginx\.ingress\.kubernetes\.io/force-ssl-redirect=true'`

**Comment by thehejik** [comment]
@riqueps thanks for opening this issue, now it should be possible to set a custom ingress annotations for both server/epinio and dex/auth endpoints at once via for eg. ` --set 'ingress.annotations.traefik\.kubernetes\.io/router\.entrypoint=websecure' --set 'ingress.annotations.traefik\.ingress\.kubernetes\.io/router\.tls=true'`

**Comment by riqueps** [comment]
Tks @thehejik !!
I'll test it, once a new epinio version was released.
