### ISSUE TITLE
Integrate Epinio web-ui with Dex

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1989]
Integrate Epinio web-ui with Dex in order to allow federated users log into epinio web-ui too.

Example: Give us the option to login using Federated (OpenID/SAML) or Local users. Like Neuvector did.

![image](https://user-images.githubusercontent.com/47371890/211374335-6b4fd0c8-5c31-41f4-9516-8aa4a46f80e4.png)

**Comment by enrichman** [comment]
Hi @riqueps , thanks, we are already working on this! https://github.com/epinio/ui/issues/167
It still needs a bit of testing and development though.

I will close this issue since there is already the other one in progress.
