### ISSUE TITLE
AWS IAM support mainly for accessing S3 without providing AWS_SECRETS

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2006]
Ref. https://github.com/epinio/epinio/issues/1925 should contain all the info.

**Comment by andreas-kupries** [comment]
@thehejik From the tag on this issue I guess that the request is to write some documentation.
Reading through the description and comments on #1925 I have trouble getting a coherent picture of what exactly should be documented ?!

How to set up an IAM ?
How to tell epinio (through its chart values) to use IAM ?
The latter seems to be documented in the #1988 PR fixing the 1925, as
"If no credentials are specified then the IAM Role authentication will be used."

@enrichman Your thoughts ?

Right now I am going with "Tell epinio to use AWS IAM".

**Comment by andreas-kupries** [comment]
Thanks for confirming. Mostly done with exactly this now.
