### ISSUE TITLE
Port-forwarding not compatible with recent Kubernetes versions

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2009]
### Issue
On this PR https://github.com/epinio/epinio/pull/2001/ we bumped Kubernetes version in K3s from `v1.20.11-k3s2` to `v1.25.4-k3s1` 

Port-forwarding started to fail with error:

```
❌  error port forwarding to application: error upgrading connection: 
```

The same happens with `v1.26.0+k3s2`, `v1.24.9+k3s2`, `v1.23.15+k3s1`

### Steps to reproduce

- Change `K3S_IMAGE` on `scripts/acceptance-cluster-setup.sh` to any of the above
- Deploy `epinio` using:
```
make acceptance-cluster-delete 
make acceptance-cluster-setup 
export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig 
make install-cert-manager 
make prepare_environment_k3d
```
- Push an app
```
➜  epinio git:(main) epinio push -n sampleapp-1 -p assets/golang-sample-app
```
- Redirect port-forwarding:
```
➜  epinio git:(main) epinio app port-forward sampleapp-1 8088:8080
``` 

### Observed behavior
Following error appears:
```
❌  error port forwarding to application: error upgrading connection: 
```

### Expected behavior
Port-forward should work with recent k3s vesions like `v1.26.0+k3s2` displaying an output like this

```
➜  epinio git:(main) ✗ epinio app port-forward sampleapp-1 8088:8080    

🚢  Executing port forwarding
Namespace: workspace
Application: sampleapp-1
Forwarding from 127.0.0.1:8088 -> 8080
Forwarding from [::1]:8088 -> 8080
Handling connection for 8088
```

Note: applying a curl should confirm a new entry with the port-forward:
```
➜  epinio git:(main) curl localhost:8088
```
---
### Extra notes
The following versions (`v1.22.16+k3s1` and `v1.21.14+k3s1`) seemed to allow port-fowarding but did not work using the `golang-sample-app` commented above.

Error appearing for `v1.22.16+k3s1`:
```
error pushing app to server: can't deploy app: Internal Server Error: Get "https://github.com/epinio/helm-charts/releases/download/epinio-application-0.1.24/epinio-application-0.1.24.tgz": EOF
```

Error for `v1.21.14+k3s1`:
```
 [stage-workspace-sample-b75c89bd4bdb236cb43caf9f89969cbf9das9nrt] buildpack ERROR: failed to build: exit status 1 
```

**Comment by andreas-kupries** [comment]
Confirmed behaviour, good and bad for 1.20.11 and 1.23.15.

Looking into the E server logs I see an additional line

> 2023/01/25 14:18:37 http: proxy error: http2: invalid Upgrade request header: ["SPDY/3.1"]

Based on additional log entries I added this seems to be reported from

https://github.com/epinio/epinio/blob/97509919cc87fe7cb4d2a9eb85c32a1d30411da3/internal/api/v1/application/portforward.go#L93-L106

I am guessing that Kube switched to a new protocol (`SPDY`), and the go code from `net/http/httputil` is not uptodate to handle that.

I will check if Go 1.19 has changes in that area.

**Comment by andreas-kupries** [comment]
Reduced the failing block to
https://github.com/epinio/epinio/blob/97509919cc87fe7cb4d2a9eb85c32a1d30411da3/internal/api/v1/application/portforward.go#L106

**Comment by andreas-kupries** [comment]
https://github.com/pomerium/pomerium/issues/2126#issuecomment-827137371 contains
> ... Unfortunately out of the box the Go HTTP reverse proxy doesn't support SPDY, because it will use HTTP/2 first. ...

Related PR ... https://github.com/pomerium/pomerium/pull/2134/files#diff-f6d92a8f39b323b40cde569ed5f78ba3e1704e2c5976fa7b9046f8b093fef485

**Comment by andreas-kupries** [comment]
Note: Our `exec` uses the same reverse proxy (code) as the port forwarding. Should be affected by the same issue.

**Comment by andreas-kupries** [comment]
Notes ...

 - Giving the reverse proxy a clone of the default http transport replaces the `invalid Upgrade request header: ["SPDY/3.1"]` error with `x509: certificate signed by unknown authority`.
 - The issue with speedy is gone, and replaced by an issue with cert verification. Worse, this fails for the kube 1.20.11 also, i.e. our normally working base case.
 - I believe that speedy is ok because we modified the default http transport to not use http v2.
 - It is unclear why the certs have become an issue. Looking into the structures the transport has all the system certs, and extended trust from other places. The cloning was not an issue either, the certs (pool) was properly cloned over.
 - Forcing `InsecureSkipVerify: true` to bypass cert checking stops the `x509` server error, however something else still chokes because the client now report a third error, namely `error upgrading connection: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}`. Again, this is for the base case.

**Comment by andreas-kupries** [comment]
A confusing part in my notes is that the documentation for the reverse proxy says
> // The transport used to perform proxy requests.
	// If nil, http.DefaultTransport is used.
	Transport [http](https://pkg.go.dev/net/http).[RoundTripper](https://pkg.go.dev/net/http#RoundTripper)

Yet the behaviour seems to be different when I explictly set (a clone of) the DefaultTransport, vs. not.
And when not setting it, the Transport seems to be nil ... Although I will check that now.

**Comment by andreas-kupries** [comment]
I may have to implement the `ErrorLog`, `ModifyResponse`, and `ErrorHandler` function vectors to see more details.

**Comment by andreas-kupries** [comment]
Ah! The transport is __not__ nil. It is a custom transport set by the kube rest client.
