### ISSUE TITLE
epinio-server:v1.6.0 image not compatible with aarch64 - exec format error

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2012]
When deploying epinio v1.6.0 chart on aarch64 I found out that epinio-server pod doesn't start.

Image: ghcr.io/epinio/epinio-server:v1.6.0

```
k logs epinio-server-8db54d4fd-fpp77 -n epinio 
exec /epinio: exec format error
```
Deployed by:
```
helm upgrade --install epinio --namespace epinio epinio/epinio --set skipTraefik=true --set global.domain=1.2.3.4.nip.io --create-namespace
```

Other pods are running.

**Comment by enrichman** [comment]
FIxed with https://github.com/epinio/epinio/pull/2015
