### ISSUE TITLE
Add helm-s3 plugin support

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#2018]
**Describe the solution you'd like**
- Add [helm-s3 plugin](https://github.com/hypnoglow/helm-s3) support to epinio in order to allow epinio create custom services which it's helm-charts are stored on s3.
- [Setup chart repository on Amazon S3 ](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/set-up-a-helm-v3-chart-repository-in-amazon-s3.html)

**Additional context**
This feature will be very useful for all AWS users which wanna store it's epinio custom app/service charts privately on S3.

**Comment by enrichman** [comment]
As of today we are using the `helm` client library directly within our code, so we don't see at the moment an easy maintainable way to support the `helm-s3` plugin.
