### ISSUE TITLE
`dex-tls` secret is updated many times a second

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#2041]
**Describe the bug**

Hint: Make sure to search through the existing issues, as they often contain important information on recent changes.

**To Reproduce**
1. Install Epinio 1.6.1 via instructions at https://docs.epinio.io/howtos/install_epinio_on_k3d
2. View the `epinio:dex-tls` secret
   - data changes multiple times a second
   - annotation `cert-manager.io/certificate-name` flips between dex-tls and dex
   - annotation `cert-manager.io/issuer-group` flips between cert-manager.io and empty

The rate of churn can be seen by streaming the `cert-manager/cert-manager-...` pod's logs, or after importing the cluster into Rancher and viewing the `resource.change` websocket events. From what i can tell the change happens ~20 times a second. 

**Expected behavior**
Secret does not change 20 times a second

**Logs**
`cert-manager/cert-manager-...`
```
I0123 17:33:32.717313       1 secret_manager.go:94] cert-manager/certificates-issuing "msg"="applying Secret data" "key"="epinio/dex-tls" "message"="unexpected managed Secret Owner Reference field on Secret --enable-certificate-owner-ref=true" "resource_kind"="Certificate" "resource_name"="dex-tls" "resource_namespace"="epinio" "resource_version"="v1" "secret"="dex-tls"
I0123 17:33:32.755313       1 secret_manager.go:94] cert-manager/certificates-issuing "msg"="applying Secret data" "key"="epinio/dex" "message"="unexpected managed Secret Owner Reference field on Secret --enable-certificate-owner-ref=true" "resource_kind"="Certificate" "resource_name"="dex" "resource_namespace"="epinio" "resource_version"="v1" "secret"="dex-tls"
```

Couldn't see anything interesting in the `epinio-server` logs 

**Cluster (please complete the following information):**
 - Provider: k3d
 - Kubernetes Version: v1.24.4-k3s1

**Desktop/CLI (please complete the following information):**
 - OS: linux
 - Epinio Version: 1.6.1
 - Epinio Install Options: as per https://docs.epinio.io/howtos/install_epinio_on_k3d

**Comment by andreas-kupries** [comment]
Could it be that there are two components are fighting over the resource ?
There is also the comment https://github.com/epinio/epinio/issues/2003#issuecomment-1398328623
where it is mentioned that ... there is a weird thing with dex-tls secret, it was issued, but there are two certificates using the same secret.

**Comment by andreas-kupries** [comment]
Having two 2 certs fight over the data in the secret would explains things.

**Comment by andreas-kupries** [comment]
The certs are named `dex` and `dex-tls`.

**Comment by andreas-kupries** [comment]
confirmed for my k3d setup

Looking at the cert resources in the cluster
  - `dex` is managed from the helm chart (going by the annotations)
  - `dex-tls` has the `dex` Ingress as owner reference. The ingress will be in the helm chart.

**Comment by andreas-kupries** [comment]
Yep:

> apiVersion: cert-manager.io/v1
> kind: Certificate
> metadata:
>   name: dex
>   namespace: "{{ .Release.Namespace }}"
> spec:
>   dnsNames:
>   - "auth.{{ .Values.global.domain }}"
>   issuerRef:
>     kind: ClusterIssuer
>     name: {{ default .Values.global.tlsIssuer .Values.global.customTlsIssuer | quote }}
>   secretName: dex-tls

And the ingress

> 
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: dex
>   namespace: {{ .Release.Namespace }}
>   annotations:
>     cert-manager.io/cluster-issuer: {{ default .Values.global.tlsIssuer .Values.global.customTlsIssuer | quote }}
>     traefik.ingress.kubernetes.io/router.entrypoints: websecure
>     traefik.ingress.kubernetes.io/router.tls: "true"
>     {{- range $key, $value := .Values.ingress.annotations }}
>     {{ $key | quote }}: {{ $value | quote }}
>     {{- end }}
> spec:
>   [...]
>   tls:
>   - hosts:
>     - "auth.{{ .Values.global.domain }}"
>     secretName: dex-tls

**Comment by andreas-kupries** [comment]
I suspect that the `dex` cert was made to explicitly generate the secret for the ingress, under the assumption that the ingress only consumes the secret. However as we can see, the ingress creates its own cert, for the same secret. I wonder if the `cert-manager.io/cluster-issuer` annotation on the ingress causes that.

**Comment by andreas-kupries** [comment]
I will now create two PR's for testing things.
- In one PR I will remove the `dex` secret
- In the other I will drop the `cluster-issuer` annotation from the ingress.

I plan to run both through the regular CI.

**Comment by andreas-kupries** [comment]
Basic testing (i.e. setting up cluster, installing E, inspecting cert-manager logs) shows that both changes are indeed possible fixes. I.e. only one cert is created, either by helm, or by ingress, and no figthing happens.

And it is indeed the annotation on the ingress which triggers some controller to auto-generate the `dex-tls` cert, and from there the secret.

I am still not sure which of the two fixes I like better.
But lets see first what the full CI tells us.
