### ISSUE TITLE
Autocompletion for `epinio app exec` doesn't work

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2046]
**Describe the bug**
During the last [Deployment Sharing Session](https://github.com/epinio/epinio/wiki/Deployment-Sharing-Session#2023-01-26) I've seen that the autocompletion for `epinio app exec` doesn't work

**To Reproduce**
I tried to `[tab]` during a `epinio app exec` expecting to get the app name but it didn't work.

**Expected behavior**
The list of the running applications should appear.

**Comment by andreas-kupries** [comment]
Hm

```
work@tagetarl:~/SUSE/dev/epinio> ep __complete app show f
fox
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
work@tagetarl:~/SUSE/dev/epinio> ep __complete app exec f
:0
Completion ended with directive: ShellCompDirectiveDefault
```

So, the completion handling in the client is different.
Yet both have the same 
```
ValidArgsFunction: matchingAppsFinder,
```

... different `ExactArgs` however (`1`/show vs `2`/exec) ...

**Comment by andreas-kupries** [comment]
No. Wrong location, looked at `CmdAppExport` :( .... `CmdAppExec` has no `ValidArgsFunction`. And that is the issue.
