### ISSUE TITLE
epinio not fully compatible with EKS 1.24

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2083]
**Describe the bug**
Epinio cli is unable to communicate with epinio-server websocket for unknow reason.

**EDIT:** we identified two issues:
1) Unable to communicate with `epinio-server` websocket when streaming logs - this can be solved by adding `nginx.org/websocket-services: epinio-server` annotation to the epinio ingress (when using nginx-ingress ingress controller)
2) EKS v1.24 dropped dockershim and now using containerd CRI which is pulling images over HTTPS only. But internal epinio registry is using HTTP so EKS is unable to pull images from it. Workaround described [here](https://github.com/epinio/epinio/issues/2083#issuecomment-1434854235).

**To Reproduce**
* deploy EKS 1.24 (eu-central-1) by latest eksctl cli, install cert-manager and nginx-ingress-controller, deploy epinio (1.6.2) in same way as EKS-CI job does where it's failing for a while
* configure route53 to use EXTERNAL-IP hostname value from (elb):  `kubectl get svc -n ingress-nginx ingress-nginx-controller`
* `epinio login ...`,  push an app by `epinio app push --name sample --path ./sample-app/`
```
...
Staging application with code...

🕞  Running staging

🚢  Streaming application logs
Namespace: workspace
Application: sample

❌  failed to tail logs: cannot parse JSON response: 'Bad Request
{"errors":[{"status":500,"title":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header","details":"\nServer Backtrace: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}]}': invalid character 'B' looking for beginning of value

Deploying application ...
............................................................2023/02/15 16:04:10 EpinioApiClient: "msg"="request failed" "error"="Post \"https://epinio.bla.suse.dev/api/v1/namespaces/workspace/applications/sample/deploy\": EOF"

❌  error pushing app to server: can't deploy app: making the request: Post "https://epinio.bla.suse.dev/api/v1/namespaces/workspace/applications/sample/deploy": EOF
```

**Expected behavior**
The app should be deployed without any error message present.

**Additional info**
* It works normally on EKS 1.23
* I checked EKS 1.24 changelog but didn't find anything related to ingress or ELB

**Comment by andreas-kupries** [comment]
Extended logging (i.e. `TRACE_LEVEL=20`) for client and server should tell us (a bit) more. Mainly if the client requests make it through to the server at all, and the exact nature of the error responses seen by the client.

**Comment by thehejik** [comment]
The first issue related to streaming logs can be solved by the annotation.

But there is another problem with accessing internal registry - I don't think it is related to ingress - it uses nodePort address to access `nginx:30500` which forwards communication to `registry:5000` (two containers running in one pod).

```
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  28s                default-scheduler  Successfully assigned workspace/rapp-7d1043473d55bfa90e8530d35801d4e381bc69f0-58b4c5f565-bz4s4 to ip-192-168-57-97.eu-central-1.compute.internal
  Normal   BackOff    26s                kubelet            Back-off pulling image "127.0.0.1:30500/apps/workspace-app:ba7e6814d19e098b"
  Warning  Failed     26s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    13s (x2 over 27s)  kubelet            Pulling image "127.0.0.1:30500/apps/workspace-app:ba7e6814d19e098b"
  Warning  Failed     13s (x2 over 27s)  kubelet            Failed to pull image "127.0.0.1:30500/apps/workspace-app:ba7e6814d19e098b": rpc error: code = Unknown desc = failed to pull and unpack image "127.0.0.1:30500/apps/workspace-app:ba7e6814d19e098b": failed to resolve reference "127.0.0.1:30500/apps/workspace-app:ba7e6814d19e098b": failed to do request: Head "https://127.0.0.1:30500/v2/apps/workspace-app/manifests/ba7e6814d19e098b": http: server gave HTTP response to HTTPS client
```

**Comment by andreas-kupries** [comment]
The `http: server gave HTTP response to HTTPS client` shows some kind of mismatch.

According to our https://github.com/epinio/epinio/blob/main/docs/explanations/architecture/container-registry.md
our registry is secure, for access by staging.

And for access by the app we put an nginx in front. The nginx accepts HTTP, and then talks HTTPS to the registry.

The mismatch above seems to indicate an issue in the path `nginx---registry`, where nginx is the https client, and somehow got an http response from the registry ?!

**Comment by andreas-kupries** [comment]
Registry/nginx logs ...

> kubectl logs -c registry -f -n epinio registry-6fb4c66574-rz2zh|grep -v probe | grep -v 10.42.0.1
> kubectl logs -c nginx -f -n epinio registry-6fb4c66574-rz2zh

where `10.42.0.1` is the host the kube probe seem to be coming from in my testenv. This will vary by environment/cluster.
And the name of the pod too, of course.

When pushing I see the requests from staging in the registry log, and on deployment I see the app pull requests in both nginx and registry logs.

I wonder how that looks when it fails.

**Comment by andreas-kupries** [comment]
The logs from k3s
[NGINX.log](https://github.com/epinio/epinio/files/10765695/NGINX.log)
[REGISTRY.log](https://github.com/epinio/epinio/files/10765696/REGISTRY.log)

**Comment by thehejik** [comment]
The logs from EKS 1.24
[nginx.log](https://github.com/epinio/epinio/files/10766265/nginx.log)
[registry.log](https://github.com/epinio/epinio/files/10766266/registry.log)

**Comment by thehejik** [comment]
I found a way how can we force EKS 1.24 CRI to use HTTP instead of its default HTTPS for pulling images:

* created a busybox pod mounting `/etc` hostPath volume from the node to `/tmp` in the pod in RW mode:
* Inside this pod called `mkdir -p /tmp/containerd/certs.d/127.0.0.1:30500`
* followed by:
```
cat > /tmp/containerd/certs.d/127.0.0.1:30500/hosts.toml << EOF
server = "http://127.0.0.1:30500"

[host."http://127.0.0.1:30500"]
  capabilities = ["pull"]
EOF
```
* epinio is then able to pull images from internal registries (even without restarting CRI)
* **WARNING:** this needs to be done on all nodes

**Comment by thehejik** [comment]
Assigning myself to this Issue - I will try to comment these EKS 1.24 issues in documentation.

**Comment by thehejik** [comment]
CI fixed and documentation done. close
