### ISSUE TITLE
DEX UI not working after helm upgrade

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2108]
### Issue

Dex UI does not work when upgrading Epinio from a previous version. It needs to be recreated.

### Steps to reproduce
- Install Epinio on previous version to `v1.7.0` (ie `v1.6.2`)
- Upgrade Epinio via helm

Observe how the following error screen is displayed:

![Image](https://user-images.githubusercontent.com/37271841/221211594-a235d68c-259a-4e3b-b213-c41db1ad6870.png)

### Workaround
Restart Dex using:

```
kubectl delete pod -n epinio -l [app.kubernetes.io/name=dex](http://app.kubernetes.io/name=dex)
```

**Comment by enrichman** [comment]
Just adding this as a reference but we can fix this automatically restarting the pod if something in the secret changes: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

We need to check if that's feasible adding annotations to the Dex deployment.

**Comment by enrichman** [comment]
Having a deeper look at this it's not possible to do it in an "easy" way. The annotation should be added in the Dex deployment subchart (not possible), and possibily it's better to let the user decide how and when restart the deployment of Dex.

I will add a note in the release, but I think it's fine to close this issue like this.
