### ISSUE TITLE
Create epinio deleteAll command for Applications, Services, Namespaces, Configurations

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2114]
### Request: 
implement a deleteAll command targeting `Applications`, `Configurations`, `Namespaces` or `Services` individually to delete all elements within.
So:

- `epinio app deleteAll`
- `epinio configuration deleteAll`
- `epinio services delete All`
- `epinio namespaces deleteAll`

We have implemented already a bulk deletion endpoint for each, but it is still needed to specify the name of each one (ie: if we have 2 apps  `app-1`, `app-2`, we would need to delete them as `epinio app delete app-1 app-2`

The idea is to list all apps and present either in applications, services or configurations and delete them later.

Something like:

Use case would be:

- Say we have 2 apps `app-1`, `app-2`
- We delete them both with 1 command:
```
epinio app delete ALL 
```

- Output:

```
🚢  Deleting Applications...
Names: app-1, app-2
Namespace: workspace

✔️  Applications Removed.
```

**Comment by mmartin24** [comment]
Checked on branch https://github.com/epinio/epinio/pull/2138

- Checked all `applications`, `namespaces`, `configurations` and `services` can be deleted using the new `--all` flag:

  ```
  ➜  epinio git:(2114-delete-all) epinio configuration delete --all             

  🚢  Querying Configurations for Deletion...
  Namespace: workspace

  🚢  Deleting Configurations...
  Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9
  Namespace: workspace
  .......
  ✔️  Configurations Removed.
  Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9
  Namespace: workspace
  ```


- Checked that deletion is not performed if an application is bound to a service, showing the request for using `--unbind` flag to force deletion.
- Checked that `--all` flag works as expected in conjunction with `--unbind` to force deletion of services bound to apps.

----
## Corner cases:
@andreas-kupries  could you please check these 2 corner cases?

- ####  Corner case 1: if a service has been bound to an app and later unbound, it appears listed as configuration and  cannot be deleted
  ```
  ➜  epinio git:(2114-delete-all) epinio configuration delete --all             
  
  🚢  Querying Configurations for Deletion...
  Namespace: workspace
  
  🚢  Deleting Configurations...
  Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9, xaf6aeed8322120ee03b1c212346c-mysql
  Namespace: workspace
  ..
  ❌  error deleting configuration: Configuration belongs to service 'mysql-svc-1', use service requests
  ```
    I have a few questions here:
      - Is this the expected behavior?
      - If so, could we then solve this issue by applying another query for deleting this service?
      - If the previous point is not possible, could we at least display a message suggesting the user to delete the service separately?

- #### Corner case 2: do we want to exclude the targeted namespace from the `--all` flag deletion?

  When deleting all namespaces it includes the targeted namespace. I wonder if it makes sense to delete all or on the contrary is better to skip the targeted one if we understand the user wants to operate in this namespace and delete the rest.

**Comment by andreas-kupries** [comment]
Pushed commits 4b626d43e2c50313f598e91290933568c36d59c0 and 157965ee0f646470c06090a57514d0d940507490.

**Comment by mmartin24** [comment]
> Pushed commits [4b626d4](https://github.com/epinio/epinio/commit/4b626d43e2c50313f598e91290933568c36d59c0) and [157965e](https://github.com/epinio/epinio/commit/157965ee0f646470c06090a57514d0d940507490).

Thanks, @andreas-kupries .

I just checked it and seemed to work fine.

For `configurations` with "pre-bonded" services now we get the message of the problematic one on the error message:
```
🚢  Deleting Configurations...
Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9, xaf6aeed8322120ee03b1c212346c-mysql
Namespace: workspace
..
❌  error deleting configuration: Configuration 'xaf6aeed8322120ee03b1c212346c-mysql' belongs to service 'mysql-svc-1', use service requests
```

For `namespaces` now we see the warning specifying the count and names of the namespaces to be deleted:
```
➜  epinio git:(2114-delete-all) epinio namespace delete --all
You are about to delete 4 namespaces (workspace, ns-1, ns-2, ns-3)
and everything they include,i.e. applications, configurations, etc.
Are you sure? (y/n): 
```

They seem quite nice additions indeed.

**Comment by mmartin24** [comment]
Retested for `v1.8.0-rc`:
- Simple delete `--all for ` applications, services, configurations, and namespaces -> OK
- Display of deletion in place checked -> OK
- Namespace deletion outputs a confirmation prior to deletion -> OK
- Deletion of bound app to service with `--unbind` flag-> OK
- Deletion of bound app to configuration `--unbind` ->OK, but got error during binding
 
 Note:
 During the binding of the configuration with an app, an error was observed,; despite this fact,  the configuration took place:
 ```
➜  epinio git:(main) ✗ epinio configuration bind config-1 testapp  

🚢  Bind Configuration
Configuration: config-1
Application: testapp
Namespace: workspace

❌  error binding configuration: Internal Server Error: configuration not found
➜  epinio git:(main) ✗ epinio configuration list                 

🚢  Listing configurations
Namespace: workspace

✔️  Epinio Configurations:
|   NAME   |            CREATED             |  TYPE  | ORIGIN | APPLICATIONS |
|----------|--------------------------------|--------|--------|--------------|
| config-1 | 2023-04-26 13:12:33 +0200 CEST | custom |        | testapp      |

```

**Comment by mmartin24** [comment]
> Note: During the binding of the configuration with an app, an error was observed,; despite this fact, the configuration took place:
> 
> ```
> ➜  epinio git:(main) ✗ epinio configuration bind config-1 testapp  
> 
> 🚢  Bind Configuration
> Configuration: config-1
> Application: testapp
> Namespace: workspace
> 
> ❌  error binding configuration: Internal Server Error: configuration not found
> ➜  epinio git:(main) ✗ epinio configuration list                 
> 
> 🚢  Listing configurations
> Namespace: workspace
> 
> ✔️  Epinio Configurations:
> |   NAME   |            CREATED             |  TYPE  | ORIGIN | APPLICATIONS |
> |----------|--------------------------------|--------|--------|--------------|
> | config-1 | 2023-04-26 13:12:33 +0200 CEST | custom |        | testapp      |
> ```

After reinstalling a brand-new environment this was not observed again.
I think this can be ignored
