### ISSUE TITLE
PCCI - write flows using platform defaults / standard setup instead of customized by us

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#2122]
Me on slack:
> The tests have cases testing with nginx and cases testing with traefik.
And wish to be platform independent
(We are testing against EKS, AKS, GKE, and RKE)
Thus they disable platform stuff which may interfere with the particular choice.

AB answering:
> The setup may be more realistic is to create an rke2 ec2 instance, point the epinio dns records to that VMs public IP, install Longhorn or use a preferred storageclass on the ec2 instance, install epinio pointing to the dns domain already configured, aws s3 and an external registry.

By implementing this issue in CI we will get following:
- EC2 instance running SLE15SP4 chost byos AMI with a public IP assigned and enabled SSH access
- Deployed latest RKE2 with nginx-ingress configured to use AWS ELB as a LoadBalancer (needs upstream nginx-ingress)
- Route53 DNS CNAME entries pointing to the ELB to serve endpoints from the cluster by using our domain zone
- Deployed Longhorn storage used as a default SC
- Deployed epinio with letsencrypt-production issuer, AWS S3 (and external registries)

This test will have to use SSH for a cluster deployment from our runner and then to fetch (scp) the rke2.yaml kubeconfig - the rest will be done directly from the runner.

**Comment by thehejik** [comment]
So far I've created following resources in AWS:
- New ssh-keypair `epinio-ci`
- New VPC named `epinio-ci-vpc` using one availability zone with one private and one public subnet - default sg with allowed inbound ports 22, 6443, 443, 80
- New EC2 InstanceTemplate named `epinio-ci-sle15sp4-chost-template` using `amazon/suse-sles-15-sp4-chost-byos-v20221118-hvm-ssd-x86_64` AMI `ami-0a6dc65c883a3b14f`, enabled assigning of a public IP and with user-data creating /root/.bashrc with ENV suitable for RKE2 (mainly setting $PATH and $KUBECONFIG) and with following tags set on EC2 Instance `Name=epinio-ci-rke2` and `Creator=epinio-ci`

CI should be able to deploy plain SLE15SP4 EC2 instance by running `aws ec2 run-instances --launch-template='LaunchTemplateName=epinio-ci-sle15sp4-chost-template' --no-cli-pager --region eu-central-1 --count 1`

**Comment by thehejik** [comment]
Following resources were added into our aws account to make RKE2 aware of running on AWS EC2 and use amazon cloud provider, docu [rancher here](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon), [aws here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#create-iam-role):
* new policy `epinio-ci-RKE2` (meant to be used for all nodes/roles)
* new role `epinio-ci-RKE2-role` with attached policy
* IAM instance profile `epinio-ci-RKE2-profile` with added role `epinio-ci-RKE2-role`

The tag `kubernetes.io/cluster/epinio-ci-RKE2ID=owned` has been assigned to following resources:
- Instance Template `epinio-ci-sle15sp4-chost-template`
- to both `private` and `public` subnets of the VPC `epinio-ci-vpc`
- to security group `sg-088df57e596f525ab` (used in the template)

After deploying the RKE2 on the provisioned ec2 node I was able to use `LoadBalancer` type of service (so ELB privisioning works as expected) for a testing nginx workload. Internal rke2-nginx-ingress does use `ClusterIP` for its service so it must be additionally configured over helm.

**Comment by thehejik** [comment]
Initial work done, test is green, will continue within #2203
