### ISSUE TITLE
Time to push an application too lengthy

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently it takes over 1 minute to deploy a simple PHP app on a fresh environment and around 30 seconds when the app has been previously pushed as can be seen here:

From fresh environment:

https://user-images.githubusercontent.com/37271841/223100379-725dce48-9267-4601-820e-86f9fd992e0d.mov

Once the app has been pushed

https://user-images.githubusercontent.com/37271841/223100394-5c1f7886-4ab0-4072-8e61-ab12eb612661.mov

### Expected Behavior

Times should not be that lengthy in either case.
I am not sure what is the minimum possible time but it should not be 1 minute when environment is fresh or 30 when the app has been previously pushed.

We should investigate why this happen and attempt to determine the minimum time needed. 

### Steps To Reproduce

1. Install Epinio and latest UI version
2. Push the following app as source file from UI [sample-app.tar.gz](https://github.com/epinio/ui/files/10897728/sample-app.tar.gz)

Observe pushing times above mentioned

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Epinio Version: `v1.7.0-14-g007abcb2
- Cluster: 
  - Provider: k3d
  - Options: 1 node
  - Kubernetes Version: v1.25.4+k3s1
```

### Logs

![image](https://user-images.githubusercontent.com/37271841/223117927-04945b6a-a32f-4f0b-a9b8-74e8833c0ee1.png)

![image (1)](https://user-images.githubusercontent.com/37271841/223117950-f836a304-ecd5-49fc-8a34-174a357d3536.png)

_No response_

**Comment by enrichman** [comment]
Let's try a quick test with a smaller builder image to see if there are some improvements.
The suspect is that the Paketo full builder image is taking a lot of time during the download and/or staging.

**Comment by mmartin24** [comment]
> Let's try a quick test with a smaller builder image to see if there are some improvements. The suspect is that the Paketo full builder image is taking a lot of time during the download and/or staging.

@enrichman , I could not repeat the test above using the file [sample-app.tar.gz](https://github.com/epinio/ui/files/10897728/sample-app.tar.gz) and Packeto Image `paketobuildpacks/builder:tiny` due to error with `Procfile`:

```
│ buildpack fail: paketo-buildpacks/procfile@5.6.0                                                                                                                              
│ buildpack ERROR: No buildpack groups passed detection.                                                                                                                        
│ buildpack ERROR: Please check that you are running against the correct path.                                                                                                  
│ buildpack ERROR: failed to detect: no buildpacks participating      
```

However, I managed to do some measurements using:
- Source type: `Git URL`
- URL: `https://github.com/epinio/example-go`  
- Branch: `main`
- env: `PORT=8080`

Results:

| BuildPack Image | 1st attempt (s) | 2nd attempt (s) |  
|---|---|---|
| paketobuildpacks/builder:full | 57 | 36 |  
| paketobuildpacks/builder:tiny | 42 | 32 |  

So it does seem the the size of the Buildpack image impacts on the time count.

**Comment by enrichman** [comment]
Having a talk about this during our grooming session we have agreed that less then a minute is ok. Let's close this.
