### ISSUE TITLE
Display deleted status in CLI for bulk deletion

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2131]
### Issue
Currently when performing bulk deletion in CLI it may take some time until the action is completed and the user does not see if the action is being carried. The only thing displayed are these dots:

![Image](https://user-images.githubusercontent.com/37271841/223687138-b871031e-394e-48ce-b0ab-6d535337768f.png)

### Proposal
As discussed in meeting, perhaps we could improve this by adding a status of the apps that are being removed. Something like:

```🚢  Deleting Applications...
Names: testapp-1, testapp-2, testapp-3, testapp-4, testapp-5, testapp-6, testapp-7
Namespace: workspace

Status:
Application "testapp-1" removed
Application "testapp-2" removed ...

```

**Comment by mmartin24** [comment]
I checked directly it on branch https://github.com/epinio/epinio/pull/2138

- Checked all `applications`, `configurations` and `services` displayed status as they are being deleted:

  ```
  ➜  epinio git:(2114-delete-all) epinio app delete --all

  🚢  Querying Applications for Deletion...
  Namespace: workspace

  🚢  Deleting Applications...
  Names: testapp-1, testapp-10, testapp-2, testapp-3, testapp-4, testapp-5, testapp-6, testapp-7, testapp-8, testapp-9
  Namespace: workspace
  ...
  ✔️  testapp-10 deleted
  ✔️  testapp-2 deleted
  ✔️  testapp-1 deleted
  ✔️  testapp-3 deleted
  ...
  ✔️  testapp-5 deleted
  ✔️  testapp-4 deleted
  ...
  ✔️  testapp-6 deleted
  ✔️  testapp-7 deleted
  ✔️  testapp-8 deleted
  .
  ✔️  Applications Removed.
  ```
  
- Observed particularly in `configurations` does not display status while deleting 10 configs if the deletion part is relatively fast (2-3 seconds). @andreas-kupries  Is this expected?
  ```
  ➜  epinio git:(2114-delete-all) epinio configuration delete --all             

  🚢  Querying Configurations for Deletion...
  Namespace: workspace

  🚢  Deleting Configurations...
  Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9
  Namespace: workspace
  .......
  ✔️  Configurations Removed.
  Names: config-1, config-10, config-2, config-3, config-4, config-5, config-6, config-7, config-8, config-9
  Namespace: workspace
  ```

**Comment by andreas-kupries** [comment]
Yes, it is expected. The tracking is done by polling, i.e. a background goroutine queries the API in a loop. To keep load on the server low I set a poll interval of two seconds. If the deletion is faster no output is given and IMHO not needed either.
