### ISSUE TITLE
Avoid waiting during service creation

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2133]
After [this](https://github.com/epinio/epinio/pull/1764) refactor the original behaviour of the cli during the creation of a service changed. We are now waiting for a response from the server, while before we were just returning early.

**Is your feature request related to a problem? Please describe.**
This behaviour will hang the cli, and could be not desirable for the creation of services that takes a long time.

**Describe the solution you'd like**
It will be nice to rollback the original "fire and forget", and maybe improve it adding a `--wait` flag to optionally ask for waiting the completion.

**Comment by riqueps** [comment]
hello @enrichman , any news on this feature?

**Comment by enrichman** [comment]
Hi @riqueps, this is scheduled for the next `v1.8.0` that should be available in a couple of weeks.

It's basically ready but we are planning to release a small patch in the next days, and some more features for the new one. :slightly_smiling_face:

**Comment by riqueps** [comment]
Great @enrichman, a small patch release would help us a lot to advance with the integration with aws rds.
Looking forward to this.

**Comment by enrichman** [comment]
It seems that the service status is "deployed" while is still creating. We should check the status of the Helm installation and return "deployed" only at the end of the release.

**Comment by Oziel-Silva** [comment]
Another important and interesting thing to note is that Epinio could make calls to the Helm API in parallel mode, allowing Helm installation to run in the background and keeping the Epinio-cli free without waiting for it (or using other approaches that allow it). And then the status of the installation can be checked using the command ```epinio service list```. This is important because when Helm has a hook for post-installation using pods or jobs, Helm will wait for it, even when we use the flag ```--wait=false```.

**Comment by enrichman** [comment]
@Oziel-Silva today I had a quick look and it could be a little bit more difficult. If you try to install something with Helm (not with Epinio) then it will exit immediately, and the release will be marked as `deployed`, even if it's still deploying the resources. It means that understand if the release is "done" is a bit more complicated.

There is a `--show-resources` flag in the `helm status` command that will return the resources, and we can maybe check these, but it's going to be something more complex that I will probably need to discuss with @andreas-kupries.

**Comment by andreas-kupries** [comment]
Regarding
> Epinio could make calls to the Helm API in parallel mode

please note that we use the https://pkg.go.dev/github.com/mittwald/go-helm-client as a simplified API over the multitude of `helm` API packages. I am not sure if this wrapper exports a `parallel mode`. A first look over and through the mittwald documentation does not indicate the presence of such a thing.

Of course, E itself could wrap the call to helm deploy into a go routine. Not sure how far this would emulate the referenced parallel mode, versus not.

@enrichman 

> There is a --show-resources flag in the helm status command

I see no such thing for `helm status --help`, helm version 3.7.2. What is your helm version ?

Regarding release status I concur with @enrichman that the existing statuses are not good to detect a release whose resources are not running yet. This all falls under `deployed`, which can then later flip to `failed` when something went bad. There simply is no status to indicate "deployed, not fully running yet" -- https://pkg.go.dev/helm.sh/helm/v3/pkg/release#Status

Going back to `show-resources` I also see no such thing exposed by the mittwald wrapper. While there is a `GetRelease()` function this does not provide access to a list of resources created for the release. Worse, the returned `Release` structure looks to be the official release information from the helm API packages. IOW even bypassing the mittwald wrapper for this is likely of no help.

I would move this to a spike for 1.9 or even 1.10.
I would not have this block the 1.8.

**Comment by andreas-kupries** [comment]
Created a spike for this, for the 1.9 timeframe, see https://github.com/epinio/epinio/issues/2195
With that this can be closed again as done.
