### ISSUE TITLE
[FEATURE] support gitlab and github authentication

### ISSUE THREAD

**Issue by abonillabeeche** [epinio/epinio#2139]
This is a request to support the CLI-related implementation of [#63](https://github.com/epinio/ui/issues/63)

**Comment by enrichman** [comment]
Hi @abonillabeeche, just to refine the requirements this is not related to the CLi but is on the server side.
The CLI will just provide the github/gitlab/git url but the download of the source code will be done on the Epinio side.

**Comment by mmartin24** [comment]
This issue will be handled in here: https://github.com/epinio/epinio/issues/2236
Closing issue.
