### ISSUE TITLE
Support for the Paketo Jammy Full Builder

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2153]
Epinio works by default with the [Paketo Full Builder](https://github.com/paketo-buildpacks/full-builder) that is based on the Bionic Ubuntu (18.04).
We are providing the possibility to use custom builders, and we should at least support the [Paketo Jammy Full Builder](https://github.com/paketo-buildpacks/builder-jammy-full), that is based on the latest Ubuntu LTS (Jammy 22.04)

This is not working because of some permission issues with the hardcoded user in our build scripts during the staging phase.

We are using the `creator` directly, with the 1000:1000 user/group:

https://github.com/epinio/helm-charts/blob/a61e29bfb28909e12d5bf169166a3e1c0ae3384d/chart/epinio/templates/stage-scripts.yaml#L83-L94

while the Paketo Jammy stack seems to have a 1001 user instead: https://github.com/paketo-buildpacks/jammy-full-stack/blob/main/stack/stack.toml#L7-L12

This results in an error:

```
buildpack ERROR: failed to chown volumes: chown /layers: operation not permitted
```

We should see if we can still use the `creator` in a different way, or if we should use `pack` instead.

**Comment by agracey** [comment]
I would hope that the user/group are specified in the OCI metadata for the builder image. I'm pretty sure that's part of the buildpack spec

**Comment by agracey** [comment]
Also, why would jammy pick uid 1001?!? That feels like it's just inviting bugs

**Comment by enrichman** [comment]
At the moment our staging scripts are hardcoded and are used in every builder. This is causing the issue that we have seen. Instead of rewriting/updating the scripts to make them work with the bew builder, we should find a way to use specific scripts for different builders.

**Comment by andreas-kupries** [comment]
> IIRC, you should just be able to drop the uid and group options

That does not help the script for the `unpack` phase.
This script runs a direct `chown` using the "known" user/group ids.

**Comment by andreas-kupries** [comment]
The user and group ids are actually also baked into the E server as well.

https://github.com/epinio/epinio/blob/b312089eb0d126d1ab3cf7f337dcc41ae30db6f0/internal/api/v1/application/stage.go#L614-L617

E basically tells the container under which user/group to run.

**Comment by andreas-kupries** [comment]
That being said, after changing all the user id references deployment of the sample php app works fine.
IOW, the user id difference looks to be the only important between `builder` and `builder-jammy-full`.
