### ISSUE TITLE
Add BE validation for creating Namespaces with CAPS

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2155]
### Issue
We need to ensure that Epinio backend handles correctly the incapabilty to create a namespaces with caps.

A related issue in the UI: https://github.com/epinio/ui/issues/111. There a 500 error would be triggered when creating a namespace with capital letters. Although this has been handled in the UI, we should ensure it is handled also in the backend.

Currently, the CLI shows this:

```
➜  epinio git:(main) epinio namespace create NS1

🚢  Creating namespace...
Name: NS1

❌  error creating epinio-controlled namespace: namespace name incorrect: a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

```

**Comment by mmartin24** [comment]
> > @richard-cox Enrico mentions that `this has been handled in the UI, ...` What is the error message the UI provides in that case ?
> 
> > And another question - Does this rejection of caps letters apply to applications, services, and configurations as well ?
> 
> @torchiaf can advise?

FYI: When I tested it [here](https://github.com/epinio/ui/issues/111#issuecomment-1482590539) the message displayed was:
```
Namespace's name must consist of lower case alphanumeric characters or '-' and must start and end with an alphanumeric character (e.g. 'my-name' it '123-abc')
```
![image](https://user-images.githubusercontent.com/37271841/228524091-6a004649-b177-442d-8a88-0c9da9080cfe.png)

**Comment by mmartin24** [comment]
> And another question - Does this rejection of caps letters apply to applications, services, and configurations as well ?

@andreas-kupries , the error seems extensible to `applications`, and `configurations` but not to `services`:

Error in `applications`:
```
➜  epinio git:(main) epinio app create APP-1 

🚢  Create application
Namespace: workspace
Application: APP-1

❌  error creating app: Internal Server Error: App.application.epinio.io "APP-1" is invalid: metadata.name: Invalid value: "APP-1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Error in `configurations`:
```
➜  epinio git:(main) epinio configuration create CONFIG-1 foo bar

🚢  Create Configuration
Name: CONFIG-1
Namespace: workspace
| PARAMETER | VALUE |         ACCESS PATH          |
|-----------|-------|------------------------------|
| foo       | bar   | /configurations/CONFIG-1/foo |

❌  error creating configuration: Internal Server Error: failed to create secret: Secret "CONFIG-1" is invalid: metadata.name: Invalid value: "CONFIG-1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

`Services` as commented is allowed to use CAPS:
```
➜  epinio git:(main) epinio service create mysql-dev SVC-1                      

🚢  Creating Service...
Catalog: mysql-dev
Service: SVC-1
Wait For Completion: false
```

I can create a separate ticket for applications and configurations if needed.

**Comment by andreas-kupries** [comment]
I will add this to the existing PR. Easier as the work is already in my mind.

**Comment by torchiaf** [comment]
Hi @andreas-kupries @richard-cox , the error message is generated by the UI:

https://github.com/torchiaf/dashboard/blob/2be0cd003360fd9fea58f6a278a7dfc502d8b30e/pkg/epinio/l10n/en-us.yaml#L262

And it says:
```
'Namespace's name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc')'
```

**Comment by andreas-kupries** [comment]
> Hi @andreas-kupries @richard-cox , the error message is generated by the UI:
> 
> https://github.com/torchiaf/dashboard/blob/2be0cd003360fd9fea58f6a278a7dfc502d8b30e/pkg/epinio/l10n/en-us.yaml#L262
> 
> And it says:
> 
> ```
> 'Namespace's name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc')'
> ```
> 
> As @mmartin24 suggested.

Yes, see https://github.com/epinio/epinio/issues/2155#issuecomment-1488459263

**Comment by mmartin24** [comment]
Verified in `v1.8.0-rc1`:

- Namespaces and Configurations are prevented from being created if Caps is added.
- Output message is correct

Example with `Namespaces`
```
  epinio git:(main) ✗ epinio namespace create NS1

🚢  Creating namespace...
Name: NS1

❌  error creating epinio-controlled namespace: Namespace's name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc').
```
```
➜  epinio git:(main) ✗ epinio info                                 

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.25.4+k3s1
Epinio Server Version: v1.8.0
Epinio Client Version: v1.8.0
```
