### ISSUE TITLE
Get real service name instead of Md5 hash

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#2188]
**Is your feature request related to a problem? Please describe.**

Working to have some native aws cloud services on epinio service catalog we  want to have the ability to tag the aws service with the real service name and not the md5 hash.
This would help identify the resources from aws point of view.

**Describe the solution you'd like**

Through helm-chart values I'm able to have the {{  Release.name }}, which is the md5 hash.
Would be nice to have something like {{ .Values.epinio.servicename }}, where this returns the real service name.

**Comment by mmartin24** [comment]
Groomed and requires discussion/investigation.
