### ISSUE TITLE
Honor pre-delete hooks for services

### ISSUE THREAD

**Issue by mageran** [epinio/epinio#2194]
**Is your feature request related to a problem? Please describe.**
I have written a new catalog service that creates a container in a data storage whenever a service (that has been created with the new catalog service) is bound to an app. I added a pre-delete hook in my helm-chart that fails, when this container is not empty. This should prevent the service from being deleted, but Epinio does not honor that. I can see in the events/logs that the delete-hook is working as expected, but Epinio still deleted the service.

**Describe the solution you'd like**
Epinio should check the pre-delete hook result and prevent the service from being deleted if it fails. In addition there should be the possibility for the dev to supply a reason message that then can be displayed by the Epinio client (similar to the one that shows when the service is still bound to an app)

**Describe alternatives you've considered**
There are really no good alternatives to this, the "safest" way would just be to leave the container contents alone, which would create a lot of "orphaned" content. Force-deleting the content is also not an option especially in a prod environment

**Additional context**

**Comment by enrichman** [comment]
Hi @mageran, thank you for the feedback. Would it be possible for you to provide a simple helm chart that we can use to replicate the behaviour? It will be easier for us to test this scenario. Thanks!

**Comment by mageran** [comment]
Sure: https://mageran.github.io/helm-charts-repo/minio-service-dev-0.1.0.tgz

For context, I'm making the internal minio service accessible for app developers, see [here](https://github.com/mageran/minio-epinio). I'm creating a bucket when the service is bound to an app; when deleting the service, I want to prevent deletion when the bucket is not empty, which isn't working right now.

**Comment by gitricko** [comment]
@enrichman remember the request on exposing minio as a backing service. @mageran has already figure how to do this using the epinio/k8 way. Would be good to see it as part of the standard install.

**Comment by enrichman** [comment]
Hi @mageran @gitricko, we have probably a clue on what it's happening but we have not yet started a deeper investigation.

About `minio` as a backing service were you thinking about a completely separate instance running for development purposes? I'm not sure about having multiple MinIO instances in the same cluster, or even in the same namespace (if a user is going to create multiple minio services). We should try that, but I think it will be pretty resource demanding. Maybe for development there are other options. Maybe the `s3gw` could be something that we can evaluate to try, if lighter.

**Comment by mmartin24** [comment]
Tested on latest `epinio(main)` using [this](https://github.com/mageran/minio-epinio) really nice setup by @mageran  and working. 
Now it is not possible to delete the service in the given conditions.

```
➜  minio-epinio git:(main) ✗ epinio service delete --all --unbind                                     

🚢  Querying Services for Deletion...
Namespace: workspace

🚢  Deleting Services...
Names: devMinio
Namespace: workspace
.....
❌  error deleting service: error deleting service helm release: deleting release: 1 error occurred:
	* job failed: BackoffLimitExceeded


➜  minio-epinio git:(main) ✗ epinio service list                 

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|   NAME   |            CREATED             |  CATALOG SERVICE  | VERSION |  STATUS  | APPLICATIONS |
|----------|--------------------------------|-------------------|---------|----------|--------------|
| devMinio | 2023-07-11 15:36:02 +0200 CEST | minio-service-dev | v1      | deployed | pyhw         |

```

Adding screenshot before (deletes service on 1.8.1) / after (it does not on 1.9.0+):

![image](https://github.com/epinio/epinio/assets/37271841/69835984-e680-4e62-bdbb-465888921913)

**Comment by mageran** [comment]
That's great! Looking forward to the release!
Is there also a way to supply a custom reason message on why the deletion failed?

**Comment by enrichman** [comment]
> That's great! Looking forward to the release! Is there also a way to supply a custom reason message on why the deletion failed?

Not really, or at least it's not something that we can get from the error. We are just aware that the release deletion failed.
If really needed we could think about some enhancement to go through the Job logs or anything, but not sure how easy it is.

**Comment by mmartin24** [comment]
Rechecked in 1.9.0-rc4 and working:
```
➜  minio-epinio git:(main) ✗ aws --no-verify-ssl --endpoint-url https://minio.172.19.0.3.omg.howdoi.website s3 cp README.md  s3://x3b302cdc9c34cf4411bce2b95f13.workspace.s3.bucket

urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'minio.172.19.0.3.omg.howdoi.website'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
upload: ./README.md to s3://x3b302cdc9c34cf4411bce2b95f13.workspace.s3.bucket/README.md
➜  minio-epinio git:(main) ✗ epinio service bind devMinio pyhw

🚢  Binding Service...
➜  minio-epinio git:(main) ✗ epinio service list              

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|   NAME   |            CREATED             |  CATALOG SERVICE  | VERSION |  STATUS  | APPLICATIONS |
|----------|--------------------------------|-------------------|---------|----------|--------------|
| devMinio | 2023-07-17 13:25:56 +0200 CEST | minio-service-dev | v1      | deployed | pyhw         |
➜  minio-epinio git:(main) ✗ epinio service delete --all --unbind 

🚢  Querying Services for Deletion...
Namespace: workspace

🚢  Deleting Services...
Names: devMinio
Namespace: workspace
.....
❌  error deleting service: error deleting service helm release: deleting release: 1 error occurred:
        * job failed: BackoffLimitExceeded


➜  minio-epinio git:(main) ✗ epinio info                         

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.25.4+k3s1
Epinio Server Version: v1.9.0-rc4
Epinio Client Version: v1.9.0-rc4
➜  minio-epinio git:(main) ✗ 
```
