### ISSUE TITLE
Restart/Restage do not effectively apply env vars

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2220]
## Issue.
Once an app is deployed, applying the env vars later with restart/restage seem not to have an efect on making the app work.

So this will deploy a fully working app:
```
epinio push --name testapp-gituburl-0 --git https://github.com/epinio/example-go,main --env='BP_KEEP_FILES=static/*'
```

However if deploy without the en vars first and later add them it wont:

```
epinio push --name testapp-gituburl --git https://github.com/epinio/example-go,main
epinio app env set testapp-gituburl BP_KEEP_FILES 'static/*'
epinio app restage testapp-gituburl 
```

The details show the env var is there but it returns a 404 on the UI:
```
🚢  Show application details
Namespace: workspace
Application: testapp-gituburl

✔️  Details:
|         KEY          |                                            VALUE                                            |
|----------------------|---------------------------------------------------------------------------------------------|
| Origin               | https://github.com/epinio/example-go                                                        |
|                      | @ main                                                                                      |
| Created              | 2023-04-18 17:28:02 +0200 CEST                                                              |
| Status               | 1/1                                                                                         |
| Username             | admin                                                                                       |
| Running StageId      | bbe8c56067eeb990                                                                            |
| Last StageId         | 1706ef1b1da34745                                                                            |
| Age                  | 1m39s                                                                                       |
| Internal Route       | rtestapp-gituburl-3609caf5e8714c257de51705edff8e44d5a20d36.workspace.svc.cluster.local:8080 |
| Active Routes        |                                                                                             |
|                      | testapp-gituburl.192.168.16.3.omg.howdoi.website                                            |
| App Chart            | standard                                                                                    |
| Desired Instances    |                                                                                           1 |
| Bound Configurations |                                                                                             |
| Environment          |                                                                                             |
|   - BP_KEEP_FILES    | static/*                                                                                    |
| Chart Values         |                                                                                             |

✔️  Instances: 
|                              NAME                               | READY | MEMORY  | MILLICPUS | RESTARTS |  AGE  |
|-----------------------------------------------------------------|-------|---------|-----------|----------|-------|
| rtestapp-gituburl-3609caf5e8714c257de51705edff8e44d5a20d36xffm5 | true  | 1.8 MiB |         0 |        0 | 1m39s |

```

![Image](https://user-images.githubusercontent.com/37271841/232830371-bdff7e8e-0d63-4a8a-ac51-73859f8602f4.png)

**Comment by andreas-kupries** [comment]
Notes:

  - `restage` does not `restart` the app. You can this in `app show`, last stage id changes, running stage id does.
  - That said, `restart` does help, and that is where a bug is. After the restart `app show` shows the new stage id id as the running as well. However looking at the kube resources, i.e. pod, the `image` __has not changed__. It still shows the image from the old stage id.

It looks that a restart is not properly setting the image id to use, for the new stage id.

**Comment by andreas-kupries** [comment]
The issue might be in the `restage` anyway. The restage command runs staging, and updates the `stageId` in the app resource. It does not update the `imageurl` in the resource, which is where `restart` pulls the information from.

I will have to re-read all the code around imageURL. There are some notes that the handling might contain special cases.

**Comment by andreas-kupries** [comment]
PR https://github.com/epinio/epinio/pull/2227 extends the restart API endpoint to detect mismatch between stage id and image url and update the image url to the new stage id before performing the restart.

Then it things should work, by
  - push (without env)
  - app set env
  - app restage
  - app restart

**Comment by mmartin24** [comment]
> PR #2227 extends the restart API endpoint to detect mismatch between stage id and image url and update the image url to the new stage id before performing the restart.
> 
> Then it things should work, by
> 
> * push (without env)
> * app set env
> * app restage
> * app restart

@andreas-kupries I tested in your branch using the 4 steps mentioned and worked, so the fix is ok
For easier reproduction steps later simply copy:
```
epinio push --name testapp-githuburl --git https://github.com/epinio/example-go,main
epinio app env set testapp-githuburl BP_KEEP_FILES 'static/*'
epinio app restage testapp-githuburl
epinio app restart testapp-githuburl
```
However. thinking in the UI, the user may need to hit the first option to restage and a second to restart. I wondered if there is any way these 2 could be combined somehow or if it does not make sense here.

Thanks

**Comment by andreas-kupries** [comment]
I was confused initially as well, I had thought that `restage` would include a `restart`.
At the API level I believe that the two should be kept separate.
In the CLI and UI having restage do a restart would IMHO be better.
Would make that a separate issue though

**Comment by mmartin24** [comment]
> I was confused initially as well, I had thought that `restage` would include a `restart`. At the API level I believe that the two should be kept separate. In the CLI and UI having restage do a restart would IMHO be better. Would make that a separate issue though

Thanks, @andreas-kupries, it makes sense to tackle this separately.

**Comment by mmartin24** [comment]
Retested as in commented [above](https://github.com/epinio/epinio/issues/2220#issuecomment-1516136638) in `v1.8.0-rc1`
