### ISSUE TITLE
Add `restart` within `restage` Epinio command in CLI

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2230]
## Issue
After https://github.com/epinio/epinio/pull/2227 an env var would take effect if deployed in a later stage; however, it would require to `restage` first and `restart` later. 

## Request
The request is to minimize these 2 actions by doing a `restart` automatically after a `restage` and ensure that the additions of env vars take place

So instead of doing this...

```
epinio push --name testapp-githuburl --git https://github.com/epinio/example-go,main
epinio app env set testapp-githuburl BP_KEEP_FILES 'static/*'
epinio app restage testapp-githuburl
epinio app restart testapp-githuburl
```
... we could drop the last command and still work

**Comment by enrichman** [comment]
We can add a `--restart` flag to the `restage` command. If no workload is present, or the instances are scaled to `0` then only arestage will be performed.

**Comment by mmartin24** [comment]
Checked `restage` includes `restart` by default 
Checked `--no-restart` flag after restage prevents from restarting

Tested in `v1.9.0-rc2-1-g2240f783` like this:

```
epinio push --name testapp-githuburl --git https://github.com/epinio/example-go,main
epinio app env set testapp-githuburl BP_KEEP_FILES 'static/*'
epinio app restage testapp-githuburl
```

Note: Checked also ui did not inherited this implementation.

**Comment by mmartin24** [comment]
Rechecked in `v1.9.0-rc3`and working:
![image](https://github.com/epinio/epinio/assets/37271841/2c11c6fa-d20a-4792-804a-4e879b5f906f)
