### ISSUE TITLE
Clean up self-hosted CI runners

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#224]
While running with existing (warmed up) clusters is helpful for CI runs, there's no action/task to remove clusters at a later time.

Also lowering the number of gingko nodes (in `Makefile`) does not tear down excess clusters.

All this is irrelevant for GH hosted runners, but can get problematic with self-hosted ones.

**Comment by jimmykarily** [comment]
We now delete the clusters after tests are done:

- https://github.com/epinio/epinio/blob/main/.github/workflows/main.yml#L231-L233
- https://github.com/epinio/epinio/blob/main/.github/workflows/aks-letsencrypt.yml#L149-L157

Closing this.
