### ISSUE TITLE
Remove `target: <namespace>` from `settings.yaml` when logging to another cluster

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2299]
**Describe the bug**
RKE2 EC2 CI [jobs](https://github.com/epinio/epinio/actions/runs/4954930538/jobs/8863872559#step:15:81) are failing because they run on a shared gh-runner where another CI job wrote the `~/.config/epinio/settings.yaml` file before and did settings of the new default `target` namespace in it.

The EC2 job is then trying to create an app but it uses the non-existing namespace from the previous run hence the app deployment is failing.

The workaround is to delete the `~/.config/epinio/settings.yaml` and start the login from scratch.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. add `target: <non-existing-namespace>` into `settings.yaml` file
2. Push an app
3. See the error:
```
  🚢  Create application
  Namespace: namespace-759461032
  Application: apps-149210746

  ❌  error creating app: Not Found: namespace 'namespace-759461032' does not exist
```

**Expected behavior**
I see several options which may address this issue:
* introduce new `epinio login --target-namespace`
* on a new `epinio login` call we may delete the `target:` line esp. when login to a different cluster
* Introduce new `epinio logout` which would delete the settings.yaml file
* support multiple epinio endpoints/clusters in settings.yaml
* remove the `target` when epinio detects a non-existing target within `epinio login`

**Comment by thehejik** [comment]
Something is wrong after merging the PR. After login the new `settings.yaml` contains `namespace: ""` (the workspace ns exists) and after targeting there is no `target: <namespace>` anymore but `namespace: <target-ns>` is changed.

This is fresh login:
```
$ dist/epinio-linux-amd64 login -u admin -p password --trust-ca https://epinio.10.100.103.16.nip.io/

🚢  Login to your Epinio cluster [https://epinio.10.100.103.16.nip.io/]

✔️  Trusting certificate for address https://epinio.10.100.103.16.nip.io/...

⚠️  Epinio server version (v1.8.0) doesn't match the client version (v1.8.0-25-g4cc2ef9f)

⚠️  Update the client manually or run `epinio client-sync`

✔️  Login successful
2023/05/18 07:21:38 EpinioApiClient: "msg"="request failed" "error"="Get \"/api/v1/namespaces/workspace\": unsupported protocol scheme \"\""

⚠️  Current namespace 'workspace' not found in targeted cluster

⚠️  Cleared current namespace

⚠️  Please use `epinio target` to chose a new current namespace
```

**Comment by andreas-kupries** [comment]
The big clue likely is in the message
> 2023/05/18 07:41:49 EpinioApiClient: "msg"="request failed" "error"="Get \"/api/v1/namespaces/workspace\": unsupported protocol scheme \"\""

It fails to retrieve namespace information and treats that as `namespace missing`.
While the issue looks to be in the client somehow.

It believes that the protocol schema is `""`, the empty string.

Investigating now.

**Comment by andreas-kupries** [comment]
> there is no target: <namespace> anymore but namespace: <target-ns> is changed instead.

That is correct. The `namespace` field in the settings is the targeted namespace. This field is not called `target`.
See https://github.com/epinio/epinio/blob/22d40644d4769b14b650b0e923790a60dc53a3d7/internal/cli/settings/settings.go#L41

**Comment by andreas-kupries** [comment]
Ok. Starting without any settings file is indeed key to induce the error.

**Comment by andreas-kupries** [comment]
Without the settings file, the E client we have has no API information. Trying to then invoke any API will fail. I have to save, and then create a new client with the proper information to be able to actually check for the namespace.

I.e. a bit of an ordering and initialization issue.
