### ISSUE TITLE
[CLI] Add auto completion options after --git-provider flag

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2302]
## Issue
Following work after https://github.com/epinio/epinio/pull/2298

The auto-completion capability for the options described in the above pr are missing:
```
git
github
github_enterprise
gitlab
gitlab_enterprise
```

~~We should enable it to be consistent with autocompletion in other commands.~~
It would be nice to implement this if possible

**Comment by andreas-kupries** [comment]
Supported by cobra: https://github.com/spf13/cobra/blob/main/shell_completions.md#specify-dynamic-flag-completion

**Comment by andreas-kupries** [comment]
> We should enable it to be consistent with autocompletion in other commands.

This is actually the first place where we would have auto-completion of option values.

**Comment by mmartin24** [comment]
> > We should enable it to be consistent with autocompletion in other commands.
> 
> This is actually the first place where we would have auto-completion of option values.

I meant it for the functionality itself, didn't mean it, particularly for the values. Having said this, I will re-write the description above.
