### ISSUE TITLE
Reproduce error decoding PEM with external registry

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2318]
In some cases we have an error while trying to decode certificate secrets for external registries.

We should try to reproduce it to understand which could be the issue.

**Comment by thehejik** [comment]
From email communication from FB we found out that they are using subCA certificate with CA:true for their external registry which was not supported by cahash.go, it should be addressed by https://github.com/epinio/epinio/pull/2348

**Comment by thehejik** [comment]
Customer confirmed the fix works for him, it will be part of upcoming release, in meantime ` --set image.epinio.tag=v1.9.0-rc2` can be used.

**Comment by thehejik** [comment]
Issue reproduced, documentation created https://github.com/epinio/epinio/blob/main/docs/howtos/public_external_registry.md
