### ISSUE TITLE
Allow the user to get service credentials

### ISSUE THREAD

**Issue by giubacc** [epinio/epinio#2328]
**Is your feature request related to a problem? Please describe.**
Since we are developing: https://github.com/epinio/epinio/issues/2037 that is: exposing services created with epinio to the user; we are required also to equip the user with the credentials needed to access the exposed services.
Currently, there is no such command that the user can invoke to get the credentials for an instance of a service.
The only way the user can obtain the credentials is to search into some kubernetes secretes; since epinio is designed to provide a layer to hide kubernetes concepts, the current available method seems to be logically unacceptable. 

**Describe the solution you'd like**
I would like, as user, a command such as:

`epinio service show-credentials mysql`

**Comment by andreas-kupries** [comment]
> Currently, there is no such command that the user can invoke to get the credentials for an instance of a service.
The only way the user can obtain the credentials is to search into some kubernetes secretes

Actually not quite. When the service is bound to an application the K secrets with the credentials are marked as E configurations, and using `configuration show` on these does list the relevant keys and values. Finding the configurations for the service is do-able using a combination of `configuration list` and `grep <service-name>`.

Even so, agreed that automating the above process and printing the information as part of `service show` would improve GOOBE.

**Comment by enrichman** [comment]
Agree on just improving the `service show` command adding more info about the credentials.
