### ISSUE TITLE
CAHash helper produces identical error messages for two different situations.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#2332]
**Describe the bug**

The `helper/cahash` package does not allow users to distinguish cert data which are not in PEM format, vs cert data which does not contain a regular (non-CA) cert. 

Change the error message for the `not found` situation to distinguish this from the `bad format`.

See https://github.com/epinio/epinio/blob/d185a22d0facf42e87249874dc3510c5a1fa49a1/helpers/cahash/cahash.go#L50-L69, specifically lines 55 and 69.

**Comment by enrichman** [comment]
Fixed by https://github.com/epinio/epinio/pull/2348
