### ISSUE TITLE
Cannot update source from a failed app

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to update a source from a failed app is not possible

### Expected Behavior

It should be possible to source a failed up and have it into a running state

### Steps To Reproduce

1. Install latest  `epinio-dev` commit (Currently: 23d440198092d8ac60089a7d176e041f2b9b68dd (HEAD -> epinio-dev, origin/epinio-dev) )
2. Deploy a faulty app (ie folder with images)
3. Try to update to a valid app (ie: source type = file with [sample-app.tar.gz](https://github.com/epinio/ui/files/11476924/sample-app.tar.gz))

Observe error:
![image](https://github.com/epinio/ui/assets/37271841/265bed31-93c8-4243-b9b2-5ca692484403)

### Environment

```markdown
- OS: Linux
- Architecture:amd64
- Epinio Version: v1.8.0-20-g912b8964
- Cluster:
  - Provider: k3d
  - Options:1 node
  - Kubernetes Version: v1.25.4+k3s1
```

**Comment by mmartin24** [comment]
https://github.com/epinio/epinio/issues/2363#issuecomment-1576842871

> Does this happen when changing the instance count when just using an app created by the CLI, or does the app need to come from the UI (and also updated by UI)?

@richard-cox, it does not necessarily need to come from UI; it happens when cli updates from the faulty app with the instance count. Having said this the UI shows the error described initially (unable to update if app is faulty). Let's check if the UI remains affected after the BE team takes a look. 

Note: I made sure this only occurs when the app was in previous faulty state. If you deploy a healthy app with `-i 1` it works.

**Comment by andreas-kupries** [comment]
The `create` box has to go after the `app exists` check

**Comment by enrichman** [comment]
> The `create` box has to go after the `app exists` check

Yes, probably it's easier to understand. I put it before because it's the `create` API that will return the `app-exists` response, so it's actually the check that we do for the app existance.

**Comment by andreas-kupries** [comment]
Oh! Create and get an error back when it exists. Ok, then the flow as shown makes sense.

**Comment by enrichman** [comment]
@torchiaf @richard-cox 

Regarding this issue we need to change the behavior of the `update` endpoint, and the client will need to handle it with a separate API call. This will break a couple of things that will need to be updated.

We are going to postpone this for the `1.10.0` since it's not critical, or maybe we can think about a `1.9.1` with just some fixes.
