### ISSUE TITLE
Disable Windows in epinio rancher app

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2368]
Seems the epinio chart for rancher marketplace is enabled for windows but we don't offer windows containers so it makes no sense.

https://github.com/rancher/charts/blob/c5dcee5d4b8bb7116ff90c56b19469acebdf204d/charts/epinio/102.0.2%2Bup1.6.2/Chart.yaml#LL9C1-L9C46

**Comment by andreas-kupries** [comment]
Done with https://github.com/rancher/charts/pull/2670
