### ISSUE TITLE
[CLI] Validate `--git-provider` option for `push` command

### ISSUE THREAD

**Issue by torchiaf** [epinio/epinio#2376]
**Describe the bug**
It is possible to assign GitLab provider to a new application where the source repository is GitHub and vice versa.

Hint: Make basic validation, comparing the Git URL and git provider, or derive provider from Git URL.

**To Reproduce**

1. Run:` epinio push --name gitlab-cli-main --git-provider gitlab --git https://github.com/richard-cox/epinio-sample-app,main`

**Expected behavior**
An error is thrown since the provider is GitLab but the URL is from GitHub

**Comment by mmartin24** [comment]
Rechecked in `Epinio Server Version: v1.10.0-rc1`
