### ISSUE TITLE
ClusterIssuer `s3gw-letsencrypt-issuer` Unavailable after installing Epinio with s3gw

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2391]
**Describe the bug**
After installing Epinio 102.0.3+up1.8.1 as Rancher app or with S3GW enabled (instead of default Minio) the ClusterIssuer `s3gw-letsencrypt-issuer` resource is Unavailable.

EDIT: also reproducible with "normal" Epinio v1.8.1 helm chart without Rancher:
```
$ helm upgrade --install epinio --namespace epinio epinio/epinio --set global.domain=mydomain --create-namespace --set minio.enabled=false --set s3gw.enabled=true
$ kubectl get ClusterIssuer s3gw-letsencrypt-issuer  -o yam
```

![image](https://github.com/epinio/epinio/assets/12828077/b4c7dc62-0e07-4700-a098-acaccfc40abd)

The issue comes from s3gw [values.yaml](https://github.com/rancher/charts/blob/dev-v2.7/charts/epinio/102.0.3%2Bup1.8.1/charts/s3gw/values.yaml#L25) where this is set:

```
  email: "mail@example.com"
```

According to the message it seems the email cannot end with `example.com`

```
$ kubectl get ClusterIssuer s3gw-letsencrypt-issuer -o yaml
...
status:
  acme: {}
  conditions:
  - lastTransitionTime: "2023-06-21T08:07:47Z"
    message: 'Failed to register ACME account: 400 urn:ietf:params:acme:error:invalidContact:
      Error creating new account :: invalid contact domain. Contact emails @example.com
      are forbidden'
    observedGeneration: 1
    reason: ErrRegisterACMEAccount
    status: "False"
    type: Ready
```
I see two options how to resolve this:
- patch the email value to something like `epinio@suse.com`
- remove the ClusterIssuer block from its helm [template](https://github.com/rancher/charts/blob/e3d59d89ead47b7a7a082434b5e14df0dc107872/charts/epinio/102.0.3%2Bup1.8.1/charts/s3gw/templates/tls-issuer.yaml#L24)

Also it has not so nice consequence in Rancher App overview page (the graph should be all green):
![rancher](https://github.com/epinio/epinio/assets/12828077/a3d64cec-1111-44fb-a3e4-74400b1e8c57)

**Comment by thehejik** [comment]
Fixed by changing the email value to `epini@suse.com` within https://github.com/rancher/charts/pull/2733

![image](https://github.com/epinio/epinio/assets/12828077/3f680be9-e7d4-4245-9138-9d771fc2c4c2)

**Comment by thehejik** [comment]
This is addressed in Epinio Rancher App `102.0.3+up1.8.1`, but we should also resolve this in "normal" helm chart.

**Comment by giubacc** [comment]
@thehejik mind creating an issue on s3gw repository pointing this downstream issue?
In principle we could explicitly set in the s3gw's subchart the value for `email` with the value usedin the Epinio chart.
I don't know if this is an issue: we've probably set `example.com` with the explicit intent of generating a failure.
But the most obvious cause of this is that we never properly think about this because we never tested a scenario using letsencypt.

**Comment by thehejik** [comment]
Reported upstream https://github.com/aquarist-labs/s3gw/issues/596

**Comment by giubacc** [comment]
thanks @thehejik

**Comment by enrichman** [comment]
Closing this waiting for the next release/steps from the `s3gw`.
