### ISSUE TITLE
Support for list of strings as a value for custom service settings

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2401]
original ref: https://github.com/epinio/epinio/issues/1633

Currently only standalone values as strings are supported, if you try to use settings for something like `annotations: {}` it will fail.

Reproducer:
* Add settings for existing catalog service:
```bash
$ kubectl edit services.application.epinio.io -n epinio mysql-dev
# add this at values level and save:
  settings:    
    primary.service.annotations:                                              
      type: string
```
* Deploy the service from modified catalog:
```
$ epinio service create mysql-dev mysql6 -v primary.persistence.annotations=first --wait

🚢  Creating Service...
Catalog: mysql-dev
Service: mysql6
Wait For Completion: true

❌  error creating service: service create failed: Internal Server Error: error deploying service helm chart: installing or upgrading service SYNC: 1 error occurred:
	* StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal string into Go struct field ObjectMeta.spec.volumeClaimTemplates.metadata.annotations of type map[string]string
```

* When index is used `-v primary.persistence.annotations[0]=second`
```bash
$ epinio service create mysql-dev mysql6 -v primary.persistence.annotations[0]=second --wait

🚢  Creating Service...
Catalog: mysql-dev
Service: mysql6
Wait For Completion: true

❌  error creating service: service create failed: Bad Request: Setting "primary.persistence.annotations[0]": Not known
```

**Comment by andreas-kupries** [comment]
The validation of chart values has to strip a `[...]` suffix from the key before trying to look it up.

The deeper backend itself should already support the syntax, due to its use of helm packages for the parsing and manipulation (Handling of helm client's `--set` option.).

**Comment by andreas-kupries** [comment]
Confirmed reproduction

**Comment by andreas-kupries** [comment]
Note: The example `primary.persistence.annotations` field is __not__ a sequence (list of strings, `[]string`).
It is a `map[string]string`.
