### ISSUE TITLE
s3gw install failing after new `publicDomain` field

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2405]
## Issue
Rancher ui tests detected a failure on 06/30/23 while attempting to install s3gw on tests ([Rancher-UI-1-Chrome #653](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5418767030/jobs/9854388362#step:3:120))

```
helm install --namespace=epinio --timeout=10m0s --values=/home/shell/helm/values-epinio-1.8.1.yaml --version=1.8.1 --wait=true epinio-install /home/shell/helm/epinio-1.8.1.tgz
creating 1 resource(s)
creating 1 resource(s)
creating 1 resource(s)
Error: INSTALLATION FAILED: execution error at (epinio/charts/s3gw/templates/chart-validation.yaml:2:4): Please provide a value for `.Values.publicDomain`.
```

![Image](https://user-images.githubusercontent.com/37271841/250072884-e9217d0b-7c1f-4d46-8bbb-54d310a32a86.png)

It seems there is a new mandatory field required: `Values.publicDomain`

**Comment by mmartin24** [comment]
Tests green again after https://github.com/epinio/epinio/pull/2406

https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5422803263
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5422265593

![image](https://github.com/epinio/epinio/assets/37271841/35302f19-5ef5-4b37-981c-4eb46e0d8c84)

**Comment by enrichman** [comment]
Ref: https://github.com/aquarist-labs/s3gw-charts/pull/108

**Comment by mmartin24** [comment]
Closing issue since the error is no longer observed after https://github.com/epinio/epinio/pull/2406
