### ISSUE TITLE
`epinio service port-forward` should fail if service does not exist

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2425]
Relevant comment: https://github.com/epinio/epinio/pull/2366#issuecomment-1588688645

## Issue
`epinio service port-forward` command does not fail if the service does not exist:

```
➜  epinio git:(main) ✗ epinio service list                       

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|   NAME    |            CREATED             | CATALOG SERVICE | VERSION |  STATUS  | APPLICATIONS |
|-----------|--------------------------------|-----------------|---------|----------|--------------|
| svc-mysql | 2023-07-04 15:15:29 +0200 CEST | mysql-dev       | 8.0.31  | deployed |              |
➜  epinio git:(main) ✗ epinio service port-forward redis-dev 3308

🚢  Executing port forwarding
Namespace: workspace
Service: redis-dev

```

## Steps to reproduce:
- Once epino is deployed, log in and do not create a service.
- Run `epinio service port-forward redis-dev 3308` (observe how service port-forwarding is executed)

To check the logs run on a separate terminal `telnet localhost 3308` and observe how it kills the port-fowarding

![Image](https://user-images.githubusercontent.com/37271841/250938519-3df8c0aa-b8f0-4e2c-97c3-d4ddeb88c9ea.png)

## Expected behavior
If the user is logged in and the service does not exist, the service port forward should fail.

**Comment by andreas-kupries** [comment]
It is weird that there is no error message, like for app forwarding.
The presumed service forward handler does the same kind of checks and error responses as the apps forward handler.

Something asks for the list of services, very early, does not use the information, superfluous.
Where app forward triggers the web socket handler for it, the service forward sock handler is not reported as called.

It seems I have to debug first what exactly is called by the client, where, and how.

**Comment by andreas-kupries** [comment]
Ah, the early `service` list is a pre-check that the E API server is available.
Might be better to use `info` instead, the list could be expensive.
Regardless, that is not our issue, looks like.

**Comment by andreas-kupries** [comment]
:bulb: The service forwarder sets up a local listener, for the local port - And then, when a connection is made to that port, then it opens a websocket to the E API endpoint ... And then the checks will happen.

And confirmed.

Easiest fix looks to be to change the `service list` API check into a `service show` equivalent, to check for API and service.

**Comment by giubacc** [comment]
Exactly! I think that could be the most convenient solution; you'd use the show call to check both the connectivity and the service's existence at the same time (also without paying the list cost). So win-win.

**Comment by andreas-kupries** [comment]
PR made and in CI

**Comment by mmartin24** [comment]
Rechecked in `Epinio Server Version: v1.10.0-rc1` and working

```
➜  epinio git:(main) ✗ epinio service port-forward redis-dev 3308

🚢  Executing port forwarding
Namespace: workspace
Service: redis-dev

❌  error port forwarding to service: service 'redis-dev' does not exist
➜  epinio git:(main) ✗ epinio info                               

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.25.4+k3s1
Epinio Server Version: v1.10.0-rc1
Epinio Client Version: v1.10.0-rc1
```
