### ISSUE TITLE
Arguments on 'epinio service create'.

### ISSUE THREAD

**Issue by irving200** [epinio/epinio#2450]
**Is your feature request related to a problem? Please describe.**
When creating a service, there is no way to customize it beyond the current chart referenced in the catalog.

**Describe the solution you'd like**
A way to pass values through arguments during 'epinio service create' would give us the option to use those custom values to deploy a service tailored to that specific instance.

**Describe alternatives you've considered**
Right now, we are using the .Release.Namespace to do most of the customization, but that only gets us so far.

**Comment by enrichman** [comment]
Hi @irving200, this is a duplicated issue (see: https://github.com/epinio/epinio/issues/1633 and https://github.com/epinio/epinio/pull/2389) and I'm happy to tell you that the feature will be in release `1.9.0` (scheduled for next week).

The way that we implemented it is similar to the customization of the AppChart values.
For more details you can already check the upcoming docs: https://docs.epinio.io/next/howtos/create_custom_service#user-settable-configuration-values

Closing this. :slightly_smiling_face:
