### ISSUE TITLE
If staging fails, the CLI doesn't stop waiting

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#246]
I tried to run codimd in carrier, and the buildpack doesn't like the nodejs engine version causing the stage to fail. (I found this out via the tekton dashboard)

Due to this failure, the pipeline failed in the staging task but the dots never stopped on the CLI.

**Comment by andreas-kupries** [comment]
How long did you wait ?
(The standard timeout of the cli here is 5 minutes)

**Comment by agracey** [comment]
Definitely not 5 minutes because I had already seen the pipeline in the failed state

**Comment by jimmykarily** [comment]
Relevant: #357
