### ISSUE TITLE
When using archive if it as a subfolder it dont compile

### ISSUE THREAD

**Issue by yodatak** [epinio/epinio#2465]
Hi when i download git archive from gitlab he create a subfolder inside the archive.
Epinio cannot find the app in the subfolder 

it can be interesting to support by default the gitlab zip export of a repo

Thanks

**Comment by yodatak** [comment]
I do it in web interface and I take the zip created by gitlab and it failed because it have a subfolder, ours dev use the web interface because of proxy and admin restrictions

**Comment by enrichman** [comment]
Ah, I see. Thank you for the clarification. I checked and it's actually the same for Github.
I think that it's something we can think about. It should be just a matter of checking if the archives contains only a folder and upload the contents instead of everything.

**Comment by andreas-kupries** [comment]
@yodatak You did not mention which language your application is in.

For PHP it possible to set the environment variable `BP_PHP_WEB_DIR` to tell the PHP buildpack in what directory the app sources are in.

This is used for the test deploying `wordpress` .
There the app sources are in the `wordpress` directory, the single subdirectory in the archive.
It might be a good idea to check if other buildpacks support similar environment variables.

If yes, then this would IMHO better than magically treating a single subdirectory.

**Comment by andreas-kupries** [comment]
Deeper research today shows that I am somewhat mistaken about the `BP_PHP_WEB_DIR`.
It specifies the location of the files to serve by the PHP web server, with a default of `htdocs`.
Of course, the `.php` files among these files are the app, so it manages to work out.

However most other languages do not really have equivalents
(See howto section of https://paketo.io/docs/)

`java` and `node.js` may work as well, via `BP_NODE_PROJECT_PATH`, and `.net` possibly too, via `BP_DOTNET_PROJECT_PATH`. The rest I saw nothing similar, not in the howtos, nor in the linked references.

In the end we look to need the magic indeed.
