### ISSUE TITLE
s3gw resources having wrong names in Epinio v1.9.0-rc4

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2466]
**Describe the bug**
Many of s3gw resources have wrong names after deploying epinio v1.9.0-rc4 with s3gw. For instance its pod and ReplicaSet are named `epinio-*` and not `s3gw-*` anymore. 

Most critical problem seems to be that app deployment doesn't work at all because the needed s3gw tls secret has wrong name as well.

![image](https://github.com/epinio/epinio/assets/12828077/b9d27ac8-1aa6-4e3f-8823-caf72ffbb5ff)

Where the secret in the cluster is actually named `epinio-epinio-cluster-ip-tls`

The Epinio release is currently using `quay.io/s3gw/s3gw:v0.18.0` 

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio with flags `--version 1.9.0-rc4 --set minio.enabled=false --set s3gw.enabled=true`
2. Push an app over UI
3. See the error above ^

**Expected behavior**
* The app should be deployed after pushing
* The s3gw resources should be named with s3gw prefix

**Comment by giubacc** [comment]
bug on upstream confirmed
