### ISSUE TITLE
Display better message when not finding default epinio `settings.yaml` file

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2467]
## Issue
Currently if default epinio settings.yaml file is not found the message displayed is:

```
❌  error retrieving Epinio environment information: making the request: Get "/api/v1/info": unsupported protocol scheme ""
```

## Request

It would be nice to say something as  `"settings.yaml" file not found in /home/mmartin/.config/epinio/` or similar

## To reproduce:
- remove `/home/mmartin/.config/epinio/settings.yaml ` from your respective path
- run `epinio info`

**Comment by thehejik** [comment]
Verified in `v1.10.0-rc1`

Before
```
$ rm -r ~/.config/epinio/
$ epinio-1.9 info

❌  error retrieving Epinio environment information: making the request: Get "/api/v1/info": unsupported protocol scheme ""
```

After
```
$ epinio-1.10 info

❌  error retrieving Epinio environment information: Client settings not found. Please ensure that the cluster is running, Epinio is installed, and the client is logged in.
```
