### ISSUE TITLE
Environment variable containing whitespace in --env option not working

### ISSUE THREAD

**Issue by mageran** [epinio/epinio#2468]
**Describe the bug**
When specifying -e option on an epinio app push command, and the value contains a whitespace then staging fails, because apparently the string following the whitespace in the value is interpreted as another command line option.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

epinio app push --name app-name --builder-image paketobuildpacks/builder -e 'BPE_JAVA_TOOL_OPTIONS: '-Xms1024m -Xmx3048m'

**Expected behavior**
The value of the environment variable would be set including the whitespace and staging would not fails because of that.

**Logs**

Staging logs excerpt:

/stage-support/build: line 23: export: `-Xmx3048m': not a valid identifier

**Comment by enrichman** [comment]
Hi @mageran, it seems that you're quoting the variable not in correct way.

Can you try with:
```
epinio app push --name app-name --builder-image paketobuildpacks/builder -e 'BPE_JAVA_TOOL_OPTIONS=-Xms1024m -Xmx3048m'
```

**Comment by mageran** [comment]
Sorry, my sample code above was not accurate. I used your cmdline and it still gives me that error.


🚢  Streaming application logs
Namespace: workspace
Application: app-name
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] download-s3-blob By _ _ __ ___ _____ root /aws 
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] download-s3-blob Completed 256.0 KiB/49.5 MiB (8.3 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/49.5 MiB (13.5 MiB/s) with 1 file(s) remaining
<a few hundred lines deleted>
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] buildpack /workspace/source/app/gradle/wrapper 
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] buildpack /workspace/source/app/gradle/wrapper/gradle-wrapper.jar 
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] buildpack /workspace/source/app/gradle/wrapper/gradle-wrapper.properties 
🕞  [stage-workspace-app-na-b36fca383391129c8b00abb6d6449e49d8ar2htm] buildpack /stage-support/build: line 23: export: `-Xmx3048m': not a valid identifier

**Comment by enrichman** [comment]
Yes, sorry, I stopped just having a look at the first lines of the command:

```
-> % epinio push --git https://github.com/epinio/example-java -n java -e 'BPE_JAVA_TOOL_OPTIONS=-Xms1024m -Xmx3048m'

🚢  About to push an application with the given setup
Manifest: <<Defaults>>
Name: java
Source Origin: https://github.com/epinio/example-java
AppChart: 
Target Namespace: workspace
Environment 'BPE_JAVA_TOOL_OPTIONS': -Xms1024m -Xmx3048m
Routes: <<default>>
```
 and I was thinking that it was enough. I think I have an idea of what is happening.

As a workaround you can comment this line: https://github.com/epinio/helm-charts/blob/112b7297998eb5fc1527a65b63b97630f8067721/chart/epinio/templates/stage-scripts.yaml#L86

You probably don't need it, unless you are behind a proxy and setting also the `HTTP_PROXY` or `HTTPS_PROXY` env vars.

**Comment by mageran** [comment]
Thanks. I'll try the workaround.

**Comment by enrichman** [comment]
Hi @mageran, I was just checking this issue. Did the workaround work for you?

**Comment by mageran** [comment]
Yes, It worked. Thanks again.

**Comment by thehejik** [comment]
Verified in `v1.10.0-rc1`.

With v1.9.0 I was able to reproduce the issue with `https://github.com/paketo-buildpacks/samples/tree/main/java/maven` example and then after pushing by:
```bash
$ epinio app push --name app-name --builder-image paketobuildpacks/builder -e 'BPE_JAVA_TOOL_OPTIONS=-Xms1024m -Xmx3048m' --path ./

🚢  About to push an application with the given setup
Manifest: <<Defaults>>
Name: app-name
Source Origin: /home/thehejik/git/paketo-buildpacks-samples/java/maven
AppChart: 
Target Namespace: workspace
Environment 'BPE_JAVA_TOOL_OPTIONS': -Xms1024m -Xmx3048m
Builder: paketobuildpacks/builder
Routes: <<default>>

...
🕞  [stage-workspace-app-na-71edccb7b9ea3a42e2536a34af11ae4f4d5l4nps] buildpack /workspace/source/env/CNB_PLATFORM_API 
🕞  [stage-workspace-app-na-71edccb7b9ea3a42e2536a34af11ae4f4d5l4nps] buildpack /stage-support/build: line 23: export: `-Xmx3048m': not a valid identifier 
```

With `v1.10.0-rc1` the same application was built correctly.
