### ISSUE TITLE
GraphQL endpoint for UI connections

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#248]
When we get to building a UI, GraphQL can make the process significantly faster.

**Comment by kkaempf** [comment]
Let's focus on performance when we have clear indications where the bottleneck is :wink:

**Comment by agracey** [comment]
Yeah, that why I submitted with "later" :D 

And IMO, GraphQL is more about developer experience than any performance improvement!

**Comment by agracey** [comment]
I'm going to close this until someone other than me asks for it
