### ISSUE TITLE
Add missing branch and revision info when pushing from CLI

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2491]
From the CLI is possible to push just specifying the git url, or a branch.

In those cases the UI is not able to show the branch or the revision, and a user doesn't know which commit is the source from.

**Comment by mmartin24** [comment]
Checked in `Epinio Server Version: v1.10.0-rc1`

Rechecked all 6 scenarios.

Pasting here the example of scenario 1 working in the latest rc:

1.  Pushing the app from the second commit from not main branch fails to display in UI the correct branch and commit selection. (FAILED)

```
epinio push --name testatpp-gitlab-cli-1-nomainbranch-from-nofirstcommit --git https://gitlab.com/richard-cox/epinio-sample-app,ee069123
```

![image](https://github.com/epinio/epinio/assets/37271841/4194629f-3f2e-4868-841d-59e995b0e3c5)
