### ISSUE TITLE
no space left on device for staging cache volumes

### ISSUE THREAD

**Issue by pedro-brito-ilia** [epinio/epinio#2504]
We have an Epinio deployed on an EKS cluster using EBS volumes. On smaller applications, it works just fine, but when we deploy bigger apps, we are having issues with no space left on the staging cache volumes.

This is the error log:
🕞  [stage-e0c9-9678c7bd12f004a0e13d06ccae91152574cc2j5s] buildpack Warning: Failed to cache layer 'paketo-buildpacks/conda-env-update:conda-env-cache': caching layer (sha256:daa1014ba8a918cfd02236168151a5892e2f6a545661c5632e86c15076d339af): write /workspace/cache/staging/sha256:daa1014ba8a918cfd02236168151a5892e2f6a545661c5632e86c15076d339af.tar: no space left on device 
🕞  [stage-e0c9-9678c7bd12f004a0e13d06ccae91152574cc2j5s] buildpack Warning: Failed to export cache: setting cache metadata: marshalling metadata: write /workspace/cache/staging/io.buildpacks.lifecycle.cache.metadata: no space left on device 

Sometimes, this blocks the deployment from completing, and other times it just bypasses and the deployment finishes as usual. After some investigation, we found the volume where Epinio stores the cache and discovered trough our observability tool that the volume is in fact overloaded with data.

![Screenshot 2023-08-03 at 16 14 54](https://github.com/epinio/epinio/assets/112405514/5abed1dc-dc60-49b9-bd48-88e88525c2ac)

We found the code snippet where Epinio creates this volume, but it seems like 1Gi is a hardcoded value:
https://github.com/epinio/epinio/blob/main/internal/api/v1/application/stage.go#L98C20-L98C20

The question here is: How do we customize the size of the cache volumes? Or is there another way to solve this issue without modifying this.

**Comment by gitricko** [comment]
1G is too low... we should be able to specify the size

**Comment by enrichman** [comment]
Thanks for the bug report and for the investigation. This looks to have an high priority, and we're going to have a look at it next week.
