### ISSUE TITLE
API for enhanced epinio information pre-log in

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#2515]
**Is your feature request related to a problem? Please describe.**
- When the Epinio UI is embedded in the Rancher UI it shows a list of all epinio clusters. The user will be able to select a cluster and (soonish) sign in using either a local user or one via dex
- In order to support this the UI needs to know...
  - Cluster State
    - It confirms the epinio cluster's API is available by making a request to `/api/v1/info`. 
  - Cluster Version
    - It shows the version the epinio cluster via the contents of the `/api/v1/info`. This is a nice to have and adds information the user may want to see in that context
  - Cluster Auth Mechanisms
    - It's possible to remove the dex provider such that only the local user auth mechanism is supported
    - If the dex provider is not available the user should not be able to log in via dex
- For the first two this depends on the `/info` endpoint. However this requires credentials which at that point the user does not have. This might have always been like this (for demo's credentials were hardcoded)

**Describe the solution you'd like**
An endpoint that will
- be reachable without credentials
- provide the Epinio version 
- provide the supported auth mechanism

**Describe alternatives you've considered**
- There's a `/ready` endpoint which could be used / beefed up. At the moment though it's not available due to CORS errors

**Additional context**
- I'll link the UI PR containing auth integration when it's up. That will need this new endpoint

**Comment by enrichman** [comment]
Let's schedule this for the next milestone. I'm just curious to know if exposing the cluster/Epinio version could be considered as a security flaw.

**Comment by andreas-kupries** [comment]
@richard-cox 

> There's a /ready endpoint which could be used / beefed up. At the moment though it's not available due to CORS errors

On a first glance simply extending `/ready` might be the easiest way to do this.
How complicated is fixing the CORS errors on your side ?
Would a new endpoint, like, for example `/hello`, also be subject to CORS rules ?

@enrichman 

> ... if exposing the cluster/Epinio version could be considered as a security flaw.

IMHO not really.
Concealing it feels like `security by obscurity` to me, and that is something which in general will not work.
I strongly suspect that there will be over ways of fingerprinting an E server to determine its version even if we hide it.

**Comment by richard-cox** [comment]
@andreas-kupries I think the CORS errors were more related to somewhere API side that allowed cross-origin requests from specific domains (the rancher url is supplied via helm value, and checked in go middleware somewhere). We might have a way around this UI side, but won't be available in this first iteration of auth (it will probably require changes Rancher API side).

@enrichman it might be worth checking with the security team. otherwise, given the user must have some visibility of kube resources, is the epinio version stored somewhere easily accessibly via the kube api?

**Comment by enrichman** [comment]
I've checked with @thesp0nge. It should be fine for the same reason exposed by @andreas-kupries.

By the way the user should/could not have any access to the kube APIs/resources.

**Comment by andreas-kupries** [comment]
Ok. Thanks for all the answers. Plan now is to move `/info` to unauthenticated, and extend it with the information about auth methods.
