### ISSUE TITLE
Cancelled downloads are blocking new downloads.

### ISSUE THREAD

**Issue by torchiaf** [epinio/epinio#2516]
**Setup**
- Epinio version: 1.9.0

**Describe the bug**

The Applications export creates a new zip file containing charts, values and the `image` part.
The download of the image part is demanded to a new job on Epinio cluster.
When the export is cancelled by the user, the job remains active and this prevents new exports, I assume because the old job blocks the creation of a new one.

```
> kubectl get jobs -n epinio
image-export-job-works-178b20f32af5b3baa26f5cab37eee65f4454f5e9   0/1           11s        11s
```

**To Reproduce**

1 Go to Applications -> menu -> 'Export App'.
2 Click on 'Chart and Images' tab and click 'Export'
3 Wait ~5 seconds and click cancel.
4 Do again points 1 & 2 (same application)

**Screenshots**

![image](https://github.com/epinio/ui/assets/26394656/4a057b6b-a930-4480-80ce-9ea575606166)

![image](https://github.com/epinio/ui/assets/26394656/67a20c4a-e98e-4338-8f26-5da8c88e917a)

![image](https://github.com/epinio/ui/assets/26394656/8fbeec37-adbe-40df-be87-eb4b84d04e4e)

**Additional context**

**Comment by andreas-kupries** [comment]
While waiting for cluster to be up I looked more, and the `job already exists` error is definitely backend, and points at the code choosing a name for the job (using just namespace and app name). Should also use some kind of serial and/or nanosecond time. Above clash would be triggered by multiple concurrent requests (from different users) for the same app too. That should be even easier to reproduce.

And while writing Richard points to the same, regarding job identification.
Will also have a look into intercepting the htpp cancellation (something with go contexts).

**Comment by andreas-kupries** [comment]
Replicated for concurrent export request on same app.
Replicated for export request after a cancellation.
Replicated job left behind after command abort.
