### ISSUE TITLE
It's not possible to edit Service chart values/settings

### ISSUE THREAD

**Issue by torchiaf** [epinio/epinio#2518]
Related issue: [#252 ](https://github.com/epinio/ui/issues/252)

Service/edit APIs to be provided.

**Comment by thehejik** [comment]
After updating E server with the fix incorporated I'm still unable to Edit most of the options of existing service over UI. Only `Bind to Application` is active but this is possible even in v1.9.0.

Reopening, please close if this is expected.
![image](https://github.com/epinio/epinio/assets/12828077/791c3bfe-e3f7-4650-99d4-168bd5ab0c4a)

**Comment by andreas-kupries** [comment]
I suspect that the UI has not implemented this yet.
