### ISSUE TITLE
Request to add chart value settings in `services` api response

### ISSUE THREAD

**Issue by torchiaf** [epinio/epinio#2519]
The service's custom settings are currently provided only by service's details API:
https://github.com/epinio/epinio/blob/4b1a314b7f6967761d7dbe7c805b58fe9b5d2297/docs/references/api/swagger.json#L1424

It would be convenient on the UI to have the same info in the services list API. This would avoid the UI to do an extra call when edit/view a service.

**Comment by andreas-kupries** [comment]
With the data now sitting in the K secrets representing a service this should be efficiently do-able now.
When it was pulled out of the helm release itself that was expensive.

**Comment by torchiaf** [comment]
> Hi @torchiaf Are you talking about the `settings` field in Service data ?
> 
> This information is provided by `service list`, see
> 
> ```
> 023/08/21 16:57:18 EpinioApiClient: "level"=5 "msg"="response decoded" "response"=[{"meta":{"name":"baku","namespace":"workspace","createdAt":"2023-08-21 16:56:32 +0200 CEST"},"catalog_service":"post-cv","catalog_service_version":"15.1.0","status":"deployed","boundapps":[],"settings":{"foo.fox.lair":"hohum"}}]
> ```
> 
> This is however only true for services which have the `settings` field in their K secret.
> 
> IOW, services which were created with a server at commit [4b1a314](https://github.com/epinio/epinio/commit/4b1a314b7f6967761d7dbe7c805b58fe9b5d2297) (or later). That is the current main. Alternate commit [9b4672a](https://github.com/epinio/epinio/commit/9b4672a157e803966499069a6e3c042b5c891dad) should also work, that is the PR, before it was merged.
> 
> Can you check which version of the server you used in your tests ? I currently suspect something not quite current main, just a bit older.
> 
> If a service is created by an older server (i.e. not the commits above) then it does not have the `settings` field in its secret. In that case the server currently falls back to the old way of heuristically pulling the information out of the helm release of the service itself. Which is expensive. And thus currently disabled for service listings.

Thank you @andreas-kupries .
I verified that with latest version of main the settings information is correctly provided into `services` list response.

**Comment by andreas-kupries** [comment]
:+1: and good luck
