### ISSUE TITLE
json output for epinio cli command - for automation

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#2525]
**Is your feature request related to a problem? Please describe.**
epinio cli is great, easy to use and understand. However, when we start to use the cli output for automation, it gets alittle tougher to parse.

eg: `epinio namespace list`
```
(base) ➜  environment epinio namespace list             

🚢  Listing namespaces

✔️  Epinio Namespaces:
|           NAME           |            CREATED            |          APPLICATIONS          |                 CONFIGURATIONS                  |
|--------------------------|-------------------------------|--------------------------------|-------------------------------------------------|
| bruno                    | 2023-08-21 13:13:26 +0000 UTC |                                |                                                 |
| fred                     | 2023-07-14 06:36:01 +0000 UTC |                                |                                                 |
| hadirga                  | 2023-07-04 17:25:14 +0000 UTC |                                | x6435997084156c96650cecfa7d24-postgres-secret   |
| hadirgax                 | 2023-08-26 00:22:00 +0000 UTC | leager, leager-python          | x1447c2a7c89e244a61fd3f0822f9-rabbitmq,         |
|                          |                               |                                | x1447c2a7c89e244a61fd3f0822f9-rabbitmq-config,  |
|                          |                               |                                | x1db0d53592d5cc7bf5dbe5c7ba7e-postgresql,       |
|            
```

**Describe the solution you'd like**
I wonder if it is beneficial to have an epinio flag called --json so that the output from the shell would be a json output for easy parsing.
eg:
`epinio namespace list --json`

Would give:
```json
{
  [
   {
      'name': 'bruno',
      'created': '2023-08-21 13:13:26 +0000 UTC',
      'applications': {
       ...
       }


   }


  ]

} 
```
**Describe alternatives you've considered**
Using complex shell cutting and piping

**Comment by enrichman** [comment]
Yes, we already had the same issue opened for a while (https://github.com/epinio/epinio/issues/435).
It's probably feasible but we would need a bit of refactor and cleanup of the CLI. Now it's a bit better than before, but still not that easy.

I would like to keep this in the radar.

**Comment by gitricko** [comment]
Just to give you some context (actually just coincidental as i was asking for this feature to make it easy for me to undeploy/remove resources that dev creates and forgot to remove from the cluster)

We have a terrible bug that we found that was suddenly not working in our pipeline. (and we forgot that we upgraded to 1.9.0)

Our engineers use `epinio configuration show CONFIG-NAME` for retrieve metadata for our pipeline testing. This is ok when we are using 1.8.x but since we upgraded to 1.9... it show this.


![1 9 0](https://github.com/epinio/epinio/assets/18060558/bf878cb8-9de4-48b9-91a7-82487eae87a0)

As a result, the value we send was wrong... We still need to talk to the engineer the intent where we are retrieving the values this way instead from the container... but now u see why having a --json is important as it give us a way to retrieves value easily ;-)

**Comment by enrichman** [comment]
I see. I've opened an epic to slowly adding the flag to the commands. The first will be the `namespace`, and maybe we can make it for the next release.
Do you have any other critical commands that are automated?

- https://github.com/epinio/epinio/issues/2526
  - https://github.com/epinio/epinio/issues/2527

**Comment by enrichman** [comment]
I will close this in favor of the epic 🙂
