### ISSUE TITLE
Deleting a service with a bound app will prevent the app being bound to any service

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#2551]
**Describe the bug**
After a service is bound to an application, deleting the service with
```
DELETE /api/v1/namespaces/<ns>/services?services[]=<service name> {"unbind": true}
```
results in the app unable to be bound to a new service with 
```
POST /api/v1/namespaces/<ns>/services/<new service name>/bind POST {"app_name":"<app name>"}
```
```
{"errors":[{"status":500,"title":"configuration not found","details":"\nServer Backtrace: configuration not found"}]}
```

**To Reproduce**
1. Run the latest nightly UI
2. Create any type of application
3. Create a service and bind the application to it
    - Note the API requests made to create the service, fetch the service and the bind to it 
5. From the service list delete the service
    - Note the API request to delete the service
6. Create a new service and bind the application to it
   - Note the API  to bid will fail with `configuration not found`

**Expected behavior**
Request to bind completes

**Cluster (please complete the following information):**
 - Provider: k3d
 - Kubernetes Version: v1.25.7+k3s1

**Desktop/CLI (please complete the following information):**
 - Epinio Version: v1.9.0-23-g58d35b2e

**Additional context**
- Originating from https://github.com/epinio/ui/issues/289#issuecomment-1706537496
- I noticed on one run that trying to concurrently delete services where at least on service had a failed bind attempt also resulted in the same `configuration not found` error. 
- Possibly irrelevant, the UI now no longer waits for the service instance to be `deployed` before binding. This works (see step 3 above) but might leave something in a bad state?
- Using

**Comment by mmartin24** [comment]
ok, I managed to reproduce in cli as this:

```
epinio push -n sample -p /home/mmartin/suse/epinio-repos/epinio/assets/sample-app
epinio service create postgresql-dev svc-1 && sleep 2 && epinio service bind svc-1 sample   
epinio service delete svc-1 --unbind
epinio service create postgresql-dev svc-2 && sleep 2 && epinio service bind svc-2 sample
```
Output:
```
🚢  Binding Service...

❌  error binding service: service bind failed: configuration not found
```

Later, I could see how the service was created but not bound:
```
➜  epinio git:(main) ✗ epinio service list

🚢  Listing Services...
Namespace: workspace

✔️  Details:
| NAME  |            CREATED             | CATALOG SERVICE | VERSION |  STATUS  | APPLICATIONS |
|-------|--------------------------------|-----------------|---------|----------|--------------|
| svc-2 | 2023-09-06 13:08:18 +0200 CEST | postgresql-dev  | 15.1.0  | deployed |              |
```

**Comment by andreas-kupries** [comment]
Investigation confirms.

```
epinio push -n fox -p assets/sample-app
epinio service create postgresql-dev box --wait
epinio service create postgresql-dev lair --wait
epinio service bind box fox
```

Binding is tracked application side, opaque secret

Here: `fox-svc-07ce22adc9673c807018333c73d4e7d9e30bba38`

The bound services are represented by the keys in the secret. No values (`0 bytes`).
Here `box`.

`service unbind box fox`

 - Removes the key (here: `box`) from the secret.

`ep service delete box --unbind`

 - Is not updating this secret.

`ep service bind lair fox`

 - Fails because during re-deployment of the app it tries to get the configurations for the deleted `box` to bind them. This happens before the information for `lair` is added to the secret.

After deleting the secret the retrying `bind lair fox` recreates it and works.

Note that this is __not__ a feasible workaround in general, because the secret may have other services
recorded, beyond the deleted.

**Comment by andreas-kupries** [comment]
Code investigation. Core of `service unbind` is at

https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/unbind.go#L95-L99

Note:
  - https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/unbind.go#L104 deletes the binding itself, and
  - https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/unbind.go#L115 looks to be the call where the application is updated about the deletion.
    Confirmed, see https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/application/services.go#L164-L170

What does `delete --unbind` do:

  - Core deletion starts at https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/delete.go#L128
  - For bound services, when unbind is requested it calls on the core `UnbindService`: https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/delete.go#L149-L150
  - So, this should also update the app secret.

Possibilities:
  - It does not find the apps the service is bound to, so never calls on UnbindService.
  - In UnbindService an error prevents update of the secret, yet somehow also not reporting that error.

This needs some more server side tracing to see details

**Comment by andreas-kupries** [comment]
Well, the `boundAppNames` is ok, it shows the app. Not is is
https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/delete.go#L140
The `appConfigurationsMap` is empty.
Thus `UnbindService` is not called.

Creation of that map happens in
https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/delete.go#L98-L123

The
https://github.com/epinio/epinio/blob/4dc715ef45b6fb7f9fb635352f065e4d686f07b1/internal/api/v1/service/delete.go#L116
uses an empty `boundAppNames`. The variable is extended later with the found app.
It should use `bound`, I believe.

**Comment by andreas-kupries** [comment]
Looks to have been introduced by myself, in commit 648f435a6c8bac5c9aed89784eda1be1696c2f84.
( https://github.com/epinio/epinio/commit/648f435a6c8bac5c9aed89784eda1be1696c2f84#diff-59bc23aa448f05a7b65aeba85389600e8f244f53c68f07493b7afb6e9d6e1061R105 )
This is PR #1790 implementing the bulk deletion of services.

**Comment by mmartin24** [comment]
Checked on `Epinio Client Version: v1.10.0-rc1-9-g25d8695b`  and in UI using latest ui image.
Notes: to avoid issues with charts, I used `make appchart` from epinio repo

#### Checked on CLI 

<details> 

<summary> Tests done with all 5 services</summary>

```
epinio push -n sample -p /home/mmartin/suse/epinio-repos/epinio/assets/sample-app

# Create `postresql` svc, bind, delete, create new service and bind
epinio service create postgresql-dev svc-1-postgres && sleep 2 && epinio service bind svc-1-postgres sample   
epinio service delete svc-1-postgres --unbind
epinio service create postgresql-dev svc-2-postgres && sleep 2 && epinio service bind svc-2-postgres sample

# Create `mysql` svc, bind, delete, create new service and bind
epinio service create mysql-dev svc-1-mysql && sleep 2 && epinio service bind svc-1-mysql sample   
epinio service delete svc-1-mysql --unbind
epinio service create mysql-dev svc-2-mysql && sleep 2 && epinio service bind svc-2-mysql sample

# Create `mongodb-dev` svc, bind, delete, create new service and bind
epinio service create mongodb-dev svc-1-mongodb && sleep 2 && epinio service bind svc-1-mongodb sample   
epinio service delete svc-1-mongodb --unbind
epinio service create mongodb-dev svc-2-mongodb && sleep 2 && epinio service bind svc-2-mongodb sample

# Create `rabbitmq-dev` svc, bind, delete, create new service and bind
epinio service create rabbitmq-dev svc-1-rabbitmq && sleep 2 && epinio service bind svc-1-rabbitmq sample   
epinio service delete svc-1-rabbitmq --unbind
epinio service create rabbitmq-dev svc-2-rabbitmq && sleep 2 && epinio service bind svc-2-rabbitmq sample

# Create `redis-dev` svc, bind, delete, create new service and bind
epinio service create redis-dev svc-1-redis && sleep 2 && epinio service bind svc-1-redis sample   
epinio service delete svc-1-redis --unbind
epinio service create redis-dev svc-2-redis && sleep 2 && epinio service bind svc-2-redis sample

```

</summary>
</details>

Results:

```
➜  epinio git:(main) ✗ epinio service list

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|      NAME      |            CREATED             | CATALOG SERVICE | VERSION |  STATUS  | APPLICATIONS |
|----------------|--------------------------------|-----------------|---------|----------|--------------|
| svc-2-mongodb  | 2023-09-15 12:50:24 +0200 CEST | mongodb-dev     | 6.0.3   | deployed | sample       |
| svc-2-mysql    | 2023-09-15 12:50:04 +0200 CEST | mysql-dev       | 8.0.31  | deployed | sample       |
| svc-2-postgres | 2023-09-15 12:49:47 +0200 CEST | postgresql-dev  | 15.1.0  | deployed | sample       |
| svc-2-rabbitmq | 2023-09-15 12:50:48 +0200 CEST | rabbitmq-dev    | 3.11.5  | deployed | sample       |
| svc-2-redis    | 2023-09-15 12:51:16 +0200 CEST | redis-dev       | 7.0.7   | deployed | sample       |
```

---
### Checked on UI

I checked the following for all services with single app and worked:

Service creation + binding
Delete service with app binded
Create new service + binding again

**Comment by mmartin24** [comment]
Rechecked in `Epinio Server Version: v1.10.0-rc2` and working

- Working in cli using the same tests as above:
```
➜  epinio git:(main) ✗ epinio service list

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|      NAME      |            CREATED             | CATALOG SERVICE | VERSION |  STATUS   | APPLICATIONS |
|----------------|--------------------------------|-----------------|---------|-----------|--------------|
| svc-2-mongodb  | 2023-09-21 12:21:05 +0200 CEST | mongodb-dev     | 6.0.3   | deployed  | sample       |
| svc-2-mysql    | 2023-09-21 12:20:29 +0200 CEST | mysql-dev       | 8.0.31  | deployed  | sample       |
| svc-2-postgres | 2023-09-21 12:18:01 +0200 CEST | postgresql-dev  | 15.1.0  | deployed  | sample       |
| svc-2-rabbitmq | 2023-09-21 12:21:53 +0200 CEST | rabbitmq-dev    | 3.11.5  | deployed  | sample       |
| svc-2-redis    | 2023-09-21 12:22:35 +0200 CEST | redis-dev       | 7.0.7   | not-ready | sample       |

➜  epinio git:(main) ✗ epinio info           

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.25.4+k3s1
Epinio Server Version: v1.10.0-rc2
Epinio Client Version: v1.10.0-rc2
```
- Rechecked in UI as well and working
