### ISSUE TITLE
ModSecurity rules 921150 and 921120 triggered 

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#2559]
**Describe the bug**

When a layer 7 inspection (GCP Cloud Armor) solution is enabled, the following ModSecurity paranoia 1 rules block standard communication between epinio cli and epinio server:

- `epinio app push`, get blocked during code upload operation.
  - 921150 HTTP Header Injection Attack via payload (CR/LF detected)
  - 921120 HTTP Parameter Pollution after detecting bogus char after parameter array

- Details:
  - https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-921-PROTOCOL-ATTACK.conf
  - Paranoia level 1 is the lowest level and should not report any false positive.

**GCP logs**

![image](https://github.com/epinio/epinio/assets/47371890/e73e6bb7-e51d-439f-a3a8-f21e32071769)

![image](https://github.com/epinio/epinio/assets/47371890/de68d0c5-4205-4fba-bb79-5c5afdb737d2)

**Epinio cli output error**

```
🚢  About to push an application with the given setup
Manifest: <<Defaults>>
Name: conda-test2
Source Origin: /Users/henrique/Downloads/samples/python/conda
AppChart: 
Target Namespace: henrique
Routes: <<default>>
⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)
2023/09/11 11:21:36 EpinioClient/Push: "level"=5 "msg"="validate app name" "Name"="conda-test2" "Namespace"="henrique" "Sources"="/Users/henrique/Downloads/samples/python/conda"
Create the application resource ...
2023/09/11 11:21:36 EpinioApiClient: "level"=5 "msg"="executing request" "method"="POST" "uri"="" "body"="{\"name\":\"conda-test2\",\"configuration\":{\"instances\":null,\"configurations\":null,\"environment\":null,\"routes\":null}}" "header"={"Authorization":["Bearer "],"Proxy-Authorization":["Bearer "]}
2023/09/11 11:21:37 EpinioApiClient: "level"=5 "msg"="response is not StatusOK: application 'conda-test2' already exists" "body"="{\"errors\":[{\"status\":409,\"title\":\"application 'conda-test2' already exists\",\"details\":\"\"}]}"
Application exists, updating ...
2023/09/11 11:21:37 EpinioClient/Push: "level"=5 "msg"="app exists conflict" "Name"="conda-test2" "Namespace"="henrique" "Sources"="/Users/henrique/Downloads/samples/python/conda"
2023/09/11 11:21:37 EpinioApiClient: "level"=5 "msg"="executing request" "method"="PATCH" "uri"="" "body"="{\"instances\":null,\"configurations\":null,\"environment\":null,\"routes\":null}" "header"={"Authorization":["Bearer "],"Proxy-Authorization":["Bearer "]}
2023/09/11 11:21:37 EpinioApiClient: "msg"="decoding json error" "error"="invalid character '<' looking for beginning of value" "body"="<!doctype html><meta charset=\"utf-8\"><meta name=viewport content=\"width=device-width, initial-scale=1\"><title>403</title>403 Forbidden"
2023/09/11 11:21:37 EpinioClient/Push: "level"=4 "msg"="return" "Name"="conda-test2" "Namespace"="henrique" "Sources"="/Users/henrique/Downloads/samples/python/conda"
❌  error pushing app to server: parsing error response: invalid character '<' looking for beginning of value

```

### To reproduce
- Install epinio on GCP GKE environment
- Expose epinio server through an Application LB
- Create a Cloud Armor security policy 
  `gcloud compute security-policies create TEST-SECURITY_POLICY --type=CLOUD_ARMOR`
- Create rule for protocol-attack
  `gcloud compute security-policies rules create 217 --project=GCP_PROJECT_ID --action=deny-403 --security-policy=TEST-SECURITY_POLICY --expression=evaluatePreconfiguredWaf\(\'protocolattack-v33-stable\',\ \{\'sensitivity\':\ 1\}\) --description=Protocol-Attack`
- Attach it to the ALB
- Push an APP

**Comment by thehejik** [comment]
We were able to reproduce the first security issue `921150 HTTP Header Injection Attack via payload (CR/LF detected)` according to the reproducer. The second one didn't show up - we tried also with IAP involved but it didn't make any difference.

There are traces od `\r\n` character in `body` string:

`
2023/10/18 16:00:51 EpinioClient/Push: "level"=5 "msg"="upload code" "Name"="sample-armor" "Namespace"="workspace" "Sources"="/app"
2023/10/18 16:00:51 EpinioApiClient: "level"=5 "msg"="executing request" "method"="POST" "uri"="" "body"="--f686e3ad494745695699c77fb1ea46ad7cd962522ca240d8f8f227ef1eaf\r\nContent-Disposition: form-data; name=\"file\"; filename=\"blob.tar\"\r\nContent-Type: application/octet-stream\r\n\r\nbla.tgz\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000000644\x000001750\x000000144\x0000000000000\x0014513757660\x00013360\x00 ...\r\n--f686e3ad494745695699c77fb1ea46ad7cd962522ca240d8f8f227ef1eaf--\r\n" "header"={"Content-Type":["multipart/form-data; boundary=f686e3ad494745695699c77fb1ea46ad7cd962522ca240d8f8f227ef1eaf"],"Authorization":["Basic YWRtaW46cGFzc3dvcmQ="]}
2023/10/18 16:00:51 EpinioApiClient: "msg"="decoding json error" "error"="invalid character '<' looking for beginning of value" "body"="<!doctype html><meta charset=\"utf-8\"><meta name=viewport content=\"width=device-width, initial-scale=1\"><title>403</title>403 Forbidden"
`

**Comment by thehejik** [comment]
I switched to HTTP and used wireshark to decode the traffic but everything looks valid, still failing on `921150`:
![push_headers_gce](https://github.com/epinio/epinio/assets/12828077/9f6a9521-ec91-4e52-8100-3afffc5a2991)

**Comment by thehejik** [comment]
After switching to HEX I found out that after the final boundary string `--f75[]bc2--` is CRLF which shouldn't be probably there:
![hex](https://github.com/epinio/epinio/assets/12828077/d556c182-55e5-4771-a0d2-00398e09101e)

**Comment by andreas-kupries** [comment]
Actually, AFAIR the CR LF is part of the boundary string in the MIME spec.
Because the boundary is a line.

Looking at https://www.ietf.org/rfc/rfc2046.txt at the first mention of boundary is

> The body must then contain one or more body parts, each preceded by a boundary delimiter line, and the last one followed by a closing boundary delimiter line. After its boundary delimiter line, each [...]

**Comment by thehejik** [comment]
@andreas-kupries Thanks, it must be something else, I even modified the close boundary to not contain the CRLF chars and it is still failing on 403

**Comment by thehejik** [comment]
I enabled verbose logging on the security policy and this is what I got:
```json
    "enforcedSecurityPolicy": {
      "name": "epinio-test-security-policy",
      "matchedFieldLength": 100,
      "priority": 217,
      "preconfiguredExprIds": [
        "owasp-crs-v030301-id921150-protocolattack"
      ],
      "configuredAction": "DENY",
      "matchedOffset": 62,
      "matchedFieldType": "ARG_NAMES",
      "matchedLength": 1,
      "matchedFieldValue": "\r",
      "outcome": "DENY"
    }
```

It looks that Cloud Armor interprets one of the POST argument as `\r` for some reason. It is unclear to me from where I should start to count the offset.

**Comment by thehejik** [comment]
We are not alone https://stackoverflow.com/questions/73473504/getting-403-error-in-cloud-armor-when-sending-multipart-form-data-as-content-typ

**Comment by thehejik** [comment]
This seems to be issue on Google side, tracked here https://issuetracker.google.com/issues/290276290
