### ISSUE TITLE
Find a solution to fix rate limiting of certifcate creation in LetsEncrpt

### ISSUE THREAD

**Issue by rohitsakala** [epinio/epinio#256]
This issue https://github.com/SUSE/carrier/issues/179 was solved by using production certificate generation servers of LetsEncrypt. According to this [0], there is rate-limiting of 50 per week i.e 50 apps per week which is bad.

[0] https://letsencrypt.org/docs/rate-limits/

OR 

Think if we have to change to rancher/Heruko style where a subdomain is mapped to an app and the subdomain url is mapped to the DNS of the user using CNAME records. 

https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

**Comment by kkaempf** [comment]
50 apps per week for a development/testing setup should be sufficient. Customers looking for 'production grade' setups will bring their own certificate.

Flagging as 'later'.

**Comment by agracey** [comment]
We just need to document this limit explicitly. And maybe even show an error explaining it if a user runs into it?

**Comment by jimmykarily** [comment]
We allow the user to use any issuer they want, including letsencrypt-staging which has higher limits ([that's what we use in CI for example](https://github.com/epinio/epinio/blob/main/assets/tests/letsencrypt-staging.yaml)). Showing a warning when the limit it hit just for letsencrypt production, is useful but too low in the priorities. I'll close this for now. If people really stumble on this, please re-open.
