### ISSUE TITLE
Fix PCP tests and workflows

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2594]
**Describe the bug**
Several workflows are breaking our images because we are pushing a build from one helper:

See: https://github.com/epinio/epinio/issues/2583#issuecomment-1729697684

![image](https://github.com/epinio/epinio/assets/1763949/f72041ff-57ae-487a-b4c1-1db1960357c0)

I'm going to stop these workflows until we have a cleaner and proper solution.

First we should understand why we are building and pushing the image from the test. Why is not available? Will a `nightly` build solves this issue?

Then we can probably simplify the workflow files, scenarios and so on, if they are running the same tests just in different cloud providers. It will be nice to have a setup_cluster command to provision the cluster properly, in the same fashion that we did for the delete_cluster.

**Comment by andreas-kupries** [comment]
The non-upgrade flows ... Are nightlies to test the current head. So they also do step 3, and when operating against a public cloud step 5, 6.

So they have the same conflict when they run against a release commit.

**Comment by enrichman** [comment]
I was thinking to introduce `nightly` builds, as we did for the `epinio-ui`. Basically every night we are building a `latest-next` image, this is used for the tests. We could use the same approach on the server, and test the upgrade from the latest release to the nightly.

Maybe the different registry (or namespace/version?) could be used as a quick fix.

**Comment by andreas-kupries** [comment]
The builds here are nightlies, afaik
so maybe have them tag their image as latest-next would be enough ?
