### ISSUE TITLE
Fix testing image push

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2599]
See: https://github.com/epinio/epinio/issues/2583#issuecomment-1729697684

Issue: https://github.com/epinio/epinio/actions/runs/6256478299/job/16987443577#step:13:277
It's in the installation tests, no idea why we are building and pushing the image

[epinio/acceptance/helpers/epinio/epinio.go](https://github.com/epinio/epinio/blob/102befe27c52dd7963d5ac2d3aad889d830086b8/acceptance/helpers/epinio/epinio.go#L64-L73)

Lines 64 to 73 in [102befe](https://github.com/epinio/epinio/commit/102befe27c52dd7963d5ac2d3aad889d830086b8)

```go
 By("Pushing server image to GHCR ...") 
 // PUBLIC_CLOUD is present 
 // Pushing new image into ghcr for the public cluster to pull from 
 out, err = proc.RunW("docker", "tag", local+":latest", remote) 
 Expect(err).NotTo(HaveOccurred(), out) 
 By(out) 
  
 out, err = proc.RunW("docker", "push", remote) 
 Expect(err).NotTo(HaveOccurred(), out) 
 By(out) 
```

introduced here: https://github.com/epinio/epinio/pull/1764

---

To fix this "quickly" we can try to push the image to a different registry or namespace.

**Comment by andreas-kupries** [comment]
Another quick fix could be to use a different label, i.e. `testpc` or similar instead of `latest`.

**Comment by andreas-kupries** [comment]
Note: The head of epinio has this changed quite a bit.
The modern code receives the tag to apply from the environment variable `EPINIO_CURRENT_TAG`.
This variable is set by the various workflows.

IOW
```
work@tagetarl:~/SUSE/dev/epinio> grep -rn EPINIO_CURRENT_TAG .
./.github/workflows/upgrade-bound.yml:92:          export EPINIO_CURRENT_TAG="$(git describe --tags)"
./.github/workflows/rke-upgrade.yml:165:          export EPINIO_CURRENT_TAG="$(git describe --tags)"
./.github/workflows/eks-upgrade.yml:172:          export EPINIO_CURRENT_TAG="$(git describe --tags)"
./.github/workflows/gke-upgrade.yml:174:          export EPINIO_CURRENT_TAG="$(git describe --tags)"
./.github/workflows/upgrade.yml:92:          export EPINIO_CURRENT_TAG="$(git describe --tags)"
./acceptance/helpers/epinio/epinio.go:55:	tag := os.Getenv("EPINIO_CURRENT_TAG")
```

The use of `git describe --tags` explains why things go bonkers, as that will overwrite images created by release with the same tag.

The original code actually used `latest`, which might not have been a problem.

I will change the flows now to prepend the prefix `test-` to the tags. This will also go into the cleanup workflow.
