### ISSUE TITLE
Pre-release image marked as `latest`

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2603]
When we do a release candidate it is marked as `latest`, but it shouldn't

The `latest` tag should point to the latest stable release:

![image](https://github.com/epinio/epinio/assets/1763949/8fdc9daa-a017-4d3a-a954-fc1edb778578)

This happens because the `goreleasear.yml` file that we are using for `-rcX` and stables is the same.
We should see if there is a way to not push `latest` for release candidates, or we need to split/separate the two workflows in two different config files.

**Comment by andreas-kupries** [comment]
https://goreleaser.com/customization/release/#github
```
  # If set to false, will NOT mark the release as "latest".
  # This prevents it from being shown at the top of the release list,
  # and from being returned when calling https://api.github.com/repos/OWNER/REPO/releases/latest.
  #
  # Available only for GitHub.
  #
  # Default is true.
  # Since: v1.20.
  make_latest: true
```
And also:
```
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
```


Lets try with `prerelease: auto` first.
If that is not good enough, split the flows and set `make_latest: false` in the RC flow.

Note: We are at go releaser v1.20.0, i.e. `mark_latest` should work, should we need it.
