### ISSUE TITLE
Epinio `v1.10.0` Rancher Marketplace update

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2612]
We need to bump the latest Epinio version in the Rancher Marketplace.

**Comment by andreas-kupries** [comment]
package and image bumps to perform

### CHANGES

| Package       | Version               | Image                         | Version                       |
|---            |---:                   |---                            |---:                           |
| epinio        | :arrow_right: 1.10.0  | epinio/epinio-server          | :arrow_right: v1.10.0         |
| dex           | :arrow_right: 0.15.2  | epinio/epinio-ui              | :arrow_right: v1.10.0-0.0.1   |
|               |                       | epinio/epinio-unpacker        | :arrow_right: v1.10.0         |
|               |                       | paketobuildpacks/builder      | :arrow_right: 0.2.443-full    |
|               |                       | ghcr.io/dexidp/dex            | :arrow_right: 2.37.0          |
|               |                       | skopeo/stable                 | :arrow_right: v1.13.2         |

### NEW

| Package       | Version       | Image                         | Version                       |
|---            |---:           |---                            |---:                           |
| epinio        | 1.10.0        | epinio/epinio-server          | v1.10.0                       |
| dex           | 0.15.2        | epinio/epinio-ui              | v1.10.0-0.0.1                 |
| minio         | 5.0.13        | epinio/epinio-unpacker        | v1.10.0                       |
| kubed         | 0.13.2        | paketobuildpacks/builder      | 0.2.443-full                  |
| s3gw          | 0.14.0        |                               |                               |
|               |               | quay.io/minio/mc              | RELEASE.2023-06-28T21-54-17Z  |
|               |               | quay.io/minio/minio           | RELEASE.2023-07-07T07-13-57Z  |
|               |               |                               |                               |
|               |               | ghcr.io/dexidp/dex            | 2.37.0                        |
|               |               |                               |                               |
|               |               | amazon/aws-cli                | 2.9.14                        |
|               |               | skopeo/stable                 | v1.13.2                       |
|               |               | rancher/kubectl               | 1.22.6                        |
|               |               | registry                      | 2.8.1                         |
|               |               | nginx                         | 1.23.2-alpine                 |

### OLD

| Package       | Version       | Image                         | Version                       |
|---            |---:           |---                            |---:                           |
| epinio        | 1.9.0         | epinio/epinio-server          | v1.9.0                        |
| dex           | 0.4.13        | epinio/epinio-ui              | v1.9.0-0.0.3                  |
| minio         | 5.0.13        | epinio/epinio-unpacker        | v1.9.0                        |
| kubed         | 0.13.2        | paketobuildpacks/builder      | 0.2.441-full                  |
| s3gw          | 0.14.0        |                               |                               |
|               |               | quay.io/minio/mc              | RELEASE.2023-06-28T21-54-17Z  |
|               |               | quay.io/minio/minio           | RELEASE.2023-07-07T07-13-57Z  |
|               |               |                               |                               |
|               |               | ghcr.io/dexidp/dex            | 2.36.0                        |
|               |               |                               |                               |
|               |               | amazon/aws-cli                | 2.9.14                        |
|               |               | skopeo/stable                 | v1.10.0                       |
|               |               | rancher/kubectl               | v1.22.6                       |
|               |               | registry                      | 2.8.1                         |
|               |               | nginx                         | 1.23.2-alpine                 |

**Comment by andreas-kupries** [comment]
Testing the charts PR has to wait on the image-mirror PR getting merged.

**Comment by andreas-kupries** [comment]
The image-mirror PR got merged today. Testing of the chart PR should now be possible.
