### ISSUE TITLE
Failing staging job with low network bandwidth

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2628]
# Issue
@enrichman  reported a failure in the staging job related in a situation of low network bandwidth.

# To reproduce
To mimic the low bandwidth issue we will use a CNI plugin, namely `bandwidth` to manipulate network bandwidth in a specific pod, in this case, in the staging one.

Steps:

1. Download CNI plugins at: https://github.com/containernetworking/plugins and extract them. For this example downloaded version was 1.3.0

```
curl -L -o cni.tgz https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
tar -xf cni.tgz
```

2. Create `cni` bin directory and move `bandwidth` plugin there (feel free either to add the rest or discard them):
```
sudo mkdir -p /opt/cni/bin
sudo mv bandwidth /opt/cni/bin
```

3. Install k3s, cert-manager and epinio. Run:

Initial set-up:
```
ETH_DEV=$(ip route | awk '/default via / { print $5 }')
export MY_IP=$(ip a s ${ETH_DEV} | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
export MY_HOSTNAME="${MY_IP}.nip.io"
export EPINIO_SYSTEM_DOMAIN="${MY_IP}.nip.io"
export DASHBOARD_VERSION=epinio-dev
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export HELM_VERSION=3.9.0
export K3S_VERSION=v1.27.6+k3s1
```

install-k3s
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${K3S_VERSION} sh -s - --write-kubeconfig-mode 644
## Wait for K3s to start
timeout 2m bash -c "until ! kubectl get pod -A 2>/dev/null | grep -Eq 'ContainerCreating|CrashLoopBackOff'; do sleep 1; done"
```

install-cert-manager
```
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm upgrade --install cert-manager --namespace cert-manager jetstack/cert-manager \
    --create-namespace \
    --set installCRDs=true \
    --set extraArgs[0]=--enable-certificate-owner-ref=true \
    --wait
```

install-epinio
```
helm repo add epinio https://epinio.github.io/helm-charts
kubectl rollout status deployment traefik -n kube-system --timeout=480s
helm upgrade --install epinio -n epinio --create-namespace epinio/epinio --set global.domain=${EPINIO_SYSTEM_DOMAIN}
kubectl rollout status deployment epinio-server -n epinio --timeout=480s
```

4. Now, for steps 5 and 6 the following annotations will be needed: (Ref: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/ingress-bandwidth: 1M
    kubernetes.io/egress-bandwidth: 1M
```

5. Within the Epinio repo go to `internal/api/v1/application/stage.go` add the `ActiveDeadlineSeconds` annotation to `180` seconds to ensure the failure this time:

```
Spec: batchv1.JobSpec{
    BackoffLimit: pointer.Int32(0),
    ActiveDeadlineSeconds: pointer.Int64(180),
```

6. Add the bandwidth annotations here:

```
Annotations: map[string]string{
    // Allow communication with the Registry even before the proxy is ready
    "config.linkerd.io/skip-outbound-ports": "443",
    models.EpinioCreatedByAnnotation:        app.Username,
    "kubernetes.io/ingress-bandwidth": "1M",
    "kubernetes.io/egress-bandwidth": "1M",
```

7. Still on Epinio repo, run after:
```
make 
make patch-epinio-deployment
```

8. Log in and push an application
```
epinio login -u admin https://epinio.$EPINIO_SYSTEM_DOMAIN
epinio push -n lowbandwidth-app-2-1m -p /home/mmartin24/suse-repos/epinio-end-to-end-tests/epinio/assets/sample-app
```

# Observed behavior:

The staging job fails promptly and silently.
```
kubectl logs -f -n epinio  epinio-server-8d7f58588-gwc4h                             

Epinio version: v1.10.0-15-g5a609f4b

listening on localhost on port 8030
2023/10/05 11:46:01 EpinioServer: "msg"="ERROR" "error"="Failed to stage" "requestId"="ccf16e47-3057-4d31-ba73-383678b5c2ab" "origin"="/api/v1/namespaces/workspace/staging/6a2dd1c4bb6f00db/complete" "error"="Failed to stage"
2023/10/05 11:46:01 EpinioServer: "msg"="Error" "error"="Failed to stage"
```
Note: thanks @thehejik for the help reproducing this.

---
Once done k3s can be removed by:
```
k3s-killall.sh  
k3s-uninstall.sh
```

**Comment by andreas-kupries** [comment]
Adding ` ActiveDeadlineSeconds: pointer.Int64(180),` was a forced abort. With low bandwith this is easily triggered.
Without it I see one explicit issue in E itself causing a timeout.
- E uses the `StagingComplete` endpoint to check on the progress of staging. The client's form of `Are we there yet?`.
- The server endpoint has a deadline of 10 minutes for that endpoint, and then times out.
- The client retries the check 10 times. This gives us an overall timeout of 100 minutes.
- This can be triggered by bandwidth around `0.5M`.
- However, the registry the image is saved to may have it own deadline to protect against overlong connections. As such may be a denial of service attack.

Such an abort from the registry looks like

> 🕞  [stage-workspace-lowban-b650cdd5504e1f4315af727328aae6d49825hhxv] buildpack       registry.epinio.svc.cluster.local:5000/apps/workspace-lowbandwidth-half:b7504efcc562932f - Patch "https://registry.epinio.svc.cluster.local:5000/v2/apps/workspace-lowbandwidth-half/blobs/uploads/0cd42eb7-a922-40fa-b8b4-0440b0160ad0?_state=9Ew0E_rAcVHhrI82_rR1fy9JT9UzMhFdk_qPLJRE8RJ7Ik5hbWUiOiJhcHBzL3dvcmtzcGFjZS1sb3diYW5kd2lkdGgtaGFsZiIsIlVVSUQiOiIwY2Q0MmViNy1hOTIyLTQwZmEtYjhiNC0wNDQwYjAxNjBhZDAiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMTAtMjdUMDk6MTI6MTAuNDM0NjQ2NDU0WiJ9": stream error: stream ID 9; INTERNAL_ERROR; received from peer 
🕞  [stage-workspace-lowban-b650cdd5504e1f4315af727328aae6d49825hhxv] buildpack ERROR: failed to export: failed to write image to the following tags: [registry.epinio.svc.cluster.local:5000/apps/workspace-lowbandwidth-half:b7504efcc562932f: Patch "https://registry.epinio.svc.cluster.local:5000/v2/apps/workspace-lowbandwidth-half/blobs/uploads/0cd42eb7-a922-40fa-b8b4-0440b0160ad0?_state=9Ew0E_rAcVHhrI82_rR1fy9JT9UzMhFdk_qPLJRE8RJ7Ik5hbWUiOiJhcHBzL3dvcmtzcGFjZS1sb3diYW5kd2lkdGgtaGFsZiIsIlVVSUQiOiIwY2Q0MmViNy1hOTIyLTQwZmEtYjhiNC0wNDQwYjAxNjBhZDAiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMTAtMjdUMDk6MTI6MTAuNDM0NjQ2NDU0WiJ9": stream error: stream ID 9; INTERNAL_ERROR; received from peer]

**Comment by andreas-kupries** [comment]
IMHO this can be closed with no further action.

**Comment by mmartin24** [comment]
As it turns out, the log failures were not the initially observed.
We tried playing a bit more adjusting bandwidth from 0.5 to 8Mb and width sample apps and go-app without success.
Therefore I'll close the issue as non-reproducible.
Leaving nonetheless the steps to deploy and adjust the `Bandwidth`plugin on this confluence page for later use: https://confluence.suse.com/display/Epinio/Pod+Network+manipulation+with+CNI+%27Bandwidth%27+plugin+in+Epinio+using+K3s

**Comment by mmartin24** [comment]
Adding one extra comment on the Golang app push mentioned [above](https://github.com/epinio/epinio/issues/2628#issuecomment-1785128602).
This was the error log obtained:
```
  [stage-workspace-goapp--23206f90d78759b2c909b42762219de8bf5b9l9s] buildpack ERROR: failed to export: failed to write image to the following tags: [registry.epinio.svc.cluster.local:5000/apps/workspace-goapp-githuburl-4m:8ea621f356cd47db: Patch "https://registry.epinio.svc.cluster.local:5000/v2/apps/workspace-goapp-githuburl-4m/blobs/uploads/9c3e6230-6b6a-4538-a899-f8e5016f3062?_state=iuHUEAxci5y2PGCnAOJMUOJBiQaNTCcwLGwE-9QKCUd7Ik5hbWUiOiJhcHBzL3dvcmtzcGFjZS1nb2FwcC1naXRodWJ1cmwtNG0iLCJVVUlEIjoiOWMzZTYyMzAtNmI2YS00NTM4LWE4OTktZjhlNTAxNmYzMDYyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIzLTEwLTMwVDExOjU5OjA2LjE0MTA2NzQzOFoifQ%3D%3D": http2: server sent GOAWAY and closed the connection; LastStreamID=19, ErrCode=NO_ERROR, debug=""] 
```
Looking at the `GOAWAY` error [here](https://stackoverflow.com/questions/45209168/http2-server-sent-goaway-and-closed-the-connection-laststreamid-1999) it seems a closed connection at some point occasioned by timeout, backend closed, etc.
