### ISSUE TITLE
Wordpress example not working with `BP_PHP_VERSION=8.0.x` and `paketobuildpacks/builder-jammy-full:0.3.290`

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2686]
# Issue
UI tests detected a problem when binding MySQL service to an app:

![Image](https://github.com/epinio/epinio/assets/37271841/ddc3c349-4b6a-484e-b3ec-7f3196fd2f6b)

This is also reproducible in CLI:
```
epinio service create mysql-dev mycustom-service
epinio push --name testapp-wordpress-80x --path /home/mmartin/suse/epinio-repos/example-wordpress -e BP_PHP_VERSION=8.0.x -e BP_PHP_SERVER=nginx -e BP_PHP_WEB_DIR=wordpress -e DB_HOST=x8e5ee833a0f2faebaf5c4171baca-mysql -e SERVICE_NAME=mycustom-service
sleep 2 # To avoid binding issues
epinio service bind mycustom-service testapp-wordpress-80x
```

Erro outputr:

```
 [stage-ns-wordpress-tes-9519204a1ca4beaac479298ecf45f328991cmc2v] buildpack failed to satisfy "php" dependency version constraint "8.0.x": no compatible versions on "io.buildpacks.stacks.jammy" stack. Supported versions are: [8.1.23, 8.1.24, 8.2.10, 8.2.11] 
```

If trying any of the versions suggested (`8.1.23`, `8.1.24`, `8.2.10`, `8.2.11`), then it seems it misses a component (ie with version `8.2.11`)

```
epinio push --name testapp-wordpress-8211 --path /home/mmartin/suse/epinio-repos/example-wordpress -e BP_PHP_VERSION=8.2.11 -e BP_PHP_SERVER=nginx -e BP_PHP_WEB_DIR=wordpress -e DB_HOST=x8e5ee833a0f2faebaf5c4171baca-mysql -e SERVICE_NAME=mycustom-service
sleep 2 # To avoid binding issues
epinio service bind mycustom-service testapp-wordpress-8211
```

Output
```
rtestapp-wordpress-821-7cbe10c9bfea5ffa81f1c74431347087c62zb859 2023/10/30 14:50:05 [error] 27#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'my_database.wp_options' doesn't exist in /workspace/source/app/wordpress/wp-includes/wp-db.php:2056
```

# Notes

Not sure if this may be related to the fact now we are using `paketobuildpacks/builder-jammy-full:0.3.290` as default  when I try with `paketobuildpacks/builder:0.2.443-full`  as it was [here](https://github.com/epinio/epinio/pull/2659/files#diff-b2c00d79ad17e059690b488444b832566cde058ceede7269fb388ca1222c24cdL43)  it works.

![Image](https://github.com/epinio/epinio/assets/37271841/41a09ef1-8cbc-4953-b29a-811f611f8478)

# Possible solutions:
- Change UI tests to point at old packet buildback and warn in docs
- Try to see if bumping the application may help. Pastin here some possible link to explore courtesy of Tomas: https://core.trac.wordpress.org/browser/tags/6.3.2/src
- Identifying exactly how to tackle the `Uncaught mysqli_sql_exception`

**Comment by thehejik** [comment]
Ref. ```https://github.com/docker-library/wordpress/discussions/677``` also includes patch for WP code.

**Comment by mmartin24** [comment]
> Ref. `https://github.com/docker-library/wordpress/discussions/677` also includes patch for WP code.
Thanks @thehejik . Your fix seems to have worked:

![image](https://github.com/epinio/epinio/assets/37271841/8dc2f727-8e84-4a9d-9509-5a57ca4e63b6)

**Comment by mmartin24** [comment]
Closing issue after merge and successful UI test [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6730558658/job/18294100107):
![image](https://github.com/epinio/epinio/assets/37271841/9c1772af-7fd8-4cfc-bc49-f65bab509b0d)
