### ISSUE TITLE
Restrict namespaces api to some namespaces

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2705]
Enhance auth roles so that user should able to delete `ns1` and `ns3` but not `ns2`

**Comment by enrichman** [comment]
@mmartin24 I've put this in review because looking at the code it was already implemented. And doing a check it's actually working as expected.

I've tried to create two namespaces from two different users (`epinio` and `epinio@epinio.io), and they were not able to delete the roles where they didn't have visibility. Putting this in review for one more check.

**Comment by mmartin24** [comment]
> @mmartin24 I've put this in review because looking at the code it was already implemented. And doing a check it's actually working as expected.
> 
> I've tried to create two namespaces from two different users (`epinio` and `[epinio@epinio.io](mailto:epinio@epinio.io)), and they were not able to delete the roles where they didn't have visibility. Putting this in review for one more check.

Thanks @enrichman for the note. I am thinking perhaps there was a before/after the namespace_read option became default for all users.
Not sure though if this is working as expected or if perhaps I am missing something.  I tried to create a namespace `ns-4` with a user that has `blank` role on a particular namespace (`ns-2`) and I was able:

![image](https://github.com/epinio/epinio/assets/37271841/2a0bac98-9390-4620-aaa5-3160f12dc106)

Shouldn't I have been prevented from doing this?

**Comment by mmartin24** [comment]
Ok commented offline.
Checked that epinio user does not "see" other users namespaces and a second user, namely epinio@epinio.io does not "see" either the namespaces from "epinio" one. The case commented above is a corner case and we can wait if a customer ever sees a problem in the future. Closing issue
