### ISSUE TITLE
Panic during OIDC login

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2713]
Related to #2704 

While logging with OIDC we had a panic for non-existing users.

**Comment by mmartin24** [comment]
Checked and working now in `v1.11.0-rc1-7-ga9f33edb` vs failing in `v.1.11.0-rc1`

![image](https://github.com/epinio/epinio/assets/37271841/9167c178-e2b9-494f-90d2-70acff420b8c)

**Comment by mmartin24** [comment]
Rechecked in `v1.11.0-rc2` and working


![image](https://github.com/epinio/epinio/assets/37271841/c22026ef-ec8e-4388-9778-d473b9a45c85)
