### ISSUE TITLE
Epinio Server Overwhelming Kubernetes API

### ISSUE THREAD

**Issue by Oziel-Silva** [epinio/epinio#2748]
**Describe the bug**
When we execute some of Epinio's commands, such as `epinio service list`, the CLI takes too much time to respond.
On the Kubernetes side, the epinio-server-pod is logging unexpected API calls.

PS: A possible cause can be that the Kubernetes-client inside the pod, is making these k8s-API calls. 

**To Reproduce**

Epinio installed on GKE.

do:
`epinio service list`

**Expected behavior**
Get the command response as soon as possible.

**Logs**
there are dozens and dozens of them
`│ I0110 21:41:43.505456       1 request.go:696] Waited for 6.179313475s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/dlp.cnrm.cloud.google.c │
│ I0110 21:41:53.514965       1 request.go:696] Waited for 7.190299622s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/gcp.example.com/v1alpha │
│ I0110 21:42:03.531495       1 request.go:696] Waited for 8.173326637s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/snapshot.storage.k8s.io │
│ I0110 21:42:14.610042       1 request.go:696] Waited for 1.186562201s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/kms.cnrm.cloud.google.c │
│ I0110 21:42:24.625912       1 request.go:696] Waited for 2.170262859s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/spanner.cnrm.cloud.goog │
│ I0110 21:42:34.630628       1 request.go:696] Waited for 3.184122218s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/resourcemanager.cnrm.cl │
│ I0110 21:42:44.643675       1 request.go:696] Waited for 4.180912814s due to client-side throttling, not priority and fairness, request: GET:https://10.44.0.1:443/apis/acme.cert-manager.io/v1 │
`

**Comment by enrichman** [comment]
Hi @Oziel-Silva , we had a similar issue with our tests. To mitigate the problem you can try to add the `KUBE_API_QPS` and `KUBE_API_BURST` env vars increasing the default value. We use 50 and 100 in our tests, but your mileage may vary.

Ref: https://github.com/epinio/epinio/pull/2373
