### ISSUE TITLE
[maintainence] update dockerhub auth for repo

### ISSUE THREAD

**Issue by vtrenton** [epinio/epinio#2788]
looks like the dockerhub creds have not been added:

```
Run docker/login-action@v2
  with:
    ecr: auto
    logout: true
  env:
    SETUP_GO_VERSION: 1.[2](https://github.com/epinio/epinio/actions/runs/12105191461/job/34549759227?pr=2780#step:4:2)0.4
Error: Username and password required
```

we need to get these updated.

**Comment by krumware** [comment]
We need to update:
- Publication and credentials to the new Epinio docker organization
- Credentials to Splatform
- Credentials to GHCR (maybe)

**Comment by vtrenton** [comment]
Dockerhub creds are up to date.
