### ISSUE TITLE
Remove dependency to openssl

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#298]
In order to make the tekton pods trust our registry CA and push the generated image there, we need to place the ca in a directory inside the pod using a very specific name. The name of the file has to be similar to whatever this command generates:

```
openssl x509 -hash -noout
```
more here: https://github.com/epinio/epinio/blob/8fd8ba151c814670289831aa7c94c991a2001e6d/helpers/exec.go#L151-L157

While migrating from bash scripts to go code, we couldn't find an way to produce that SHA in go so we [shelled out to `openssl`](https://github.com/epinio/epinio/blob/8fd8ba151c814670289831aa7c94c991a2001e6d/helpers/exec.go#L164). This is a dependency that seems unreasonable and we should try to get rid of it.

I found a (random) link which explains a bit what's going on: https://docs.infor.com/ln/10.5/it-it/lnolh/help/tt/onlinemanual/https_soap_generate_hash.html

**Comment by jimmykarily** [comment]
https://github.com/tektoncd/pipeline/issues/1171

**Comment by manno** [comment]
I tried this, but it didn't work immediately

**Comment by andreas-kupries** [comment]
Notes on the branch above 

- Intial thoughts after going over the changes:
    > I note that while a configMap `config-registry-cert` holding the cert is made I do not see a place which refers this map :interrobang: Or is that an automatic thing ? ...Ok, I found the original config map the new one is based, on in `pipeline-v0.19.0.yaml` ... and now I am wondering if the new definition actually replaces the original. I mean, AFAICT the branch now has two config maps with the same name, the original in the `pipeline-*.yaml`, and the new in `staging.yaml`. Which of these will be used ? Above mentions that the change "didn't work immediately". What was expected and what was seen instead ? Could it simply be necessary to remove the definition from pipeline-*.yaml ?

- Trying to deploy I see something more concrete:
    > error: error parsing /tmp/epinio033443770: error converting YAML to JSON: yaml: line 14: could not find expected ':'

  That looks to be an issue with the temp file after the cert is interpolated into it, in `applyTektonStaging`. Some kind of quiting issue, I suspect.

**Comment by andreas-kupries** [comment]
Yes. Placing the pem into `"..."` quoting makes this issue go away.

Next issue:
  - The config map is specified to be in namespace `tekton-pipelines`.
  - The command uses `-n epinio-workloads`.
  - :boom: `error: the namespace from the provided object "tekton-pipelines" does not match the namespace "epinio-workloads". You must pass '--namespace=tekton-pipelines' to perform this operation`

I suspect that the config map has to be applied separately. That of course means, that a separate file is required as well.

**Comment by andreas-kupries** [comment]
Running the :cat2: shows errors around registry use and certs:
```
[STAGE] step-create ERROR: failed to get previous image: connect to repo store 'registry.epinio-registry/apps/apps-547213978': Get "https://registry.epinio-registry/v2/": x509: certificate signed by unknown authority 
```

Checking the cert in registry and tekton config map showed differences wrt lines. My `"..."` is likely at fault. Redoing that for proper multi-line yaml makes the cert differences go away. The error above however is still present.

**Comment by andreas-kupries** [comment]
Reading the https://tekton.dev/docs/pipelines/install/#configuring-self-signed-cert-for-private-registry again, it talks about a self-signed cert which gores into the config map.

Looking into the code I am basing the experiments on I see that it places the __CA__ cert into the config map.
Not the cert itself.
That does not feel correct.

**Comment by andreas-kupries** [comment]
Also relevant: https://github.com/tektoncd/pipeline/pull/2787 looks to be the CR which added the above self-signed cert support.

**Comment by andreas-kupries** [comment]
@jimmykarily @manno @thardeck 

Enclosed result of a deeper look into the configurations of registry and tekton.
This is the current working configuration, using and depending on `openssl`.
This is not Mario's branch attempting to get rid of `openssl`.
I wanted to understand the working setup first before trying more changes.
In the end I got a number of questions instead

# Registry Certs, Creation, Use

The `container-registry` chart has/creates 3 cert related (quark) secrets

|Name			|Kind	|Notes			|Notes II			|
|---			|---	|---			|---   				|
|`registry-tls`		|Plain	|What CA does this use?	|__k3s-server-ca__! Cluster CA	|
|`registry-tls-self-ca`	|CA	|Self-signed?		|__Self-signed__! `registryCA`	|
|`registry-tls-self`	|Plain	|CA is previous		|	      			|

Question:

  - __Why__ do we have 2 plain secrets ?

    One signed by cluster CA (as noted by the README)

    The other signed by a custom CA, which itself is self-signed

Namespaces:

  - `epinio-registry`.
  - `epinio-workloads` - Tekton Staging ?

Volumes:

|Name		|Registry Mount		|Nginx Mount		|
|---		|---	  		|---			|
|`tls`		|/etc/registry/certs	|/etc/nginx/certs	|
|`tls-self`	|			|/etc/nginx/certs-self	|

Services:

  - cluster-ip: `registry`
  - nodeport: `registry-node`

Same ports both

  - 5000: `registry`
  - 443:  `registry-tls`
  - 444:  `registry-tls-self`	?

__What__ is the `tls-self` port 444 for ?

ATTENTION:

  - Port 443 is served by the custom CA signed `tls-self` secret
  - Port 444 is served by the cluster signed `tls` secret

This is per config map `registry-nginx-config`, mounted as `/etc/nginx/conf.d/default.conf`.

Thus __why__ are the nginx cert assignments swapped ?

The `tls-self` cert serves the `tls` port, and vice versa.

# Tekton

`staging.yaml`

Volumes:

|Name			|Secret			|Part	|Mount					|
|---			|---			|---	|---					|
|registry-certs		|registry-tls		|n/a	|n/a					|
|registry-certs-self	|registry-tls-self	|ca	|/etc/ssl/cert.pem			|
|registry-certs-self2	|registry-tls-self	|ca	|/etc/ssl/certs/{{CA_SELF_HASHED_NAME}}	|

Why is the `tls-self` CA cert (custom CA) mounted in two locations ?

Why is the `tls-self` cert not mounted ?

Why do we have a volume for the `tls` cert and do not mount it ?

**Comment by andreas-kupries** [comment]
Notes from today's experiments:

  1. Changing the `tls-self` cert from being signed by a custom CA (`tls-self-ca`) to cluster-signed breaks `ep push`, i.e. the pulling of the (app?) image from the registry, by tekton, run into the `unknown authority error`. I.e. the kube cluster CA is not known/trusted in the pods.
  2. The volume/mount of the `tls-self` CA cert as `/etc/ssl/cert.pem` is superfluous. Removing it does not break anything.
  3. Trying to mount the `tls-self` CA cert into `/usr/local/share/ca-certificates` and then using `update-ca-certificates` (as part of the step command) to update the `/etc/ssl/certs` runs into permission issues. The destination is root-owned, and the step command is run by the non-root user `cnb`. That user is not a sudoer either, so `sudo` is out as well. Re-chowning the destination is out also, as that is run as `cnb` too, and we do not have `sudo`.

**Comment by andreas-kupries** [comment]
More notes:

  4. Tried to create (not use) a self-signed cert via quarkssecrets. Failed. We can apparently create a CA cert which is self-signed, but not a regular cert. Of course, I am not well versed in QS, so I likely did something wrong in the setup. @manno, can you confirm the limitation or provide counter config ?

      Basic idea was to configure tekton with a self-signed registry cert instead of the CA cert for the registry cert.

  5. I am not sure where the cert from the `config-registry-cert` config map ends up. I looked into the `step-create` container of the `...-stage-...` pod (where it tried to pull from the registry) and certainly found no changes in the `/etc/ssl` setup it has, compared to a pod without that CM doing anything. Maybe it is passed in somewhere more explicitly ? (cli argument of something or other ?)

**Comment by andreas-kupries** [comment]
Looking again into go code for doing the `openssl -hash`.
Found https://github.com/spacemonkeygo/openssl
Asked https://github.com/spacemonkeygo/openssl/issues/146
Related: https://stackoverflow.com/questions/30059107/get-x509-certificate-hash-with-openssl-library
Seems that `-hash` is the (new form of the) subject hash.

The interesting part of the above is that it seems to be a go wrapper to the openssl.so (shared lib).
Apache v2 license.

https://stackoverflow.com/questions/19237167/the-new-subject-hash-openssl-algorithm-differs

My SO search is https://stackoverflow.com/search?q=%5Bx509%5D+hash

**Comment by andreas-kupries** [comment]
Vlad mentions: https://github.com/paketo-buildpacks/ca-certificates

A buildpack which can add CA certs.

**Comment by andreas-kupries** [comment]
Apparently it is possible to have multiple buildpacks apply to an app during staging.
As we use the `full` builder image we might have this pack already, and need only config for it.
Vlad cautions that at the time he looked it was not part of that build.
To verify.

Note: With the pack cert config moves out of tekton deployment somewhere into app push.

Currently suspecting that we have to add some kind of manifest file into the pushed sources, for the pack to detect and act on.
Vlad agrees

> that would be my starting point too
try to write some config  as part of the push to gitea

**Comment by jimmykarily** [comment]
I see this when I'm staging the sample app:

```
step-create Adding layer 'paketo-buildpacks/ca-certificates:helper'                                                                                                                                                                        
```
I guess that means we already have that buildpack.

On the other hand, the buildpack has to generate that hash in order to install the needed CAs. I think the method that does that is this:

https://github.com/paketo-buildpacks/ca-certificates/blob/3fcb74748ede6221d0392f8258ef2fb1393a79b7/cacerts/certs.go#L99-L114

We can simply use the same code to generate the hash and avoid hijacking the staging process altogether.
