### ISSUE TITLE
Binding Service on push

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#303]
The UX of pushing an app, waiting for it to fail, then binding the service is really painful. It'd be nice if there was a way to push with a binding as a single step.

**Comment by jimmykarily** [comment]
An alternative is to create the application without really running it. E.g.

```bash
$ epinio push sample -i 0 # creates the deployment but with 0 instances
$ epinio services create-custom myservice user andrew
$ epinio service bind myservice sample
$ epinio app update sample -i 1 # Scales up the deployment 1 instance
```

If I'm not mistaken that's how you would do it in cloudfoundry too (with the `no-start` parameter)

**Comment by andreas-kupries** [comment]
No. In cloudfoundry `no-start` is distinctly separate from the `number of instances`. You can configure an app for 10 instances and still use no-start to prevent it from being started at all. Start/stop in CF is very much separate from scaling up/down.

**Comment by andreas-kupries** [comment]
See branch https://github.com/epinio/epinio/tree/ak-issue-303-push-with-services for stash of the current incomplete work.
Will not compile!! (See servicebindings.go changes for why. Partial, stopped mid-change)
