### ISSUE TITLE
Signing app images built by buildpacks

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#309]
[This blog](https://raesene.github.io/blog/2021/03/21/Trying-out-cosign) explains how to sign your images with [cosign](https://github.com/sigstore/cosign).

**Comment by agracey** [comment]
We should also look at the "keyless" signing that sigstore is working on. I don't know if that's something we should actually tie into in the first security milestone, but it is likely good to be aware of.

**Comment by agracey** [comment]
It looks like the buildpack task should work with Tekton Chains: https://github.com/buildpacks/tekton-integration/pull/34

**Comment by agracey** [comment]
This will be addressed upstream: https://github.com/buildpacks/rfcs/issues/192 

Will leave open to track but pulling off milestone. (Should we have a label for "upstream work"?)
