### ISSUE TITLE
Passwords and other secrets in server logs

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#314]
The last merge (PR #282) extended the server side logging with display of request bodies.

While this is good for debugging issues in the communication between client and server it also means that the log may contain sensitive data like credentials or some such. See for example the user-specified data when creating a custom service.

On the other hand, the default server verbosity is low enough to not log anything.

On the third hand, one of the first things we may do when suspecting a communication issue will be to ask the user to bump the server verbosity (by patching the server deployment / pod) so that we can get detailed logs.

This needs at least a note in the documentation. Best placed wherever we document how to crank up server verbosity.

Maybe further separate the logging of request bodies from general logging.
I.e. control body logging with either a separate option, or place at an even higher verbosity level.

**Comment by enrichman** [comment]
Probably outdated. Closing it.
