### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#321]
Now that we have an API, we need to document it so others can consume it.

- [x] research on a good way to document APIs
- [x] start with API documentation
- [x] visible in the online documentation (done here: https://github.com/epinio/docs/pull/23)

depends #818 #806

**Comment by kkaempf** [comment]
See https://github.com/epinio/epinio/pull/272

**Comment by agracey** [comment]
#250 as well

**Comment by jimmykarily** [comment]
done
