### ISSUE TITLE
Drop container registry tarball

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#331]
The tarball for the container registry chart is generated by `helm package`, from the `assets/container-registry` hierarchy.
There is no need to have the tarball be a part of the repository. The assets are enough.

Remove the tarball, and modify the Makefile to generate it as part of the `embed_files` target.
IOW make the `update_registry` target a dependency of `embed_files`.

**Comment by andreas-kupries** [comment]
Of course, if there is good reason to keep the tarball, add this reason to the developer documentation, to preemptively answer the question.

**Comment by jimmykarily** [comment]
Done here: https://github.com/epinio/epinio/pull/413
