### ISSUE TITLE
Server/Dashboard: Error showing "About" (/info) page

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#332]
Installed Epinio to RKE2 cluster with `./epinio-0.0.11 install --system-domain epinio.paas.suse.de`.
Accessing "http://epinio.epinio.paas.suse.de/" works, showing the Epinio dashboard (https will not work).

If I click on "About" (-> http://epinio.epinio.paas.suse.de/info), I'll get the following error message:

`html/template:page_template:113:15: no such template "new-org-modal"`

and the server logs:

`2021/04/27 08:21:33 http: superfluous response.WriteHeader call from github.com/epinio/epinio/internal/web.handleError (applications_controller.go:163)`

This hould not happen, and the info page should be shown.

**Comment by svollath** [comment]
Still happens with Epinio-0.0.12: "html/template:page_template:113:15: no such template "new-org-modal""

**Comment by andreas-kupries** [comment]
```
> grep -rn new-org-modal .
./assets/embedded-web-files/views/modals.html:1:[[define "new-org-modal"]]
./assets/embedded-web-files/views/main_layout.html:113:    [[template "new-org-modal"]]
```

The line number in the error message matches the location in the `main_layout.html` file where the template is invoked.
I suspect that `modals.html` is somehow not present/used/invoked, leaving the the template it defines as not known.

**Comment by andreas-kupries** [comment]
The template `icon-plus-rectangle` defined in`icons.html` otoh does not cause an error. Lets see how that file is made use of.

**Comment by andreas-kupries** [comment]
```
./internal/web/info_controller.go:37:	Render([]string{"main_layout", "icons", "info"}, w, r, data)
./internal/web/applications_controller.go:109:	Render([]string{"main_layout", "icons", "modals", "applications_index"}, w, r, data)
```

looks promising.

**Comment by andreas-kupries** [comment]
Certes.
