### ISSUE TITLE
Application abstraction

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#347]
Because:

- You can create apps that are not started (like in cf), bind services to them and then start them (fixing: #303)
- You can pull codes from different locations (e.g. gitea, s3, minio, github, other) and you can store this in for on the application abstraction
- You can store the epinio deployment information on it (e.g. which "revision" or "deployment id" is currently being run). We can rollback based on this info.
- You can run expensive operations like tarball extraction in a queue in the background (see also: https://github.com/epinio/epinio/pull/338/files#r625631405).

## Acceptance Criteria

1. There is a Custom Resource that represents an Epinio application
1. Every other resource belonging to the application (Deployment/Ingress/Service/Secret) has an owner reference to the CR.
1. All resources share the same label(s) identifying the application
1. Any metadata (e.g. stageID of the running app, commit id of the running app etc) are stored on the CR.
1. When the CR is deleted, so do all the other resources (owner relationship).
1. Epinio commands that list or show applications use this new CRD (instead of Deployments that they do now).
1. `epinio push` should create a CR for the app
1. [can be moved to a new issue] A new command `epinio app create` exists that simply creates the application without doing staging or pushing of the code or anything else. Just creates the CR.

## Stories

We discussed this more and created the following stories (TBD): #508  #509 #510 #511 #512 #513 #514 #515 #516 

## (Likely) Related Bugs

#536

**Comment by manno** [comment]
We have two(three) different kinds of data for an application:

* the **application data** itself, which is just files and directories
* **application meta data**, like the name and organzitation it belongs to (user provided)
  * **deployment info**, we generate, the webhook, the k8s resources in the `.kube` folder (generated)
 
### Idea 1 - blob store + crd

We can split the application data (files) from the meta data and store them separately.
We create a CRD that holds the meta data and references the application data.
When deploying, we generate the tekton staging inputs and finally the k8s resources (deployment) from that CRD.

It's enough to support one source (git?) initially.

**Comment by jimmykarily** [comment]
#303 could also be fixed by implementing an "instances" parameter on `cf push`. E.g. `epinio push sample -i 0` (this should create a deployment with 0 instances. After connecting the services the user could do something ilke this to start it: `epinio app update sample -i 1`

**Comment by jimmykarily** [comment]
This may also be the solution to #375 . For some applications, it's necessary that the environment variables are set before the app can be successfully staged. We would need to store the environment variables somewhere, before a Deployment even exists.

**Comment by jimmykarily** [comment]
We decided to do a spike on App CRD (https://github.com/kubernetes-sigs/application). We will use it as the single object identifying an application in Epinio. We will also use the controller to specify ownership relationships between the App crd and the various other resources so we can simplify app deletion.

![image](https://user-images.githubusercontent.com/2794419/121159926-4e377f00-c854-11eb-928a-952fa58fe85e.png)

The env variables (staging and runtime)  will simply be secrets  "attached" to the Application.

**Comment by manno** [comment]
We discussed splitting this into more stories

* AppCRD as single source of truth (in progress)
* Adding OwnerRefs to the AppCRD
* Adding `epinio app create` CLI subcommand

**Comment by jimmykarily** [comment]
We split this in various stories (see description). Those stories will be added to their respective milestones. Closing this one.
