### ISSUE TITLE
Epinio API has Authentication

### ISSUE THREAD

**Issue by manno** [epinio/epinio#350]
Instead of implementing auth in the API, we put the API behind traefik and use a [traefik middleware](https://doc.traefik.io/traefik/middlewares/basicauth/) to only allow authenticated connections.

The CLI knows how to authenticate. 
We support basic auth first, storing the CLI's user and password in the shell environment (viper).

**Comment by andreas-kupries** [comment]
#### The cli knows how to authenticate

  - Environment variables.
      - EPINIO_USER
      - EPINIO_PASSWORD
  - cli uses `viper` to access them.
  - cli internal `curl` function is extended to pull the credentials out of the config and apply to the request.

**Comment by andreas-kupries** [comment]
Hah! I tried the last from the v1.7 #authentication link in the previous commit, i.e. added suitably changed annotations to the api ingress.

Traefik log now contains

```
{"level":"error","msg":"Failed to retrieve auth configuration for ingress epinio/epinio: failed to load auth credentials: secret \"epinio\"/\"epinio-api-auth-secret\" not found","time":"2021-05-11T09:33:07Z"}
```

That is correct, I did not apply the secret yet.
Yet its presence shows me that traefik saw and processed the annotations.
That is a first.
The error goes away with the secret added to the cluster.

And running `ep org list`:

````
work@tagetarl:~/SUSE/dev/epinio> ep org list

🚢 Listing organizations
error listing orgs: Unauthorized: 401 Unauthorized
```

That is correct as well. The cli does not provide user/pass yet.

Ok.

:heavy_check_mark: first part. Traefik is configured for basic auth, and applies it properly

Further :tada: no need for all the middleware CRD and resources. Just the annotations and the secret, everything else traefik does for us.

Next:
  - Modify the API functions to provide the credentials.
  - Configure and deploy secret as part of the install.

**Comment by andreas-kupries** [comment]
Use `--k3s-server-arg --disable --k3s-server-arg traefik` to start a k3s/k3d without traefik.
Each use of `--k3s-server-arg` provides a single additional argument to the `k3s server` command.
With the above the server sees `--disable traefik`.
See https://rancher.com/docs/k3s/latest/en/networking/
