### ISSUE TITLE
Pushing an app using a directory path no longer works

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#353]
Doing a `cf push sample assets/sample-app` no longer works:

```
~/workspace/epinio (main)*$ ./dist/epinio-linux-amd64 push --verbosity 1 sample assets/sample-app/
W0505 06:04:52.502202    6064 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0505 06:04:52.507256    6064 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0505 06:04:52.523119    6064 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
🚢 About to push an application with given name and sources into the specified organization
Name: sample
Sources: assets/sample-app/
Organization: workspace
⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)
Compressing application code ...
error pushing app to server: can't create archive: walking buildpack.yml: buildpack.yml: stat: stat buildpack.yml: no such file or directory
```

the reason must be that the `f.Name()` method here:
https://github.com/epinio/epinio/blob/main/internal/cli/clients/client.go#L881
returns the base path for the file, skipping the directory.

Doing a push from within the app directory still works.
We need to make sure the files are read from the app directory when one is provided. Still we may want to keep the file paths "flat" inside the tarball. A quick look in the archiver package code shows there is a function `NameInArchive` which could be useful.

## Acceptance Criteria

- Bug is fixed
- There is a test for this

**Comment by andreas-kupries** [comment]
>  Still we may want to keep the file paths "flat" inside the tarball

Not sure what you mean by flat ? Reducing the directory hierarchy of the application to single directory with all files ?

I would expect that to break applications. If the sources have some kind of structure I would expect that the sources are matched to that structure and that execution will fail if we re-arrange things underneath. 

Then there is the possibility of a more structured app having files with the same name in different branches of its directory structure. Flattening that and you lose one of the files. Another breakage.

I strongly recommend that the tarball keeps the directory structure of the sources.

As a side note, this means that we should get us a sample application which does have a (much) more complex directory structure than what we currently have with `assets/sample-app`.

**Comment by andreas-kupries** [comment]
Pulling back to continue work. Have to rethink assembly (paths in the tarball - absolute, relative - how does that look in the gitea repo)

**Comment by andreas-kupries** [comment]
Check complete, is :heavy_check_mark: as is. Back to done.
