### ISSUE TITLE
Handle first and followup pushes the same way - wait for the app to be up[dated]

### ISSUE THREAD

**Issue by thardeck** [epinio/epinio#357]
As the issue #262 demonstrated the user experience is different when an app is pushed for the first time in contrast to when it is updated later.

At the moment `epinio app push` does wait until the app is online when pushed for the first time, but when pushed again it directly exits so the user might expect the app to be updated while it is not - for quite some time.

So we should handle both cases the same way.

**Comment by jimmykarily** [comment]
Relevant: #246
