### ISSUE TITLE
Application logs endpoint and command

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#367]
The only time we show logs are during staging. There is no way for the user to read the application logs in the command line.

It's very common for developers to want to look at they application's logs to debug an issue or generally see what's going on.

## Acceptance Criteria

- There should be an endpoint in the API that streams application logs from all the application instances (pods).
- There should be a command to read the logs of the application. E.g. `epinio app logs sample`
- There should be an optional flag to stream the staging logs 
  e.g. `epinio app logs sample --staging`
- The logs from the various instances/pods should be tagged with the name of the pod or some unique identifier (e.g. a prefix: `[uuid_here] Listening on port 8080`)

**Comment by agracey** [comment]
If we are ok adding AGPL components, Loki has a pretty decent websocket hook for streaming logs

**Comment by jeff-hobbs** [comment]
While AGPL components are compatible with the direct project, they might cause friction with a wider audience. Let's make sure to explore other possible solutions first.

**Comment by jimmykarily** [comment]
Loki or some other similar tool will be needed when we want to allow the user to forward logs to some other service or if we want to host such a service (e.g. Loki) in the cluster itself.
Right now I was mostly thinking something equivalent of this command, implemented in go:

```
kubectl logs -f --selector=app.kubernetes.io/instance=gitea -n gitea
```

we already have proper labels on the application pods (also the staging ones), which should allow us to filter the right pods. There is also code that does this for staging logs: https://github.com/epinio/epinio/blob/7a6b60e56b3abf345b5446822db7fbb860830b5e/helpers/kubernetes/tailer/setup.go

should be easy to re-use it for applications.
