### ISSUE TITLE
Delete apps in an org parallelly

### ISSUE THREAD

**Issue by rohitsakala** [epinio/epinio#370]
Ex - Suppose if there are 1000 apps, then deletion of apps in an org takes some time. We need to always keep in mind scalability and write the code.

**Comment by Raullllll** [comment]
Hello! I find epinio very interesting and I'd like to contribute. Can I submit a pull request for this issue?

**Comment by kkaempf** [comment]
> Hello! I find epinio very interesting and I'd like to contribute. Can I submit a pull request for this issue?

Yes, please go ahead and thanks for your help !
