### ISSUE TITLE
Epinio documentation

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#377]
Before we call Epinio [SLC](https://medium.com/@nimay/shifting-prototyping-mindsets-from-mvp-to-slc-eab5bc42b6b2) we need documentation that is:
- up-to-date
- usable (searchable?)
- just enough (not necessarily diving into the internals of Epinio but enough for our users to use all Epinio features).

We can have documentation in any format that satisfies the above but a separate site might be the only option for "usable" if we want to support searching.

**Comment by kkaempf** [comment]
Focus on correctness and completeness for the initial open-source release. Leave extras (like searching) for the 'beta' release.

**Comment by jimmykarily** [comment]
That makes README.md and `/docs/*.md` files a viable solution.

**Comment by jimmykarily** [comment]
Note: document this: https://github.com/epinio/epinio/issues/380

**Comment by rohitsakala** [comment]
Action Items

- [ ]  Update README.md
- [ ] Update /docs/*.md
