### ISSUE TITLE
Tekton dashboard should be either not accessible or password protected

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#378]
If people are deploying Epinio in production, we should not expose more services than we need to the public.

The Tekton dashboard is accessible to anybody without a password (Unless #376 changes that).

If we decide we want the dashboard to be available, we should make sure it's password protected and served over tls.

If we don't need it, we should not deploy it at all.

**Comment by andreas-kupries** [comment]
>(Unless #376 changes that).

It doesn't. Focus of 376 was the API ingress only.

**Comment by andreas-kupries** [comment]
The tekton dashboard looks to be a viewer for the tekton resources in the system, mainly pipelines and tasks, and their runs.

I do not see this as something the user needs access to.

It is a nice way of looking at the tekton things when debugging an issue with tekton.
That said, all the information shown is likely also accessible via regular `kubectl` commands.
If not as pretty.

Personal verdict: Should not be exposed.

@jimmykarily @thardeck @manno ^ Your opinions ?

**Comment by jimmykarily** [comment]
I think we should not deploy the dashboard at all. I agree, all the needed information is available via `kubectl`.
