### ISSUE TITLE
Support Multiple Ingresses When Staging

### ISSUE THREAD

**Issue by manno** [epinio/epinio#384]
The user has [multiple Ingress Controllers](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#using-multiple-ingress-controllers) in their cluster and wants Epinio not to use the default Ingress class.

Some of these Ingresses might use public IPs, or have a higher cost.

The user can specify their [Ingress classes](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) for
* Epinio services, when installing Epinio
* each workload, when pushing

The user should also be able to specify an existing ClusterIssuer, so they can bring their own certs.

**Comment by jimmykarily** [comment]
Custom cluster issuers are also mentioned here: https://github.com/epinio/epinio/issues/63

**Comment by manno** [comment]
Also: https://github.com/epinio/epinio/issues/522

**Comment by manno** [comment]
closed in favor of #496
