### ISSUE TITLE
Don't use app name in staging pod names

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#392]
This is a regression of #322 . We introduced the same bug here: https://github.com/epinio/epinio/blob/main/internal/api/v1/stage.go#L120 

When the app name is used together with the uid for a pod name, it limits the available characters by the number of characters in the uid. We have labels that allow us to filter the staging pods of the app, the pod doesn't need to have the app name in it.

**Comment by jimmykarily** [comment]
We should write a test to make sure we don't introduce this again in the future. The test should deploy an app with a name having the maximum number of characters allowed for a pod name and it should succeed.

**Comment by andreas-kupries** [comment]
What is the maximum number allowed ?

**Comment by jimmykarily** [comment]
> What is the maximum number allowed ?

https://github.com/epinio/epinio/pull/397#issuecomment-842140634
