### ISSUE TITLE
Service selector is overlybroad

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#395]
It looks like the service description also points at the staging pods as well. I don't know if this would cause any issue but it might be worth refining the selector a bit

![image](https://user-images.githubusercontent.com/442274/118335283-2ad31b80-b4c4-11eb-91c3-d4e94e1d12b0.png)

**Comment by andreas-kupries** [comment]
What version of epinio is the bug for ?

I am asking because recent changes to the pipelines and staging may have made this moot.
See https://github.com/epinio/epinio/blob/main/internal/api/v1/stage.go#L125

**Comment by andreas-kupries** [comment]
Ok. Maybe not. This looks to be an app service, and the selector is

```
  selector:
    app.kubernetes.io/name: <appname>
```

and that label does indeed exist on the staging pods (clone, stage, run).

A different is in the component label. The app itself is labeled with `app.kubernetes.io/component: application`.
Staging pods have `app.kubernetes.io/component: staging` instead.
