### ISSUE TITLE
Fast uninstall completes while `service-catalog` namespace still exists

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#412]
Confirmed in a second run of the new fast uninstall (See #409 ) that `epinio uninstall` returns while the namespace `service-catalog` is still present. IOW a wee bit too quickly, should have waited for it.

The namespaces `minibroker` and `google-service-broker` are ok even without explicit waiting, they terminate very quickly, and early enough.

**Comment by jimmykarily** [comment]
I think we shouldn't rely on anything being fast. We should probably add code to wait for namespaces to be gone in every deployment.
