### ISSUE TITLE
Enable rotation of passwords

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#419]
See #61 for the original ticket.

While this ticket was about generating and rotating passwords only `generation` was implemented in the linked PRs.
Implementation of rotation got deferred.
This is what this ticket is for, to capture the remaining tasks from the referenced.

  - Could be an `epionio rotate` command taking the same credentials options as `epinio install`.
  - Would have to call on the relevant deployments to re-deploy the parts of the system with the credentials.
  - Sounds a bit like we need an additional method in the `Deployment` interface, i.e. `Rotate(...)`.

**Comment by enrichman** [comment]
Outdated.
