### ISSUE TITLE
The install doc doesn't actually have instructions to install Epinio itself

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#423]
https://github.com/epinio/epinio/blob/main/docs/install.md

**Comment by andreas-kupries** [comment]
What about https://github.com/epinio/epinio/blob/main/README.md#install-epinio ?

**Comment by agracey** [comment]
Yeah, this is much better. I can change the link from epinio.io to use this instead

**Comment by agracey** [comment]
Just made the changes on the website. Closing
