### ISSUE TITLE
Traefik 2 errors

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#424]
On a k3d cluster with our Traefik installed (2.3.3), when pushing applications I see a errors in the traefik pod:

```
time="2021-05-26T15:24:35Z" level=error msg="Cannot create service: subset not found" serviceName=apps-756569080 servicePort=8080 providerName=kubernetes ingress=apps-756569080 namespace=orgs-801917837                                 
```

Those don't appear when Traefik v1 is installed.

This seems relevant: https://community.traefik.io/t/kubernetes-ingress-cannot-create-service-subset-not-found/7723

**Comment by manno** [comment]
Is there any other problem, except for the message?  Is the error reported for services that have an endpoint?

Relevant discussion starting here: https://github.com/traefik/traefik/issues/6821#issuecomment-713187574 
 
> it is normal to see this message upon creation of a new ingress, as Traefik is watching for the endpoints and it may not be ready or created yet by Kubernetes

There are some comments about having outdated caches in k8s or not enough RAM, but on my test installation all the messages refer to services with non-existing endpoints.

**Comment by andreas-kupries** [comment]
I have seen this kind of message also. However I believe that this is simply a transient thing, i.e. reported during start up, while the ingress has no backing service yet. I.e. a temporary thing we can ignore. And, I believe, also not something we can fix. Trying to would mean to wait for services to start during install, and then pushing the ingress resources.

IMHO this ticket can be closed as `invalid`.
