### ISSUE TITLE
Audit Logs

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#426]
Some admins will want to be able to review actions taken by users.

In my opinion, a JSON stream endpoint to subscribe to audit events would satisfy the requirement as well as pave the way for additional third-party integrations. If we wanted, we could write a reference implementation that stored the log in a postgres database?

**Comment by jimmykarily** [comment]
I think this issue will be also solved with what is described here: https://github.com/epinio/epinio/issues/593

One would simply have to register to all events using the same event mechanism. Maybe some filtering should also be possible but the basic idea should work for auditing.

**Comment by agracey** [comment]
That makes sense to me. I wonder if we should write a "reference implementation"?

**Comment by agracey** [comment]
Closing as duplicate of events hook
