### ISSUE TITLE
Document Buildpack Limitations and Restrictions

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#432]
## Acceptance Criteria

The main project's README should have a section about buildpacks explaining:
  - what buildpacks are
  - how is Epinio using them
  - links to the upstream docs
  - links to the docs about custom builder images
  - links to the tekton buildpacks pipeline
 
We shouldn't make this section too long. It should only be enough information for the user that has no previous knowledge on buildpacks, to understand if their preferred language/framework is supported or how they could add support for it (custom builder image feature).

**Comment by jimmykarily** [comment]
@agracey please check the description above and edit if you think it's missing something.

**Comment by agracey** [comment]
That looks like a good starting place! I have it on my short list to collect all the environment variables that buildpacks use into a single place with some descriptions of how to use them. Once I do that, we can add a link to it as well
