### ISSUE TITLE
Empty list from API should return `[]` instead of `null`

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#436]
It would be nice to always return valid json with a 200 of `Content-Type: application/json`. This makes parsing easier 😃

**Comment by andreas-kupries** [comment]
May we have concrete examples of where you saw the issue ?

**Comment by agracey** [comment]
`/api/v1/orgs/workspace/services` 

![image](https://user-images.githubusercontent.com/442274/120235897-e5c31f00-c20f-11eb-88ce-644ad14b24f9.png)

**Comment by agracey** [comment]
Closing this as the route doesn't even exist anymore
