### ISSUE TITLE
Epinio API over TLS

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#439]
Follow up of #130 

Epinio CLI (or other consumers) should talk to the Epinio API over TLS. It could be either plain TLS (like apps have) or mTLS. In any case, this story is about encryption and not authentication. For the latter we have basic auth and that's good for now. 

## Acceptance Criteria

- The epinio API endpoint is secured with TLS
- The API is not accessible without TLS (disable http).

**Comment by jimmykarily** [comment]
Traefik can do mTLS too: https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls
If that's too complicated let's stick to plain one-way TLS.

**Comment by andreas-kupries** [comment]
Looking first for the place where the client adds the protocol to the server url I find that the protocol is currently something the user can change via epinio's `config.yaml` file.

```
epinio_protocol: http
epinio_ws_protocol: ws
```

Does that make sense ?
Anybody remembering the reasons why this was put into the configuration ?

Ping to @thardeck @jimmykarily @rohitsakala @viovanov

**Comment by jimmykarily** [comment]
I guess it was there because on local clusters we served epinio over http but it was possible (through user's manual invervention?) to have it served over https too. Now we are switching to only-tls so, having it configurable doesn't make sense.

**Comment by agracey** [comment]
Just make sure there's an easy and self-documenting way to disable ssl verification

**Comment by jimmykarily** [comment]
> Just make sure there's an easy and self-documenting way to disable ssl verification

this may be better than my suggestion here: https://github.com/epinio/epinio/pull/445#issuecomment-853681776

Instead of relying on the domain to figure out if certs are self-signed, let them be whatever they want and use a flag `epinio --skip-ssl-verify` (you know, cf style).

**Comment by andreas-kupries** [comment]
@agracey 
> Just make sure there's an easy and self-documenting way to disable ssl verification

Right now ssl verification is not and cannot be disabled.

@jimmykarily 
> Instead of relying on the domain to figure out if certs are self-signed ...

This happens only for install (match for `omg.howdoi.website`).
The underlying mechanism however does not disable verification.
Install pulls the CA cert for the self-signed cert, and stuffs that into epinio's config file.
Then, whenever epinio is run it picks up that cert and adds it to the pool of CAs it verify against.

While I could have simply disabled verification for the self-signed cert this way of having the needed CA cert in the config means that the way is open for customers to create and use their own certs, self-signed or not, non-standard CA or not, and be able to work with all that. They simply have to stuff their CA cert(s) into the config.

Here is an example config:

```
certs: |
  -----BEGIN CERTIFICATE-----
  MIIDOTCCAiGgAwIBAgIQVeImVMCzYZ1YA4Eg08QSWzANBgkqhkiG9w0BAQsFADAv
[...]
  SvDaeNCm6BcKhJClCA==
  -----END CERTIFICATE-----
org: workspace
pass: c02a75b07c7fd8d5
user: 44885cef1891ee17
```

**Comment by andreas-kupries** [comment]
And that reminds me, I should write the documentation for this now, before I am forgetting ...
Expect another commit sometime during the day with that.

**Comment by jimmykarily** [comment]
Extracted to a new issue: #456
