### ISSUE TITLE
Allow for easy port forwarding for remote debugging

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#448]
I'd like to be able to get IDE debugging of my applications.

For examples of how we did it in CF, see: https://github.com/SUSE-Developer-Community/sandbox-welcome-content/blob/master/content/cli.md#debugging (Sorry, the rendered page was shut down with the sandbox)

**Comment by jimmykarily** [comment]
ssh tunneling is too big of a feature and currently not in the top priorities. In the meantime, there is `kubectl port-foward` (https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/). Depending on how we implement multi-user (see #486), users may or may not have `kubectl` access to the kubernetes cluster. If they do, `kubectl port-foward` should do the trick, no? I haven't checked the code but maybe it's even possible to expose that through some epinio command.

**Comment by agracey** [comment]
Yeah, this might need to be pushed out a bit

**Comment by agracey** [comment]
Dup of #1099 Oops
