### ISSUE TITLE
Only delete PipelineRuns when staging succeeds

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#452]
This is a follow-up story to investigate is this is possible: https://github.com/epinio/epinio/pull/443#discussion_r644510047

**Comment by agracey** [comment]
It would be nice to have a rolling set of previous staging attempts available. (maybe 2 success and 2 failures?) This way you can debug build issues without the "last known good" state always disappearing on you.

**Comment by agracey** [comment]
*Having deleted my fair share of known good states by accident...

**Comment by jimmykarily** [comment]
This is a feature of its own. Just keeping the old PipelineRuns and staging pods around won't be enough to make any use of them. The user would need a way to:
- list available staging processes (the things we keep around)
- identify what version of the code was part of which staging process
- see logs of a specific staging process (among the available)
- (?) reproduce one of the successful staging processes by pushing again with the same version of the code (as in rollback but to a version further back in history).

A workflow that allows one to keep staging logs from previous builds could be implemented in other ways. For example, one could simply push the app as a separate app (e.g. myapp-staging) to test it before pushing to the final location. I don't know if you have other use cases where this won't cut it.

That said, this issue is only trying to ensure that there will be no case in which we miss the staging logs of a currently running application. Right now, the old staging logs are deleted even when staging fails which leaves the old version of the application running but the staging logs are gone.

**Comment by andreas-kupries** [comment]
Re-read the staging code, below a simplified sequence diagram of the push and stage process.

  - The `unstage` of old runs currently happens in the handling of the `/stage` API.
  - Proposal based on it:
      - Wrap the `wait for pipeline run` into a new API call `/staged` or some such.
      - The client is changed to simply call this API. When it returns the app staging has completed, successfully or not
      - The waiting now happens on the server
      - The unstage of old moves to the server-side code of the new API, and is called only on success

### Existing Sequencing

```
Client				API					Server
------				---					------
`push`
	client.Push()

	uploadCode()
	\--->			/orgs/:org/applications/:app/store
									ApplicationController.Upload()
									Receive tarball
									Unpack tarball
									Save to gitea
									Return
	/<---							<-------/

	stageCode()
	\--->			/orgs/:org/applications/:app/stage
									ApplicationController.Stage()

									__Unstages old pipeline run__

									Generate and post pipeline run (PR)
									Return
	/<---							<-------/

	tailing logs, goroutines					At this point the PR runs concurrently
	running in background						in the cluster, managed by tekton
		   							the client side will know when it
									completes successfully, or not
	waitForPipelineRun (stageId)				<-------/

	!!!	talks directly to the cluster (Kubectl)
	!!!	polls the PR with stage id for status
	NOTE	stop the tailer when done, error or not

	waitForApp (stageId)

	!!!	talks directly to the cluster (Kubectl)
	!!!	polls the kube deployment with stage id
	!!!	for status

	bind services ... not relevant to the spike
```
