### ISSUE TITLE
Guided service creation

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#454]
It would be awesome if there's a way to have a process where you say `epinio services create` and it prompts you with the classes, then the plans, then any options on the plan.

**Comment by agracey** [comment]
The reason I ask is that I always have to run `epinio service list-classes` then `epinio service list-plans` then finally the `epinio service create` for every service I create!

**Comment by andreas-kupries** [comment]
Try the command completion. That should work at least for classes and plans. Options on a class/plan are, AFAIK, not programmatically available.

**Comment by agracey** [comment]
Command completion gets me that part. OSBA does indeed allow for plans to specify a schema (both for binding and instance creation). That'd be a much larger feature request through if the data isn't already there.

**Comment by agracey** [comment]
I'll close this issue and open another one specifically about the schema support if that becomes an actual issue. I'm not sure if minibroker uses those fields.
