### ISSUE TITLE
Allow the user to use latest buildpacks and stack (change the builder version)

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#455]
The user may want to use a different builder image for the following reasons:

- Use a newer version (security updates, new features etc)
- Use an older version (compatibility issues, apps not ready to upgrade etc)
- Use a custom version (with custom buildpacks they maintain, smaller image etc)

There is only one place where the url to the builder image is used and that is in the tekton pipeline. Being able to change that is only a matter or propagating the user's preference down to the pipeline. Maybe persisting that preference in the Epinio config is also good UX (in which case there should be a way to inspect the currently used image, store the builder image used for staging on the apps themselves and allow the user to change the persisted setting)

**Comment by agracey** [comment]
I'm going to add the Beta tag on this as it'll allow for python support

**Comment by agracey** [comment]
I think this is a duplicate of #283

**Comment by agracey** [comment]
Sry, didn't mean to close...

**Comment by jimmykarily** [comment]
> I think this is a duplicate of #283

Yes "custom buildpacks" means "custom builder image". Let's keep this one.

**Comment by agracey** [comment]
For when we get ready to do this:

Instead of maintaining a builder image that includes the config, we should be able to mount the toml from a ConfigMap and have it defined at runtime. This way we can inject whatever buildpacks are desired

**Comment by manno** [comment]
@agracey I replaced the custom builder manually: https://github.com/epinio/epinio/blob/main/docs/custom-python-builder.md

However, Tekton does not support `project.toml`.

Maybe we can make the [builder image argument](https://github.com/epinio/epinio/blob/main/assets/embedded-files/tekton/pipeline.yaml#L64-L65) configurable for apps, so they can be pushed with another (existing) builder.


(previous discussions: https://github.com/epinio/epinio/issues/484)
