### ISSUE TITLE
Video / blog post about Epinio's current state.

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#457]
As we getting closer to our [SLC](https://www.courtneyarnott.com/blog/simple-lovable-complete) release, lots of improvements and features are being added to Epinio. It's a good time to create a video that presents what is currently possible with Epinio.

**Comment by jimmykarily** [comment]
This has been delayed by #476, #477 and #481. Because of the first 2 issues, I opted for a demo of a development setup. Then I hit #477 . The mariadb service creates a `my_database` database by default and we could use this to still present the functionality.

**Comment by jimmykarily** [comment]
I created this repository to document all the findings: https://github.com/epinio/example-wordpress
It will be presented as part of the video too.

**Comment by gitricko** [comment]
This is deprrecated right? I think it is still a good idea to have a update demo video for the latest release. With possibily https via let's encrypt

**Comment by jimmykarily** [comment]
Yes it would be nice to have more videos but they take quite some time to produce. We are preparing a video with Django/Python which should be ready soon though.

**Comment by gitricko** [comment]
When you guys are ready with `service catalog create`, i am willing to help... at least creating a reasonable complicated microservices here:
https://github.com/gitricko/nameko-devex

It has 3 backing services (rabbitmq, postgres, redis)
It has automation scripts, currently kubecf + performance test via blazemeter.

**Comment by jimmykarily** [comment]
A `service catalog create` command is probably not needed, because it is meant to used by operators (which have kubectl access to the cluster) and would be equally complex to a `kubectl apply` command. Services can be added to the catalog by simply creating a "Service" custom resource. See also my other comment here: https://github.com/epinio/epinio/issues/1281#issuecomment-1092498281

@gitricko I had a look at your repository but I can't tell if a `service catalog create` command is required for what you want to do. Let us know if that's the case with some more details about your use case.

**Comment by gitricko** [comment]
Thanks @jimmykarily for looking into my repository. If you read this:
https://github.com/gitricko/nameko-devex/blob/master/README-DevOps.md#setup-2

It is exactly the use-case that your team is trying to do (exactly following the workflow of CF)
- Create necessary backing service `cf cs` 
- Push app with manifest that binds to it (or use `cf bs`)
I just create `short-cuts` via makefile to simplifed matters...

**Comment by jimmykarily** [comment]
@gitricko gotcha! Here you are: https://github.com/epinio/helm-charts/pull/173/files
I'm not sure if this default helm chart works for you though.

In the meantime, regarding this issue, the video has long been published here: https://www.youtube.com/watch?v=ySbaBRIim28 I'm closing this.
