### ISSUE TITLE
Deleting an app leaves ingress behind

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#461]
Reproduce:

- Push an app (the sample app will do)
- Delete the app
- `kubectl get ingress -n workspace` : the ingress is still there.

We should fix this and add a test to ensure this doesn't happen again.

NOTE: This may be solved with #347 (because of the ownership reference). We only have to add a test in that case.

**Comment by andreas-kupries** [comment]
Confirmed. Looking now where it should be deleted.
When #347 comes in, then we can delete the explicit code removing the ingress.
