### ISSUE TITLE
Allow passing helm chart parameters through minibroker

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#481]
Although we allow passing parameters with:

```
epinio service create wordpressdb3 mariadb 10-3-22  auth.database wordpress
```

1. The parameters are written in the wrong place: 
  https://github.com/epinio/epinio/blob/main/internal/services/catalog_service.go#L401-L404 (They should be inside `spec`: https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/parameters.md#design)
2. We only support top level keys. The example above needs to set an object `{ "auth": { "database": "wordpress"}}` but it sets `{ "auth.database": "wordpress"}` which doesn't have the [desired effect](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#mariadb-common-parameters)

## Acceptance Criteria

- The user should be able to pass a full json instead of just key-value pairs
- There is a test that checks that it is possible to provision a mariadb database by defining the database in params. The database should automatically be created (the mariadb pod has mysql cli available so we can `kubectl exec` something to check if the database is there).

**Comment by jimmykarily** [comment]
@andreas-kupries do you think I should change the custom service as well to accept json? This will be more consistent.

**Comment by andreas-kupries** [comment]
The data for the custom service is the data the application sees. 
The data you are passing for regular service is what the service sees for its configuration.

I do not believe that json makes sense for custom service at all.
The data goes to completely different destinations

**Comment by jimmykarily** [comment]
The example is the description is wrong (I was looking at the bitnami chart). The right one is this: https://github.com/epinio/epinio/pull/482#issuecomment-859606288
