### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#484]
Currently, python is not a supported language. As this is a very common language, we need to add support. 

It appears that there are python buildpacks in the paketo-community org:  https://github.com/paketo-community/python

As an aside, would it be worth compiling our own builder image so we can better control what languages and frameworks we support? (and as an even further aside, should we enable discussions in the repo?)

**Comment by jimmykarily** [comment]
The Epinio team doesn't have the capacity right now to build and maintain a custom builder image. If there is a Python buildpack we should ask why it's not in the full-builder here: https://github.com/paketo-buildpacks/full-builder.

That said, we are planning to support a configurable builder image in Epinio (#455). That means, if someone has a builder image with Python support, they will be able to use it. If we ever have the capacity to maintain our own builder image, it will probably be used as such (a custom builder image).

Regarding discussions, I don't have experience on how they are supposed to be used. Drop a line in Slack so we can discuss it, or let's bring it up in retro.

**Comment by agracey** [comment]
Do you know who I should contact for adding python to the full-builder? I can try to find what it would take to get it included upstream

This is going to be required for a lot of potential users so we need to have a "mostly supported" answer.

**Comment by jimmykarily** [comment]
Maybe just open an issue on the repo I linked above? (https://github.com/paketo-buildpacks/full-builder). By the way, there seem to be other builder that support Python: https://tanzu.vmware.com/developer/guides/python/cnb-gs-python/#get-the-list-of-suggested-builders
