### ISSUE TITLE
Allow for using a dockerfile build instead of buildpacks

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#485]
For existing projects or those without build pack support, it would be nice to give an escape hatch using a dockerfile. (maybe through a `--dockerfile` option?)

FWIW, Kaniko can do this in a rootless way with similar permissions to the buildpack runner and there's a task in the tekton hub.

**Comment by agracey** [comment]
This is actually being worked on upstream as an extension of the buildpacks project

**Comment by enrichman** [comment]
Let's close this waitging for news from the buildpacks project.

@agracey if you have any reference that we can link to this issue to track down the development of this it would be nice to have it here. :slightly_smiling_face:
