### ISSUE TITLE
Epinio Production Install IP Chicken and Egg

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#488]
While trying to deploy Epinio on Digital Ocean a problem with the sequence in which things are being installed and provisioned was hit.

Up to now, Epinio installs its components in the following sequence:

- It installs Linkerd
- It installs Traefik (on an annotated namespace, so traefik control plane pods are meshed)
- It installs cert-manager
- It installs Epinio server (the Epinio API endpoint)
- It creates a certificate for the Epinio server using cert-manager CRDs

It actually does more, but these are the steps that reproduce the issue we have. The first bullet (linkerd) is probably also irrelevant to this discussion.

When a custom system domain is used (not the `omg.howdoi.website`), Epinio will ask the cert-manager to create a let's encrypt certificate for the Epinio server. This involves an HTTP challenge which is automatically solved by the cert-manager. Before that happens, cert-manager does a "self test" request, trying to access the http url which satisfies the http challenge. That url is in the form of "http://mycustomdomain.org/..."
Obviously for this to work, the domain used by the user (the system domain) should already resolve to the API address of the loadbalancer (in other words it should point to the cluster).

Long story short, the moment we ask the cert-manager to create a let's encrypt certificate for a custom domain, that domain must already point to the cluster. If that is not the case, the failed DNS query is cached and the cert-manager doesn't recover (maybe it will after DNS cache has expired, we didn't wait that long).

The chicken-egg problem in this case was that we don't know the loadbalancer IP address, before we deploy a service on the cluster that actually needs a load balancer IP. `epinio install` is the thing that triggers the IP address allocation but also the thing that will fail if the system domain doesn't resolve to that IP address. Obviously there is no time for the user to setup the DNS while `epinio install` is running (and before we hit the cert-manager problem).

We thought of 2 ways to solve this problem:

1. We implement an `epinio install traefik` command to allow the user to only install traefik to the cluster. This should trigger the IP address allocation. We will print the IP address when this command returns so the user can setup the system domain to point to that IP address. When that's done, the user can run `epinio install` to resume the epinio installation.

2. We implement an `epinio install --traefik-loadbalancer-ip=1.2.3.4` flag. In most public cloud providers, you can allocate a public IP address and use it as the `LoadBalancerIP` field in the services you create. This flag will allow the user to do exactly that. First the user "buys" an IP address from the public cloud provider. Then the user sets up  the system domain she is planning to use for Epinio to point to that IP address. Finally the user installs epinio with the new flag set to that IP address. This will instruct Epinio to set the `LoadBalancerIP` field of the Traefik service to this IP address and hopefully the public cloud provider will respect that setting.

The relevant issues on our board are:

- Solution 1: #477 -- PR #491
- Solution 2: #476 

Related: #489 (Document Traefik/Linkerd meshing)

**Comment by andreas-kupries** [comment]
From chatting with Chris, in mail and teams a few more things which better fit here.
Taken from https://github.com/epinio/epinio/issues/476#issuecomment-861230797 :

> Chris pointed out that it may be hard to recover if the user releases the IP address after installing Epinio. E.g.

> - The user gets an Elastic IP address (AWS) to be used as `--loadbalancer-ip` in `epinio install`
> - The user sets up system domain with this IP address
> - The user installs Epinio
> - The user releases that Elastic IP address
> - Boom!

> Epinio is no longer reachable and the loadbalancer ip address is hardcoded in our epinio service. The only way to fix this is to directly access the service and change the load balancer ip. We could implement a new epinio command for that but it certainly adds complexity.


> Another approach (suggested both by Mario and Chris) is to use DNS challenge instead of the HTTP one (https://cert-manager.io/docs/configuration/acme/dns01/). This requires API access to the DNS provider. Many DNS providers allow remote configuration through some API but many don't.

> One more approach could be to only use self-signed certificates when first installing Epinio and let the user upgrade to let's encrypt (or other signer) with an explicit Epinio command. E.g. epinio certs-signer letsencrypt --update-existing
This command would re-generate all certs using the letsencrypt signer (epinio server cert, app certs etc).
Or it could be per end point. E.g. something like this: epinio app change-cert-signer letsencrypt myapp

> This would allow the user to setup another signer later on and be able to use it for new or existing applications.

**Comment by agracey** [comment]
Re-asking from #476 

I personally like the self-signed by default with an option to upgrade their LE setup. From an outside perspective, that seems like it would be the easier code to maintain longer term?

I think I have a few questions:
- What's the brittleness of each option? (how easy would it be for a user to screw up either the setup or the maintenance?)
- What's the cost to change from one option to the other if we see that people don't like the option we picked?
- Are there any k8s features that might be coming in the future that would change any of this?

Another thing to think of is if a user wants to do SSL termination external to the cluster (which is what we did for the CAP sandbox). This would obviously not be something that Epinio can or should automate, I just want to make sure that whatever option we choose it doesn't exclude that use case.

**Comment by agracey** [comment]
This is solved now, right?

**Comment by jimmykarily** [comment]
> This is solved now, right?

Kind of. Users have these options now:

- Install traefik with a separate command, find the IP address and finish the installation
- Install all in one go with `--ingress-service-ip` option (with cloud providers that support it).

so the original issue in the description is solved. Regarding your questions:

> What's the brittleness of each option? (how easy would it be for a user to screw up either the setup or the maintenance?)

If they manually go crazy deleting CAs we generate and such then they won't be able to recover, at least not using epinio commands. It's not a scenario we care to support I guess.

> What's the cost to change from one option to the other if we see that people don't like the option we picked?

Being able to switch to other issuers/CAs is a feature of its own and is not currently implemented. We need to provide a way to re-generate all the certs and update all the Ingresses. We have 4 ingresses for epinio components (registry, epinio api, dex, traefik forward auth) plus all the ingresses for running applications. It's doable but it needs some work to make it happen.

> Are there any k8s features that might be coming in the future that would change any of this?

Nothing that I know of but I'm not constantly monitoring future plans for Kubernetes, I could be missing something.

We can close this issue I think and create issues for additional features we want to implement.
