### ISSUE TITLE
Document the need for Traefik to be meshed with Linkerd in Epinio

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#489]
Document that

  - Traefik has to be meshed with Linkerd for fully secure communication from outside to epinio API, and applications.
  - This meshing is done automatically by the standard install commands (`install`, and `install-ingress` (See #491)).
  - A non-epinio Traefik (Custom user's, or system (`k3d`)) is __not__ meshed by default, and thus less secure.

See if we can document how to fix that issue for a non-epinio Traefik (configuration, and other steps to take).

### Old description

Epinio currently deploys Traefik after deploying Linkerd, and annotates Traefik for integration with the Linkerd mesh.

There are persistent doubts floating around about actually needing Traefik to be part of the mesh.

For example, communication with the Ingress Controller part of Traefik is indirect, by posting and removing Ingress kube resources.

On the other hand, Traefik seems to establish an `svclb` pod which might be a LoadBalancer. That would have to be part of the mesh to secure the communication from that LB to the service endpoints in Epinio and Application Pods.

On the third hand are some clues pointing to the svclb pod "only" setting up iptables rules for the necessary routing. In that case the pod may not be involved at all ?!

**Comment by andreas-kupries** [comment]
@kkaempf In the discussion this morning, after standup, we wondered if Suse has experts around "Virtual Networking" as done by Linkerd or other tooling, which could help explain to us how this works at deeper levels. The name "Cilium" also floated around. Could you investigate/find such people ?

**Comment by kkaempf** [comment]
Answered in Slack :wink:

**Comment by andreas-kupries** [comment]
Answer: Yes, the meshing is needed, per various Slack threads.

Have to document the unmeshed cases (non-epinio Traefik).

**Comment by andreas-kupries** [comment]
Renaming the issue now.
