### ISSUE TITLE
CLI (except install,update creds) doesn't need a kubernetes connection

### ISSUE THREAD

**Issue by manno** [epinio/epinio#508]
Thinking of Epinio as differenct components, we would speak of:

* installer
* cli
* web server
* api server

The cli parts that deal with applications, shouldn't need a separate kubernetes connection (`KUBECONFIG`).

## Acceptance

* the remaining code parts that use kubectl use the api server instead
* implements Match* as API endpoint (some could be part of `Index`)

**Comment by jimmykarily** [comment]
Superseded by #620 (was a duplicate but kept the newer one because it had a more detailed description).
