### ISSUE TITLE
Listing apps, should show application resources instead of deployments

### ISSUE THREAD

**Issue by manno** [epinio/epinio#510]
Now listing apps, we see all the deployments. With the introduction of an application resource, that might exist before the deployment (workload), exists, we want the user to see it in the CLI output.

**Note**: The same might be true for other commands, like `app show`. We might need to create follow up stories.

relies on #509 

## Acceptance Criteria

* epinio show app includes apps without deployments

**Comment by andreas-kupries** [comment]
Attention #375. The new commands have the same issue when following the pattern of the existing commands.
Fixing that there we can fix the other app commands also. I.e. this ticket. See #587.
