### ISSUE TITLE
`kubernetes.io/ingress.class` should be an annotation

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#520]
The ingress Epinio creates for application has a *label*

```
  kubernetes.io/ingress.class: traefik
```

This is wrong. According to the documentation ([link1](https://cloud.google.com/community/tutorials/nginx-ingress-gke#configure_ingress_resource_to_use_nginx_ingress_controller), [link2](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation)), that should be an annotation. 

The result is that when we deploy on gke, the application ingress gets its own public IP address and not the one of Traefik. This in turn means the application domain doesn't work (since it points to the traefik IP address).

Looking at the kubernetes docs, it seems that the annotation is deprecated, but looking at the gke docs it's probable still widely supported (see the 2 links above). We need to investigate what the proper solution is.

**Comment by andreas-kupries** [comment]
See #522 for the investigation to conduct.
