### ISSUE TITLE
Investigate Ingress Class Specification

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#522]
Followup on #520

Per the kubernetes [ingress docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), it seems that the annotation is deprecated.

According to the [gke docs](https://cloud.google.com/community/tutorials/nginx-ingress-gke#configure_ingress_resource_to_use_nginx_ingress_controller) on the other hand it is probable still widely supported.

We need to investigate what the proper solution is.

K looks to be going for a more indirect approach with 

  - A new field in `Ingress` resources specifying an `IngressClass` resource (by name)
  - And `IngressClass` resources configuring the class, including the controller to use.

**Comment by andreas-kupries** [comment]
See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class for some details

**Comment by svollath** [comment]
Just as a comment:

So in my case with RKE2 on SLE15, metallb and external-dns it's like the following:

- traefik service gets an external-IP from metallb (e.g. 10.162.231.30)
- I do a service annotaion for ext-dns for `tf1.paas.suse.de 0 IN A  10.162.231.30` (also wildcard *.tf1.paas.suse.de)
- I install an app, e.g. "sample", which will get an ingress with the NodePort-IP of its worker (e.g. 10.162.231.24)
- external-dns will automatically create an endpoint from that ingress:
```
"Endpoints generated from ingress: workspace/sample: [sample.tf1.paas.suse.de 0 IN A  10.162.231.24 [] sample.tf1.paas.suse.de 0 IN A  10.162.231.24 []]"
```
So for me it worked - while apps shouldn't get the NodePort-IP.

**Comment by andreas-kupries** [comment]
I suspect it worked by chance.

**Comment by manno** [comment]
Also see https://github.com/epinio/epinio/issues/384

**Comment by jimmykarily** [comment]
@manno I think this can be closed now? We switched to IngressClass. I'll close this, please re-open if I missed something.
