### ISSUE TITLE
Workloads should be meshed

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#532]
Reproduce:

- Install epinio
- Push an app (the sample app will do)

Although the namespace is annotated for linkerd, the application pod doesn't get a sidecar. This is because we create the application with `automountServiceAccountToken: false` (see here: https://github.com/linkerd/linkerd2/issues/3183). We do this because we don't want the code inside the application pods to be able to talk to kubernetes (which is what the servicetoken is allowing). Linkerd on the other side needs this.

We need to find a way to have a sidecar without allowing application code to do nasty things on the cluster.

**Comment by jimmykarily** [comment]
btw, staging pods have sidecars which means they don't have the `automountServiceAccountToken` set to false. Maybe they should? Should the staging pods be meshed? (if they only need to talk to the registry and the registry is not meshed then maybe they shouldn't).

**Comment by jimmykarily** [comment]
Renamed the story. Currently the workload namespaces are annotated (so they are part of the mesh) but the app pods don't get a sidecar because of the above issue. We want them to be part of the mesh because:

- Traefik will send the requests unencrypted to the apps (because TLS is terminated on Traefik so the request is flying unencrypted from there on)
- Minibroker service (or generally services running inside the cluster) are (or may be) part of the mesh. When the application is talking to the service, the traffic should be encrypted.

**Comment by manno** [comment]
Since we get the `default` service account of the namespace by default, `automountServiceAccountToken: true` should not be too bad?

**Comment by jimmykarily** [comment]
I'm trying to find proof that the default service account doesn't get any permissions. I only found this: https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account

but I'm looking for some official docs instead. Otherwise it's the code... :D

**Comment by jimmykarily** [comment]
I still see this in the events of the application pods:

```
Normal  InjectionSkipped   2m26s (x4 over 95m)  linkerd-proxy-injector  Linkerd sidecar proxy injection skipped: automountServiceAccountToken set to "false"                                                                             │
```
(and no sidecar exists)
