### ISSUE TITLE
`epinio logs myapp --staging` should not show linkerd container logs

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#534]
Right now it does:

```
...
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] linkerd-proxy 2021/06/23 09:33:11 Exiting... 
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] place-tools 2021/06/23 09:33:00 Copied /ko-app/entrypoint to /tekton/tools/entrypoint 
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] linkerd-init 2021/06/23 09:33:01 Tracing this script execution as [1624440781] 
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] linkerd-init 2021/06/23 09:33:01 current state 
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] linkerd-init ------------------------------------------------------------ 
🕞  [24ab9e2f3250887e-run-kbvbp-pod-8hfbw] linkerd-init 2021/06/23 09:33:01 :; iptables-save 

...
```

**Comment by manno** [comment]
Looks like it was only fixed for `push` https://github.com/epinio/epinio/blob/main/acceptance/apps_test.go#L93 and not for `logs`.

**Comment by andreas-kupries** [comment]
Isn't this going through the same server API ?

**Comment by andreas-kupries** [comment]
Confirmed. The output from `logs --staging` contains linkerd related lines, whereas the logs coming out of `push` do not, while they should ostensibly the same logs.

**Comment by andreas-kupries** [comment]
`log --staging` is cli/apps.go -> client AppLogs (with StageId) -> API StagingLogs -> ApplicationsController{}.Logs -> streamPodLogs -> application.Logs 

`push` logs ... cli/push.go -> client Push -> client AppLogs (with stageId) -> API StagingLogs -> s.a

So. These are the same, or rather, should be.

:bulb: (I believe). The log system auto-attaches to the pods and their containers to stream logs, using various selectors.
I could believe, and theorize, that during push the linkerd sidecar containers are coming late to the game and are thus not attached to for logging. Then, when I run `logs --staging` later the sidecars exist (for some time) by then, thus are found by the selectors, and their logs are added to the stream.

Except ... The tailer is configured using

```
ExcludeContainerQuery: regexp.MustCompile("linkerd-(proxy|init)"),
```

... One difference. Push likely has `follow` set, thus `StreamLogs`.
On the other side `log --staging` is without `follow` ... `FetchLogs`.

That looks to be a difference in application.Logs

I have to delve more where/if that makes the difference.

**Comment by andreas-kupries** [comment]
Yes, that looks to be the difference.

`StreamLogs` sets up a `Watch`. This takes the `ExcludeContainerQuery`, and thus never reports the linkerd containers for logging.
See https://github.com/epinio/epinio/blob/main/helpers/kubernetes/tailer/setup.go#L108

`FetchLogs` OTH does not `Watch` at all. It simply iterates over all the Container for the selected pods.
See https://github.com/epinio/epinio/blob/main/helpers/kubernetes/tailer/setup.go#L76-L81

FetchLogs has to be rewritten to perform the same `(Exclude)ContainerQuery` checks as done by the `Watch`.
