### ISSUE TITLE
Running a command without the required parameters should show `--help`

### ISSUE THREAD

**Issue by thardeck** [epinio/epinio#537]
If I run an epinio command and forget that there are additional parameters required, I have to rerun the command with `--help`.

Instead if required parameters are missing `--help` should be shown instead of just an error message.

At the moment it looks like this:
```
epinio services list-plans         
accepts 1 arg(s), received 0
```

And it should look like this:
```
epinio services list-plans         
accepts 1 arg(s), received 0

Lists all plans provided by the named service class

Usage:
  epinio service list-plans CLASS [flags]

Flags:
  -h, --help   help for list-plans

Global Flags:
      --config-file string       (EPINIO_CONFIG) set path of configuration file (default "/home/thardeck/.config/epinio/config.yaml")
  -c, --kubeconfig string        (KUBECONFIG) path to a kubeconfig, not required in-cluster
      --no-colors                Suppress colorized output
      --skip-ssl-verification    (SKIP_SSL_VERIFICATION) Skip the verification of TLS certificates
      --timeout-multiplier int   (EPINIO_TIMEOUT_MULTIPLIER) Multiply timeouts by this factor (default 1)
      --trace-level int          (TRACE_LEVEL) Only print trace messages at or above this level (0 to 5, default 0, print nothing)
      --verbosity int            (VERBOSITY) Only print progress messages at or above this level (0 or 1, default 0)
```

## Acceptance criteria
* Missing required parameters result in the output of `--help` of this command
* There is still an error message shown what is missing above or below

**Comment by andreas-kupries** [comment]
It looks be the `SilenceUsage: true` config in our cobra commands. Now going over all and changing them to `false`.

**Comment by andreas-kupries** [comment]
For best effect it seems that we should use `SilenceUsage: false` in general, and dynamically set it to `true` where needed. Which is when an internal error happens, i.e. from the backend and such. These are not helped by showing the usage, at all.
