### ISSUE TITLE
We should rename orgs

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#544]
The name organization likely gives the impression of harder multi-tenancy than we will want to offer (at least in the near- to mid-term).

I know we stayed away from calling them "spaces" because that can get confusing with the underlying "namespace" from k8s but that might be ok?

**Comment by jandubois** [comment]
How about "group" or "team" to make them sound less rigid?

Or maybe "topic" to show that things are separated by semantics and not by structure, or security boundary?

Of course "project" would be even better, but that is already a Rancher concept.

**Comment by agracey** [comment]
I think "team" works. It better fits how I would expect a larger organization to use Epinio.

If we do end up supporting multi-tenancy at some point, we can add orgs back in as the tenant demarcation.

**Comment by jimmykarily** [comment]
We could just call them "namespaces". It's a kubernetes term but one that is self-explanatory so nothing bad with exposing it.

**Comment by agracey** [comment]
Or "workspace"?

**Comment by agracey** [comment]
I don't know how much it matters. I just think "org" might lead to the wrong assumptions.

**Comment by kkaempf** [comment]
First step: Rename to "namespace" on user-facing side (Cobra options, tests, documentation).
