### ISSUE TITLE
Select a public cloud provider to support for SLC

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#549]
When we choose one, we should update the SLC description here: https://github.com/epinio/epinio/milestones/3/edit

**Comment by svollath** [comment]
When talking to the Public Cloud Team, and in regard to access available already, esp. for

- accessibility (for the team)
- popularity
- widest team support

we should /will start with AWS (EKS).

**Comment by kkaempf** [comment]
AWS is it !
