### ISSUE TITLE
The staging pipeline pods are never deleted /  cleaned up.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#55]
See also #17.

In testing the latest PR around app methods (`push`, `apps`, `delete`) I noticed that the `staging-pipeline-...` pods are never deleted.
While they show up in the kubectl pod listing as completed, they do show up even after `push` has the app running.
Deleting the app does not delete them either.
Nore is any reuse happening.

For the moment (pre-demo) this should be ok. However for production, maybe even MVP, I can see these pods starting to clutter the low-level pod display as apps are created, updated, and deleted, with ever more staging-pipeline pods shown.

Confirmed that creating more apps creates more sets of staging-pipeline pods, no reuse.

**Comment by jimmykarily** [comment]
In any case, when an application is deleted, the staging pods (from any staging process) are no longer needed and should be deleted.
Also, after a successful staging process, the previous staging pods are again not useful and can be deleted, unless we want the user to be able to access all previous staging logs but I don't see a valid use case for that.

**Comment by jimmykarily** [comment]
#246 is also relevant because it affects how we decide which staging process is the current one.

**Comment by andreas-kupries** [comment]
See tickets #431 and #452, and the associated pull requests.
