### ISSUE TITLE
Document file system structure of service parameters

### ISSUE THREAD

**Issue by timirnich** [epinio/epinio#550]
Epinio mounts the service credentials secret generated by minibroker into the file system of the run container under /services/<servicename>/*. Each service seems to have it's own convention which parameters get created and how they are named. Currently, the user needs to find this out by creating the service and then `kubectl describe` on the secret. This should be documented for the currently supported service types, and, ideally, also output when creating the service.

**Comment by agracey** [comment]
Chatting with Tim right now about this. 

We should also look at listing the parameters exposed in each service through `epinio service show <service name>`.

We do this for custom service, why not marketplace services?
