### ISSUE TITLE
End to End Testplan

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#566]
We need to take some time to sit down and use Epinio on a broad range of projects to feel out the rough edges.

**Comment by manno** [comment]
* buildpacks
* CLI
* cloud providers

**Comment by agracey** [comment]
Starting here: https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)

**Comment by agracey** [comment]
This is in a good state for now. 

Need to add a ticket for inclusion of Rancher Desktop
