### ISSUE TITLE
Spike: Stage an existing Docker image

### ISSUE THREAD

**Issue by manno** [epinio/epinio#574]
We can speed up CI, by removing the buildpack tekton job from a large number of our tests. They would just stage an existing Docker image.

In the future, users can stage Docker images via `epinio push`.

See #485 also

**Comment by agracey** [comment]
I'm assuming you mean `epinio push`? 😄

**Comment by rohitsakala** [comment]
Spike Investigation:

After understanding the push code and endpoints it hits, I think this is completely possible and can be done. 

Push Process Overview

-> epinio push -> AppCreate API (Creates AppCRD) -> AppUpload API (Create gitea repo) -> AppStage API (Create tekton pipelineRun)
                                       
We have a separate endpoint API for AppCreate to have the functionality of controlling the app start. We can create an app and not assign a workload, but I feel this is the wrong split. The split should be in AppStage. The Run task of the tekton pipeline should have a separate endpoint (which is only for deploying the workload).

Proposed Push Process

-> epinio push -> AppCreate API (Creates AppCRD) -> AppUpload API (Create gitea repo) -> AppStage API (Create tekton pipelineRun `clone` & `stage`) -> AppRun API (Create TaskRun `run`)

**Comment by manno** [comment]
Can you create a minimal implementation to show if CI gets faster?
