### ISSUE TITLE
Spike: Run split test suite in parallel on multiple workers

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#577]
(Converted from icebox entry)

Can the testsuite runtime be improved by running tests in parallel on multiple workers ?

**Comment by andreas-kupries** [comment]
Relevant flows:
  - `main.yml`
  - `outside-pr.yml`

These two are mostly the same. Differences are trigger conditions, ginkgo setup, and docker hub access

Provided by @manno : https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs

**Comment by andreas-kupries** [comment]
Basic plan:

- [ ] Extended Makefile with separate targets for the individual big test suites. Keep the target for the combined run, for local dev.
- [ ] New job doing only linting. Reduced setup. Dependency of the jobs running the testsuites.
- [ ] Modified old job running only unit tests and one of the testsuites. Depend on the new linting job.
- [ ] New job running the other testsuite. Depend on the new linting job
