### ISSUE TITLE
error creating org: All attempts fail:

### ISSUE THREAD

**Issue by gusraggio** [epinio/epinio#581]
Installing Epinio on top of k3d and docker desktop on macos,

MacOS: BigSur 11.4
Docker Desktop: 3.5.1.7
k3d: v4.4.6
epinio: 0.0.18

epinio install

🚢 Epinio installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain: 
  🧭  email_address: epinio@suse.com
  🧭  user: b77a5cc116acc6db
  🧭  password: 2eb63bbc003cd577

🚢 Deploying Linkerd...
✔️  Linkerd deployed

⚠️  System Ingress present, skipping
.
✔️  Created system_domain: 172.19.0.2.omg.howdoi.website

🚢 Deploying CertManager...
🚢 Deploying Quarks...
🚢 Deploying Registry...
🚢 Deploying Tekton...
🚢 Deploying Gitea...
🚢 Deploying Epinio...
🚢 Deploying Kubed...
🚢 Deploying ServiceCatalog....I0705 14:16:22.132880   23730 request.go:655] Throttling request took 1.170816899s, request: POST:https://0.0.0.0:62230/api/v1/namespaces
............................................................................................................................................................................................................................................
✔️  Quarks deployed
...................
✔️  Kubed deployed
...............
🚢 Retrying creation of API cert via cert-manager (0/10)
.........................
🚢 Retrying creation of API cert via cert-manager (1/10)
............................................
🚢 retrying to apply tekton/pipeline.yaml
.....
✔️  ServiceCatalog deployed
..
🚢 Retrying creation of API cert via cert-manager (2/10)
..........
🚢 retrying to apply tekton/pipeline.yaml
.....
🚢 retrying to create the epinio cert using cert-manager
.........
✔️  Registry deployed

✔️  CertManager deployed
..
🚢 retrying to apply tekton/pipeline.yaml
.........
✔️  Epinio deployed
......................
✔️  Tekton deployed
.................................................
✔️  Gitea deployed
.................................................
✔️  Epinio installed.
System domain: 172.19.0.2.omg.howdoi.website
API User: 0a7257e56a1a8d43
API Password: 016b4a676a0a49fa
Traefik Ingress info: [{"ip":"172.19.0.2"}]

🚢 Updating the stored credentials from the current cluster

✔️  Ok

🚢 Creating organization...
Name: workspace
error creating org: All attempts fail:
#1: Post "https://epinio.172.19.0.2.omg.howdoi.website/api/v1/orgs": dial tcp 172.19.0.2:443: i/o timeout

**Comment by gusraggio** [comment]
I just realized a note about MacOS,

https://github.com/epinio/epinio#troubleshooting

> ifconfig |grep "inet.*broadcast"
	inet 192.168.0.16 netmask 0xffffff00 broadcast 192.168.0.255
	inet 192.168.66.1 netmask 0xffffff00 broadcast 192.168.66.255

> k3d cluster create epinio -p '80:80@server[0]' -p '443:443@server[0]'

INFO[0000] Prep: Network                                
INFO[0004] Created network 'k3d-epinio' (4131525e685db34c8cfe6446b025c4118b95faa0d901b5c7178d64c949ba1708) 
INFO[0004] Created volume 'k3d-epinio-images'           
INFO[0005] Creating node 'k3d-epinio-server-0'          
INFO[0006] Creating LoadBalancer 'k3d-epinio-serverlb'  
INFO[0006] Starting cluster 'epinio'                    
INFO[0006] Starting servers...                          
INFO[0006] Starting Node 'k3d-epinio-server-0'          
INFO[0027] Starting agents...                           
INFO[0027] Starting helpers...                          
INFO[0027] Starting Node 'k3d-epinio-serverlb'          
INFO[0032] (Optional) Trying to get IP of the docker host and inject it into the cluster as 'host.k3d.internal' for easy access 
INFO[0037] Successfully added host record to /etc/hosts in 2/2 nodes and to the CoreDNS ConfigMap 
INFO[0037] Cluster 'epinio' created successfully!       
INFO[0037] --kubeconfig-update-default=false --> sets --kubeconfig-switch-context=false 
INFO[0038] You can now use it like this:                
kubectl config use-context k3d-epinio
kubectl cluster-info

> /Users/gus/Downloads/epinio install --system-domain=192.168.0.16.omg.howdoi.website

🚢 Epinio installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain: 192.168.0.16.omg.howdoi.website
  🧭  email_address: epinio@suse.com
  🧭  user: f90bb847cae330c1
  🧭  password: a57666aa8da89e4a

🚢 Deploying Linkerd...
✔️  Linkerd deployed

⚠️  System Ingress present, skipping

✔️  Created system_domain: 192.168.0.16.omg.howdoi.website

🚢 Deploying Kubed...

🚢 Deploying Epinio...🚢 Deploying ServiceCatalog...
🚢 Deploying Quarks...
🚢 Deploying CertManager...
🚢 Deploying Gitea...
🚢 Deploying Registry...
🚢 Deploying Tekton...I0705 14:45:16.729101   24155 request.go:655] Throttling request took 1.129078131s, request: POST:https://0.0.0.0:63607/api/v1/namespaces
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
✔️  Quarks deployed
....................................................................................................................................................................................
✔️  Kubed deployed
............................................................................................................................................................................................................................................................................................................................................................................
✔️  ServiceCatalog deployed
...................................
🚢 retrying to create the epinio cert using cert-manager
................
🚢 Retrying creation of API cert via cert-manager (0/10)
.
🚢 retrying to apply tekton/pipeline.yaml
.
🚢 retrying to create the epinio cert using cert-manager
....
🚢 Retrying creation of API cert via cert-manager (1/10)
........
🚢 retrying to apply tekton/pipeline.yaml
...
🚢 retrying to create the epinio cert using cert-manager
...
🚢 Retrying creation of API cert via cert-manager (2/10)
.................................................................
✔️  CertManager deployed
...
✔️  Registry deployed
................................
✔️  Epinio deployed
..................panic: Deployment tekton failed with error: Applying tekton staging resources failed:
: Failed to get registry CA from tekton-staging namespace: secrets "epinio-registry-tls" not found


goroutine 29 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc00091b200, 0x2c62350, 0xc0001a0000, 0x2c6cdd0, 0xc000103cc0, 0x2c72d58, 0xc0006c14c0, 0xc00088f080)
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:150 +0x239
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:147 +0xe59

**Comment by andreas-kupries** [comment]
What happens when you run `epinio org create workspace` manually, after the `all attempts fail` message ?

**Comment by andreas-kupries** [comment]
Note that github allows the upload and attachment of files to an issue. IOW, it is possible to attach a log instead of having to create a very large comment. See the note at the bottom of the edit field for entering a comment.

**Comment by andreas-kupries** [comment]
@gusraggio Any new to report here ?

For myself, I have seen the `error creating org: All attempts fail:` now on Linux as well, so it does not seem to be limited to OSX (with its wacky docker support). It also seems to be a heisenbug, i.e. does not seem to be deterministic.

**Comment by andreas-kupries** [comment]
Looking at
```
ship Creating organization...
Name: workspace
error creating org: All attempts fail:
#1: Post "https://epinio.172.19.0.2.omg.howdoi.website/api/v1/orgs": dial tcp 172.19.0.2:443: i/o timeout
```

again I finally note that I am __not__ seeing a message of the form
> Retrying (%d/%d) after (error))

That is the message the client prints when it [actually does retry after an error](https://github.com/epinio/epinio/blob/562b79a0252741a269683a14addfb6eb5d9d57c5/internal/cli/clients/client.go#L1107).

Checking the code a bit more, the reported `i/o timeout` is [not in the set of errors](https://github.com/epinio/epinio/blob/562b79a0252741a269683a14addfb6eb5d9d57c5/internal/cli/clients/client.go#L1102-L1104) which would trigger a retry.

I now suspect a race condition here.
The API server is reachable (Otherwise it would be a `Gateway` error, which does trigger a retry).
However it does not seem to respond quickly enough, hence the timeout ...

I could simply add this error to the set causing a retry, however that feels like a hack for the moment.
I will attempt to determine why the server is not responding quickly enough for the client, in case it is something bigger we should not simply paper over.

**Comment by gusraggio** [comment]
Hello @andreas-kupries apologies for the misunderstanding, after my initial report, I did what was described in my second comment. I was able to overcome the initial error with https://github.com/epinio/epinio#troubleshooting 

You can see what I executed on my laptop on my second comment. It ends with this error,

> ✔️ Epinio deployed
> ..................panic: Deployment tekton failed with error: Applying tekton staging resources failed:
> : Failed to get registry CA from tekton-staging namespace: secrets "epinio-registry-tls" not found
> 
> goroutine 29 [running]:
> github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc00091b200, 0x2c62350, 0xc0001a0000, 0x2c6cdd0, 0xc000103cc0, 0x2c72d58, 0xc0006c14c0, 0xc00088f080)
> /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:150 +0x239
> created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
> /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:147 +0xe59

**Comment by andreas-kupries** [comment]
Ah. Thanks for the clarification ... The missing secret ... 
That is weird.

Investigating ... It is used in two places, the container registry chart, and the tekton deployment code. It is the second which seems to fail.

> /assets/container-registry/chart/container-registry/templates/container-registry.yaml:55:    secretName: epinio-registry-tls
./deployments/tekton.go:338:// kubectl get secret -n tekton-staging epinio-registry-tls -o json | jq -r '.["data"]["ca.crt"]' | base64 -d | openssl x509 -hash -noout

In my linux install it exists twice

> work@tagetarl:~/SUSE/dev/epinio> kubectl get secret --all-namespaces | grep registry-tls
epinio-registry    epinio-registry-tls                                  kubernetes.io/tls                     3      108m
tekton-staging     epinio-registry-tls                                  kubernetes.io/tls                     3      108m

Implies that the quarks-secret functionality for copying secrets may be involved ... If not ... I have to my co-workers about recent work in the areas ...

@rohitsakala Is `epinio-registry-tls` one of the secrets where your addition of `kubed` for copying secrets is involved ?
Or is that still handled by the quarks-secret ?

@gusraggio Can you check in your install if that secret exists at all and if yes, where ? See my command above to query the cluster. (I am currently suspecting that the base secret is created correctly (in epinio-registry), and that the copying to the `tekton-staging` namespace did not happen, somehow. And if yes then that may be an issue with the MacOS k3d. I vaguely remember that we saw something like that before. ... Will search the project now ...

**Comment by andreas-kupries** [comment]
Ah. I remembered #110 which was RKE, longhorn, and some other things ... Not MacOSX. And closed without resolution because we could not get proper repro going, from the end of the comment log.

Hm.

**Comment by gusraggio** [comment]
I was able to deploy my frist epinio app! 👨🏻‍💻🤩😍

The only thing that, I think changed, since last week, is k3d 4.4.7. The version of docker is the same one and the epinio version is the same.

Thanks for all the help @andreas-kupries

**Comment by andreas-kupries** [comment]
Ok. I will then close this ticket.
