### ISSUE TITLE
Epinio server not working on localhost

### ISSUE THREAD

**Issue by malcolmlewis** [epinio/epinio#582]
Hi
The option to run the localhost server to access Applications is not working on v0.0.18, if I run `epinio server` on v0.0.17 I can browse organizations and applications and connect to the route. On v0.0.18 the server starts but no information on the application is visible. 

System details:
openSUSE Tumbleweed 20210704
Docker 20.10.6_ce-1.2
k3d version v4.4.6
k3s version v1.21.1-k3s1 (default)
Epinio Version: v0.0.18

As a side note, incorrect version numbers are shown for epinio;

```
:~> epinio version 

Epinio Version: v0.0.18
Go Version: go1.16.5

:~> epinio info 

Epinio Environment

Platform: k3s
Kubernetes Version: v1.21.1+k3s1
Gitea Version: unavailable
Epinio Version: v0.0.17 <=== incorrect
```

**Comment by andreas-kupries** [comment]
Using a freshly created k3d/k3s cluster and installing the epinio I do not see the incorrect version.

```
work@tagetarl:~/SUSE/dev/epinio> ep version
Epinio Version: v0.0.18-15-g0a86081
Go Version: go1.14.15
work@tagetarl:~/SUSE/dev/epinio> ep info

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.20.6+k3s1
Gitea Version: unavailable
Epinio Version: v0.0.18-15-g0a86081
```

So. I suspect that your cluster is still running the old version of epinio for the server, somehow.
I further suspect that this may also be the cause of your other issues.

**Comment by jimmykarily** [comment]
I verified that the `Epinio version` returned by `epinio info` is the one of the server binary. This means your cluster was somehow still running the epinio server `v0.0.17` (previous install?). @malcolmlewis can you re-try with consistent versions and see if your problems are solved? Start with a fresh cluster to be sure.

**Comment by kkaempf** [comment]
I see a similar effect with a [local install](https://github.com/epinio/epinio/blob/main/docs/developer/howtos/development.md#installing-epinio) on a fresh minikube cluster:

```
> epinio info

✔️  Epinio Environment
Platform: minikube
Kubernetes Version: v1.21.2
Gitea Version: unavailable
Epinio Version: unavailable
```

**Comment by jimmykarily** [comment]
I had that when my epinio config was not up to date. Can you try some other epinio command to see if cli can talk to the server? E.g. `epinio apps list`. If not, try running this first: `epinio config update-credentials` and then re-try.

**Comment by kkaempf** [comment]
Even after running `epinio config update-credentials` `epinio apps list` fails with
```
> epinio apps list

🚢 Listing applications
Organization: workspace
error listing apps: Get "https://epinio.192.168.49.0.omg.howdoi.website/api/v1/orgs/workspace/applications": dial tcp 192.168.49.0:443: connect: network is unreachable
```

So my problem might be related to using `--skip-default-org` during installation ?!

**Comment by jimmykarily** [comment]
if you are using a development build of epinio, the steps to install epinio included skipping the creation of the default org (https://github.com/epinio/epinio/blob/main/docs/developer/howtos/development.md#installing-epinio). After patching the server deployment (see the instructions on the link), you should run `epinio orgs create workspace` to create it.

**Comment by malcolmlewis** [comment]
Hi
Still no luck here, cleaned out all images and started test again;
```
epinio apps list

🚢 Listing applications
Organization: hello

✔️  Epinio Applications:
|    NAME    | STATUS |                  ROUTES                  | SERVICES |
|------------|--------|------------------------------------------|----------|
| helloworld | 1/1    | helloworld.172.18.0.2.omg.howdoi.website |          |

epinio config update-credentials

🚢 Updating the stored credentials from the current cluster

✔️  Ok

epinio info 

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.21.2+k3s1
Gitea Version: unavailable
Epinio Version: v0.0.18
```

**Comment by jimmykarily** [comment]
@malcolmlewis are you trying to run the server outside the cluster? Right now, the cli discovers the server's url by looking at the cluster ingresses. [There is a plan](https://github.com/epinio/epinio/issues/620) to change this and then you should be able to run the server outside the cluster but for now, that is not possible. Do you need that for debugging/development? If yes, then there is already a way to do that:

- https://github.com/epinio/epinio/blob/main/docs/developer/howtos/development.md#installing-epinio
- https://github.com/epinio/epinio/blob/main/docs/developer/howtos/behind-the-curtains.md

**Comment by malcolmlewis** [comment]
@jimmykarily yes outside the cluster, on the host machine, this feature works if I switch to v0.0.17? I'm testing the rpm version I built on OBS (static binary).

**Comment by jimmykarily** [comment]
I don't think the server works outside the cluster in `v0.0.17` either. I mean, the server can probably start but there is no way to point the cli to it. [The comment you sent above](https://github.com/epinio/epinio/issues/582#issuecomment-883428603) shows that `epinio apps list` works as expected. Isn't that enough to tell that it's working?

As long as you build a tagged version of Epinio, you can simply install it as per the docs. You don't need to patch any deployment or anything. The only exception is when we first tag a commit, until the release pipeline is finished and the new images for the epinio server available. But that usually only takes some minutes.

**Comment by malcolmlewis** [comment]
@jimmykarily Hi, perhaps some clarification on the purpose of the server is needed?

In version v0.0.17 if I run from the cli `epinio sever --port 30000` and open a web browser to localhost:30000 I can select the name in the dropdown and the URL is populated in the browser window, click the link and opens the page. Is this not the intended purpose of the server option on the host?

**Comment by jimmykarily** [comment]
The epinio binary is really 2 applications in one. The same binary is both the cli and the server. Have a look at the image here:
https://github.com/epinio/epinio/blob/main/docs/user/explanations/detailed-push-process.md#the-process-visualized

The "Epinio API" box in the image, is actually the epinio binary running the `epinio server` command. The user is running the same binary from outside the cluster in order to talk to the api (e.g. by running the `epinio push` command).

The user is not supposed to run the `epinio server` command ever. When you run `epinio install`, epinio sets up the various components on your cluster. One of them is the epinio API which runs the server.

I hope this clarifies how `epinio server` is used.

**Comment by malcolmlewis** [comment]
@jimmykarily understood now, this issue can be closed then. Perhaps the completion should be removed or a reference in the inline help?

**Comment by jimmykarily** [comment]
Created a PR to improve the inline docs: https://github.com/epinio/epinio/pull/685
