### ISSUE TITLE
CLI should be configurable through environment variables

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#585]
For use from existing CI/CD, we will need to support setting of url, username, and password through environment variables.

**Comment by andreas-kupries** [comment]
Are you talking about the API url, etc ?
What are the use cases you are looking at to need this ?

Note that user and password might already react to EVs.
At least if my reading of
https://github.com/epinio/epinio/blob/c7d14e711666f75d5eb4cd3613c3c17f6708733e/internal/cli/config/config.go#L40-L46
is correct. I.e. might be `EPINIO_USER`, and `EPINIO_PASS`.

The API url ... is effectively `epinio`+systemdomain, and actually pulled out of the epinio ingress in the cluster targeted by the `KUBECONFIG` variable.

**Comment by agracey** [comment]
I'll try this out and see what I can get working.

**Comment by agracey** [comment]
This didn't seem to work, I ended up mounting in a configmap to get something going

**Comment by agracey** [comment]
I'll test this again next week but adding to Beta 3 as it can help with external integrations
