### ISSUE TITLE
Path based routing

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#594]
I'd like to have multiple applications share a hostname with path based routing. 

The obvious use case here is splitting `/api` from `/static`  so UI code is in a different project (built then hosted statically) from the API code. The reason they need to be able to be on the same host is for CORS simplicity.

**Comment by jimmykarily** [comment]
To simplify the command line syntax, let's switch to this:

```
epinio app update sample --route someother.10.86.4.38.omg.howdoi.website/api --route someotherdomain.org
```

Epinio should figure out which part of the `route` is the domain and which is the path.
