### ISSUE TITLE
Remove the broken minikube start instruction from the docs

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#599]

**Comment by manno** [comment]
@rohitsakala tells me this works with the right Kubernetes version. I tested 1.20.6 with the virtualbox driver, which didn't work. 

Also I think we should remove Thulio's ISO image.

**Comment by kkaempf** [comment]
Which part of the documentation is wrong ? I'm mostly testing with minikube (on kvm) and it's working nicely for me.
