### ISSUE TITLE
Write test plan for installing on supported platforms. Automate that plan.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#600]
Like AWS.

**Comment by manno** [comment]
Also maybe a separeate test suite for "installer tests". That tests letsencrypt with a predefined domain? And minikube as well as AWS CI runners for the installer suite?

**Comment by jimmykarily** [comment]
Maybe extend the work started here: #642

**Comment by manno** [comment]
We have a https://github.com/epinio/epinio/tree/main/acceptance/install
and https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)
