### ISSUE TITLE
Generate all passwords.

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#61]
Right now there are hardcoded passwords in various places:

  - [x] [api password](https://github.com/epinio/epinio/blob/main/internal/cli/install.go#L33)
  - [x] [tekton gitea access](https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L373) :arrow_up_down: [gitea setup](https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L135)
  - [x] [tekton registry access](https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L409) :arrow_up_down: [registry setup](https://github.com/epinio/epinio/blob/main/assets/container-registry/chart/container-registry/templates/container-registry.yaml#L8)

Unsure about the tokens below. Are they related to the gitea user/pass ? Derived ?

  - [-] [gitea internal token](https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L152)
  - [-] [gitea jwt token](https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L160)

Some of these services are exposed publicly through Ingress resources and thus make Carrier installation open to malicious users.

Every password we use should be generated and possible to rotate.

If it's too much work, consider splitting the generation and the rotation in 2 different stories.

**Comment by jimmykarily** [comment]
Let's also fix this: https://github.com/epinio/epinio/pull/376#discussion_r632360177

**Comment by andreas-kupries** [comment]
Updated description, links were broken due to development having moved on and moving files.
- gitea went to a slightly different directory.
- eirini is gone in full

**Comment by andreas-kupries** [comment]
# Generation

  - [api password](https://github.com/epinio/epinio/blob/main/internal/cli/install.go#L33)

    Change default to a DynDefault. The func generates a hexified random string
   Need a generator for random strings - https://gist.github.com/dopey/c69559607800d2f2f90b1b1ed4e550fb

  - [tekton gitea access](https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L373) :arrow_up_down: [gitea setup](https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L135)

    Create gitea user/pass deployment options. DynDefaults. Note that doing this also makes them available to the person doing the `ep install`. Rework the gitea and tekton deployments to use the new options.

  - [tekton registry access](https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L409) :arrow_up_down: [registry setup](https://github.com/epinio/epinio/blob/main/assets/container-registry/chart/container-registry/templates/container-registry.yaml#L8)

    The chart has to be modified to export the credentials as chart config variables (values.yaml).
    After that is done we can handle the information as above, with new deployment options.
   Note that we need our htpasswd replacement to generate the string for the auth secret.

In the above all the passwords (or even users and passwords) become deployment options of the `ep install` command.
This can be become unwieldy as more credentials accumulate.
OTOH, this is also an incentive to keep the number of credentials low.

# Rotation

  - Could be an `ep rotate` command taking the same credentials options as `ep install`. 
  - Would have to call on the relevant deployments to re-deploy the parts of the system with the credentials.
  - Sounds a bit like we need an additional method in the Deployment interface, i.e. `Rotate(...)`.

**Comment by manno** [comment]
We generate random strings here, but the random numbers are not cryptographically secure: https://github.com/epinio/epinio/blob/main/internal/api/v1/stage.go#L124-L138

* api password

Epinio CLI could always fetch this via kubectl?
But an API user (curl), would need to know it.

* tekton gitea

Not sure how much Gitea is left, I think the Tekton pipeline just needs a Git URL (server/commit) now, maybe we can add
credentials to that.

* tekton registry
We may have to switch from Tekton Resources (alpha, deprecated?) to Tasks from the [task catalog](https://github.com/tektoncd/catalog/tree/main/task) (supported).
Maybe it's easier to configure the [Kaniko task](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1-to-v1beta1.md#replacing-an-image-resource), than the image resource.


I would argue that we don't need to expose the passwords as options, if the user doesn't enter them manually.
So, we only need to expose the API login as a deployment option?

**Comment by andreas-kupries** [comment]
> We generate random strings here, but the random numbers are not cryptographically secure: https://github.com/epinio/epinio/blob/main/internal/api/v1/stage.go#L124-L138

Interesting.
The https://github.com/thanhpk/randstr I mentioned is very similar.
Moving `uid` into `helper` somewhere should make it more generally available.
Then I do not have to import another external package.

> Epinio CLI could always fetch this via kubectl, maybe? Or does it already?

No. `ep install` stores them into the `EPINIO_CONFIG` file. And of course into the kube resources.

> Most Gitea connections are done from the API now (workspaces, create/delete git repos, commit).

And these connections do not need the [credentials](https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L135) to access gitea ?

> The CLI client does use UserInfo/ServerInfo/Domain from the gitea package. If we switch domain detection (#379) we could get rid of that?

Unable to find these in the code ... Reading more closely I suspect you are talking about `getMainDomain`, `getGiteaCredentials`, and `getGiteaURL`. 

`getMainDomain` should be switchable to use the API ingress instead.
The `getGitea*` functions might still be needed by the server code.
See above, about server actions on the gitea repos.
If the gitea server actions do not require credentials, then we should see to getting rid of them.

> tekton registry

Changing resources to tasks would be a big switch I do not see to be in scope for this ticket.

Exposing as options. If we need the credentials, we need them in both tekton and registry deployments, i.e. both deployments need access to the same information. Currently `kubernetes.InstallationOptions` are the only way to get such data into deployments.

See https://github.com/epinio/epinio/blob/main/internal/cli/install.go#L10

And using these automatically makes them cobra options too.

**Comment by andreas-kupries** [comment]
Created draft PR #405 ... Moved uid into helper package, and made API defaults credentials dynamic.

Next up, investigate the gitea ingress and gitea access credentials more.

**Comment by manno** [comment]
Right, the gitea usage in the client I refered to, was `GiteaClient.ServerVersion()`, `GiteaClient.GetMyUserInfo()` and `GiteaClient.Domain` in client.go.

I would try to hide credentials from the user, that they don't have to know. So we can rotate and generate the credentials more easily. Otherwise you have to ask, "Is that a user-provided value, can I rotate it, how do I show the updated value" and so on. You also have to document and test that then.
Not exposing the Tekton credentials for example, makes it an implementation detail..

**Comment by andreas-kupries** [comment]
Yeah. I have seen GetMyUserInfo now also. (Currently essentially removing the ingress).
Have to check if we still need this. A caller (`check()`) was superfluous already.
Have ideas for hiding the creds from the user.

**Comment by andreas-kupries** [comment]
From the slack, by @jimmykarily :

> @andreas-kupries  fyi the gitea database gets dummy credentials by default too:
> [database]                                  
DB_TYPE = postgres
HOST = gitea-postgresql.gitea.svc.cluster.local:5432
NAME = gitea                                         
PASSWD = gitea                                  
PATH = /data/gitea/gitea.db
USER = gitea   
>
> (found this with: kubectl get secrets -n gitea  gitea -o json | jq -r  '.data["app.ini"]' | base64 -d) Maybe the helm chart allows us to use custom creds.

Investigate now.

**Comment by andreas-kupries** [comment]
The gitea chart's values.yaml contains
```
postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
```
and the `templates/gitea/config.yaml` reads the information.

So, at first glance this looks to be something we can set when we deploy gitea.

**Comment by andreas-kupries** [comment]
See #415 for the change.

**Comment by andreas-kupries** [comment]
I believe that this is done/complete with #418
Well, except for rotation. New issue now, or just keep and new series of PR's ?

**Comment by jimmykarily** [comment]
There are already some ideas about Rotation on this story. Either create a new one, move ideas there and change the title on this one, or continue on this issue with new PRs.

**Comment by andreas-kupries** [comment]
Rotation is deferred now, and captured in ticket #419.
