### ISSUE TITLE
Cert creation issue while trying to install epinio on k3s/d on  Docker for OSX.

### ISSUE THREAD

**Issue by rkazak** [epinio/epinio#610]
I am trying to use epinio on Kubernetes with Docker for OSX.

I get the following error;

`
🚢 Retrying creation of API cert via cert-manager (0/10)
..................
🚢 Retrying creation of API cert via cert-manager (1/10)
............panic: Deployment epinio-registry failed with error: failed trying to create the epinio API server cert: All attempts fail:
#1: conversion webhook for cert-manager.io/v1alpha2, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": x509: certificate signed by unknown authority

goroutine 56 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc00026efc0, 0x2c62350, 0xc00019e000, 0x2c6cdd0, 0xc000104320, 0x2c72ca8, 0xc0007d8980, 0xc0007d8920)
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:150 +0x239
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:147 +0xe59
`

I am running with macOS Catalina, 10.15.7

The following is my Docker configuration

`
(base) rkazak@rkazaknb ~ % docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 21
  Running: 20
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: 6G6I:NN5T:AXOM:WNRO:CWBU:X2XB:Q2TQ:FOXM:CVGT:TXWT:EPRP:DAGU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

And using k3d
`
 k3d --version
k3d version v4.4.7
k3s version latest (default)
`

Attached are the logs from 

`
(base) rkazak@rkazaknb ~ % docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                                                                      NAMES
a6aa9ec0f369   rancher/k3d-proxy:v4.4.7   "/bin/sh -c nginx-pr…"   26 minutes ago   Up 26 minutes   80/tcp, 0.0.0.0:55408->6443/tcp                                            k3d-epinio-serverlb
aa07972f1ade   rancher/k3s:latest         "/bin/k3s server --t…"   26 minutes ago   Up 26 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   k3d-epinio-server-0
(base) rkazak@rkazaknb ~ % 
`

[rancher_k3d_proxy.log](https://github.com/epinio/epinio/files/6805330/rancher_k3d_proxy.log)
[rancher_k3s_latest.log](https://github.com/epinio/epinio/files/6805331/rancher_k3s_latest.log)

Is there anything else I can provide in terms of logs?

**Comment by kkaempf** [comment]
Which version of Epinio are you using ?

**Comment by rkazak** [comment]
(base) rkazak@rkazaknb ~ % epinio version
Epinio Version: v0.0.18
Go Version: go1.16.5

**Comment by rohitsakala** [comment]
This should have been solved by https://github.com/epinio/epinio/commit/5fbab5d0807f44b91e6b73cd777e32ef2fe55e8f.

@rkazak We will be releasing v0.0.19 soon either tomorrow or the day after tomorrow. So you can use that.
