### ISSUE TITLE
Attach Epinio to existing namespaces

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#611]
Being able to attach to existing namespaces would allow allow to do additional setup at cluster creation time. Currently if I create the namespace labels manually, I don't get the secrets copied across.

**Comment by jimmykarily** [comment]
Relevant #434 and #544 . Maybe `epinio target` command should be the one labeling the namespace if not already labeled. Or is this very unexpected?

**Comment by agracey** [comment]
I think the safer option of having a way to explicitly attach a namespace is better since it also adds the linkerd annotations which can break things in very unexpected ways (which I found out the hard way)


I wonder if a `epinio target --attach <existing ns>`  might be a good UI? That way it's the same command, just explicit about what it's doing.

**Comment by agracey** [comment]
It seems reasonable to expect our attach to "take over" the namespace. I don't think users would attach to namespaces with running apps and expect us to somehow partition the management between new and existing deployments...

FWIW, my personal use case is specific to allowing Fleet to create the NS and populate it with secrets/services.

**Comment by agracey** [comment]
@jimmykarily From what I can tell, the only thing blocking me from just adding the right labels to a namespace is that an org needs to also be created in gitea. Will a move to minio remove this constraint?

**Comment by jimmykarily** [comment]
Yes, with a move to minio/S3/other, that constraint is gone. I see we also copy a secret and we create a service account in the new namespace: https://github.com/epinio/epinio/blob/main/internal/organizations/organizations.go#L78-L109

So simply adding the labels/annotations won't be enough.

**Comment by agracey** [comment]
Added to Beta 3 as this might be more relevant with some Rancher integrations
