### ISSUE TITLE
Out of the box TLS for Applications

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#62]
One of the thing that most users find tedious and confusing is how to enable TLS for their application. There are various ways to do this but some are already popular in the Kubernetes world (see links below).

From the user's perspective, any application that is deployed on Carrier should get an https url with a proper certificate, suitable for production use.

Rancher Rio has solved this in an interesting way (that resembles what Heroku does): https://rancher.com/blog/2019/rio-revolutionizing-the-way-you-deploy-apps#automatic-dns-tls

We need to decide which option is the best for Carrier and implement it.

Links:
- https://doc.traefik.io/traefik/https/acme/
- https://cert-manager.io/docs/installation/kubernetes/

**Comment by agracey** [comment]
cert manager seems to be the "kubernetes native" way to do this and I think a [selfsigned cert](https://cert-manager.io/docs/configuration/selfsigned/) is a fine default as long as we allow for easy configuration of other signers (namely Lets Encrypt)

**Comment by jimmykarily** [comment]
Epinio (previously "Carrier") already creates let's encrypt certificates for applications. We could support other signers (e.g. #63 ) but this story can be closed.
