### ISSUE TITLE
Epinio cli should work without kube access

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#620]
There are some commands that will always need access to the kube api. E.g.
- epinio install
- epinio config update-credentials

These are considered "admin" commands. Regular epinio users should not have to run those commands. This means, all the commands that are not "admin" commands should be possible to run with no access to the kubernetes cluster. That is, with no kubeconfig in place.

Right now Epinio is still talking to the kube api for various other reasons. E.g. for shell autocompletion (find available services/apps/etc) or in order to discover the Epinio API by looking up for the ingress.

## Acceptance Criteria

- All the code that fetches information from the cluster by talking to kube is migrated to API endpoints
- No API endpoint autodiscovery happens. There should be a command to target an instance of Epinio (e.g. `epinio login`). This command should update the epinio config file if run successfully. This command is an alternative to running `epinio config update-credentials` as an admin. It can be used when no kubernetes cluster access is possible.

**Comment by agracey** [comment]
This seems like a good change to make as part of the work for multiple users

**Comment by malcolmlewis** [comment]
Hi
This would also enable the rpm completions package to build without needing kubectl as part of build requires. There is a bit of a disconnect with kubectl on openSUSE/SLE (different repos in use) except Tumbleweed.

**Comment by agracey** [comment]
I think this is a dup of #508, right?

**Comment by jimmykarily** [comment]
Yes. Although #508 is older, I will keep this one because the description feels a bit more detailed.

**Comment by manno** [comment]
> No API endpoint autodiscovery happens. There should be a command to target an instance of Epinio (e.g. epinio login). This command should update the epinio config file if run successfully. This command is an alternative to running epinio config update-credentials as an admin. It can be used when no kubernetes cluster access is possible.

Not sure I understand that acceptance criteria. Is that about the API endpoint and handled by https://github.com/epinio/epinio/issues/681?
Then that new `login` command would allow the user to set url/user/pass in the epinio.yaml config.

**Comment by jimmykarily** [comment]
> > No API endpoint autodiscovery happens. There should be a command to target an instance of Epinio (e.g. epinio login). This command should update the epinio config file if run successfully. This command is an alternative to running epinio config update-credentials as an admin. It can be used when no kubernetes cluster access is possible.
> 
> Not sure I understand that acceptance criteria. Is that about the API endpoint and handled by #681?
> Then that new `login` command would allow the user to set url/user/pass in the epinio.yaml config.

Yes. #681 only allows you to change the values in the config file by calling the kube api and discovering the API url automatically. The user should be able to target an installation of Epinio even with no Kube API access. This "login" command will allow you to set the values in the config and also verify that these values work (so it's not simply editing the file but also verifying that they work).

**Comment by andreas-kupries** [comment]
Status of command completion for commands:

|Command		|Functions					|
|---			|---						|
|target			|OrgsMatching					|
|app create		|AppsMatching	??				|
|app show		|.						|
|app update		|.						|
|app delete		|.						|
|app env list		|.						|
|app env set		|.						|
|app env show		|.						|
|app env unset		|.						|
|service delete		|ServiceMatching				|
|service show		|ServiceMatching, EnvMatching			|
|service bind		|ServiceMatching, AppsMatching			|
|service unbind		|.						|
|service create		|ServicePlanMatching, ServiceClassMatching	|
|service list-plans	|ServiceClassMatching				|

|Function		|Status			|API				|
|---			|---			|---				|
|AppsMatching		|:fire:			|				|
|EnvMatching		|:heavy_check_mark:	|EnvMatch(org, app, prefix)	|
|OrgsMatching		|:heavy_check_mark:	|Orgs()				|
|ServiceClassMatching	|:fire:			|				|
|ServiceMatching	|:fire:			|				|
|ServicePlanMatching	|:fire:			|				|

After that is done a larger code review has to go over all client commands (except server) and check that all code reached from them does not shell out to `kubectl`, `helm`, etc., nor uses an internal kube client.

... Might actually be easiest to handle by removing the `Cluster` field from the client structure. This will break all placing using a cluster client on compile, and then we can work upwards to see if that is called from client commands. If yes changes are needed. (Initial: Marking the places). And server side uses can simply get the cluster client via the memoized `GetCluster`.

**Comment by andreas-kupries** [comment]
Removing the `Cluster` field:

> internal/cli/clients/client.go:84:3: unknown field 'Cluster' in struct literal of type EpinioClient
internal/cli/clients/client.go:809:15: c.Cluster undefined (type *EpinioClient has no field or method Cluster)
internal/cli/clients/client.go:810:23: c.Cluster undefined (type *EpinioClient has no field or method Cluster)
internal/cli/clients/client.go:1560:38: c.Cluster undefined (type *EpinioClient has no field or method Cluster)
internal/cli/clients/client.go:1566:33: c.Cluster undefined (type *EpinioClient has no field or method Cluster)
internal/cli/clients/push.go:140:34: c.Cluster undefined (type *EpinioClient has no field or method Cluster)
internal/cli/clients/push.go:175:10: c.Cluster undefined (type *EpinioClient has no field or method Cluster)

Lets work through that.

**Comment by andreas-kupries** [comment]
A last point, as far as I can tell at the moment:

> internal/domain/domain.go:15:func MainDomain(ctx context.Context) (string, error) {
internal/domain/domain.go:20:	cluster, err := kubernetes.GetCluster(ctx) // Push -> MainDomain -> here (client-side! FIXIT?)
internal/cli/clients/client.go:1504:	mainDomain, err := domain.MainDomain(ctx)
internal/api/v1/deploy.go:105:	mainDomain, err := domain.MainDomain(ctx)
internal/api/v1/stage.go:174:	mainDomain, err := domain.MainDomain(ctx)

The `domain.MainDomain()` determines the main domain of an application.
It access the cluster, specifically the epinio ingress to determine the information.
It used both client- and server-side.

Clientside this is used (in `Push`) to determine the app's default route.
In the turn the route is sent to the server for both stage and deploy requests.
  - `deploy`: Takes the new route, passes it to the code generating the kube deployment.
    It also recomputes the domain and adds it to the params. The kube deployment ignores both.
    The route is used when creating the ingress.
    Nothing else seems to use the server side domain.
  - `stage`: Ignores the route passed into it. The locally computed main domain is used to compute the registry url

Current thinking:

- Drop the route calculation client side, do not pass it to staging, nor deployment.
- As the route is shown at the end of push, have it returned in an extended deploy response.
- With that change route calculation becomes confined to server side, where we can keep using the existing MainDomain function, asking the ingress.
- `stage` is modified to get rid of route information in its request.
- `deploy` is modified to remove route from request and params, to calculate the route from the main domain and return it, and use it for the creation of the ingress as before.
