### ISSUE TITLE
Epinio is tested on AWS EKS

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#625]
We should try Epinio on AWS (EKS). If there are any problems we create issues for them.

## Acceptance Criteria

- Install Epinio on AWS (EKS)
- The way to setup Epinio on EKS (as production-ready as possible) is documented in the repo.
- [Optional] Epinio acceptance tests have been run on AWS (EKS) successfully (one-off).

**Comment by svollath** [comment]
Even after several tries and debugging, I wasn't able to run the test suites against an existing epinio installation with custom domain. Therefore reported https://github.com/epinio/epinio/issues/696.

Since tests for AWS EKS are marked optional, I created https://github.com/epinio/epinio/pull/695.
