### ISSUE TITLE
I could not install epinio on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by alpushkarev** [epinio/epinio#634]
root@k3d:~# epinio install --system-domain=172.18.0.2.omg.howdoi.website

🚢 Epinio installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain: 172.18.0.2.omg.howdoi.website
  🧭  email_address: epinio@suse.com
  🧭  user: 97641b2050054cb6
  🧭  password: 4f03fab008f1383b

🚢 Deploying Linkerd...
✔️  Linkerd deployed

⚠️  System Ingress present, skipping

✔️  Created system_domain: 172.18.0.2.omg.howdoi.website

🚢 Deploying CertManager...
🚢 Deploying Epinio...
🚢 Deploying Quarks...
🚢 Deploying Gitea...
🚢 Deploying ServiceCatalog...
🚢 Deploying Tekton...
🚢 Deploying Registry...I0721 11:41:08.919302 1174054 request.go:655] Throttling request took 1.10081274s, request: POST:https://0.0.0.0:42187/api/v1/namespaces
............................
✔️  Quarks deployed
...............................................................................................................................................................................................................................................
✔️  Registry deployed
.........................................
✔️  ServiceCatalog deployed
.............................
🚢 retrying to create the epinio cert using cert-manager
................panic: Deployment epinio failed with error: failed trying to create the epinio API server cert: All attempts fail:
#1: creation of local ssl certificate failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
#2: creation of local ssl certificate failed: conversion webhook for cert-manager.io/v1alpha2, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": x509: certificate signed by unknown authority

goroutine 19 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc000214fc0, 0x20473f0, 0xc00003e0a0, 0x2051b70, 0xc000081cc0, 0x2057660, 0xc0002e2b20, 0xc0002e2b10)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:167 +0x239
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:164 +0xf45
===============================
root@k3d:~#  k3d --version
k3d version v4.4.7
k3s version v1.21.2-k3s1 (default)

root@k3d:~# epinio version
Epinio Version: v0.0.17
Go Version: go1.16.5

**Comment by kkaempf** [comment]
Your version of Epinio is over a month old. Latest releases version is `0.0.18` and we hope to release `0.0.19` real soon.

**Comment by jimmykarily** [comment]
0.0.19 is supposed to fix it. Stay tuned. We are trying to get this in: https://github.com/epinio/epinio/issues/574
We are finishing the review and then it's release time :).

**Comment by alpushkarev** [comment]
Thx

**Comment by alpushkarev** [comment]
Unfortunately v0.19  didn’t fix the issue

  
>Среда, 28 июля 2021, 17:11 +03:00 от Andrew Gracey ***@***.***>:
> 
> 
***@***.*** Did the 0.19 release fix your issue?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Alex Push

**Comment by andreas-kupries** [comment]
Is that the same cluster as used for #651 ?

When you tried with version 0.0.19, did you use a fresh cluster ?
Did you reuse the pre-0.0.19 cluster ?
If yes to the last, did you uninstall epinio before trying 0.0.19 ?
(Versus trying install over the old version ? (Which we do not support))

**Comment by alpushkarev** [comment]
fixed in v.0.21
k3d:~# epinio info

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.21.2+k3s1
Gitea Version: unavailable
Epinio Version: v0.0.21

**Comment by jimmykarily** [comment]
Glad to see that your issue was resolved. I'll close this now, but feel free to re-open or open a new issue if you face any more issues. Thanks for contributing to Epinio.
