### ISSUE TITLE
Traefik chooses .0 address on a /24 network (with minikube)

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#635]
This is a follow-up from #194 (which was about podman) to raise the traefik routing problems.

#### Environment

* Epinio v0.0.18-128-g8abd884
* Minikube 1.22.0
* openSUSE Tumbleweed

The k8s version doesn't seem to matter, I see the same problem with 1.19.13, 1.20.9, and 1.21.3

#### Installation

I install Epinio from source, `make build` and `make install` run without issues.

#### Problem

Any Epinio command can't talk to epinio-server, like
```
> epinio apps list

🚢 Listing applications
Organization: workspace
error listing apps: Get "https://epinio.192.168.49.0.omg.howdoi.website/api/v1/orgs/workspace/applications": dial tcp 192.168.49.0:443: connect: network is unreachable
```

#### Services

`kubectl get svc -A` shows
```
traefik     traefik     LoadBalancer   10.110.160.102   192.168.49.0   80:32148/TCP,443:30746/TCP       16m
```
as the only service with an external IP.

**Comment by kkaempf** [comment]
The network address is strange. The interface has 192.168.49.1:
```
15: br-951b05ee1fc3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:45:4b:68:12 brd ff:ff:ff:ff:ff:ff
    inet 192.168.49.1/24 brd 192.168.49.255 scope global br-951b05ee1fc3
       valid_lft forever preferred_lft forever
```
and `.kube/config` shows
```
    server: https://192.168.49.2:8443
```

**Comment by kkaempf** [comment]
k3d does not expose this problem

**Comment by manno** [comment]
Added a story to add docs https://github.com/epinio/epinio/issues/752

**Comment by jimmykarily** [comment]
I added this issue in the acceptance criteria of #752 . I'm closing this.

**Comment by kkaempf** [comment]
An upgrade to minikube [v1.23.0](https://github.com/kubernetes/minikube/releases/tag/v1.23.0) does not improve the situation.

**Comment by manno** [comment]
A few notes:

Epinio has some logic to guess the “domain” (`fillInMissingSystemDomain`), if `--system-domain` was not used.
 
The code is a bit similar to `kubectl get svc -n traefik traefik -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'`, but across all namespaces: https://github.com/epinio/epinio/blob/main/internal/cli/admincmd/install_client.go#L511-L524


(Not sure why that looks in all namespaces, the print system domain code we have in `traefikServiceIngressInfo` only looks in the traefik namespace: `kubectl get svc -n traefik -l app.kubernetes.io/name=traefik -o 'jsonpath={.items[0].status.loadBalancer.ingress}'`)

**Comment by juadk** [comment]
Thanks @manno for the notes.
Yesterday I managed to install Epinio with two different ways:
1. Force the load-balancer IP like this:
`epinio install --loadbalancer-ip 192.168.49.3`
2. Use the minikube tunnel feature without setting metallb
I don't think they are the good things to document, it's rather workarounds.
However, I still don't know why Traefik chooses .0 address, isn't it something in the Traefik code?
If I understand correctly the Epinio's code, we just select the IP chosen by Traefik, maybe I can check where we configure Traefik. 
WDYT?
