### ISSUE TITLE
linkerd install fails because 'ConfigMap/linkerd-config already exists.'

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#638]
`epinio install` (v0.0.19) on minikube fails with

> Can't install the Linkerd control plane in the 'linkerd' namespace. Reason: ConfigMap/linkerd-config already exists.  

for the `linkerd-install` container (from `splatform/epinio-linkerd:2.10.2`)

**Comment by kkaempf** [comment]
This happens with minikube, k3d is not showing this problem.

**Comment by rohitsakala** [comment]
@kkaempf Could not reproduce this on minikube. Can you recheck?

**Comment by kkaempf** [comment]
Seems to be fixed, cannot reproduce either.
