### ISSUE TITLE
With default settings, ingress is looking for wrong secret name

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#639]
When I push an app, the ingress that gets created expects a tls-secret with the name of `<FQDN>-tls`. The secret that gets created is `<app name>-tls`. This is leading to traefik to not set up the route. 

If I update the secret name manually, it works as expected. (Although it looks like it might still be a self-signed cert?)

I installed Epinio 0.0.19 using `epinio install` onto a k3s 1.20 cluster.

**Comment by agracey** [comment]
Ok, more interestingly, this only causes issues on my k3s 1.20 cluster and not my rancher desktop/k3s 1.21 cluster. 

I wonder if this is a difference in traefik versions?

**Comment by agracey** [comment]
It seems like Traefik 1.x fails to add the route whereas Traefik 2.x will still allow traffic through even though it can't find the cert.

![image](https://user-images.githubusercontent.com/442274/126670650-d42f4613-ed2a-4dc7-9c18-cede45d67227.png)

**Comment by agracey** [comment]
For that route, I'm getting the traefik default cert:

![image](https://user-images.githubusercontent.com/442274/126670900-a0d53ef9-55ab-49e8-985b-ed71cb326d4b.png)

**Comment by andreas-kupries** [comment]
PR #656 should fix this.
