### ISSUE TITLE
Gitea PostgreSQL fails to create /bitnami/postgresql directory - permission denied

### ISSUE THREAD

**Issue by rssfed23** [epinio/epinio#641]
Following the k3d quickstart 
MacOS 
Docker CE 20.10.7
k3d v4.4.7
Single node using rancher.io/local-path storage driver (default)

Gitea fails to deploy. Specifically, the gitea postgres container fails to deploy with the following in the logs:
```
│ postgresql 12:29:51.56 INFO  ==> ** Starting PostgreSQL setup **                                                                                                     │
│ postgresql 12:29:51.57 INFO  ==> Validating settings in POSTGRESQL_* env vars..                                                                                      │
│ postgresql 12:29:51.58 INFO  ==> Loading custom pre-init scripts...                                                                                                  │
│ postgresql 12:29:51.58 INFO  ==> Initializing PostgreSQL database...                                                                                                 │
│ mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied                                                                                              │
│ postgresql 12:29:51.59 INFO  ==> Stopping PostgreSQL...
```

Not sure if this relates to https://github.com/epinio/epinio/issues/615, but as different platform logging here.

**Comment by andreas-kupries** [comment]
Attempting to reproduce failed for me.
Data points from description and my attempts, in tabular form:

|OS|Docker|k3d|Epinio|Result|
|---|---|---|---|---|
|MacOS|20.10.7|4.4.7|?| :boom: |
|Linux|20.10.6-ce|4.4.4|v0.0.19-33-g2de03c8| :heavy_check_mark: |
|Linux|20.10.6-ce|4.4.7|v0.0.19-33-g2de03c8| :heavy_check_mark: |
|Linux|20.10.6-ce|4.4.7|v0.0.19| :heavy_check_mark: |
|Linux|20.10.6-ce|4.4.7|v0.0.18| :heavy_check_mark: |

Differences left to the original report: OS, Docker version, maybe Epinio version.

What version of Epinio did you use ?
Do you have a Linux box available to test with and compare ?

**Comment by agracey** [comment]
This is an issue with HostPath and NFS volumes. I just opened https://github.com/epinio/epinio/issues/684

**Comment by kkaempf** [comment]
I see this now in Windows with Rancher Desktop (RD) v0.4.0. It didn't happen with RD v0.3.0

**Comment by kkaempf** [comment]
> This is an issue with HostPath and NFS volumes. I just opened #684

Not sure about this.

A local build with this patch

```
--- a/deployments/gitea.go
+++ b/deployments/gitea.go
@@ -202,7 +202,7 @@ postgresql:
        defer os.Remove(configPath)
 
        if out, err := helpers.RunProc(currentdir, k.Debug,
-               "helm", action, "gitea", "--values", configPath, "--namespace", GiteaDeploymentID, giteaChartURL); err != nil {
+               "helm", action, "gitea", "--values", configPath, "--set", "volumePermissions.enabled=true", "--namespace", GiteaDeploymentID, giteaChartURL); err != nil {
                return errors.New("Failed installing Gitea: " + out)
        }
```
does **not** fix this problem.

**Comment by jandubois** [comment]
@kkaempf Since you are deploying postgresql as a subchart, you have to prefix any value changes with the subchart name:

```
... --set postgresql.volumePermissions.enabled=true ...
```

**Comment by jandubois** [comment]
FWIW, postgresql deployed fine for me with Rancher Desktop 0.4.0 on macOS even without the permissions change, but it should be safer to always include that setting.

**Comment by kkaempf** [comment]
Confirmed fixed, postgresql runs nicely now. But lead to #732 😠 🤦🏻‍♂️
