### ISSUE TITLE
Windows installation fails with: unknown flag --enable-certificate-owner-ref

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#659]
#### Environment

- Windows 10
- k8s 1.19.x, installed via Rancher Desktop v0.3.0
- Epinio v0.0.19

#### Problem

`epinio install` fails installing CertManager with `unknown flag --enable-certificate-owner-ref`:

![epinio-windows](https://user-images.githubusercontent.com/37742/128140218-16a0f319-b6f8-4c76-9095-54df8e3e1a8e.jpg)

**Comment by andreas-kupries** [comment]
Fixed by #663
