### ISSUE TITLE
Windows binary should default to "--no-colors"

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#660]
As Windows cannot [display emojies](503) or handle [color output](659) in a reasonable way, the `--no-colors` flag should default to `true` in Windows.

**Comment by agracey** [comment]
Isn’t this really a bug on windows terminal? 😇

**Comment by mook-as** [comment]
FWIW, [Windows Terminal](https://www.microsoft.com/en-ca/p/windows-terminal/9n0dx20hk701) supports colours and emoji, but the old [console host](https://docs.microsoft.com/en-us/windows/console/ecosystem-roadmap#windows-console-host) doesn't.

I think you may be able to call [`GetConsoleMode`](https://docs.microsoft.com/en-us/windows/console/getconsolemode) to check if those are available? Not sure here…

**Comment by andreas-kupries** [comment]
@agracey @mook-as See https://github.com/epinio/epinio/issues/673#issuecomment-897492832

**Comment by andreas-kupries** [comment]
Upstream ticket https://github.com/mattn/go-colorable/issues/58

**Comment by kkaempf** [comment]
Confirmed working in #671

**Comment by andreas-kupries** [comment]
Got a [patch from upstream](https://github.com/mattn/go-colorable/issues/58#issuecomment-897683350) for our color issues. We used the `color` package incorrectly to be portable.

Patch is applied, confirmed working. Given that I am moving this ticket now to `wontfix` as now generally defaulting to colors will work in the Windows terminals as well.
