### ISSUE TITLE
Release script creates wrong impression for "fixed bugs"

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#665]
Generating a new release seems to take all lately closed issues as input for the "fixed bugs" list.

As it happened with the [v0.0.20 release](https://github.com/epinio/epinio/releases/tag/v0.0.20), this makes issues like #194 appear as fixed while it actually was 'closed, documented unfixed'.

Adding to 'beta' milestone since this should be fixed latest with the beta release.

**Comment by jimmykarily** [comment]
We should label issues better and then we should read the release notes and fix whatever is wrong. I don't think we could make the automation a lot smarter.
