### ISSUE TITLE
Set flag to fix postgres volume permissions

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#684]
We should set the `volumePermissions.enabled=true` flag when installing the postgres for gitea.  This would fix potential issues with hostpath and nfs volumes.

See: https://github.com/rancher-sandbox/rancher-desktop/issues/502#issuecomment-898563507

**Comment by kkaempf** [comment]
Do we have a reported case why this is needed ? How can we test that this actually fixes a problem ?

**Comment by agracey** [comment]
Yes, I can no longer install on Rancher Desktop and Rob hit the same issue in: https://github.com/epinio/epinio/issues/641

This can be tested by installing the bitnami postgres chart by itself to see the same error.

**Comment by kkaempf** [comment]
Then I'd close this as a duplicate of #641 ?!

**Comment by kkaempf** [comment]
Closing in favor of #641
