### ISSUE TITLE
Install tests: setup persistent AWS cluster for tests.

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#687]
(tests will epinio uninstall to remove resources)

In order to create the tests for `load-balancer-ip` and in order to test on AWS (https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)) we need to have access to a permanent cluster.

# Acceptance Criteria

- There is a way (script or docs) to create the cluster on AWS
- One the install tests (new or existing) on that cluster
- The cluster is cleaned up and re-used every time
- There is no way to run 2 jobs at the same time on the same cluster (each one messing the other job's results).

Consider these solutions for the first item above:

- https://github.com/suse/catapult
- other? (@kkaempf)
- custom script

**Comment by rohitsakala** [comment]
Cost Estimation 

Assumption - We run the EKS test every day once.

| Resources | Cost/Hour | Qty | Cost/Month |
| ------------- | -------- | ---- | ----------- |
| 1. EKS Control Plane   | 0.10$      | 1    | ~73$ |
| 2. EKS Worker Nodes (Spot Instances) | 0.0499$ | 2   | ~73$ |
| 3. EKS Storage - 40 GB   |  0.005$  |    2 | 8.80$ |

Two Scenarios
| Cluster Always Running |  Create & Delete ( 1 hour / Day ) |
| --------- | --------|
|  ~155$/month | ~7$/month  |

**Comment by jimmykarily** [comment]
This is done. We will followup with a story to implement the test. For now we just have a way to create the cluster.
