### ISSUE TITLE
Document how to set up DNS for a custom system domain

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#689]
Questions to answered:

- Do I need a wildcard domain (and why)?
- What kind of record do I need (A one, CNAME one?)

**Comment by manno** [comment]
System domain is always a wildcard domain (?), documentation should mention that.
Maybe document an example (bind style) config for such a domain.

Are there alternatives to a wildcard domain? Maybe explain how the default 'magic' domain is different from a wildcard domain (it resolves entries like <name>.<ip>.domain to <ip>).

**Comment by svollath** [comment]
Decided for a doc restructure - finally information on how to setup DNS is covered in "install_epinio_customDNS.md"

The current branch https://github.com/epinio/epinio/tree/svollath-doc-restructure isn't complete (missing RKE2 still), and I need to fully review it for myself again, before creating a PR (most likely also from a cleaner branch, then).

Up to now I did
- introduce "System Requirements"

Reduced doubled documentation texts, by
- split off "Epinio CLI Installation"
- split off "magicDNS Installation"
- split off "customDNS Installation"

Linking from
- Install*DNS -> System Requirements, Install CLI
- Install CLI -> System Requirements, Install Dependencies
- Cluster Installs -> Install magicDNS and/or Install customDNS

**Comment by svollath** [comment]
Dropped idea for current RKE2 addition due to issue https://github.com/epinio/epinio/issues/722 - covered in issue #747 .

Made clean branch https://github.com/epinio/epinio/tree/svollath-doc-restructure-clean for review in PR https://github.com/epinio/epinio/pull/748 .

**Comment by svollath** [comment]
https://github.com/epinio/epinio/pull/748 was merged
