### ISSUE TITLE
Application names should map to "safe" URLs

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#690]
Right now application names like `12factor` can't be used because they result in a route like `12factor.omg.howdoi.website` which is not a valid url (because it starts with a number?).

We need some small library that generates url-safe routes for an application given the application name.
Ideally the route should still have a part of it that looks like the application name so it's easy to tell which application this route belongs too.

**Comment by manno** [comment]
```

Deploying application ...
error pushing app to server: can't deploy app: Internal Server Error: {"errors":[{"status":500,"title":"Service \"12factor\" is invalid: metadata.name: Invalid value: \"12factor\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","details":""}]}
```

Same problem with capital letters.


`Sanitize` code from quarks-utils: https://github.com/cloudfoundry-incubator/quarks-utils/blob/master/pkg/names/names.go#L39-L46

**Comment by andreas-kupries** [comment]
I do not see the referenced code helping with the leading `1` of `12factor`. I.e. it will not be removed or otherwise hidden (Prepend with an `a` or other alpha character).

**Comment by andreas-kupries** [comment]
Code locations:

- https://github.com/epinio/epinio/blob/99b98c09c15d7a7c61e5e32aaf211c656b11b78a/internal/cli/clients/client.go#L1337 (push command backend, client-side)
- https://github.com/epinio/epinio/blob/99b98c09c15d7a7c61e5e32aaf211c656b11b78a/internal/cli/clients/client.go#L1499-L1505 (work function, also client-side)

**Comment by andreas-kupries** [comment]
Nope. This is __not about routes__.
The error message references the `metadata.name` of the app service.
I.e. of a kube object.
It is just that the object name is apparently used for kube internal DNS.

We already have a function to generate names which keep to the length limit (see `names.GenerateDNS1123SubDomainName`).
TODO is handling leading digits, capital chars, underscores, etc.

This has to be applied to the app Service, and Ingress. And of course the places where these are referenced.
