### ISSUE TITLE
Replace gitea with S3 compatible storage

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#699]
Right now, in Epinio v0.0.21, the process of uploading and staging the code is as follows:

- The cli uploads the code as a tarball.
- The server endpoint extracts the tarball and pushes it to Gitea
- When the cli asks the code to be staged, the tekton pipeline is creating a temporary PVC to be used as the `source` tekton workspace (https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#volumeclaimtemplate). That PVC is deleted when the PipelineRun is deleted (which happens when the next staging process succeeds).

In order to implement build cache (https://github.com/epinio/epinio/issues/688) we will need to make the PVC for the sources a permanent PVC which will not be automatically deleted as above, but we will rather need to manage its lifecycle in our code (e.g. delete it when the app is deleted etc). See the linked issue for more details.

Having a permanent PVC that has a copy of the application’s code makes Gitea feel a bit redundant. Instead of storing the code on Gitea when the cli uploads it, we could directly store it on that permanent application PVC. We can then make the sources available to the tekton pipeline using the `sources` workspace (https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#using-persistentvolumeclaims-as-volumesource) without any need for a “clone” Task.

Such a solution allows us to get rid of Gitea which is currently only acting as a storage for code. There are some things we need to think about though, namely:

- What do we replace the gitref with? Possibly a UUID or anything that won’t create conflicts should do.
- Is staging faster this way? Probably yes, because we don’t need to clone anything and the code for staging is living on a PVC (like it did before, after cloning)
- Is the “upload” endpoint faster?
- Is there any limit on how many PVCs we can have? Is one PVC per app prohibiting? Even if there is a limit, we would face that problem anyway, since the tekton pipeline right now, creates a PVC for each PipelineRun (so minimum one PVC per pushed app).
- Where does a PVC live in kubernetes? Do we need any “placement” rules to make sure source code transactions are as fast as possible?
- How will this work in the future, when/if we implement rollbacks for apps?
- Does the new solution take up more disk space in total than what we currently have?

Regarding the last item, here is a comparison:

Gitea:

- Gitea deployment size - flat size, doesn’t increase with the number of apps
- One git tree per pushed application - depending on the types of changes on the source code, this can be from a little larger than a “flat” checkout of the code to seriously larger (e.g. if big blobs have been removed at some time in history)
- One PVC per PipelineRun - Full clone of the same git repo (or a shallow copy?)

So worst case scenario: 2 full git clones + gitea deployment size

PVCs:

- One “shallow” copy of the source code per pushed app - multiplied by the number of previous versions we want to keep around (e.g. when we implement rollbacks). While a new push is happening we will need 2 copies of the code for some time (before we delete the old copy upon successful staging).

One of the problems with the suggested solution is, how do we get the uploaded tarball (the "upload" request) written in the application PVC. The code runs inside the epinio server pod and that pod doesn't have that PVC bound. We probably need some temporary pod with the PVC mounted to which we will send the file over. This should be fast and secure. It should also handle the cases when something goes wrong and not leave partly copied code around that will break some next staging.

**Comment by manno** [comment]
mounting volume from multiple  pods: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by kkaempf** [comment]
We should add a `post-beta1` label to this :wink:

**Comment by agracey** [comment]
Would this help the upgradability as it removes our responsibility for maintaining statefulness? If so, let's put it after the multi-user story and before the declarative install (as it might make that easier as well?)

For "What do we replace the gitref with?", would UUIDv5 make sense?


I don't see any issues upfront, but another concern to be aware of is making sure we don't make HA and DR too difficult. If a cluster fails, can we come back online without needing to repush anything manually?

**Comment by agracey** [comment]
Also, if there's a component that we can build to help with volume creation and loading in a single step, that might be useful in a larger context.

**Comment by jimmykarily** [comment]
I found this: https://thenewstack.io/beyond-block-and-file-cosi-enables-object-storage-in-kubernetes/ (more details here: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1979-object-storage-support). So the future looks bright.

We are not there yet though so I was reading this: https://cloud.redhat.com/blog/how-to-backup-clone-and-migrate-persistent-volume-claims-on-openshift and it just hit me that we can do the same. We don't need to have the application PVC mounted on the epinio server pod in order to copy the data. We can spin up a Job/Pod that has that PVC mounted, plus one more PVC which is always mounted on the epinio server (as a common filesystem between the epinio server and the "copying" pod). The process is as follows:

- `epinio install` makes sure there is a PVC mounted on the epinio server pod
- when the user uploads the code of an application (the "upload" API endpoint), the epinio server puts the application code on a directory on that PVC
- the epinio server starts a Job/Pod that has 2 PVC mounted: the one that has the application code and the new one where the application code should be transfered.
- the Job/Pod copies the code from one PVC to the other and returns.
- The epinio server cleans up the application code from its "source" PVC.

We need to check the limitations on mounting multiple PVCs on one Pod (the links Mario provided above).
Also the epinio server PVC will require enough space to hold all the applications that are being uploaded in parallel so it introduces a limitation on how many apps can be deployed in parallel. Lastly, that PVC will allow access to any application's code from any copying Job/Pod that is running in parallel (different directories only?). Given the epinio code is responsible for all the copying, I don't think that is a security issue (we don't run any third party code).

**Comment by jimmykarily** [comment]
Another option is for the epinio server to spin up a pod that acts as a server (even running a minio server) and send it the file over. That pod/server should have the PVC mounted and should store the file there. Spinning up a minio server seems simple: https://docs.min.io/minio/baremetal/

This may be better than running a long lived minio server because we can have on PVC per app instead of one PVC backing minio for every application. Not sure which is better.

**Comment by jandubois** [comment]
> even running a minio server

I thought we are supposed to avoid AGPL components, and MinIO is AGPLv3 now...

**Comment by jimmykarily** [comment]
Any solution that needs 2 PVCs mounted on the same pod, is affected by these limitations: https://kubernetes.io/docs/setup/best-practices/multiple-zones/#storage-access-for-zones . In other words, we can't be sure that both PVCs are within the same zone, thus kubernetes may not be able to schedule the Pod.

Not mounting 2 PVCs means we need to send over the file over the network, which very much sounds like an object storage solution (like minio or other). I tried to come up with an idea that works with mounted PVCs and copying files between them but in every case, some Pod must have 2 PVCs mounted at the same time (so limited by the above restrictions).

There are other S3 compatible, software defined, object storage solutions that are not GPL but minio is by far the most popular. Others I found:

- https://lakefs.io/
- https://github.com/scality/cloudserver
- http://openio.io/
- https://ceph.io/ceph-storage/object-storage/ (yes Ceph!)
- more...

In various links:

- https://betterprogramming.pub/4-open-source-object-storage-platforms-for-2021-ceeaceb7e273
- https://www.google.com/search?client=firefox-b-d&q=S3+compatible+open+source+object+storage

**Comment by jandubois** [comment]
> * more...

Not sure why SeaweedFS doesn't have more Google-juice, but it has 10× the number of Github ★s (13K) than any of the projects listed above (and is Apache licensed):

https://github.com/chrislusf/seaweedfs

**Comment by jimmykarily** [comment]
Thanks for adding seaweedfs to the list @jandubois , it looks like  good candidate. They only dowside I see is that it needs a database for the "filer": https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files . That's where the metadata for the files are stored (e.g. which volume the file lives in). Gitea's database was one of the most resource hungry pods in an Epinio installation. We don't want to replace it with another resource hungry database. Still, maybe it's worth a try.

Like @manno suggested in Slack, if the solution we pick is S3 API compatible, we can allow the user to opt out for another compatible solution in the future. E.g. during installation, the epinio operator could decide to use AWS S3 instead, which should completely skip Minio/seaweedfs/whatever installation altogether.

**Comment by manno** [comment]
I installed minio manually via the operator (https://gist.github.com/manno/8cdffe67081ac0294d57b7e955b0e0a5#file-create-minio-sh).

An initial push with the internal blob store worked.

TODO

- [x] API: Replace StageID / BlobUID
- [ ] Install default blobstore, unless external settings
- [ ] MiniIO, multiple versions bug?
- [x] Tekton, add endpoint protocol
- [ ] Drop Git push, `epinio push git://`
- [x]  S3 secret, can't see any better way, as aws-cli requires inifile config and we don't want to dupe.
- [ ] Rename s3manager.S3ConnectionDetails -> s3manager.Settings maybe?

**Comment by jimmykarily** [comment]
Using the gist from @manno above, minio no longer shows that bug with the multiple copies of the same object. It seems that's the right way to deploy minio. The latest commit that differentiates between stage ID and blob UID seems to have broken the cleanup code (I still see the old object after pushing the app again successfully) . Needs fixing.

**Comment by jimmykarily** [comment]
```
MinIO Tenants require that the StorageClass sets volumeBindingMode to WaitForFirstConsumer. The default StorageClass may use the Immediate setting, which can cause complications during PVC binding. MinIO strongly recommends creating a custom StorageClass for use by PV supporting a MinIO Tenant.
```
from here: https://github.com/minio/operator#tenant-storage-class

I think it's fine to use the default storage class for now and just document this requirement. In the future we can add a deployment option for the user to define which storageclass to be used for minio.

**Comment by manno** [comment]
> I think it's fine to use the default storage class for now and just document this requirement. In the future we can add a deployment option for the user to define which storageclass to be used for minio.

There are also lots of options to deploy with, regarding HA: 
* sizing: https://docs.min.io/minio/k8s/tenant-management/deploy-minio-tenant.html#id14
* affinity: https://docs.min.io/minio/k8s/tenant-management/deploy-minio-tenant.html#complete-the-pod-affinity-step

I think for large production  setups our installer won't be good enough. I'm putting standalone mode (1 server) into the default YAML.
