### ISSUE TITLE
Release notes (still) pick 'closed issues' wrong

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#713]
https://github.com/epinio/epinio/releases/tag/v0.0.22 lists 'Set flag to fix postgres volume permissions #684' as closed issue, while #684 is on no project or milestone.

We need to get the release notes creation fixed.

**Comment by andreas-kupries** [comment]
Looking at the parameters for the action, at https://github.com/heinrichreimer/action-github-changelog-generator#inputs
it seems that 

|Name|Description|
|---|---|
|excludeLabels |			Issues with the specified labels will be excluded from changelog|
|verbose| 			Run verbosely|

might be useful. The first to as a means of preventing the obvious nonsense from getting into the output. The second to get better insight into the operation of the action. Note also that there seem to be no parameters to influence how the action maps labels to sections. Part of the reason I want `verbose` is the hope that its output will enable us to gain a deeper understanding of the mapping. Enough that we can tailor our labels (text and use) to the needs of the tool. Of course, reading the sources of the action will hopefully help also, and maybe even more.

Proposal. Exclude issues with labels
|Label|
|---|
|apparently external cause	|
|chore				|
|devops admin			|
|duplicate			|
|epic				|
|invalid			|
|later				|
|overcome by events		|
|spike				|
|wontfix			|

**Comment by andreas-kupries** [comment]
Hm. I might be wrong about excluding `epic`s. Seeing when they are closed, not just the subordinate tickets is likely useful.

**Comment by andreas-kupries** [comment]
The underlying tool is https://github.com/github-changelog-generator/github-changelog-generator

Reading its [option documentation](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options) and re-reading the action I find that the mapping is controlled by the following 6 parameters:

|Parameter		|Section			|Default				|
|---			|---				|---					|
|breakingLabels		|Breaking changes		|backwards-incompatible, breaking	|
|enhancementLabels 	|Implemented enhancements	|enhancement, Enhancement		|
|bugLabels 		|Fixed bugs			|bug, Bug     				|
|deprecatedLabels 	|Deprecated			|deprecated, Deprecated			|
|removedLabels 		|Removed			|removed, Removed			|
|securityLabels		|Security fixes			|security, Security			|

It is not clear if an issue which falls under more than one section as per the mapping is put into all of them, or just the first matching. If the latter, order of searching for match, i.e. priority is unknown.

**Comment by andreas-kupries** [comment]
And everything tagged with a label not found in any of the above likely goes into the general section for "Closed Issues".

**Comment by andreas-kupries** [comment]
The only labels important to us (as we have them) are `bug`, `enhancement`, and `security`.
Just excluding a lot (as done in #735) might help somewhat, keeping the general section down.
