### ISSUE TITLE
Epinio push fails with Longhorn storage class

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#722]
I just installed 0.0.22 and am unable to push any apps:

I'm running a multi node k3s-v1.21 cluster with Longhorn as my default storage-class.

In the cleanup pod I'm seeing:

`Warning  FailedMount  36m                kubelet, display-office  Unable to attach or mount volumes: unmounted volumes=[ws-txttj], unattached volumes=[ws-txttj linkerd-p │
│ oxy-init-xtables-lock tekton-creds-init-home-hgsrr tekton-internal-tools tekton-creds-init-home-tpt9n layers-dir tekton-internal-secret-volume-registry-creds-qqnjm tekton- │
│ creds-init-home-t7stq tekton-internal-home tekton-internal-results tekton-internal-downward podinfo linkerd-identity-end-entity kube-api-access-bbgwj tekton-internal-works │
│ pace registry-certs tekton-internal-scripts tekton-internal-secret-volume-gitea-creds-2gzcs empty-dir[]: timed out waiting for the condition                                │
│   `

**Comment by agracey** [comment]
Switching default storage class to local-path

**Comment by agracey** [comment]
I wonder if this has to do with the lack of node specificity in the volume?

**Comment by svollath** [comment]
Guess I see the same with RKE2 and Longhorn (1master ("CriticalAddonsOnly=true:NoExecute"), 2 workers).

Staging fails for "Multi-Attach error for volume", with different effects - depending which pods came up first and attached the volume in the first place (or on what worker?).

Staging pods:
```
0813d16eebf21f2e-cleanup-bgpng-pod-knbdw   0/2     Completed   1          32m   10.42.1.48   tf4-worker1   <none>           <none>
0813d16eebf21f2e-clone-s4b8p-pod-qspmt     0/3     Completed   1          31m   10.42.1.49   tf4-worker1   <none>           <none>
0813d16eebf21f2e-stage-psgm2-pod-gh6tc     0/4     Init:0/3    0          31m   <none>       tf4-worker0   <none>           <none>
affinity-assistant-024198d94f-0            2/2     Running     0          32m   10.42.1.47   tf4-worker1   <none>           <none>
affinity-assistant-f00f0b8031-0            2/2     Running     0          32m   10.42.2.46   tf4-worker0   <none>           <none>
```

Pod log snippet
```
29m         Warning   FailedScheduling         pod/0813d16eebf21f2e-cleanup-bgpng-pod-knbdw   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
29m         Warning   FailedScheduling         pod/0813d16eebf21f2e-cleanup-bgpng-pod-knbdw   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
29m         Normal    Scheduled                pod/0813d16eebf21f2e-cleanup-bgpng-pod-knbdw   Successfully assigned tekton-staging/0813d16eebf21f2e-cleanup-bgpng-pod-knbdw to tf4-worker1
29m         Normal    SuccessfulAttachVolume   pod/0813d16eebf21f2e-cleanup-bgpng-pod-knbdw   AttachVolume.Attach succeeded for volume "pvc-c7cdf0eb-c804-4d9a-9e56-8f8d1feb3be0"
```

tekton-staging events snippet
```
29m         Warning   FailedAttachVolume       pod/affinity-assistant-f00f0b8031-0            Multi-Attach error for volume "pvc-c7cdf0eb-c804-4d9a-9e56-8f8d1feb3be0" Volume is already used by pod(s) affinity-assistant-024198d94f-0, 0813d16eebf21f2e-cleanup-bgpng-pod-knbdw
```

At least it lists two pods that use the volume already, and they are both on worker1 - and the pod failing is on wroker0.

The PVC has
```
  accessModes:
  - ReadWriteOnce
```
not sure if `ReadWriteMany` would make a difference here.

**Comment by manno** [comment]
This [Tekton docs on workspaces](https://tekton.dev/vault/pipelines-v0.23.0/workspaces/#specifying-workspace-order-in-a-pipeline-and-affinity-assistants) describes how the affinity-assistant pod should help to avoid problems like this.

Basically, the affinity pod makes sure all `TaskRun` pods are scheduled on the same node as the volume.

However, the docs mention possible problems if nodes are missing a "`topologyKey`"

I verified in the pipeline, that all Tasks are sequential. They all use `runAfter` and should not be running in parallel.

Regarding the log from @svollath , I'm not sure how that would happen: Why are there two affinity pods on different nodes and why is one task on a different node? There are really no "topology" or "failover" labels on the nodes?

**Comment by agracey** [comment]
If it's helpful, here are the labels on one of my nodes: 

I don't see topology or failover. If you tell me what to add, I can tag and try again

```
Name:               opensuse
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=opensuse
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=k3s
Annotations:        csi.volume.kubernetes.io/nodeid: {"driver.longhorn.io":"opensuse"}
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"c6:d4:02:cc:25:3a"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.1.13
                    k3s.io/hostname: opensuse
                    k3s.io/internal-ip: 192.168.1.13
                    k3s.io/node-args: ["agent"]
                    k3s.io/node-config-hash: 6G4ZF3WOHQYALHXUQJY46ATYZ7XIOJAONZFDWDWP347AQJOTPJ3A====
                    k3s.io/node-env:
                      {"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/9df574741d2573cbbe6616e8624488b36b3340d077bc50da7cb167f1b08a64d1","K3S_TOKEN":"********","K3S_U...
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by svollath** [comment]
It seems that tekton-staging starts one "affinity-assistant" per (worker-)node:

```
7580b2f8691afed9-cleanup-5vdxh-pod-x8vfz   0/2     Init:0/3   0          7m12s   <none>       tf4-worker1   <none>           <none>
affinity-assistant-7241bf251c-0            2/2     Running    0          7m12s   10.42.1.28   tf4-worker0   <none>           <none>
affinity-assistant-8147ed7d1d-0            2/2     Running    0          7m12s   10.42.2.24   tf4-worker1   <none>           <none>
```

"7580b2f8691afed9-cleanup-5vdxh-pod-x8vfz" on worker1, and
"affinity-assistant-8147ed7d1d-0" on worker1

... all try to get the same volume of "affinity-assistant-7241bf251c-0" on worker0.


```
> kubectl describe pod 7580b2f8691afed9-cleanup-5vdxh-pod-x8vfz -n tekton-staging
...
Warning  FailedAttachVolume  97s        attachdetach-controller  Multi-Attach error for volume "pvc-ac3a1c86-cd8c-4e4f-b291-2cabaac592cd" Volume is already used by pod(s) affinity-assistant-7241bf251c-0
```

```
> kubectl describe pod affinity-assistant-8147ed7d1d-0 -n tekton-staging
...
Warning  FailedAttachVolume  18m        attachdetach-controller  Multi-Attach error for volume "pvc-ac3a1c86-cd8c-4e4f-b291-2cabaac592cd" Volume is already used by pod(s) affinity-assistant-7241bf251c-0
```

**Comment by agracey** [comment]
> @agracey Can you provide instructions on how you installed Longhorn, so I can reproduce? It's probably the default install on k3s?
> I tried it with k3d, but the k3d images are missing `open-iscsi`, so it doesn't work.


It's not the default on k3s but I am using k3s as my distro. I installed through the Rancher UI. IIRC, the only options I changed were setting the multiplicity lower than the default so my little home network didn't get bogged down in replications.

I did have to install the open-iscsi package on each node before the pods came up healthy.

**Comment by agracey** [comment]
It might be good to see if there's a way to do RWO for the workspace storage?

**Comment by manno** [comment]
Note: in the meantime we figured out that tekton uses one affinity-assistant per volume. We use one volume via two sub-paths, therefore we get to assistants.

**Comment by svollath** [comment]
I successfully tested epinio-0.1.0 on RKE2 with Longhorn v1.1.1 (with default volumebindingmode: Immediate).
This was fixed by https://github.com/epinio/epinio/pull/798 .
@agracey , feel free to retest in your environment and/or close this issue.

**Comment by agracey** [comment]
Testing now

**Comment by agracey** [comment]
Yes, without editing anything I was able to push and app with Longhorn as my default storage class. Closing now.
