### ISSUE TITLE
Staging logs don't always show up

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#724]
I'm seeing an intermittent issue where the staging logs don't always show up. It seems to be pretty random and I'm betting it's a network issue or something. 

The next time I see it, I'll see if they can be retrieved afterwards with `epinio logs --staging` and update this ticket

**Comment by andreas-kupries** [comment]
Could it be a race also ?
A quickly started app with not much of logs, faster than the client trying to retrieve them ?
What application was used ?

Do you have captures of the output with the logs missing ?
(Extended TRACE_LEVEL ? (TRACE_LEVEL=6 will capture all tracing we currently have))

Given your suspicion of network issues ... Cluster with epinio is not on the same box as the client ?

**Comment by andreas-kupries** [comment]
Looking a bit a logs for a run showing the staging logs I noticed

```
2021/08/30 11:16:14 epinio/631 "level"=1 "msg"="received request"  "method"="GET" "uri"="/api/v1/orgs/workspace/staging/b0e789281a9e2dc5/logs?follow=true\u0026stage_id=b0e789281a9e2dc5" "user"="a42607e9bc02c85b"
2021/08/30 11:16:14 epinio/631 "level"=2 "msg"="request"  "body"="n/a"

2021/08/30 11:16:21 log-tracing "level"=1 "msg"="starting the tail for pod b0e789281a9e2dc5-cleanup-cdpbq-pod-fvs5v"  
```

Note the 7 seconds between receiving the request and the first action which may generate user-visible data!
(The server log does not show the log entries streamed over the web socket)

I will dig a bit more into this area, see if I can determine what is done in that time.

**Comment by andreas-kupries** [comment]
Moving back into the icebox until we have a repro with extended tracing

**Comment by agracey** [comment]
I don't believe I've seen this since 0.1.1. I don't know if it's load related but going to close until I see it again and can repro.
