### ISSUE TITLE
Gitea fails to create /data/git/.ssh directory - permission denied

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#732]
While [postgresql](https://github.com/epinio/epinio/issues/641) runs nicely with v0.0.23, it's `gitea` now failing with

> Failed to create '/data/git/.ssh': mkdir /data/git: permission denied

on Windows running with rancher-desktop

**Comment by kkaempf** [comment]
Nope, this problem is not fixed :-/

**Comment by kkaempf** [comment]
.

**Comment by kkaempf** [comment]
Shouldn't https://github.com/epinio/epinio/blob/9f86f4ab9d6c4cfe8e3402a3f9080fbdfd6fb610/deployments/gitea.go#L178 read `/data/gitea/...` instead of `/data/git/...` ?! 🤔

**Comment by kkaempf** [comment]
> read `/data/gitea/...` instead of `/data/git/...` ?! 🤔

Hmm, probably not. https://github.com/go-gitea/gitea/blob/f3b36e2a3947782df8eb41a4049743b7806b0e62/docker/root/usr/bin/entrypoint#L27 lists `/data/git`

Btw, `kubectl describe` shows `/data` as mounted "rw".

**Comment by agracey** [comment]
If you still have the busted install, open a terminal on the rancher-desktop WSL2 and run `la -la /var/lib/rancher/k3s/storage/`

**Comment by andreas-kupries** [comment]
Do you mean `ls -la /var/lib/rancher/k3s/storage/` ? (`la` -> `ls`)

**Comment by agracey** [comment]
> Do you mean `ls -la /var/lib/rancher/k3s/storage/` ? (`la` -> `ls`)

Yes… yes I did 😁

**Comment by agracey** [comment]
My thought is that if we see the permissions be something different than 777, we can compare against changes in the local path provisioner.

**Comment by kravciak** [comment]
I have the same problem on Ubuntu (k3d cluster with ubuntu containers), not sure it's only windows issue

**Comment by jimmykarily** [comment]
I'm using:

- Windows 10
- rancher desktop `v0.4.1`
- Epinio `v0.0.24`
- Kubernetes `v1.21.4`

and Epinio installs just fine with a simple `epinio install`. The only problem I had was DNS issues, probably related to this: https://github.com/rancher-sandbox/rancher-desktop/issues/572 (I fixed it by adding `8.8.8.8` in the resolv.conf)

Here is the output of that `ls` command:

```
/mnt/c/Users/Dimitris # ls -la /var/lib/rancher/k3s/storage/
total 16
drwx-----x  4 root    0 4096 Sep  7 06:06 .
drwxr-xr-x  6 root    0 4096 Sep  7 06:06 ..
drwxrwxrwx  3 1001 1001 4096 Sep  7 06:08 pvc-b1e878c3-f3f0-4a25-ba9f-d0e1fb7973f9_gitea_data-gitea-postgresql-0
drwxrwxrwx 11 root    0 4096 Sep  7 06:09 pvc-d01bc0dd-ea56-4780-aff9-0aed225a2f3a_gitea_data-gitea-0
```

**Comment by kkaempf** [comment]
`/var/lib/rancher/k3s/storage` is empty on my WSL instance.

**Comment by kkaempf** [comment]
Comparing my and @jimmykarily's Windows setup:
I was running RD with k8s 1.21.3 vs. jimmykarily running k8s 1.21.4

Re-testing with 1.21.4 makes `epinio install` succeed. Downgrading to k8s 1.21.3 makes it fail again. 🤦🏻‍♂️ 

The [upstream changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1213) doesn't contain any hint 🤷🏻‍♂️

**Comment by kkaempf** [comment]
Kubernetes 1.20.10 is also fine.
