### ISSUE TITLE
Guidance for brand-new users

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#737]
We should have entry-level documentation for developers without previous Kubernetes knowledge.
It should cover (resp. link to)
- how to install Epinio
- how to find additional documentation (doc structure explanation)
- some guidance for typical apps (i.e. Rails, PHP, Nodejs, Java)

**Comment by jimmykarily** [comment]
>     how to install Epinio

Is this enough? https://github.com/epinio/epinio/blob/main/docs/user/tutorials/quickstart.md

>     how to find additional documentation (doc structure explanation)

Is this enough? https://github.com/epinio/epinio#how-the-documentation-is-organized

> some guidance for typical apps (i.e. Rails, PHP, Nodejs, Java)

Maybe add some links to example projects like: https://github.com/epinio/example-rails ?  We can start with what we have and create some stories to add more example apps (e.g. for Java, etc).

**Comment by manno** [comment]
More sample apps are here: 

* https://github.com/paketo-buildpacks/samples
* https://github.com/buildpacks/samples

**Comment by kkaempf** [comment]
@agracey 👆🏻 👆🏻 👆🏻
