### ISSUE TITLE
Document how to install Epinio on Rancher Desktop

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#740]
We need to make sure that Epinio and Rancher Desktop work well together. 

See also: https://github.com/rancher-sandbox/rancher-desktop/issues/558

## Acceptance Criteria

- Document how to install Epinio on Rancher Desktop - Windows
- Document how to install Epinio on Rancher Desktop - Mac
- Document how to install Epinio on Rancher Desktop - Linux
- Document the test in the wiki page

**Comment by jimmykarily** [comment]
Automating RD is not possible yet. We decided to keep it as a manual test for now. Let's document the Epinio installation on RD (Windows, Mac, Linux)

**Comment by manno** [comment]
Test plan: https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)

**Comment by jimmykarily** [comment]
If it doesn't work on some platform, we should document that and add links to the issues on RD that are blocking it.

**Comment by thardeck** [comment]
> If it doesn't work on some platform, we should document that and add links to the issues on RD that are blocking it.

Linux support spike: https://github.com/rancher-sandbox/rancher-desktop/issues/426

**Comment by kkaempf** [comment]
I tested Epinio 0.1.1 on RD 0.5.0 (Windows 10) and had trouble with network (Epinio cli couldn't reach Epinio server). Turns out that RD 0.5.0 defaulted to k8s 1.21.4 on my machine. Switching to k8s 1.21.5 made Epinio 0.1.1 work.
Tested
- `epinio install` ✅ 
- `epinio info` ✅  (server connection)
- `epinio push` ✅  (sample app)

**Comment by thardeck** [comment]
> I tested Epinio 0.1.1 on RD 0.5.0 (Windows 10) and had trouble with network (Epinio cli couldn't reach Epinio server). Turns out that RD 0.5.0 defaulted to k8s 1.21.4 on my machine. Switching to k8s 1.21.5 made Epinio 0.1.1 work.

Epinio `1.24.4` seems to work fine on my machine but not `1.22.2`.

**Comment by thardeck** [comment]
Rancher desktop is already mentioned as installation target in https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)

**Comment by manno** [comment]
> Rancher desktop is already mentioned as installation target in the [ŧest plan](https://github.com/epinio/epinio/wiki/Release-Test-Plan(s))

That needs a note that we can only do manual testing and some description or a just a check list on how to do the manual testing. 
Examples:

**Comment by thardeck** [comment]
Moved rancher tutorial to docs: https://github.com/epinio/docs/pull/3
