### ISSUE TITLE
Add docs for Epinio on minikube

### ISSUE THREAD

**Issue by manno** [epinio/epinio#752]
We have docs for k3d, aks and others. We're missing Minikube docs.

Docs should cover these drivers:

* virtualbox
* docker

This page has some instructions for the required MetalLB addon:
https://github.com/epinio/epinio/blob/main/docs/user/howtos/provision_external_ip_for_local_kubernetes.md#minikube
and should cover this: https://github.com/epinio/epinio/issues/635

**Comment by kkaempf** [comment]
minikube (on kvm) with Kubernetes v1.21.4 is fine. See #790.
