### ISSUE TITLE
Wrong API endpoint of existing default config file is kept

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#768]
**Describe the bug**
Using Epinio-0.0.24 on linux. If there's a config file from a previous install already, e.g. `~/.config/epinio/config.yaml` - `epinio install` will read that file, and use the previous configured API endpoint, even if the system domain will change.

**To Reproduce**
Have a pre existing `~/.config/epinio/config.yaml` config file - e.g. from "install=>uninstall" procedure.
Make sure the `Traefik Ingress info` (traefik public IP) will differ for the next installation (if you always get the same IP, you could change the former one in the config file, to see the effect later).

1. Install Epinio with `epinio install` (e.g. getting `Traefik Ingress info: [{"ip":"20.75.240.33"}]`)
2. Uninstall Epinio with `epinio uninstall`
3. Install Epinio with `epinio install` (e.g. getting `Traefik Ingress info: [{"ip":"20.72.177.217"}]`)
4. See Epinio picking up a new external IP (e.g. `Traefik Ingress info: [{"ip":"20.72.177.217"}]`), and later fail with
e.g. `🚢 Retrying (0/10) after Post "https://epinio.20.75.240.33.omg.howdoi.website/api/v1/namespaces": dial tcp 20.75.240.33:443: i/o timeout`, which is the old API endpoint.

**Expected behavior**
Since finally Epinio will rewrite the default config file with the current API endpoint information, I'd expected that it will not read, or keep the existing value from the default config file, when running a plain `epinio install`.

**Logs**
existing "~/.config/epinio/config.yaml":
```
api: https://epinio.20.75.240.33.omg.howdoi.website
certs: |
  -----BEGIN CERTIFICATE-----
********
  -----END CERTIFICATE-----
colors: true
epinio_protocol: http
epinio_workloads_namespace: epinio-workloads
epinio_ws_protocol: ws
gitea_namespace: gitea
gitea_protocol: http
namespace: ""
org: workspace
pass: ********
user: ********
wss: wss://epinio.20.75.240.33.omg.howdoi.website
```

Output from `epinio install`:
```
> ./epinio install                                          

🚢 Epinio v0.0.24 installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  skip-cert-manager: false
  🧭  system_domain: 
  🧭  email_address: epinio@suse.com
  🧭  user: 082338fdc859745b
  🧭  password: eb21266ce034e7b9
  🧭  tls-issuer: epinio-ca
  🧭  use-internal-registry-node-port: true
  🧭  loadbalancer-ip: 

🚢 Deploying Linkerd...
✔️  Linkerd deployed

🚢 Deploying Traefik Ingress..........................
✔️  Traefik Ingress deployed
.
✔️  Using system_domain: 20.72.177.217.omg.howdoi.website

🚢 Deploying Gitea...

🚢 Deploying Tekton...
🚢 Deploying CertManager...
🚢 Deploying ServiceCatalog...🚢 Deploying Registry...
🚢 Deploying Kubed...
🚢 Deploying Epinio...I0907 16:04:15.588976   15287 request.go:655] Throttling request took 1.015143713s, request: POST:https://sebi-ch1l8-sebi-ch1l8h-epin-f416cc-12b10ce2.hcp.eastus.azmk8s.io:443/api/v1/namespaces
............................................................
✔️  Kubed deployed
.................................................................................................................................
✔️  CertManager deployed
..............................................................
✔️  ServiceCatalog deployed
......................
✔️  Registry deployed
...................................................
✔️  Tekton deployed
..
✔️  Epinio deployed
................
✔️  Gitea deployed

✔️  Epinio installed.
System domain: 20.72.177.217.omg.howdoi.website
API User: 082338fdc859745b
API Password: eb21266ce034e7b9
Traefik Ingress info: [{"ip":"20.72.177.217"}]

🚢 Updating the stored credentials from the current cluster
Config: /home/paas/.config/epinio/config.yaml

✔️  Ok

🚢 Creating namespace...
Name: workspace

🚢 Retrying (0/10) after Post "https://epinio.20.75.240.33.omg.howdoi.website/api/v1/namespaces": dial tcp 20.75.240.33:443: i/o timeout
```

Final "~/.config/epinio/config.yaml" after install:
```
api: https://epinio.20.72.177.217.omg.howdoi.website
certs: |
  -----BEGIN CERTIFICATE-----
********
  -----END CERTIFICATE-----
colors: true
epinio_protocol: http
epinio_workloads_namespace: epinio-workloads
epinio_ws_protocol: ws
gitea_namespace: gitea
gitea_protocol: http
namespace: ""
org: workspace
pass: ********
user: ********
wss: wss://epinio.20.72.177.217.omg.howdoi.website
```

**Cluster (please complete the following information):**
 - Provider: AKS
 - Options: 2 nodes, kubelb
 - Kubernetes Version: v1.20.9

**Desktop/CLI (please complete the following information):**
 - OS: Linux
 - Epinio Version: 0.0.24
 - Epinio Install Options: none/default

**Comment by andreas-kupries** [comment]
I am taking this as this may be the cause behind #758 . And even if not, I am already in the guts of the config handling because of that one.

**Comment by andreas-kupries** [comment]
Reading the logs in full now this definitely looks very similar to #758 where a different api url was used in the post-install when the configured domain.
