### ISSUE TITLE
API: Convert organization entity to object and expand content

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#769]
**Is your feature request related to a problem? Please describe.**
In `v0.0.21` the response to `/api/v1/orgs` is an array of strings rather than an array of objects. This differs from other resource types and thus has to be handled as a special case. 

This also only allows a 'name' field.

**Describe the solution you'd like**
The response should contain an array of org objects. If there is any additional org related data that could be added at the same time too.

**Additional context**
More info in the org = prettier ui :)

**Comment by andreas-kupries** [comment]
@richard-cox The new response is an array of objects. Each object holds the namespace name, and the names of the apps and services in the namespace, as arrays.

Example:

```
[
  { "name": "world",
    "apps" : [ "hello", ...],
    "services": [ "continents", ...]
  }, ...
]
```

I hope that is good enough, or if you expected app/service details also.

**Comment by richard-cox** [comment]
@andreas-kupries There's a further discussion to be had on scaling, and making some optional and changing the level of detail. This is perfect for the beta though
