### ISSUE TITLE
API: Fetch all applications rather than just those in an org

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#771]
**Is your feature request related to a problem? Please describe.**
In `v0.0.21` applications can be fetched via `/api/v1/orgs/<org name>/applications`. To fetch all applications regardless of org client has to iterate over all orgs.

**Describe the solution you'd like**
Add an  `/api/v1/applications` endpoint. that returns all apps in all orgs

**Comment by kkaempf** [comment]
Not sure if we want to cross namespace boundaries 🤔

**Comment by jimmykarily** [comment]
Right now, all users can do everything on Epinio (no roles). When we add roles, we can limit this new endpoint to list only applications to which the current user has access. I think it's fine to proceed here.

**Comment by jimmykarily** [comment]
> Not sure if we want to cross namespace boundaries thinking

Right now, all users can do everything on Epinio (no roles). When we add roles, we can limit this new endpoint to list only applications to which the current user has access. I think it's fine to proceed here.
