### ISSUE TITLE
API: Support GET for namespaces

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#773]
**Is your feature request related to a problem? Please describe.**
In `v0.0.21` I couldn't find a way to fetch an org directly. Tried both `/api/v1/orgs/<org name>` and `/api/v1/organizations/<org name>` but both return `405 Method Not Allowed`

**Describe the solution you'd like**
Add an an `/api/v1/orgs/<org name>` endpoint to fetch the org (at the moment this returns a string... but after #769 hopefully an object)

**Comment by kkaempf** [comment]
`orgs` was changed to `namespaces` in #739 👀

**Comment by jimmykarily** [comment]
Let's implement this on #769 directly (no need to implement the "poor" endpoint and expand it)
