### ISSUE TITLE
API: Formalise app state

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#774]
**Is your feature request related to a problem? Please describe.**
In order to show the state of an application (errored/red, caution/yellow, all good/green, etc) the client needs a formalised state.
At the moment, in `v0.0.21`, it looks like the app only has a [string value](https://github.com/epinio/epinio/blob/8101428b71fcc7fae4dac3a66d73024e5f9d238c/internal/api/v1/models/app.go#L19) that could either show a status sentence or number of instances running (haven't played around with this, so could be wrong about specifics). 
- `0/1`
- `Inactive, without workload. Launch via "epinio app push"`

I've tried fetching the stage associated with the app to see if it had anything more, but just get a 404 - `/api/v1/orgs/<org name>/staging/<stage_id>/logs`.

**Describe the solution you'd like**
A clear enum based state regarding the health of the application, a separate state for number of instances running and another for target number of instances.

The enum could be any number of values, they would just need to be defined so we can associate certain behaviour in the UI.

**Comment by jimmykarily** [comment]
Relevant #786

**Comment by jimmykarily** [comment]
As we discussed in a call, we are going to report 2 different statuses back:

- The workload status. This is the answer to "is my app reachable?" question (or how reachable it is)
- The application status. This is providing information that reflects some user action on the application

Useful workload status information:
- Number of ready replicas (the properly running ones) - could be zero if there is no workload yet or zero is explicitly asked for
- Desired replicas
- Status of all replicas (to be able to tell why the failed ones fail)

Possible application statuses:
- no workload (when no Deployment exists)
- Staging (when a PipelineRun is currently running) - with various workload statuses
- Running (with various workload statuses)
- Being deleted

For example:

A workload status "1/1" with an application status "staging" means your application is reachable and someone is pushing the application right now.

Other example:

A workload status "0/0" with an application with no workload means nobody pushed the application yet. It was simply "created".

This is the rough idea. The details of the various possible statuses and the format of the json responses from the API can be refined.

**Comment by agracey** [comment]
I like the split of workload status vs application status vs application health.
