### ISSUE TITLE
CLI: Expand on debug content 

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#775]
**Is your feature request related to a problem? Please describe.**
When specifying the most chatty and deepest level of additional feedback for a command (`--verbosity 1 --trace-level 5`) there's a number of things missing that are really helpful

- ~post/patch data~ i might have been wrong about this
- response data
  - sometimes this is shown (push app), sometimes not (apps list) 
- request headers

**Describe the solution you'd like**
Add the above information to, i guess, the `trace-level`, either 5 or a new 6?

@neillsom

**Comment by richard-cox** [comment]
It also looks like one of the `push` requests isn't being logged

```
Uploading application code ...
2021/09/08 17:31:59 EpinioClient/Push "level"=2 "msg"="upload code" "Name"="sample-2" "Organization"="workspace" "Sources"="sample-app" 
2021/09/08 17:32:01 EpinioClient/Push "level"=4 "msg"="upload response" "Name"="sample-2" "Organization"="workspace" "Sources"="sample-app" "response"={"git":{"revision":"0584f8b9b72b7d7fe6599f279b58003a864143e4","url":"http://gitea-http.gitea:10080/workspace/sample-2"}}
```

Was expecting something like

```
2021/09/08 17:32:01 EpinioClient "level"=1 "msg"="POST <url>"  
2021/09/08 17:32:01 EpinioClient "level"=2 "msg"="<response>"
```

**Comment by manno** [comment]
@rohitsakala 

Can you add request logging to the client and the server, please.
At a higher trace level we should see the full request and the received response, including the response headers.  

I think this is a good story for a refactoring. Our "internal/cli/client" is too much of a doer. We could extract everything that talks to our API into a separate package. So when talk to the API, everything could look like this code:

```
req := models.StageRequest{App: appRef, BuilderImage: params.BuilderImage}
resp := models.StageResponse{}
resp, err = epinioapi.AppStage(req)
if err != nil {
	return err
}
```
However it would also need the logger and maybe a context.

**Comment by rohitsakala** [comment]
> @rohitsakala
> 
> Can you add request logging to the client and the server, please.
> At a higher trace level we should see the full request and the received response, including the response headers.

Sure.

> I think this is a good story for a refactoring. Our "internal/cli/client" is too much of a doer. We could extract everything that talks to our API into a separate package. So when talk to the API, everything could look like this code:
> 
> ```
> req := models.StageRequest{App: appRef, BuilderImage: params.BuilderImage}
> resp := models.StageResponse{}
> resp, err = epinioapi.AppStage(req)
> if err != nil {
> 	return err
> }
> ```
> 
> However it would also need the logger and maybe a context.

Yup a good idea.

**Comment by jimmykarily** [comment]
PR merged
