### ISSUE TITLE
We should look at the output of `gosec` and investigate/ignore the results

### ISSUE THREAD

**Issue by manno** [epinio/epinio#782]
https://github.com/epinio/epinio/actions/runs/1213826186

**Comment by andreas-kupries** [comment]
While the list is nice the messages do not seem to contain file/line information for me to find where in the code an issue was detected exactly ?!
Is it possible to configure the linter to include that information ?

Is it possible to run the linter locally ?
We do not seem to have a Makefile target for it.

**Comment by andreas-kupries** [comment]
Trying to find something reasonably easy to identify, from the linter message itself:

```
work@tagetarl:~/SUSE/dev/epinio> grep -rn InsecureSkipVerify internal/ deployments/ helpers/ acceptance/
internal/cli/config/config.go:107:				InsecureSkipVerify: true,
internal/cli/config/config.go:113:			http.DefaultTransport.(*http.Transport).TLSClientConfig.InsecureSkipVerify = true
acceptance/helpers/machine/machine.go:75:		InsecureSkipVerify: true, // self signed certs
acceptance/helpers/machine/curl.go:23:				InsecureSkipVerify: true, // self signed certs
```

The `config/config.go` occurrences are executed in response to an explicit user request (option `--skip-ssl-verification`).
Can we tell the linter to ignore something, via a code comment or the like ?

The other two occurrences are in our testsuite. That should be fine also.

**Comment by manno** [comment]
You can run `golangci-lint run` locally. It will use the `.golangci.yaml` by default. 

Since the link I posted is from an outdated commit, you can't see the code annotations on Github.

**Comment by andreas-kupries** [comment]
Thanks. Ok. I found the github for golangci-lint, and installed the latest release locally.
Still have to read the docs, for the possibility of disabling specific rules for lines/regions of a file.
