### ISSUE TITLE
Use External Registry to store images 

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#784]
**Is your feature request related to a problem? Please describe.**
There are many companies who already have a registry installed and would like to leverage the features included in it. We should allow for Epinio to use external registries.

**Describe the solution you'd like**

I would like to be able to select an external registry (and provide credentials if needed) when I install Epinio. When the option is defined, the built-in registry would not be installed and buildpacks would publish to the selected registry.

It would also likely be good to test the connection and credentials at install time to protect against user error.

**Describe alternatives you've considered**

A potential alternative (or addition) would be to allow specifying the registry on an app by app basis.

**Comment by agracey** [comment]
We should also be able to customize the image name on push. And likely the default should be something like `<namespace>/<app_name>:<build_uuid>`?

**Comment by thardeck** [comment]
Should we use a parameter like `--external-registry-url` which can contain the username and password or use different parameters for the credentials?

**Comment by jimmykarily** [comment]
Working branch: https://github.com/epinio/epinio/tree/784-use-external-registry

**Comment by jimmykarily** [comment]
If the PR grows too big, I think we can skip the validation and the customized image name on push on the first iteration. We can split them in separate issues. What do you think @agracey. Maybe they are not even blockers for beta 3?

**Comment by agracey** [comment]
Agreed. That doesn't need to be done on the first pass.

**Comment by agracey** [comment]
That said, being able to set at least the first path part is needed since that has to be a organization or project that already exists and you have push access to. 

For example, I might not have access to  `myregistry.com/workspace/appname` but likely have access `myregistry.com/dev_atgracey/workspace/appname`.
