### ISSUE TITLE
Push without deployment

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#793]
**Is your feature request related to a problem? Please describe.**

It might be useful to allow for using Epinio to push from source into an image registry (from #784)

While this might sound odd at first, I believe this could allow for reuse of the same core pipeline and build governance inside of other CI systems. We could also combine it with a GitJob (#738) and an external registry to give a DockerHub like experience. 

**Describe the solution you'd like**

I would like to be able to do something like `epinio push blah --no-deploy` to get a

**Describe alternatives you've considered**

We could instead break out the push process and pipeline into it's own project but that seems like significantly more work for less reward.

**Comment by jimmykarily** [comment]
This is low priority, we can remove it from the [Milestone](https://github.com/epinio/epinio/milestone/15) if there is not enough time.
