### ISSUE TITLE
epinio install on Windows (RD) reports " tls: protocol version not supported"

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#799]
**Describe the bug**
`epinio install` (v0.0.28) on Windows fails with
```
🚢 Now checking ability to use the API server. And setting up useful things at the same time

🚢 Creating namespace...
Name: workspace
error creating namespace: All attempts fail:
#1: making the request: Post "https://epinio.192.168.138.83.omg.howdoi.website/api/v1/namespaces": remote error: tls: protocol version not supported
```

**To Reproduce**
Steps to reproduce the behavior, e.g.:

- Rancher Desktop 0.4.1
- Epinio v0.0.28
- run `epinio install`

**Expected behavior**

Successful installation

**Logs**

see above

**Cluster (please complete the following information):**
 - Provider: RD
 - Options: 
 - Kubernetes Version: 1.21.4

**Desktop/CLI (please complete the following information):**
 - OS: Windows 10
 - Epinio Version: 0.0.28
 - Epinio Install Options: n/a

**Additional context**

**Comment by jimmykarily** [comment]
This should fix it: https://github.com/epinio/epinio/commit/a67014c320c915ad76986414a13b4d4c537ca59d

**Comment by kkaempf** [comment]
Fix confirmed. Thanks !
