### ISSUE TITLE
Support pre-binding of services to applications at rest.

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#802]
**Is your feature request related to a problem? Please describe.**

See #785 where this came up. Having the feature will make things much easier on that front.
Further, we already support app EVs for apps at rest.
Not having this for services is a limitation I see no real reason, except that apps at rest were introduced late, and not all parts of epinio got immediate support. This looks to be such a part.

**Describe the solution you'd like**

  - The `service bind/unbind` commands operate properly on apps without workload.
  - The `app create` command supports the `--bind` option of `app push`.
  - Internally, on `push` the import of the services into the deployment is done by the server component, and not the client anymore. 

**Describe alternatives you've considered**

None.

**Comment by jimmykarily** [comment]
Would it be easier if we did #836 and you rebased on top of it or should we wait until this one is done?

I'm thinking that there would be less work on this PR is the non-custom services were gone. I don't know if the biggest part of that work has already happened or if we would still save lots of work by first removing service broker (and minibroker/google broker).

**Comment by jimmykarily** [comment]
I created a draft PR here: https://github.com/epinio/epinio/pull/837

You can try to rebase on top of it and see what you get.
