### ISSUE TITLE
Support kubernetes 1.22

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#833]
Some of the components installed by Epinio are not in a version compatible with kubernetes 1.22

See some initial investigation at the comments here: https://github.com/epinio/epinio/issues/790#issuecomment-924900327

## Acceptance Criteria

- Epinio works on kubernetes 1.22
- Epinio works on older versions too (down to what version? TBD)

**Comment by jimmykarily** [comment]
Started some work here: https://github.com/epinio/epinio/tree/833-support-kube-1-22

**Comment by jimmykarily** [comment]
another one (service-catalog):

```
⚠️  Deployment service-catalog failed with error: Failed installing ServiceCatalog: Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]
```

We are on `0.3.1` and there doesn't seem to be  a newer version. I have a feeling that there isn't going to be a newer version ever.

**Comment by agracey** [comment]
W.R.T. version support:

We should support the same at the latest release of Rancher. Looks like 1.18 - 1.21  for Rancher 2.6.

That said, we should also try to support the latest as that's what a good chunk of non-commercial users will be trying us with. I'd say we likely have a 3 month  grace period from the upstream k8s release to having tested it.


W.R.T service catalog, sounds like it is now a dead project :( I can reach out to a few people on the SIG to see what their plans are.

**Comment by kkaempf** [comment]
Uhm, 1.18 to 1.22 would be 5 versions to be tested in parallel. On all our platforms. Not sure we have the QA bandwidth for that.

**Comment by agracey** [comment]
Let's do 1.20-1.22 unless I find metrics on usage that say otherwise (just sent a message asking the field)

**Comment by mattfarina** [comment]
For reference, most of the public clouds provide N-2 as their latest minor release. So, with 1.22 out they'll have 1.20 supported as their latest. This is the oldest version supported by the k8s community.

**Comment by jimmykarily** [comment]
@agracey is this beta2?

**Comment by jimmykarily** [comment]
Also cert-manager has to be bumped:

```
│ E1006 12:41:38.959912       1 start.go:170] cert-manager/ca-injector "msg"="Error registering certificate based controllers. Retrying after 5 seconds." "error"="no matches for kind \"Mut │
│ Error: error registering secret controller: no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"                                           │
```

newer versions are using `v1`: https://github.com/jetstack/cert-manager/blob/5543772de0619f70526853692743999e2da0afa5/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml#L1

**Comment by jimmykarily** [comment]
The `app-crd` CRD is no longer compatible either. While trying to fix it I hit this error:

```
⚠️  Deployment epinio failed with error: Installing epinio/app-crd.yaml failed:
The CustomResourceDefinition "applications.app.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
: exit status 1
```

Looking at [the linked PR](https://github.com/kubernetes/enhancements/pull/1111), it seems that we need an annotation like this:

```
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
```

"The value should be a link to the pull request where the API has been approved". Good luck finding a PR like this for the dead project that app-crd is.

Maybe replacing the app crd with something else (a ConfigMap) is a good idea now.

**Comment by jimmykarily** [comment]
Simply switching from `rancher/k3s:v1.22.2-k3s2` to `rancher/k3s:v1.19.15-k3s2` for the cluster image, makes it work again.

the containerd version used in the 1.19 image:

```
/ # containerd --version
containerd github.com/rancher/containerd v1.4.11-k3s1
```

**Comment by jimmykarily** [comment]
Actually the "io.buildpacks.stack.metadata" label is not that big. There is another one that certainly exceeds 4096 characters:

```
"io.buildpacks.stack.mixins": "[\"adduser\",\"adwaita-icon-theme\",\"apt\",\"apt-utils\",\"base-files\",\"base-passwd\",\"bash\",\"bind9-host\",\"binutils\",\"binutils-common\",\"b
inutils-x86-64-linux-gnu\",\"bsdutils\",\"busybox-initramfs\",\"bzip2\",\"ca-certificates\",\"console-setup\",\"console-setup-linux\",\"coreutils\",\"cpio\",\"curl\",\"dash\",\"debconf\",\"d
ebconf-i18n\",\"debianutils\",\"dh-python\",\"diffutils\",\"dirmngr\",\"distro-info\",\"distro-info-data\",\"dnsutils\",\"dpkg\",\"dpkg-dev\",\"e2fsprogs\",\"eject\",\"fdisk\",\"file\",\"fin
dutils\",\"fontconfig\",\"fontconfig-config\",\"fonts-dejavu-core\",\"gcc-7-base\",\"gcc-8-base\",\"gir1.2-freedesktop\",\"gir1.2-gdkpixbuf-2.0\",\"gir1.2-glib-2.0\",\"gir1.2-harfbuzz-0.0\",
\"gir1.2-pango-1.0\",\"gir1.2-rsvg-2.0\",\"gnupg\",\"gnupg-l10n\",\"gnupg-utils\",\"gnupg1\",\"gpg\",\"gpg-agent\",\"gpg-wks-client\",\"gpg-wks-server\",\"gpgconf\",\"gpgsm\",\"gpgv\",\"grap
hviz\",\"grep\",\"gsfonts\",\"gss-ntlmssp\",\"gtk-update-icon-cache\",\"gzip\",\"hicolor-icon-theme\",\"hostname\",\"humanity-icon-theme\",\"icu-devtools\",\"imagemagick\",\"imagemagick-6-co
mmon\",\"imagemagick-6.q16\",\"init\",\"init-system-helpers\",\" 

... and goes on and on ...
```

**Comment by jimmykarily** [comment]
In minikube (created with `minikube start --container-runtime=docker`) Epinio deploys fine, same for apps. Kubernetes version `1.22.2`. 

There are some deprecation warnings during installation that can still be fixed:

```
..W1008 09:47:14.150422   23844 warnings.go:70] cert-manager.io/v1alpha2 ClusterIssuer is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 ClusterIssuer                     
W1008 09:47:14.468075   23844 warnings.go:70] cert-manager.io/v1alpha2 ClusterIssuer is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 ClusterIssuer                       
W1008 09:47:14.670851   23844 warnings.go:70] cert-manager.io/v1alpha2 Certificate is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 Certificate                           
W1008 09:47:14.681472   23844 warnings.go:70] cert-manager.io/v1alpha2 ClusterIssuer is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 ClusterIssuer 
```

I will look into it.

**Comment by jimmykarily** [comment]
Warnings are now fixed
