### ISSUE TITLE
Service Catalog is not being maintained

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#835]
*Writing this up from the conversation this morning.

Service Catalog's last release was November of last year and utilizes some APIs that have been removed in K8s 1.22+

**Describe the solution you'd like**
Removal of svc-cat and minibroker from Epinio. For the short term replace with documentation of how to use helm (or Rancher) to install services and then expose them to applications. 

We should also rename `custom-service` to just `service` in the CLI.

Longer term, we need to figure out a better user experience based on components in active maintenance.

**Describe alternatives you've considered**
We could take on maintenance of svc-cat but I don't believe that's a viable option at the time being.

**Comment by jimmykarily** [comment]
I just realized we already had this story when I opened #836 . I will close this one as duplicate because the other has a little more information (working branch etc).
