### ISSUE TITLE
Unable to push application in 0.1.1

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#839]
**Describe the bug**
When I try to push an app after installing 0.1.1 I get:

```
Create the application resource ...
2021/09/24 10:29:23 EpinioApiClient "level"=4 "msg"="POST https://epinio.epinio.toolsroundup.dev/api/v1/namespaces/workspace/applications"  
2021/09/24 10:29:23 EpinioApiClient "level"=5 "msg"="request finished"  
2021/09/24 10:29:23 EpinioApiClient "level"=5 "msg"="response received" "status"=400 
2021/09/24 10:29:23 EpinioApiClient "msg"="response is not StatusOK after custom error handling" "error"="Bad Request: User not found in the request header" "status"=400 
2021/09/24 10:29:23 EpinioClient/Push "level"=4 "msg"="return" "Name"="test" "Namespace"="workspace" "Sources"="/home/agracey/Projects/sampleproject" 
error pushing app to server: Bad Request: User not found in the request header
```

The username and password are in the epinio config file and when I browse the the epinio ui, I can log in using the contained credentials.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

I'm running k3s in Digital Ocean and set up a ClusterIssuer called example-issuer. I know that the signing works since I also have Rancher installed.

- `epinio install --system-domain epinio.toolsroundup.dev --tls-issuer example-issuer --use-internal-registry-node-port=false --skip-cert-manager`
- `epinio push test`

**Cluster (please complete the following information):**
 - Provider: k3s on Digital Ocean droplet (ubuntu I think?)
 - Options: single node
 - Kubernetes Version: v1.21.4+k3s1

**Desktop/CLI (please complete the following information):**
 - OS: Linux
 - Epinio Version: 0.1.1
 - Epinio Install Options: custom issuer, custom domain, skip cert-manager

**Comment by agracey** [comment]
Just verified that this is not an issue with a local install on Rancher Desktop (0.5.0 pre-release). I'll uninstall and reinstall to try again

**Comment by agracey** [comment]
reinstall does not change anything. I have a public environment with this installed if anyone wants to look at it

**Comment by agracey** [comment]
I think this might be an issue with using Traefik 1 vs traefik 2

**Comment by kkaempf** [comment]
Can you upgrade Kubernetes to 1.21.5 ?
I tested Epinio 0.1.1 on Rancher Desktop 0.5.0 and failed with Kubernetes 1.21.4. It worked after upgrading to 1.21.5 🤯

**Comment by agracey** [comment]
This is for sure an issue with Traefik versions. I'm going to close and open another ticket around dropping support for traefik v1 and asking for some better error output specific to having traefik v1 installed. This is needed as k3s didn't make the change until relatively recently.
