### ISSUE TITLE
Don't fail when listing all apps and some namespace goes missing

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#856]
This is a followup of this: https://github.com/epinio/epinio/pull/837#issuecomment-932082708

It seems that while the test was running, something removed some namespace behind the scenes (or changed the target?) and made the `epinio apps list --all` command fail. We should find what the cause is and make sure this won't fail again.

**Comment by jimmykarily** [comment]
I think the problem is that we first collect all apps and then we try to fetch information about them one by one: https://github.com/epinio/epinio/blob/main/internal/application/application.go#L158-L167

If and app is removed behind the scenes it will cause this:

```
[1]     error listing apps: Internal Server Error: applications.app.k8s.io "apps-759667167" not found
```
(here: https://github.com/epinio/epinio/runs/3765228649?check_suite_focus=true#step:10:412)

The same thing happens with namespaces in FullIndex (https://github.com/epinio/epinio/blob/main/internal/api/v1/applications.go#L160-L167). If a namespace is deleted it will cause this error:

```
[1]     error listing apps: Internal Server Error: namespace namespace-270964558 does not exist
```
(here: https://github.com/epinio/epinio/runs/3765228649?check_suite_focus=true#step:10:558)

The best fix would be to not error out when a namespace or an app goes missing. We should just remove that namespace or app from the list.

**Comment by andreas-kupries** [comment]
Agreed. Race window here between getting the list and fetching details.

**Comment by jimmykarily** [comment]
working branch: https://github.com/epinio/epinio/tree/856-full-index-dont-fail
