### ISSUE TITLE
User documentation missing

### ISSUE THREAD

**Issue by JamesTryand** [epinio/epinio#859]
Main page with link to documentation doesn't work.

Going through the source code, the links in the documentation such as 'Tutorials' or any of that groups links.

In the documentation source, there exists a developer folder but not a user folder.

Developer documentation links work.

**Comment by kkaempf** [comment]
Where do you look for the "Main page with link ..." ?

The end-user docs are hosted on https://docs.epinio.io now. The developer docs are still next to the source.

**Comment by kkaempf** [comment]
Oh, the header link to "Documentation" at https://epinio.io was still wrong. Fixed :wink:

**Comment by kkaempf** [comment]
Documentation restructuring is still ongoing. I close this issue now because the link on epinio.io is fixed.

Please reopen if you find more errors / inconsistencies. Thanks !
