### ISSUE TITLE
API: Handle JS WebSocket's lack of support for auth headers

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#871]
**Is your feature request related to a problem? Please describe.**
The native JS WebSocket does not support authentication via the Authorization header. This blocks streaming application and staging logs from the browser

- https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
- https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

**Describe the solution you'd like**
There a a number of different ways auth can be handled via socket, many listed here https://websockets.readthedocs.io/en/latest/topics/authentication.html.

**Describe alternatives you've considered**
I need to discuss with Neil how we handled this in Stratos, I think we manually updated a standard https request to wss in our backend.

**Additional context**
It doesn't look like this is needed by the CLI - https://github.com/epinio/epinio/blob/6ef5cc0044f71c01cf90ed83bcdda18251c594a7/internal/cli/usercmd/client.go#L799

**Comment by jimmykarily** [comment]
@richard-cox I'm still experimenting with things but currently the plan is to have each user defined as a BasicAuth Secret. The old secrets will be gone. The new secrets will be labeled with this key and value: https://github.com/epinio/epinio/blob/871-js-compatible-auth/helpers/kubernetes/cluster.go#L54-L55

 e.g. 

```
epinio.suse.org/api-user-credentials=true 
```

I hope it not too difficult to change your logic around this.
