### ISSUE TITLE
Track Epinio external dependencies in a single file

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#881]
**Is your feature request related to a problem? Please describe.**
[Update minio and minio-operator version #880](880) made me thinking about all the external
dependencies hidden (buried) in some `.yaml` or `.go` code within Epinio.

This makes is hard to track and update dependencies. Let alone scan Epinio for external dependencies with known security problems.

**Describe the solution you'd like**
Collect all external dependencies in a single file and (ideally) create all other `.yaml` (and `.go` ?!) files from it.

Provide tooling around that file to
- look for newer versions
- scan current versions for security problems
- provide documentation about Epinio's dependencies

**Describe alternatives you've considered**
`grep`ping through the source ?!

**Comment by enrichman** [comment]
Now we have less dependencies that can be tracked in the helm chart, we also have the Rancher Marketplace integration that will scan our dependencies for security issues.
