### ISSUE TITLE
Zero instance option doesn't work with epinio push

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#891]
**Describe the bug**
I tried to deploy an app with zero instance as it's asked in our test scenario 2 ([GKE](https://github.com/epinio/epinio/wiki/Release-Test-Plan(s)) 

Ref #893, this ticket depends on resolution of this bug somewhat.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio on the platform you prefer, I used k3s `v1.21.5+k3s2`:
`epinio install`

2. Push an app:
`epinio push sample0 sample-app -i 0`

3. Look at cluster:
```
kubectl get pods -n workspace
NAME                       READY   STATUS    RESTARTS   AGE
sample0-5bf4575cb9-b8zvw   2/2     Running   0          15m
```

No error message

**Expected behavior**
We shouldn't see an instance as we used the `-i 0` option.

**Logs**
<details>
  <summary>Push logs</summary>
  <pre>
epinio push sample0 sample-app -i 0 --trace-level 5 --verbosity 1
2021/10/14 11:28:18 Config-0xc000112360 "level"=4 "msg"="Loading"  "from"="/root/.config/epinio/config.yaml"
2021/10/14 11:28:18 Config-0xc000112360 "level"=4 "msg"="Loaded"  "value"="namespace=(workspace), user=(197aa71f9db5254a), pass=(099d51a556365888), api=(https://epinio.192.168.121.19.omg.howdoi.website), wss=(wss://epinio.192.168.121.19.omg.howdoi.website), color=(true), @(/root/.config/epinio/config.yaml)"
2021/10/14 11:28:18 EpinioApiClient "level"=4 "msg"="query configuration"  
2021/10/14 11:28:18 Config-0xc000112000 "level"=4 "msg"="Loading"  "from"="/root/.config/epinio/config.yaml"
2021/10/14 11:28:18 Config-0xc000112000 "level"=4 "msg"="Loaded"  "value"="namespace=(workspace), user=(197aa71f9db5254a), pass=(099d51a556365888), api=(https://epinio.192.168.121.19.omg.howdoi.website), wss=(wss://epinio.192.168.121.19.omg.howdoi.website), color=(true), @(/root/.config/epinio/config.yaml)"
2021/10/14 11:28:18 EpinioApiClient "level"=4 "msg"="cached in config"  
2021/10/14 11:28:18 EpinioApiClient "level"=4 "msg"="return"  "api"="https://epinio.192.168.121.19.omg.howdoi.website" "wss"="wss://epinio.192.168.121.19.omg.howdoi.website"
2021/10/14 11:28:18 EpinioClient/New "level"=4 "msg"="Ingress API"  "url"="https://epinio.192.168.121.19.omg.howdoi.website"
2021/10/14 11:28:18 EpinioClient/New "level"=4 "msg"="Config API"  "url"="https://epinio.192.168.121.19.omg.howdoi.website"
2021/10/14 11:28:18 EpinioClient/Push "level"=4 "msg"="start" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" 

🚢 About to push an application with given name and sources into the specified namespace
Name: sample0
Sources: sample-app
Namespace: workspace

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)
2021/10/14 11:28:23 EpinioClient/Push "level"=5 "msg"="validate app name" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" 

Create the application resource ...
2021/10/14 11:28:23 EpinioApiClient "level"=4 "msg"="POST https://epinio.192.168.121.19.omg.howdoi.website/api/v1/namespaces/workspace/applications"  
2021/10/14 11:28:23 EpinioApiClient "level"=5 "msg"="request finished"  
2021/10/14 11:28:23 EpinioApiClient "level"=5 "msg"="response received" "status"=200 

Collecting the application sources ...

Uploading application code ...
2021/10/14 11:28:23 EpinioClient/Push "level"=5 "msg"="upload code" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" 

Staging application with code...
2021/10/14 11:28:23 EpinioClient/Push "level"=5 "msg"="staging code" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" "Blob"="5914391f-9d79-4da2-bd86-a699f88b1a82"
2021/10/14 11:28:23 EpinioApiClient "level"=4 "msg"="POST https://epinio.192.168.121.19.omg.howdoi.website/api/v1/namespaces/workspace/applications/sample0/stage"  
2021/10/14 11:28:24 EpinioApiClient "level"=5 "msg"="request finished"  
2021/10/14 11:28:24 EpinioApiClient "level"=5 "msg"="response received" "status"=200 
2021/10/14 11:28:24 EpinioClient/Push "level"=5 "msg"="start tailing logs" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" "StageID"="148181de805cd92a"
2021/10/14 11:28:24 EpinioClient/Push "level"=5 "msg"="wait for pipelinerun" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" "StageID"="148181de805cd92a"

🕞  Running staging
2021/10/14 11:28:24 EpinioApiClient "level"=4 "msg"="GET https://epinio.192.168.121.19.omg.howdoi.website/api/v1/namespaces/workspace/staging/148181de805cd92a/complete"  
2021/10/14 11:28:24 EpinioClient/Apps "level"=4 "msg"="start" "Application"="sample0" "Namespace"="workspace" 

🚢 Streaming application logs
Namespace: workspace
Application: sample0
2021/10/14 11:28:24 EpinioClient/Apps "level"=5 "msg"="application logs" "Application"="sample0" "Namespace"="workspace" 
🕞  [148181de805cd92a-fetch-sources-dqsxg-pod-hqk5s] step-awscli + aws --endpoint-url http://minio.minio-epinio.svc.cluster.local s3 cp s3://epinio/5914391f-9d79-4da2-bd86-a699f88b1a82 /workspace/source/5914391f-9d79-4da2-bd86-a699f88b1a82 
download: s3://epinio/5914391f-9d79-4da2-bd86-a699f88b1a82 to source/5914391f-9d79-4da2-bd86-a699f88b1a82 ith 1 file(s) remaining
🕞  [148181de805cd92a-extract-pg95g-pod-km8zw] step-extract total 16 
🕞  [148181de805cd92a-extract-pg95g-pod-km8zw] step-extract drwxr-xr-x    3 root     root          4096 Oct 14 09:29 . 
🕞  [148181de805cd92a-extract-pg95g-pod-km8zw] step-extract drwxrwxrwx    3 root     root          4096 Oct 14 09:29 .. 
🕞  [148181de805cd92a-extract-pg95g-pod-km8zw] step-extract -rw-r--r--    1 root     root            29 Oct 14 08:28 buildpack.yml 
🕞  [148181de805cd92a-extract-pg95g-pod-km8zw] step-extract drwxr-xr-x    2 root     root          4096 Oct 14 09:29 htdocs 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create 2021/10/14 09:29:04 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Setting permissions on '/workspace/cache'... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Setting permissions on '/tekton/home'... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Setting permissions on '/layers'... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Setting permissions on '/workspace/source'... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Parsing additional configuration... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare -> Parsing env variables... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare > Processing any environment variables... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-prepare --> Creating 'env' directory: /platform/env 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create ===> DETECTING 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Warning: Warning: buildpack paketo-buildpacks/php-web has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create 4 of 9 buildpacks participating 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create paketo-buildpacks/ca-certificates 2.4.2 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create paketo-buildpacks/httpd           0.1.3 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create paketo-buildpacks/php-dist        0.3.4 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create paketo-buildpacks/php-web         0.1.2 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create ===> ANALYZING 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Previous image with name "epinio-registry.192.168.121.19.omg.howdoi.website/apps/sample0-148181de805cd92a" not found 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Previous image with name "" not found 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create ===> RESTORING 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create ===> BUILDING 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Paketo CA Certificates Buildpack 2.4.2 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   https://github.com/paketo-buildpacks/ca-certificates 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Launch Helper: Contributing to layer 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Paketo Apache HTTP Server Buildpack 0.1.3 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Resolving Apache HTTP Server version 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Candidate version sources (in priority order): 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create       <unknown> -> "" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Selected Apache HTTP Server version (using <unknown>): 2.4.51 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Executing build process 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Installing Apache HTTP Server 2.4.51 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create       Completed in 1.239s 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Configuring environment 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     APP_ROOT    -> "/workspace/source/app" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     SERVER_ROOT -> "/layers/paketo-buildpacks_httpd/httpd" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Paketo PHP Distribution Buildpack 0.3.4 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Resolving PHP version 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Candidate version sources (in priority order): 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create       default-versions -> "7.4.*" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Selected PHP version (using default-versions): 7.4.24 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Executing build process 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Installing PHP 7.4.24 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create       Completed in 8.003s 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Configuring environment 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     MIBDIRS           -> "/layers/paketo-buildpacks_php-dist/php/mibs" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     PATH              -> "/layers/paketo-buildpacks_php-dist/php/sbin:$PATH" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     PHP_API           -> "20190902" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     PHP_EXTENSION_DIR -> "/layers/paketo-buildpacks_php-dist/php/lib/php/extensions/no-debug-non-zts-20190902" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     PHP_HOME          -> "/layers/paketo-buildpacks_php-dist/php" 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create  
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Paketo PHP Web Buildpack 0.1.2 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   PHP Web 157350bf35694c62a6480eadd16cdd82be80c7c051e203303439e65b83d239b0: Contributing to layer 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Configuring PHP Application 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Using feature -- PHP 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Writing PHPRC to shared 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Writing PHP_INI_SCAN_DIR to shared 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Using feature -- Apache Web Server 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Using feature -- PhpFpm 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     Using feature -- ProcMgr 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create   Process types: 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create     web: procmgr /layers/paketo-buildpacks_php-web/php-web/procs.yml 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create ===> EXPORTING 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'paketo-buildpacks/ca-certificates:helper' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'paketo-buildpacks/httpd:httpd' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'paketo-buildpacks/php-dist:php' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'paketo-buildpacks/php-web:php-web' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding 1/1 app layer(s) 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'launcher' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'config' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding layer 'process-types' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding label 'io.buildpacks.lifecycle.metadata' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding label 'io.buildpacks.build.metadata' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding label 'io.buildpacks.project.metadata' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Setting default process type 'web' 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Saving epinio-registry.192.168.121.19.omg.howdoi.website/apps/sample0-148181de805cd92a... 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create *** Images (sha256:39a0343f89b77d790b119a74e14cd7136266cfa247942af91a769c96b595911a): 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create       epinio-registry.192.168.121.19.omg.howdoi.website/apps/sample0-148181de805cd92a 
🕞  [148181de805cd92a-stage-mq4w6-pod-vztmf] step-create Adding cache layer 'paketo-buildpacks/php-dist:php' 
2021/10/14 11:29:59 EpinioApiClient "level"=5 "msg"="request finished"  
2021/10/14 11:29:59 EpinioApiClient "level"=5 "msg"="response received" "status"=200 
2021/10/14 11:29:59 EpinioClient/Apps "level"=4 "msg"="return" "Application"="sample0" "Namespace"="workspace" 

Deploying application ...
2021/10/14 11:29:59 EpinioApiClient "level"=4 "msg"="POST https://epinio.192.168.121.19.omg.howdoi.website/api/v1/namespaces/workspace/applications/sample0/deploy"  
2021/10/14 11:30:00 EpinioApiClient "level"=5 "msg"="request finished"  
2021/10/14 11:30:00 EpinioApiClient "level"=5 "msg"="response received" "status"=200 
2021/10/14 11:30:00 EpinioClient/Push "level"=5 "msg"="wait for application resources" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app" 

🕞  Creating application resources
2021/10/14 11:30:00 EpinioApiClient "level"=4 "msg"="GET https://epinio.192.168.121.19.omg.howdoi.website/api/v1/namespaces/workspace/applications/sample0/running"  
2021/10/14 11:30:10 EpinioApiClient "level"=5 "msg"="request finished"  
2021/10/14 11:30:10 EpinioApiClient "level"=5 "msg"="response received" "status"=200 

✔️  App is online.
Name: sample0
Namespace: workspace
Route: https://sample0.192.168.121.19.omg.howdoi.website
Builder Image: paketobuildpacks/builder:full
2021/10/14 11:30:10 EpinioClient/Push "level"=4 "msg"="return" "Name"="sample0" "Namespace"="workspace" "Sources"="sample-app"
  </pre>
</details>

**Cluster (please complete the following information):**
 - Provider:  k3s `v1.21.5+k3s2`
 - Options: No options
 - Kubernetes Version: v1.21.5+k3s2

**Desktop/CLI (please complete the following information):**
 - OS: Linux
 - Epinio Version: 0.1.2
 - Epinio Install Options: No options

**Additional context**
Nothing special to mention

**Comment by andreas-kupries** [comment]
Working on reproduction ...

> epinio push --name fox --path assets/sample-app --instances 0

Confirmed a running app pod:

> workspace         fox-b6c47fc4b-pjdtm                             2/2    Running    0         5m17s

App create client side log ...

> 2021/10/21 10:34:53 EpinioApiClient "level"=5 "msg"="request finished" "body"="{\"name\":\"fox\",\"configuration\":{__\"instances\":0__,\"services\":null,\"environment\":null}}" "method"="POST" "uri"="https://epinio.192.168.64.3.omg.howdoi.website/api/v1/namespaces/workspace/applications" 

Proper `instances` value is passed to server.

app server, scaling secret
> data:
  desired: MA==

`MA==` decodes to `0`.

Data arrived properly in server, and is stored correctly.

However
> epinio app show fox

shows `1` for `Desired Instances`. 

I am also wondering if we should actually try to deploy with instances 0 ? Might be better to skip

Lets see if the `deployment` resource survives scaling down to zero.
If not then even attempting to deploy for instances 0 will be definitely  bogus ...

Huh. Ok. The deployment survives scaling to zero and shows `0` for `spec.replicas`. 
After the `push` the `spec.replicas` was `1` actually.

And `epinio app show fox` still shows `Desired Instances` = `1` for the disabled app.
With additional log entries (decoded response) I see that this bogus value is from the server itself.

A quick check with `epinio app create dog --instances 0` shows that the `show` error is likely independent of the deploy issue. The bogus `desired instances = 1` happens for it also. And confirmed that the scale secret has the proper value.
This indicates an issue with fetching the scaling status from the secret or in processing near by.

Actually, that could explain the deploy issue also. Because deploying fetches the desired instances from the secret, so there is a shared code path there.

Note, I currently see another issue with deploying and `instances == 0`. The client waits for the app to be running. This will never happen without instances. The deploy endpoint may have to signal the client that waiting is contra-indicated.

But lets focus having deploy do the correct thing first.
