### ISSUE TITLE
Spike: Extend Gin Usage in Handlers for shared validations ...

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#903]
**Is your feature request related to a problem? Please describe.**

This is a followup to #878 and its PR #886.

We have to look at higher level features of Gin like request validation and eval where we can use them to simplify our handlers even more.

**Describe the solution you'd like**

API handlers whose repetitive validations (org existence, app existence, service existence, etc.) are moved into separate functions registered with and called by the gin framework where needed. 

Note, it is unclear right now, which validations can be implemented as gin structure validations, and which cannot.
Those which cannot may still be moved into middleware functions sitting in front of and shared by multiple handlers.

**Comment by jimmykarily** [comment]
Let's use gin when we need it (e.g. as part of some refactoring). No need for a dedicated issue. Closing this.
