### ISSUE TITLE
unknown flag: --instances 0 for epinio push command

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#904]
**Describe the bug**
Error message `unknown flag: --instances 0` when I try to push an app with zero instances.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio
2. Push an app with option `--instances 0`
4. See the error message

**Expected behavior**
The app should be deployed with 0 replica.

**Cluster (please complete the following information):**
 - Provider: GKE
 - Options: 3 nodes
 - Kubernetes Version: 1.21

**Desktop/CLI (please complete the following information):**
 - OS: Linux
 - Epinio Version: 0.1.3
 - Epinio Install Options: custom system domain

**Additional context**
N/A

**Comment by andreas-kupries** [comment]
The error message seems to indicate a quoting issue in how epinio is called.
I.e. `--instances 0` seems to be provided as a single argument, instead of two.
This would cause epinio to search for a flag called "--instances 0", and fail.

What does the code / specification calling epinio looks like ?
