### ISSUE TITLE
Get an Epinio in one click  - AWS Marketplace

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#934]
We want to give users easy ways to deploy Epinio (as in "one click"). 
We think about public cloud provider marketplaces. AWS has such a marketplace.

**Comment by agracey** [comment]
Some of the cloud team is asking about this. They would likely be the ones to build it, so I'll update accordingly.

**Comment by enrichman** [comment]
No updates since Jan. @agracey closing this.
