### ISSUE TITLE
`epinio app manifest` should update routes

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#952]
This is a fix for this comment: https://github.com/epinio/epinio/pull/942#issuecomment-958733119

Let's wait until #594 is done to avoid conflicts and fix it only once.

**Comment by andreas-kupries** [comment]
The domain configuration is, AFAICT the `routes` field of `ApplicationUpdateRequest`. Should be mapped to the yaml key `configuration.routes`.

**Comment by andreas-kupries** [comment]
Confirmed missing. Ok,time to investigate, because I saw the yaml tags on the structure, would have expected it to be marshaled.

**Comment by andreas-kupries** [comment]
Ah. Data not yet returned by the server.

**Comment by andreas-kupries** [comment]
Needs to be fixed in `application/application.go`, `fetch()`.

Yep. Use `ListRoutes()`. from the `ingresses.go` sibling.

**Comment by andreas-kupries** [comment]
No. `ListRoutes` is for the active routes of a running app. Need something new for the routes of an app at rest.
... Lets look at #954 if that already got something for this.

**Comment by andreas-kupries** [comment]
No.
