### ISSUE TITLE
API: Handle CORS

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#961]
**Is your feature request related to a problem? Please describe.**
API requests to Epinio from a browser suffer from CORS errors (see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS - resources requested from a domain different from that serving the frontend JS). 

Up till now we've only worked in a 'dev' environment where the `origin` is rewritten to match that of epinio. In product however this proxy does not exist.

There are two other methods to proxy API requests in Rancher
1. Via the Rancher instance / Steve API. This won't work as only whitelisted domains are accepted (it's best not to ad-hoc add/remove these)
2. Via the Kube API proxy. This won't work as it strips the auth header

**Describe the solution you'd like**
Best solution from a UI perspective, but less secure, is adding the header `Access-Control-Allow-Origin: *` to inform the browser the API is ok accepted these type of requests. This means the UI avoids any type of proxy either in dev world or production.

**Describe alternatives you've considered**
Alternatively the auth could support a fall back header, something like `x-epinio-auth-header` which will be checked with the `Authorization` header is missing. This would allow the UI to use the Kube API proxy. This adds a layer of complexity though and wouldn't solve the CORS issue for the standalone use case.

**Additional context**
See slack thread

**Comment by jimmykarily** [comment]
We can have a configuration option on the Epinio server with a list of domains to allow for CORS. It could be an environment variable so that a re-installation is not needed if the Web UI domain changes. Would that work for you @richard-cox ?

**Comment by richard-cox** [comment]
@jimmykarily On one hand that's a good compromise and should work fine, on the other that's additional configuration. I think the former would work but as you said, would be good to edit at run time

**Comment by kkaempf** [comment]
Adding to Beta2 (assuming that the UI release for Beta2 would need this)

**Comment by andreas-kupries** [comment]
Reminder ticket to automate QA: #971
