### ISSUE TITLE
Bundle them all! - Helm charts

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#966]
All the Helm chart we use should be bundled in Epinio.
For instance, with Traefik, if https://helm.traefik.io/ isn't available, the epinio installation fails.
Some of them are already bundled but we should bundle them all.

**Comment by jimmykarily** [comment]
The installer is no longer part of the epinio binary (#1046). This means, we don't bundle dependency helm charts and yaml files in the binary.

But we do bundle them in the `epinio-installer` helm chart image: https://github.com/epinio/installer/blob/main/Dockerfile#L31
This issue can be closed.
