### ISSUE TITLE
Create email account(s) for Epinio

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#967]
We need an Epinio email account to fill our [Epinio Helm Chart](https://github.com/epinio/epinio-helm-chart/blob/main/chart/epinio/Chart.yaml#L15) and more generally for creating accounts on websites where we can reference our Helm Chart.

Many choices:

- `epinio-team@lists.suse.com`
- `epinio-team@suse.de`
- `team@epinio.io`

And also create aliases for team's members like `julien@epinio.io,` `mario@epinio.io`

**Comment by kkaempf** [comment]
epinio-team@suse.de should just be an SD ticket away :wink:

Team, please take a decision, then I can take care about the rest.

**Comment by pgonin** [comment]
team@epinio.io would cost $4 per month with Amazon WorkMail (on AWS)
and would require domain name configuration by the team managing SUSE domains (more time than SD ticket for @suse.de)

**Comment by ldevulder** [comment]
I'm not for a @suse.de address in any case, @suse.com better in any case.

In default installation epinio@suse.com is set. Is it a fake address or a real one? If it's a real one why not using it?

**Comment by juadk** [comment]
> I'm not for a @suse.de address in any case, @suse.com better in any case.
> 
> In default installation [epinio@suse.com](mailto:epinio@suse.com) is set. Is it a fake address or a real one? If it's a real one why not using it?

For me, it always been a fake address.

**Comment by ldevulder** [comment]
> For me, it always been a fake address.

OK, is this address can be in the list? Or not because it is set by default on some installation? Or an epinio-team@suse.com?

**Comment by juadk** [comment]
> > For me, it always been a fake address.
> 
> OK, is this address can be in the list? Or not because it is set by default on some installation? Or an [epinio-team@suse.com](mailto:epinio-team@suse.com)?

To me, this email is used to get notifications about certificates expiration, so if we set our real email, we can get spammed by customer apps if they don't put their email. That's likely better to keep going with a fake one.

**Comment by kkaempf** [comment]
> I'm not for a @suse.de address in any case, @suse.com better in any case.

Why's that ?

> 
> In default installation [epinio@suse.com](mailto:epinio@suse.com) is set. Is it a fake address or a real one? If it's a real one why not using it?

Well, epinio@suse.com will be hard (if not impossible) to get. epinio@lists.suse.com is probably closest to what's available under a @suse.com domain.

**Comment by kkaempf** [comment]
Btw, Kubewarden got kubewarden@suse.de :wink:

**Comment by juadk** [comment]
Rancher is using charts@rancher.com in their charts as well as contact email on ArtifactHUB.

**Comment by ldevulder** [comment]
> Btw, Kubewarden got [kubewarden@suse.de](mailto:kubewarden@suse.de)

It's not a good idea IMHO, @suse.de shouldn't be used anymore, the official one is @suse.com.

**Comment by ldevulder** [comment]
> Why's that ?

Because the official one is @suse.com. @suse.de is the older one and according to the `.de` part only for Germany.

**Comment by juadk** [comment]
@kkaempf @pgonin , during the daily sync, the team agreed on epinio-team@suse.com 
And if it's really hard to get (I don't have the context), we can go with team@epinio.io

**Comment by pgonin** [comment]
epinio-team@suse.com is unlikely to be possible.
We need to use mailman instances either the one on lists.suse.com or the one on suse.de

**Comment by juadk** [comment]
ok so let's go with epinio-team@lists.suse.com

**Comment by pgonin** [comment]
I created epinio AWS WorkMail organization
Asking DNS setup now

**Comment by juadk** [comment]
As team@epinio.io is now active, we can start to update documentations, helm chart etc...

**Comment by kkaempf** [comment]
closing
