### ISSUE TITLE
Support upgrades

### ISSUE THREAD

**Issue by viovanov** [epinio/epinio#97]
A checklist of requirements:

- [ ] being able to programmatically tell which component was installed by Epinio
- [ ] ability to determine the version of an installed component
- [ ] ability to freeze the version of a component in Epinio (hardcoded, but clearly defined somewhere in code)
- [ ] proper handling of secrets and passwords (keep them unchanged across the upgrade ?)
- [ ] keep applications running across the upgrade
- [ ] keep applications accessible during the upgrade (traefik upgrades are the difficult point here).
- [ ] upgrades 🐱‍🏍

**Comment by jimmykarily** [comment]
This is issue is more up to date and has more information: https://github.com/epinio/epinio/issues/987#issuecomment-992215187

For the record, from the checklist above, we will get:

```
- [ ] being able to programmatically tell which component was installed by Epinio - No
- [ ] -  ability to determine the version of an installed component - Not now, maybe in the future
- [ ] ability to freeze the version of a component in Epinio (hardcoded, but clearly defined somewhere in code) - No
- [ ] proper handling of secrets and passwords (keep them unchanged across the upgrade ?) - Yes (we don't change them)
- [ ] keep applications running across the upgrade - Yes
- [ ] keep applications accessible during the upgrade (traefik upgrades are the difficult point here). - Maybe, Traefik upgrades are not Epinio's responsibility
- [ ] upgrades 🐱‍🏍 - Yes
```

Closing this issue.
