### ISSUE TITLE
Automate testing of the new -access-control-allow-origin install setting

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#971]
#970 for #961 introduced a new installer option `-access-control-allow-origin`.
This option enabled the specification of the content for the  `Access-Control-Allow-Origin` response header controlling CORS security.

This is a followup ticket to remind us to automate the testing of this option.
So far only manual testing was performed, that the header appears in responses when the information was set.

**Comment by juadk** [comment]
I think we will test the CORS feature when we will automate the UI testing #1000 
@andreas-kupries Do you think it will be enough or we need to test it in the standard CI pipeline as well?

**Comment by andreas-kupries** [comment]
... .... I believe it will be enough to have it under UI testing. That is there setting is needed, and has an effect, right? Standard CI pipeline is CLI, and the setting should not matter.

**Comment by juadk** [comment]
> ... .... I believe it will be enough to have it under UI testing. That is there setting is needed, and has an effect, right? Standard CI pipeline is CLI, and the setting should not matter.
Right, it's mandatory for testing the UI to allow communications between Rancher and Epinio's API.

**Comment by ldevulder** [comment]
It's testing during installation of Epinio in UI: https://github.com/epinio/epinio-end-to-end-tests.

Could be closed I think.

**Comment by juadk** [comment]
yes, let's close it then.
