### ISSUE TITLE
Spike: try to re-use the same image on every stage

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#975]
I'm facing a bug (https://github.com/buildpacks/lifecycle/issues/213) and while reading up on docs (https://buildpacks.io/docs/concepts/components/lifecycle/analyze/) I see that:

```
the analyzer was responsible for analyzing the metadata from the cache and the previously built image (if available) to determine what layers can or cannot be reused. 
```

I'm wondering if the fact that every time we stage an application, the APP_IMAGE is different (has the stage id in the name) makes the whole process slower because the previous image is never there and no layers can be re-used (https://github.com/epinio/epinio/blob/main/assets/embedded-files/tekton/buildpacks-task.yaml#L138).

We did this to be able to control when the running app is restarted and which artifact it runs (rather than simply replacing the image under the hood). If this makes the staging process slower though, we should find some other solution.

Let's try to use the same image all the time (no stage id in the name) and see if that improves the performance of staging after the image has been built at least once.

**Comment by jimmykarily** [comment]
NOTE: just in case someone lands here from the linked lifecycle issue, the bug in my case was that the username for the registry was empty (because I messed up the param name in the epinio cli).

**Comment by jimmykarily** [comment]
If this proves to make any difference, we can simply use the running image as `previous-image` in the pipeline. The stage-id should be available on the running deployment.

**Comment by jimmykarily** [comment]
With #991 fixed, we now need to find the previous image tag to be used as `previous-image`

**Comment by andreas-kupries** [comment]
Research Notes:

  - `assets/embedded-files/tekton/buildpacks-task.yaml:138:        - "-previous-image=$(params.APP_IMAGE)"`
  - Above is in the create task.
  - No param for previous image. Yet. 
  - APP_IMAGE is specified by server, at
  - `internal/api/v1/application/stage.go:343:				{Name: "APP_IMAGE", Value: *str(app.ImageURL(app.RegistryURL))},`
  - `ImageUrl` constructs image name as `namespace-appname:stage-id`.
  - The stage id is the only varying part now. Namespace and app name are obviously fixed to the app.
  - We need the stage id of the previous run = The stage id of the deployed app
  - Although, we can have the situation that the app is scaled to zero, effectively stopped. And then push, with a restart implied. So, not necessarily deployed when looking for the old stage id.
  - When the app is deployed the stage id is available in the labels of the pod template in the deployment
  - See `workload.go` - `stageID = deployments.Items[0].Spec.Template.ObjectMeta.Labels["epinio.suse.org/stage-id"]`.
  - Ah! We keep the previous `pipelinerun` around until the new staging has completed successfully.
  - And "epinio.suse.org/stage-id" is among its labels also.
  - Actually ! Scaling to 0 keeps the deployment around. We can always ask the deployment. It does not exists only if the app was never pushed at all. And after it was deleted. But at that point the next push is essentially the first again. And the pipelineruns would be gone also

So, in stage, get the workload, and if present, pull the previous stage id out of its labels and use that for the previous image. We need another params in the pipeline as well.

**Comment by jimmykarily** [comment]
There is still a case in which the pipelinerun may work better and that is if the client staged the app but didn't deploy it (our client doesn't do that but other clients may do). In that case, we have a pipelinerun but no deployment. If it's possible to use the pipeline run, maybe it's worth it. If it's trouble for whatever reason, the deployment should do. It's an  edge case and the worse that will happen is that the next staging won't be as fast. It would only be a problem if someone used the above edge case a lot for some reason...

**Comment by andreas-kupries** [comment]
Huh. A problem I see with pipelineruns is if there is more than one ... i.e. from various failed stagings. These are deleted only on the first successful staging. So, while most of the time there is only one run we may have more, so have to sort by time (youngest first), filtered to look only at successful runs.

On the other side, I seem to have a working implementation based on the data in the deployment. Just completed testing, first push, second push ...

**Comment by andreas-kupries** [comment]
Pushed as PR, and linked here.
