### ISSUE TITLE
Allow air gap installation for the Epinio Helm Chart (the "small" one)

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#979]
Rancher can be installed in an air gap environment, that means our Epinio Helm Chart must be compatible with that feature.
https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/

Air gap means installation without or with limited network connectivity.

Rancher has a “convention” to control the image registry, e.g.  allow for air gap installs (I think it is this https://github.com/rancher/charts/blob/dev-v2.6/charts/longhorn/longhorn/1.1.100/templates/deployment-driver.yaml#L23) which we should support

**Comment by jimmykarily** [comment]
We should make the container registry parameterized in the "small" epinio helm chart so that people can use a locally deployed registry if they want to.
