### ISSUE TITLE
UI testing for beta2

### ISSUE THREAD

**Issue by prabalsharma** [epinio/epinio#988]
Smoke testing of Epinio UI for beta2.
UI doc: https://github.com/epinio/ui/blob/beta2/README.md

**Update**: epinio-v0.2.0-rc1 is good for testing
you should just be able to update the dashboard global setting ui-dashboard-index to https://releases.rancher.com/dashboard/epinio-v0.2.0-rc1/index.html (so switching epinio-dev to epinio-v0.2.0-rc1 ) and refresh the browser to get the change

Test Plan: https://confluence.suse.com/display/Epinio/UI

**Comment by kkaempf** [comment]
This needs a clear documentation on supported browsers and browser versions

**Comment by richard-cox** [comment]
Some of the basic uses should be covered by below. A lot can be combined (create a namespace, create a service in it, create an app in the ns and bind the service to it, etc)

Application - Create (successfully deploy an application, see it ready in the app list), Edit and then Delete it
Services - Create (create a service and bind some apps to it, see it in the services list). Delete it (no edit available) (note - seeing the data associated with the service won't currently work)
Namespaces - Create (create, see it appear in the namespace list). Delete it (no edit available)

**Comment by juadk** [comment]
First tests from my side:
I used Firefox 94.0
- Deploy Rancher under docker with `ui-dashboard-index= https://releases.rancher.com/dashboard/epinio-v0.2.0-rc1/index.html` :heavy_check_mark: 
- Deploy a k3s cluster on my laptop with vagrant :heavy_check_mark: 
- Import the k3s cluster in Rancher :heavy_check_mark: 
- Install Epinio on my k3s cluster with CLI :heavy_check_mark: 
- Make sure Epinio is discovered by UI :heavy_check_mark: 
- Deploy an app with tar.gz archive :heavy_check_mark: 
- Make sure the app is reachable via its route :heavy_check_mark: 
- Delete the app through the UI :heavy_check_mark:

**Comment by juadk** [comment]
I'm trying to test it again and this time, I face this issue:
![image](https://user-images.githubusercontent.com/6025636/141994150-5c27e267-5eeb-4272-be87-f8f0504cbce4.png)
I did exactly same steps as yesterday...

**Comment by kkaempf** [comment]
My results so far: sample-app ✅  , golang-sample-app ✅  , example-wordpress ✅  , example-12factor ✅

**Comment by ldevulder** [comment]
Tests I did on Chrome 95.0.4638.69 and Firefox 94.0.1:
- Deploy Rancher under docker in a VM with `ui-dashboard-index= https://releases.rancher.com/dashboard/epinio-v0.2.0-rc1/index.html` :heavy_check_mark:
- Deploy a k3s cluster on a VM :heavy_check_mark:
- Import the k3s cluster in Rancher :heavy_check_mark:
- Install Epinio on the k3s cluster with CLI :heavy_check_mark:
- Make sure Epinio is discovered by UI :heavy_check_mark:
- Deploy an app with tar.gz archive :heavy_check_mark:
- Make sure the app is reachable via its route :heavy_check_mark:
- Delete the app through the UI :heavy_check_mark:

I also did this test:
- Deploy Rancher under docker in a VM with `ui-dashboard-index= https://releases.rancher.com/dashboard/epinio-v0.2.0-rc1/index.html` :heavy_check_mark:
- Deploy a k3s cluster on a VM from Rancher :heavy_check_mark:
- Install Epinio on the k3s cluster with CLI :heavy_check_mark:
- Make sure Epinio is discovered by UI :heavy_check_mark:
- Deploy an app with tar.gz archive :heavy_check_mark:
- Make sure the app is reachable via its route :heavy_check_mark:
- Delete the app with the CLI :heavy_check_mark:
- Make sure that the app is correctly removed from the UI :heavy_check_mark:

**Comment by ldevulder** [comment]
I did Services tests also:
- Create a service from the CLI and check that it is discovered by UI :heavy_check_mark:
- Create a service in the UI and check that it is discovered by the CLI :heavy_check_mark:
- Create an app and associate the services to it :heavy_check_mark:
- Check that the services are correctly assigned to the app in UI :heavy_check_mark:
- Check that the services are correctly assigned to the app in the CLI :heavy_check_mark:

**Comment by juadk** [comment]
### My final word about UI testing:

Today, I've tried to reproduce the sporadic issue when the deployment stays in pending state:
![image](https://user-images.githubusercontent.com/6025636/142212859-4d16f6ea-af01-48c4-9f76-45105bf1d34e.png)
I did 4 installations from scratch, the issue appeared only one time and it worked after a restart of the epinio-server POD. I can't say more...

I also tested the Services like Loic did plus:
- Delete a service bound to an app, a box asks if you want to unbind before deleting the service, after deletion, the app is still alive :heavy_check_mark: 
-  Delete a service not bounded :heavy_check_mark: 

### Bug opened during the UI testing for Beta2:
https://github.com/epinio/epinio/issues/998 - Epinio instance not accessible from Rancher if a '/' is at the end of the URL
https://github.com/epinio/ui/issues/50 - Add warning about chain reaction when you delete a namespace

Now we have to format all the tests done into the test plan.

**Comment by kkaempf** [comment]
Under some (unknown) circumstances, epinio-server can behave strangely and fails to deploy via Rancher Dashboard.

After a restart of epinio-server (by changing the deployment env variables), I cannot trigger any problems and all app deployments succeed flawlessly.

**Comment by kkaempf** [comment]
Just filed epinio/ui#52 (Dashboard crash on app creation if no namespace is defined)

**Comment by kkaempf** [comment]
Closing for now as we'll release Epinio + Dashboard v0.2.0 today.
