### ISSUE TITLE
Uninstall breaks when using external S3 storage

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#990]
**Describe the bug**
When I install with an external S3 storage then uninstall, I get this error: 

```
⚠️  Uninstall of minio-operator failed: Deleting minio/tenant.yaml failed:
error: unable to recognize "/tmp/epinio726000816": no matches for kind "Tenant" in version "minio.min.io/v2"
: exit status 1
```

**To Reproduce**
1. Install epinio with the `--s3-...` flags (I used digital ocean's spaces)
2. `epinio uninstall`

**Expected behavior**
The uninstaller should see the lack of minio tenants owned by it and skip as unneeded.

**Comment by jimmykarily** [comment]
I think this is the fix: https://github.com/epinio/epinio/pull/996
