### ISSUE TITLE
Subsequent image builds for the same app are stored in different image names

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#991]
**Describe the bug**
When I moved my epinio install to using the new external registry feature, I noticed that each push is creating an entirely new image with the `:latest` tag.

This has a few issues:

- No way to optimize storage in the registry
- Never cache's layers even if the hashes match
- Breaks ability to GC
- Breaks DO's pricing model as now I'll get charged for every `epinio push` instead of per app. 

![image](https://user-images.githubusercontent.com/442274/141802251-a00df9d3-a7db-4fd6-bc9f-5a27128c873e.png)

**To Reproduce**

1.  Install Epinio with external registry (I used digital ocean's container registry)
2. Push sample 12 factor app
3. Push again
4. Look at images that are produced

**Expected behavior**
I would expect applications with the same name to push to the same image name and only use different tags based on build id. 

**Additional context**
I'd imagine this bug is not new but only now visible with the ability to use an external registry.

**Comment by agracey** [comment]
https://github.com/epinio/epinio/pull/974#issuecomment-964888456 Here's the flags to use for docker hub

**Comment by agracey** [comment]
I'm pretty sure this is the only line needed changing and it seems encapsulated enough (good job!) to make it trivial: https://github.com/epinio/epinio/blob/b5386626ce283276147985c9c44a242a011dd035/internal/api/v1/application/stage.go#L49 

It's only referenced in two places: 
https://files.slack.com/files-pri/T02863RC2AC-F02MR8X1N8Z/image.png

**Comment by agracey** [comment]
Sorry for the screenshot of text, I'm not sure how to link to the references tab :D

**Comment by jimmykarily** [comment]
This story is partly duplicate: https://github.com/epinio/epinio/issues/975 with some reasoning on why we used a different image every time. We can probably do better.  Good points @agracey .
